Seneca-CDOT/telescope

README.md, docs/overview.md
This adds a `docs/` directory, and includes an overview document, defining the project.  I've avoided putting this in the README or other main documents, since I want to leave that for project members to do.  This document will likely get subsumed into other documents, and should serve as a starting point.
=> Add initial Overview of the project

feeds.txt, package-lock.json, package.json, src/feed-queue.js, src/feed-worker.js, src/index.js
To get us started, I've taken a crack at writing a basic queue-based producer/consumer app, based on [Bull](https://optimalbits.github.io/bull/) ([Bull on GitHub](https://github.com/OptimalBits/bull)).  **Nothing in this PR is sacred, and it can all be changed, but I wanted to get us moving forward with a basic prototype people can hack on**.
To run this, you need to have [Redis](https://redis.io/) installed (we'll need install docs added for Windows/Linux/macOS in other bugs and/or use Docker or something).
Next, you can start the server like so:
```
npm install
npm start
```
This will start the server, read the list of feed URLs in [feeds.txt](feeds.txt) (just a few to get us something to test on), and convert them into jobs for the queue.
A worker will start watching for jobs to appear …
=> A very basic queue to allow downloading feeds

README.md, docs/CONTRIBUTING.md
Fixes #27 .
This is clearly a work in progress. I will be working on finding better setup instructions, but for now this will work. I would really like feedback on how to approach issues and pull requests from the community, but what I have mirrors what I saw in other projects.
If there is anything I could add, or information I could use, please let me know. I would like to use docker, as that would simplify things greatly, and I know someone is working on it right now. I will update this as pull requests are merged and the system evolves.
=> Add CONTRIBUTING.md

.eslintrc.js, package-lock.json, package.json, test/feed-queue.test.js
This pull request sets up the testing infrastructure using [Jest](https://jestjs.io/) .
To run the test : `npm test`
I only created one simple test as a starting point. The test does check if the Redis server is open.
**NOTE**: `npm test` will most likely not end correctly with error:
"Jest did not exit one second after the test run has completed. This usually means that there are asynchronous operations that weren't stopped in your tests. Consider running Jest with `--detectOpenHandles` to troubleshoot this issue" 
(CTRL + C to exit test.)
This is because the Redis server is still online, closing the server after testing would fix the issue.
If there is a way to handle opening and closing Redis inside the project, this problem won't happen anymore <- CREATE NEW ISSUE TO SOLVE THIS
=> Adding testing infrastructure

docs/CONTRIBUTING.md
Since we haven't set up an environment like docker yet, Redis needs to be installed manually but we were missing links/instructions for the install on windows. I have added a link that offers a quick .msi installer for those using windows.
fixes #56
=> Fixes #56: Added windows redis install link

package.json
As referenced in #67, this will allow both ESLint and Jest to run when the `npm test` command is run. Right now ESLint will run first and give feed back on errors, before running Jest. This order could be changed later but also is most likely for the best right now considering Jest currently needs to be exited with CTRL+C.
=> Adding ESLint to pretest, and moving Jest to test

.eslintrc.js
Added some rules to `.eslintrc.js` that I think would be useful.
- [`no-console`](https://eslint.org/docs/rules/no-console)
- [`no-param-reassign`](https://eslint.org/docs/rules/no-param-reassign)
- [`func-names`](https://eslint.org/docs/rules/func-names)
=> Added some rules to '.eslintrc.js'

src/feed-queue.js, src/feed-worker.js, src/index.js
After merging #49 a lot of linting errors were introduced.
This fixes those errors.
Let's make sure we rebase and run the test before committing and/or submitting PR
=> Fixed linting errors

README.md
I was able to download the planet cdot code from the overview using wget
```
wget -r --no-parent https://people.gnome.org/~jdub/bzr/planet/devel/trunk/
```
Fixes: #29
=> Updated readme to include how to grab existing planet project 

index.html, planet.css, src/dialogue.js
CSS/HTML/JS updates for optimization of static webpage
Fixes #61
If you'd like to preview the website, here it is: https://odaving.github.io/telescope/
=> Enhancement (HTML/jS): modified the website

package.json, src/feed-parser.js
Fixes #16 
Hi, this is a extremely basic feed-parser that will just spit out all the posts from the feed provided to console.
=> Fixes #16: basic feed parser

.dockerignore, Dockerfile, docker-compose.yml
**_What is this pull request:_**
This will add Dockerfile and .dockerignore to the project. So that we can run the project without installing node packages like so:
```bash
$ docker-compose up --build
```
and more importantly, we can ship the Docker image to Kubernetes later on.
=> Adds Docker files as a milestone for issue-4

docs/CONTRIBUTING.md, package-lock.json
Adding **THE LIST OF THINGS THAT MUST BE DONE BY A CONTRIBUTOR BEFORE FILLING A PR**.
=> Fixes 57#: Adding TO-DOs into CONTRIBUTING.md

package-lock.json, test/feed-queue.test.js
Our one and only test is currently failing:
```
> jest
PASS  test/feed-queue.test.js
✓ Testing feed-queue.js (3ms)
Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        1.527s
Ran all test suites.
Jest did not exit one second after the test run has completed.
This usually means that there are asynchronous operations that weren't stopped in your tests. Consider running Jest with `--detectOpenHandles` to troubleshoot this issue.
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#build-times-out-because-no-output-was-received
The build has been …
```
=> Tests need to close Redis connections to pass

.stylelintrc.js, package-lock.json, package.json
Added style lint to catch invalid css styles
How to run script:
`npm run stylelint`
This PR successfully picks up the `h1c` invalid css selector in planet.css 
Fixes #118
=> Fixes #118: added stylelint

.npmrc
Fixes #133 
Added file `.npmrc` as instructed in-order to suppress npm error logs.
=> Fixes #133 - Silenced npm logs when builds fail

CODE-OF-CONDUCT.md
fixes #47 
I've added a basic code of conduct for the project which was adapted from https://www.contributor-covenant.org. The only adjustment I made to this template was adding David's email so anyone can report anything directly to him. 
I was originally going to make one from scratch but I think this code of conduct works pretty well for our project. Of course, we can personalize it a bit and make some changes in the future if we need to. If there's any adjustments you think I should make, I'll be happy to do so.
=> Fixes #47: Adding a CODE-OF-CONDUCT.md to the project 

env.example, src/feed-queue.js
Fixes #144 
Changes made:
- Added the Redis URL to `env.example` 
- Pass the URL when making Bull queue via the constructor in `src/feed-queue.js`
=> Fixes #144 - Added the Redis URL to env.example and pass it when making Bull queue

package-lock.json, package.json, src/backend/web/app.js, src/backend/web/routes/index.js, src/backend/web/server.js, test/server.test.js
fixes #63. This adds nodemon for debug builds as well as a started web server file with a health check. We can discuss additional endpoints here and I can add them in as we discuss them. I've added minimist so that the server can be started on a different port if needed. This can be used like so:  
```bash
node server.js --port=4040  # starts server at port 4040 
```
=> Fix #63: Add an Express Web Server

package.json
The coverage report gives us a percentage analysis of the statements, lines, functions, and branches covered by a test file. I configured jest within the package.json
=> Fix #120: Added a test coverage report

package-lock.json, package.json, src/text-parser.js, test/text-parser.test.js
Adding test case for parsing html to text, reference to issue #75 
@PavanKKamra, apparently JSOM does not support innetText, based on this [Issue](https://github.com/jsdom/jsdom/issues/1245). I have tested it and innerHTML and textContent works fine but innerText will return 'undefined'
=> Fixes #83: test case for text-parser

env.example, package-lock.json, package.json, src/email-sender.js
Contributes to issue #25 
I created a basic email sender using Nodemailer. 
To use the function, private information(email/pass,recipients) must be filled once the .env variables are set up. 
refer to issue #82 for the tests.
I have also left a comment at the top of the file on how to use this file. 
1. import the file (const sendEmail = require('./email-sender);) 
2. send email (sendEmail.sendMessage("Put your error message in here");)
=> Fix #25: Implement basic email sender

env.example, feeds-redlist.json, feeds.txt, src/inactive-blog-filter.js
Addresses #22. Had to perform some workarounds on this one as we do not yet have an official feed-worker implemented. That issue has been assigned to @robertbegna in issue #108, and I didn't want to take away from any work he might want to do. In order to test my implementation, I had to create a new, altered feed-worker in _/test_.
A _feeds-redlist.json_ was created in _root_, which contains filtered feeds. Since they are not permanently banned or anything, I didn't want to call it a "blacklist". Each item contains an `url` attribute for the feed, and a `lastUpdate` attribute (ISO 8601 datetime string) for the blog's last known activity, according to the feed data. A 0 value means the blog has a dead feed.
New module created in _/src/inactive-blog-filter.js_, which performs most of the …
=> Fixes #22: Inactive Blog Filter

env.example, package-lock.json, package.json, src/github-url.js, test/github.test.js
Closes #54 
This takes a valid Github URL and returns fetched data related to it from the [GitHub API](https://developer.github.com/v3/).
At the moment, it supports URLs for:
- Users: https://github.com/{myUser}
- Repositories: https://github.com/{myUser}/{repository}
- Issues https://github.com/{myUser}/{repository}/issues/{issue#}
- Pull Requests https://github.com/{myUser}/{repository}/pull/{pullRequest#}
Every request to the GitHub API returns a big chunk of data, and I chose the properties that I thought could be interesting for Telescope. This can be changed, please feel free to suggest other properties.
To see full chucks of data fetched from the GitHub API:
- User [Seneca-CDOT](https://api.github.com/users/Seneca-CDOT)
- Repository …
=> Closes #54: Fetch data from GitHub API

test/feed-parser.test.js
I think the only test case missing here is one for testing an IP address, as feedParser will actually try to connect to an IP address instead and get `ECONNREFUSED (IP here)` message instead for the test case. Perhaps @evlnyng could provide some insight if she is available.
=> Fixes #156 Add test cases for feedParser

src/feed-worker.js
updated function to return an array of "processed" post objects.
=> Fix #108: integrate feed parser with feed worker

test/inactive-blog-filter.test.js
This pull request adds testing for the `check()` function defined in [inactive-blog-filter.js](https://github.com/Seneca-CDOT/telescope/blob/master/src/inactive-blog-filter.js#L41).
This pull request does *not*, however, cover testing for the `update()` function. As noted in https://github.com/Seneca-CDOT/telescope/issues/197#issuecomment-554145637, the creation of some testing environment, or some alteration of the `update()` function needs to be done to facilitate proper testing. I plan to continue looking into this, and plan to make a separate pull request when I come up with a solution.
=> Added tests for inactive blog checking (#197)

src/email-sender.js
Nodemailer no longer has explicit variables in their transport. 
Remove the Explicit Parameter in Nodemailer transport function. Bug Fix for PR #93 #226
=> Fix #226: Remove Explicit Parameter Bug Fix

test/count-blog-domain.test.js
Test module domain-analysis.js countDomain function. Input is an array of blog url objects and expect the output to be an array of object with format {name: domainName, count: number}.
=> Fix#95 Add test for counting domains from blog posts

package-lock.json, src/login/login.html
Created a simple html login page for SAML testing purposes
=> fix #91: created a login page for SAML testing

src/frontend/style/main.css
Fixing issue #189
On mobile views we have the following issues:
- The buttons when tested with poor vision individuals I got feed back that they should be sligthly larger so I updated the font size, by a 40% ratio.
- On our close functionality we have an issue with the system where when we close on devices of small range and strange screen targets ( Asus Zenfone 2 and iPhone 4 tested) the close menu function didn't react , the solution was to increasing the close "x" to a rate of 75%
this changes can be seen prototype in
https://cagomezr.github.io/telescope-demo/
This  pull request was done as the  rebasing was having issues and having very very strange results.
=> Fixing issue #189

.travis.yml, src/feed-queue.js
We don't have an `.env` provided, and our queue depends on a Redis URL.  Let's provide a fallback.
=> Fix #238: include a default redis URL for CI

package-lock.json, package.json, test/github.test.js, test/setupJest.js
Fixes #208 and fixes #225.
The GitHub tests now use [`jest-fetch-mock`](https://www.npmjs.com/package/jest-fetch-mock)  for mock responses. I tested if offline and the tests passed.
Examples for `jest-fetch-mock` [here](https://www.npmjs.com/package/jest-fetch-mock#simple-mock-and-assert) and [here](https://github.com/mattiaerre/jest-do-it/blob/master/008-jest-fetch-mock/current-weather.test.js).
=> Fix #208 Use mock responses when testing the GitHub data fetching

test/feed-parser.test.js
As suggested in #243, I am adding `.skip()` to the failing tests while it is being fixed. I am looking into using mock responses instead (see #245).
=> Fix #243: Skipping failing tests in feed-parser.test.js

package-lock.json, package.json, src/wiki-feed-parser.js
This pull request refactors the code in the repository to use node-fetch instead of Bent for requests.
To avoid having multiple dependencies for doing the same thing, it would be a good idea to replace Bent with node-fetch wherever it is used. Closes #206
=> Fixes #206 - Refactor code to use node-fetch instead of Bent

src/feed-queue.js, src/lib/queue.js, src/lib/redis.js, src/storage.js
I'm testing a theory on the test failures in #252.  To do it, I made a fix for #258, and merged/updated the work in #252.  I want to see what this does on Travis.
=> Fix #252, #258, #299: add logging to feed queue, refactor lib/redis, lib/queue

package.json, src/backend/web/app.js, src/backend/web/routes/index.js, src/backend/web/server.js, src/count-blog-domain.js, src/lib/logger.js
=> Fix 274 Add pino logging to backend

.gitignore, .vscode/extensions.json, .vscode/launch.json, .vscode/settings.json
This PR addresses issue #256 
I added a basic `.vscode` folder with some code formatting config, extension recommendation (eslint, prettier and editorconfig) and a script to run debugging in VSCode.
I am open to more idea on what to add.
=> Fix issue #256: Add .vsccode folder

src/lib/queue.js, src/lib/redis.js
The problem was the way `src/lib/queue.js` and `src/lib/redis.js` were importing `logger`.
Adding destructuring fixed it. 
Please test it before approving.
=> Fix #305: Fix test failure with logger.debug()

src/frontend/index.html, src/frontend/style/main.css
fixes  #242 
Added the search button as well as its animation to HTML/CSS. The button will transition between two states, as pictured below 
**FROM:**
**TO:**
=> Search bar added to Navbar instead of participants

.eslintrc.js, .gitattributes, .travis.yml
This PR disallows eslint to enforce consistent line endings. This is being done to support our windows users, who are currently not able to pass linting tests. To make sure any code that is added now has consistent line endings, 'lf' in our case, I have also added a `.gitattributes` file. You can read more about it [here](https://git-scm.com/docs/gitattributes). 
Specifically about [text](https://git-scm.com/docs/gitattributes#_code_text_code) and [eol](https://git-scm.com/docs/gitattributes#_code_eol_code).
=> Fix #323: Disable linebreak style and add gitattributes

test/feed-parser.test.js, test/fixtures.js
Added new `fixtures.js` module for reusable code in testing. For now, as @ragnarokatz suggested, it contains some `nock` calls that were previously used in `feed-parser.test.js`, but could have been reused. I also created constants for the test blog URIs (atom/rss) as well as the valid feed return body, exposing them through the module. This should help begin our development of more robust tests by introducing fixtures that reproduce specific test environments. Once again, thanks to @ragnarokatz for providing the suggestion! #318
=> Addresses #318 - Add fixtures.js

src/feed-worker.js, src/index.js, test/feed-worker.test.js
Reference issue #172.
**Status update:**
Ready for review.
Solution: extracted worker callback function out, changed it to using promises instead of done, made it much easier to cope with unit testing.
**Historical conversations:** (outdated, still good for reference)
WIP Update:
I need help with writing the test cases to validate the `feed-worker.js` module. Currently it is not working.
Contrary to its name, the function `queue.process` does not process anything immediately upon its call, **it's actually registering a callback function for the queue that is only called everytime a job is placed in the queue**. See bull's official documentation here: https://github.com/OptimalBits/bull/blob/develop/REFERENCE.md#queueprocess.
Since code inside the callback function gets called at a later …
=> Fix #172: implement queue failed feeds behaviour

src/extract-urls.js, src/feed-worker.js
Got rid of the annoying console.log spams when running ```npm test```
fixes https://github.com/Seneca-CDOT/telescope/issues/333
=> deleted console logs from spamming tests

test/feed-parser.test.js, test/fixtures.js
Finishing work begun by @nazneennahar in https://github.com/Seneca-CDOT/telescope/pull/219.  This adds more tests for the feed parser, and closes #72.  I've switched to using `nock` for the network requests vs. live URLs.
=> Closes #72: Adds more test cases to feedParser.test.js

test/sanitize-html.test.js
This fixes #343, removing the `src` attribute on the test case's `<img>` element, thus papering over the issue with DOMPurify/JSDOM and `fetch()` not being present.
Probably the right fix is to move to using Puppeteer and a full DOM in the future.
=> Remove src attribute on <img> to avoid failing with fetch not existing in JSDOM

README.md
The link has been updated and now the logo link in our Readme.md points to CDOT's GitHub repo
=> Issue #348: Update logo link to Seneca-CDOT's GitHub Repository

docs/CONTRIBUTING.md, package.json
Adding jest --watch option to the code will allowed user to do detailed test on the files.
After using command `npm run watch` user will see pop up menu that will give options  what commands can be run in order to perform analysis on the files:
=> Fix #205: Add jest -watch option

src/backend/utils/inactive-blog-filter.js, test/inactive-blog-filter.test.js
Improving the coverage for the `inactive-blog-filter` file by adding tests for the `dateDiff` function. I also had to export the `dateDiff` function in order to test it. See #197, doesn't close it but helps move it forward.
- - -
Before:
- - -
After:
=> Add test for dateDiff function. Improving coverage for inactive-blog-filter.

.circleci/config.yml, .travis.yml
This attempts to add support for Chromium and Puppeteer to Circle CI, following instructions at https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md#running-puppeteer-on-circleci and using https://circleci.com/orbs/registry/orb/threetreeslight/puppeteer.  Fixes #384.
=> Fix #384: Add puppeteer orb for Circle CI builds

.travis.yml
Fixes #387 partially, by allowing Windows builds to fail, but not failing Travis overall.  This is a bandaid, meant to get our builds to pass while we sort out how to deal with Redis in CI.
=> Allow Windows builds to fail without failing Travis overall

package.json, src/backend/utils/reading-level.js, test/reading-level.test.js
Issue #84 
Implemented the [reading-level](https://www.npmjs.com/package/reading-level) node and created tests for the function.
Tests only check if the unrounded reading level matches the expected result and if errors occur, as I figured those would be the most important values. I can modify the tests to check if all the returned values match the expected result, but it requires another function to be run for each test.
Also left documentation for using reading-level in the reading level-module.
=> Added reading-level module with tests

src/backend/utils/inactive-blog-filter.js, test/inactive-blog-filter.test.js, test/test_files/inactive-blog-filter.test-active-feeds.txt, test/test_files/inactive-blog-filter.test-dead-feeds.txt, test/test_files/inactive-blog-filter.test-inactive-feeds.txt
Fixes #197: builds upon #211 and #380 to boost testing coverage for `inactive-blog-filter.js` into the green (representing a significant step towards the resolution of #268).
Fixes #199: both the `check()` and `update()` functions of `inactive-blog-filter.js` now use [fs.promises](https://nodejs.org/dist/latest-v10.x/docs/api/fs.html#fs_fs_promises_api). Thank you, @MeisterRed, for agreeing to collaborate!
=> Fixes #197, fixes #199: revamp inactive-blog-filter and tests

package.json, src/backend/utils/text-parser.js, test/text-parser.test.js
Switch from JSDOM to Puppeteer for parsing HTML to Text
=> Fixes #187: switch from jsdom to puppeteer

package.json
Addresses #406 by updating `package.json` to specify that Telescope developers must use node version 10.0.0 or later.
As suggested by https://github.com/Seneca-CDOT/telescope/issues/406#issuecomment-560959353, this pull request alone may not fully resolve that issue.
=> Addresses #406: specify node engine version in package.json

.gitignore, docs/CONTRIBUTING.md, generate_ssl_certs.sh
Fixes issue #319 
- Add bash shell script to generate ssl certificates using openSSL
- Add instructions on how to do it in CONTRIBUTING.md.
- Add certs/ folder to .gitignore
Documentation update:
Generating a a new certificate:
=> Fix #319: add script to generate ssl certificates

.gitignore, package.json
This pull request is to address #283. After a discussion with @humphd the decision was to use lighthouse. I have added two npm scripts, lighthouse-index, and lighthouse-login, to allow testing of the front-end. The results are presented in an HTML file and are displayed after executing the commands. Also added the extension to .gitignore to ensure the report results are not pushed.
=> Fixed #283 added lighthouse testing

docs/CONTRIBUTING.md
Addressing #386 , this pull request updates the CONTRIBUTING.md to include docker and docker-compose instructions. It also includes updated instructions on installing Redis. 
There are variables in the docker-compose file that use the .env file to create the environment, and I am unsure of how to replicate it in the native application instructions. In my mind, we should remove the native set up entirely, and focus on using docker.
Another aspect of this pull request is the .env file. Specifically how to fill out the credentials inside of it. I am working on this aspect but I thought I would put up a pull request and get some feedback before I continue. 
UPDATE: I have talked to some people and understood the .env file better, I will update the environment set up in a new pull request, as …
=> Fixes #386 - Added specific environment instructions in CONTRIBUTING.md

src/backend/utils/storage.js
While making changes during class, adding `guid` when storing a post (in `storage.js`) didn't get merged with the rest of the code.
Here's a fix for that.
=> Added guid when storing a post

src/frontend/index.html, src/frontend/server-sent-events.js
Fixes issue #314. 
This PR addresses the client-side changes for server sent events.  Changes were made to allow listening to the stream endpoint using EventSource. Receives data whenever a job is completed in the queue.
Server-side PR for this fix can be found in #409
=> Fixes #314: Client-side changes for server sent events

src/backend/utils/email-sender.js
I created a template for the email-sender, this will make it easier for the users to identify the errors that are coming in from the Telescope project. 
Currently when you send an email, it would send plain text for the message that is passed. 
The functionality for the email sender did not change, but is displayed in the following format
I created the email template using HTML Table elements and made a simplistic design which will make it easier for the code to be maintained/changed if necessary.
=> Fix #190: Create an template for email-sender

src/backend/web/routes/posts.js
Added encoding the url passed to the front-end.
For testing
- run telescope: `npm start` (and redis)
- requests all the posts using a browser: `localhost:3000/posts`
It returns:
```js
[
{
id: 'http://wordpress.com'
url: '/post/http://wordpress.com'
}
...
]
```
- use `url` from the json returned in the previous step to request one post
- 'localhost:3000/post/http://wordpress/com'
The expected result should be a [Post](https://github.com/Seneca-CDOT/telescope/blob/5b583c63f88d1fdf9b0aac077f744ad8ccddcb74/src/backend/post.js#L7) object
=> Fixes #428: Encode guids in URLs returned in posts JSON results #428

src/backend/index.js, src/backend/lib/shutdown.js
I refactored the shutdown logic into its own file in `lib/shutdown.js` to simplify our main entry point.  I also removed a stray `async` call and unnecessary `log()` while I was testing.
=> Refactor shutdown logic into separate file

test/wiki-feed-parser.test.js
I added some test cases for wiki-feed-parser for #220 .
The getData seems to escape all the newline characters in the body of the mock fetch response. I am not sure why it does this. 
Also not really sure what's the expected error codes in the cases of failures, such as no pre tag or failed fetch, so I only added placeholders for now.
@cryolis thoughts?
=> Fixes #220: Added testcases for wiki-feed-parser

src/backend/utils/storage.js, src/backend/web/routes/posts.js, test/storage.test.js
`GET /posts` now accepts a [query parameter](https://guides.emberjs.com/release/routing/query-params/) to request a specific number of posts, with a max of 100 posts.
If no parameter is passed, it'll returned 30 posts.
For testing:
- Run telescope `npm start` (with redis)
- In a browser, go to:
- `localhost:3000/posts`, the number of posts shown should be 30
- `localhost:3000/posts?counter=50`,  the number of posts shown should be 50
- `localhost:3000/posts?counter=200`,  the number of posts shown should be 100
=> Closes #432, #437: Limit number of posts returned by HTTP /posts route

test/posts.test.js
Initial set of tests for `/posts` route.
It checks for:
-  `/posts` should return 30 items by default
- `/posts?per_page=15` should return 15 items
- `/posts?per_page=150` should return 100 items (100 is our max value)
This can be expanded in the future adding tests for paging and count.
=> Closes #431: Add tests for HTTP /posts route

test/posts.test.js
The tests for `/posts` were failing because of `async` in the describe part of the test.
This fixes that problem.
=> Fix bug in posts tests

src/backend/feed/worker.js, src/backend/lib/queue.js
This improves our logging for errors while processing feeds in our queue.  Here's an example of what an error looks like now:
```
[ 2019-12-04 12:48:42.164 ] ERROR (43651 on brightness.local): Unable to process feed https:https://robertbegnatechblog.wordpress.com/category/open-source/feed for job 2060
err: {
"type": "Error",
"message": "Invalid URI \"https:https://robertbegnatechblog.wordpress.com/category/open-source/feed\"",
"stack":
Error: Invalid URI "https:https://robertbegnatechblog.wordpress.com/category/open-source/feed"
at Request.init (/Users/humphd/repos/telescope/node_modules/request/request.js:273:31)
at new Request (/Users/humphd/repos/telescope/node_modules/request/request.js:127:8)
at request (/Users/humphd/repos/telescope/node_modules/request/index.js:53:10)
at …
```
=> Improve error logging in worker

package.json, src/backend/feed/worker.js, src/backend/utils/sanitize-html.js, test/sanitize-html.test.js
This fixes #352, moving away from DOMPurify and JSDOM, and using [sanitize-html and htmlparser2](https://github.com/apostrophecms/sanitize-html).  This fixes a number of test failures we're seeing.
As we start using the server more, we can tweak the settings for what gets cleaned/ignored by the sanitizer.  For now, by default it allows the following:
```js
allowedTags: [ 'h3', 'h4', 'h5', 'h6', 'blockquote', 'p', 'a', 'ul', 'ol',
'nl', 'li', 'b', 'i', 'strong', 'em', 'strike', 'code', 'hr', 'br', 'div',
'table', 'thead', 'caption', 'tbody', 'tr', 'th', 'td', 'pre', 'iframe' ],
allowedAttributes: {
a: [ 'href', 'name', 'target' ],
// We don't currently allow img itself by default, but this
// would make sense if we did. You could add srcset here,
// and if you do the URL is checked for …
```
=> Fix #352: switch away from DOMPurify/JSDOM to sanitize-html

.github/ISSUE_TEMPLATE/bug-report.md, .github/ISSUE_TEMPLATE/enhancement.md
In regards to issue #347, these are the issue templates for bug reports and enhancements. They are built with the default GitHub templates and the ones used by Kubernetes in mind.
These can likely be improved and iterated on further. If there are any other things to add that would be useful, please let me know.
=> Add issue templates

.circleci/config.yml, .travis.yml, package.json
We've had a few PRs recently that missed running Prettier (probably it wasn't installed via Husky in their environment).  This adds another script to `package.json` to run [`prettier --check`](https://prettier.io/docs/en/cli.html#--check), and use it in CI to help catch PRs with missing prettier formatting.
On development machines, running `npm test` is fine, since we don't want to error if files aren't committed yet (i.e., husky+prettier haven't run yet).
=> Add test-ci script to also check prettier on CI

test/feed-worker.test.js, test/fixtures.js
Change tests in `feed-worker.test.js` to use mocked up responses from `fixtures.js` instead of going out to web to get real responses, similar to how tests are being done in  `feed-parser.test.js`.
referencing issue #469
=> Fix #469: change feed worker tests to use nock

docs/CONTRIBUTING.md, package.json, src/backend/utils/add-feed.js, tools/add-feed.js
fix #273. This PR is unfinished but I wanted to create one for feedback before I commit more work into this. I have a working script with some bugs. I've manually tested the script by checking the bull board and confirming the feed job was queued.
To run the script, use ``` npm run add-feed -- --name "bloggers name" --url <feed url> ```. This will make use of the feedQueue.add under ``` src/backend/feed/queue ``` to add a feed to the queue for processing. 
I wanted to make this as an npm script so I changed package.json but if the script is executed using npm, the appropriate error messages seem to be suppressed and it gives a vague npm error message instead. When run as ``` node add-feed.js ..etc ``` the proper error and info messages are displayed.
=> Added add-feed script to manually add a feed to the queue

src/backend/utils/storage.js, src/backend/web/routes/posts.js, test/storage.test.js
Paging added to `/posts`.
Using `page` now it's possible to request a set of posts with `per_page` number of posts in it, or `default` number of posts if `per_page` is not present.
Examples:
- `/posts` should return 30 items
- `/posts?page=2` should return 30 items, but the second 30 items in our set
- `/posts?per_page=15` should return 15 items
- `/posts?page=3&per_page=15` should return 15 items, but the third page of 15 items
`Link` headers have been added with URLs for `next`, `prev`, `first`, `last`.
These will allow the browser to navigate without having to construct URLs for the other pages.
Example:
- for `/posts?page3=per_page=15`
- `</posts?per_page=15&page=4>; rel="next"`
- `</posts?per_page=15&page=2>; rel="prev"`
- `</posts?per_page=15&page=1>; rel="first"`
- …
=> Closes #441: Update /posts route to support paging

env.example, src/backend/lib/queue.js, src/backend/lib/redis.js
Fixes #315 
- Added REDIS_PASSWORD to the env.example
- Added password to the Bull queue constructor
In order to pass password to the Redis constructor, I had to change the parameter list to the following, according to the [documentation](https://github.com/luin/ioredis/blob/master/API.md#new-redisport-host-options):
```js
new Redis(port, host, redisPassword);
```
=> Fixes #315: Added password to the Bull queue constructor

package.json, tools/README.md, tools/html-elements.js, tools/lib/process-posts.js
Enhancement
This adds a new `html-elements` tool, which allows us to get info about all the HTML elements used in blog posts, and their counts.  I wanted to know what people actually use, so we can build our UI and other tools to accommodate it.
You run it like this:
```
$ npm link
$ html-elements
Processing 5534 posts...
Processing 194,922 elements...
1. <br> (69,015)
2. <p> (36,408)
3. <a> (19,760)
4. <div> (15,244)
5. <li> (8,779)
6. <td> (7,124)
7. <strong> (6,432)
8. <img> (6,205)
9. <code> (4,448)
10. <pre> (4,076)
11. <b> (3,176)
12. <em> (2,699)
13. <ul> (2,325)
14. <tr> (1,790)
15. <h3> (1,726)
16. <i> (1,380)
17. <h4> (1,075)
18. <blockquote> (1,004)
19. <ol> (538)
20. <hr> (441)
21. <table> (365)
22. <tbody> (364)
23. <th> (269)
24. <h5> (133)
25. <iframe> …
```
=> Add html-elements tool and docs for other tools/

src/backend/utils/sanitize-html.js, test/sanitize-html.test.js
Add ```<figure>``` tag to allowedTag for sanitize-html as it is common for blog post.
feature improvement
Added 'figure' to allowedTag and changed one related test case.
=> Fix#487 add figure tag to allowedTag for sanitize-html

src/backend/lib/queue.js, src/backend/utils/count-blog-domain.js, src/backend/utils/email-sender.js, src/backend/utils/inactive-blog-filter.js, test/basic_analysis.test.js
This PR fixes #361 by adding the standard `{error}` object followed by a message for all `log.error` calls.
This is an enhancement to standardize the way we log errors, which can be very helpful in debugging if done properly.
This PR changes files that use the `log.error` functionality.
=> Fix #361: Update error logging

src/backend/feed/worker.js, src/backend/post.js, src/backend/utils/storage.js, src/backend/web/routes/post.js, src/frontend/scripts/main.js, test/feed-parser.test.js, test/fixtures.js
Fixes #496 
Bug fixes and enhancement
This PR alters the way our `Post` type works, expanding its behaviours to encompass all data parsing and database logic.  Specifically:
- Removes unneeded properties (e.g., `wordCount`)
- Renaming some of the properties to better reflect what they are (e.g., `html`)
- Adding both `url` and `site` info for a post
- Adding methods to parse a `Post` from the `article` object produced by the `feedparser`, and also from a regular JS object (e.g., from JSON or out of Redis)
- Added method to `save` a Post to redis
- Added method to get a Post `byGuid` from redis
All of the code in here is being used, but we should add more tests in another PR.  I'd do it now, but I'm building something else based on this code. …
=> Fix #496: refactor and expand Post class

test/routes.post.test.js
Added tests for `post/` route
In this PR, I have implemented tests for `/post/:guid` route.
Tests cover the following cases:  
- `404` - a post with a passed `guid` not found;
- `200` - a post with a passed `guid` found and returned;
- both _encoded_ and _not encoded_ cases are tested
While testing on my local machine with the latest version of the `master` branch, `inactive-blogs-filter` was failing - and so it did on my branch.
=> Issue 430: Added tests for the post/ route

src/backend/lib/queue.js
The queue logs everything, which is good, but only when you're debugging.  In normal operation (e.g., `info` or `error`) we don't need all this log spam.
This reduces it by moving most things to `debug` level.  I've also gotten rid of the module level sub-logging, since we don't really need it (we can probably dump it from everywhere).
=> Reduce amount of logging by queue in info vs debug level

src/backend/web/routes/posts.js, test/posts.test.js
Closes #509
Removed `/count` endpoint and added total number of posts to `X-Total-Count` header.
Also, added tests to check the value of `X-Total-Count` and removed test for `/count`.
=> Closes #509: Move /posts/count to X-Total-Count header for /posts

README.md, docs/CONTRIBUTING.md
Adds a link to our new Slack channel, so people can find it.  I put it in multiple places so it won't be missed.
=> Add link for #telescope Slack channel to various docs

docs/CONTRIBUTING.md, package.json
This tweaks our Jest setup a bit, and adjusts the docs accordingly.
First, it moves `coverage` to its own script vs. doing it every time we run the tests.  I find it annoying to have to scroll up to see what failed.  If someone wants coverage info (not the norm), they can run it manually.
Second, it allows passing file name patterns to jest so you don't have to run all the tests every time if you only want to test one thing.
=> Move coverage to its own npm script, allow passing args to Jest

env.example, src/backend/feed/processor.js, src/backend/feed/queue.js, src/backend/feed/worker.js, src/backend/index.js, test/feed-processor.test.js, tools/add-feed.js
Fixes #503
This PR improves our feed parser.  Specifically, it makes it run forever, continually downloading the feeds and parsing them into Redis.  It also allows for parallelization, so we can run multiple instances of our feed worker in different processes.
In order to make this work, I've also done a few other things:
- Moved the feed parsing to its own file, `src/backend/feed/processor.js`, so that we can run it in a separate process or processes
- Altered our retry attempts and delay timing when feeds fail.  What I have still isn't quite right, but what we had before was way to extreme, and the queue would back-up with failed jobs
- Added a new `env` variable: `FEED_QUEUE_PARALLEL_WORKERS`.  This is the number of parallel worker instances to run in separate processes, and can be 1, …
=> Parallelize feed parser, make it run forever

src/backend/feed/worker.js
This fixes a bug introduced with https://github.com/Seneca-CDOT/telescope/pull/547.  Specifically, if the `env` doesn't have `FEED_QUEUE_PARALLEL_WORKERS` set, it won't start any processor functions to deal with posts, and Redis won't have anything in it.
To test this, try starting the server with various `env` settings:
- Nothing set: `#FEED_QUEUE_PARALLEL_WORKERS`
- 1 Worker Process: `FEED_QUEUE_PARALLEL_WORKERS=1`
- 2 Worker Processes: `FEED_QUEUE_PARALLEL_WORKERS=2`
- As many Worker Processes as CPUs: `FEED_QUEUE_PARALLEL_WORKERS=*`
When the server starts, it will log out the number of parallel workers it is using, and it should match what you set in the env:
```
[ 2020-01-20 21:10:45.787 ] INFO  (42097 on brightness.local): Starting 4 instances of feed processor.
```
=> Fix logic for picking FEED_QUEUE_PARALLEL_WORKERS with missing env var

.eslintrc.js, package.json, src/backend/feed/queue.js, src/backend/utils/basic_analysis.js, src/backend/utils/email-sender.js, src/backend/utils/github-url.js, src/backend/utils/inactive-blog-filter.js, src/backend/utils/sentiment-analysis.js, src/backend/utils/storage.js, src/backend/utils/summarize.js, src/backend/utils/word-counter.js, test/basic_analysis.test.js, test/email-sender.test.js, test/feed-queue.test.js, test/inactive-blog-filter.test.js, test/posts.test.js, test/spam-checker.test.js, test/storage.test.js, test/word-counter.test.js
- **Bugfix**: Change which fixes an issue
Added eslint rules regarding promises, we have promises that have catches and returns and some don't. These rules ensure consistency
=> Fixes #525: Add eslint-plugin-promise and fix async/Promise issues

src/backend/lib/queue.js
Fixes #122
As suggested in https://github.com/Seneca-CDOT/telescope/issues/48#issuecomment-550079621, added logic to handle 'ECONNREFUSED' errors within the Bull queue: 'ECONNREFUSED' are now logged an informative blurb instead of a stack trace.
https://github.com/Silvyre/telescope/blob/818ba4c9404f2cd5f2a70b7826a3650f1c215587/src/backend/lib/queue.js#L32-L43
=> Fixes #122: add logging to inform user of Redis connection failure

src/backend/index.js, src/backend/lib/shutdown.js, src/backend/utils/wiki-feed-parser.js, test/wiki-feed-parser.test.js
This is follow-up to the work done to add eslint for Promises and async/await.  I've reduced the warnings we get down to 1.  Do do it, I made the following changes:
- switched to async/await in the shutdown code
- rewrote the wiki-feed-parser to use async/await
- refactored the wiki-feed-parser so that it doesn't expose the `getData()` function anymore.  There is no need to expose this.  I've also removed the tests for this.  The other tests we have already run that code.
There is still one warning:
```
/Users/humphd/repos/telescope/src/backend/utils/email-sender.js
67:22  warning  Avoid callbacks. Prefer Async/Await  promise/prefer-await-to-callbacks
```
My guess is we'll rip this code out soon, so I didn't bother fighting with it.
=> Reduce eslint Promise warnings, refactor wiki parser

src/backend/lib/config.js, src/backend/utils/wiki-feed-parser.js
Fixes #396
Ensures that every `process.env` call within the code base is provided with a default value (as specified in #396) to ensure that they have some value on CI, and thus do not cause unwanted behaviour during CI testing.
The default value provided to each `process.env` is either one specified within `env.example` (if one exists), or `null`.
=> Fixes #396: add default values to environment variables

src/backend/web/routes/feeds.js, src/backend/web/routes/index.js, test/feeds.test.js
Closes #523 
This PR adds the endpoints `GET /feeds` and `GET /feeds/:id` with tests.
This allows us to requests feeds from the server using:
`http(s)://localhost:3000/feeds`
The expected response should be: 
To request a specific feed:
`http(s)://localhost:3000/feeds/{id}`
Expected response:
=> Closes #523: Add /feeds route to match what /posts does

package.json, src/backend/lib/shutdown.js, src/backend/web/server.js
Fixes #603
This PR wraps our web server with the [stoppable](https://github.com/hunterloftis/stoppable), to keep track of open/long-lived web connections and close them when shutting down.  Currently, these are keeping our process from exiting cleanly.
To test this:
1. Start the server: `npm start`
1. Open some web connections (e.g., `http://localhost:3000/planet`, ``http://localhost:3000/admin/queues`, ``http://localhost:3000/graphql`, etc)
1. Kill the server in your terminal with `Ctrl+C`
You should get a clean shutdown:
```
[ 2020-01-26 08:55:49.150 ] INFO  (66737 on brightness.local): Received SIGINT, starting shut down
[ 2020-01-26 08:55:49.150 ] ERROR (66737 on brightness.local):
error: "SIGINT"
[ 2020-01-26 08:55:49.153 ] INFO  (66737 on brightness.local): Web server shut down.
[ …
```
=> Fix #603: make web server stoppable

env.example, src/backend/feed/queue.js
1. Fixes #611 
1. Fixes #608
I was trying to understand why our staging box had 68K+ delayed jobs in the queue, and discovered that we are using the wrong id name for our jobs.
When adding a job to a Bull queue, you can either use the default job number, an auto-incrementing integer, or [you can specify your own](https://github.com/OptimalBits/bull/blob/develop/REFERENCE.md#queueadd).  The problem with the latter is that it means that you can easily add multiple jobs for the same task, since each one is keyed on a number that has nothing to do with the data in the job.  If you instead provide a key that is unique to the job itself, you can have Bull ignore duplicates.
We actually tried to do this before, and instead of using `jobId` we used `id`, so Bull is ignoring it.  This change …
=> Use feed.id as jobId to de-dupe job queue

src/backend/data/feed.js, src/backend/feed/processor.js, src/backend/index.js, src/backend/utils/storage.js, test/feed-processor.test.js, test/feed.test.js, test/feeds.test.js, test/fixtures.js, test/storage.test.js
Fixes #445.  Addresses some of #548.
This PR changes how we deal with feed data that is already cached in Redis.  I've added two new optional fields to the `Feed` class: `etag` and `lastModified`.  These correspond to the HTTP headers of the same name.
An `ETag` is a kind if unique identifier for a resource.  If the resource changes, the `ETag` changes.  Likewise, the `Last-Modified` header indicates the date/time that the resource was last updated.  It's not always accurate, and may only represent the last time you requested the resource.  Taken together, the two provide useful clues for a server about whether or not a resource that you have cached is still valid, or whether it needs to send it again.
When requesting data from the server, you can add `If-Non-Match` and …
=> Use ETag and Last-Modified headers to cache feeds

src/backend/web/routes/planet.js
This sorts the planet's feed list the same as the original planet did.
=> Match original planet, sort feed list

.travis.yml
#451  fixed for windows certs. 
This installs openssl on our travis CI, and then runs a shell script that should generate the scripts needed to create our own certificates.
Travis CI is run on the github repository, so it will be using the travis ci build here to do the testing.
=> fix #451 testing certs for windows

src/backend/web/planet/views/compare-planets.handlebars, src/backend/web/planet/views/planet.handlebars, src/backend/web/routes/planet.js
This adds a new route for debugging `/planet/compare` which lets you load our old and new planets side by side in the same window to easily compare.  I got the idea from @cindyledev, who has been doing this in some issues, and it gives us a quick way to see differences.
NOTE: the two planets aren't currently pixel perfect with one another (#621 for example).
Here is what it looks like:
=> Add /planet/compare route

src/backend/data/post.js, src/backend/utils/storage.js, test/post.test.js, test/posts.test.js
This PR modifies a `Post` Object's `text` property from being a static member to a dynamic getter.  In other words, we'll only generate `.text` on demand, and don't need to store it in Redis.  This will save us a bunch of duplication in the database.
This change will require flushing Redis, so we get rid of the `text` field in our `Post` hash:
```
redis-cli flushall
```
This doesn't affect our GraphQL code at all, it still works as before.  For the HTTP route, once #443 is finished, we can update to have that be the preferred way to get plain text over HTTP.  cc @yatsenko-julia .
=> Make post.text a dynamic getter instead of storing

package.json, src/backend/data/stats.js, src/backend/utils/storage.js, src/backend/web/routes/index.js, src/backend/web/routes/stats.js
This adds some new routes, and backend support for getting some basic statistics about posts.  Here is what the data looks like:
```
$ curl localhost:3000/stats/month
{ "posts": 74, "authors": 17, "words": 15628 }
```
I'm wondering if this might be useful in our UI to show on the front page somehow, to give a sense of what's happened recently.  If we don't use it in the UI, it's interesting to be able to get this data regardless.
Specifically, I've done this:
- ability to get posts from Redis by date range
- ability to calculate stats for number of posts, number of authors, number of words in all posts for a given date range via a new `Stats` object.
- new routes to get this data: `/stats/today`, `/stats/week`, `/stats/month`, `/stats/year`.  Each of these gives stats from the beginning …
=> Initial work on /stats route for post statistics

src/backend/data/article-error.js, src/backend/data/post.js, src/backend/feed/processor.js
Part of #548
This adds a new error type, `ArticleError`, which allows us to filter out a bunch of errors we get when an article is missing data that we need to create a post.
By fixing this, I've now dealt with 2/3rds of the errors we get when running normally.  I just have to deal with fatal network errors, which I'll do in a follow-up.
To test this, run the server like this:
```
LOG_LEVEL=info npm start
```
It will look like this, showing what happens as it processes each feed, downloading content (200) or using our cached version (304), etc:
```
[ 2020-01-28 20:57:56.162 ] INFO  (80339 on brightness.local): [HTTP 200 - OK] Feed has new content: http://haxbyte.wordpress.com/category/Open%20Source/feed/
[ 2020-01-28 20:57:56.258 ] INFO  (80337 on brightness.local): [HTTP 304 - Not …
```
=> Don't log errors when articles are missing fields

src/backend/utils/sanitize-html.js, test/sanitize-html.test.js
Updated sanitize-html.js, so all needed tags are allowed, the rest are disallowed. Needed tags are taken from the list provided by @humphd in [issue-487](https://github.com/Seneca-CDOT/telescope/issues/487). Also, test for <iframe> tag added.
=> fix-556: updated sinitize-html.js and test for iframe tag added

now.json
I'm trying to a couple of tweaks to the Zeit Now `now.json` config:
- [disabling issue/PR comment spam](https://zeit.co/docs/configuration#git-integrations/github-silent).  This might be too much, and we might want to re-enable this, I'm not sure.
- [try to make it possible for people other than me to see build/deploy logs](https://zeit.co/docs/configuration#project/public).  I'm not sure if this will work without trying it.
=> Tweak Zeit Now config

src/backend/web/routes/admin.js
Currently, there's not way to have access to `dev.telescope`'s logging information. This adds an endpoint that will return the information that would normally be shown on our terminal when we run telescope locally.
Provide a name for a log file either using `LOG_FILE=` in our `.env` file, or at launch with `LOG_FILE=myfilehere npm start`
=> Access logging information using GET /admin/log

package.json, src/frontend/gatsby-config.js, src/frontend/package.json
Fixes #580 , Fixes #581 
Updating package.json, package.json and gatsby-config.json in src/frontend/. Removed redundant information. Shifting devDependencies from `src/frontend/package.json`
`"json-loader": "^0.5.7",
"node-sass": "^4.13.1",
"sass": "^1.24.4",`
to `package.json`
=> Fix #580: updating package.json, package.json in src/frontend and gatsby-config.js

Dockerfile, developer.Dockerfile
Generates docker containers using a the native multistage build process, specifically for the staging environment. This reduces the current container size from ~1.91GB (640MB with @humphd's experiment) to  ~251MB!
```
telescope_telescope           latest              95b308226ca8        4 minutes ago       251MB
<none>                        <none>              5957bf2d5b55        4 minutes ago       940MB
<none>                        <none>              986285b4fdda        8 minutes ago       773MB
node                          12.15.0-alpine3.9   72805eb6a2b6        46 hours ago        84.9MB
redis                         latest              44d36d2c2374        7 days ago          98.2MB
kristophjunge/test-saml-idp   latest              a85d01fab7df        2 years ago         457MB
``` …
=> adds: docker multistage builds for reduce container sizes

docker-compose-staging.yml, docker-compose.yml, nginx.conf, src/frontend/src/components/Layout/Layout.js
This PR changes settings in our docker-compose files to restrict access to our redis container from outside of the docker network. Port `6379` should be unreachable now.
=> fix: Change settings to restrict access to redis container

docker-compose.yml
This PR addresses 2 issues:
- Telescope still needs access to `redis` from outside of the docker network when `redis` runs using docker-compose and telescope is launched using the command line. For that, it's necessary to specify `redis'` port in the `docker-compose` file used for development.
- Also, to be able to access telescope when it's launched using docker, the port used in our `.env` must be added to our `docker-compose` file used for development.
=> Fix: Add ports for telescope and redis local deployment

src/frontend/src/components/Login/LoggedIn.jsx, src/frontend/src/components/Login/LoggedOut.jsx, src/frontend/src/components/Login/Login.jsx
@Grommers00, @agarcia-caicedo and I were discussing functional vs. class components in React.  I refactored the recent Login component we were working on at the time to be functional so we would have an example to discuss.
The main changes here:
- split out the `LoggedIn` and `LoggedOut` components to their own files
- switch from using an ES6 class to a function for Login
- use `const [email, setEmail] = useState(null);` to deal with state.  The `useState()` React function returns an array with 2 things: the current value of the state, a function to update it.
- switch from `componentDidMount()` to `useEffect()`.  Notice the use of the `[]` as the last arg, which will mean it only fires once on startup.
- moved away from Promise-based `fetch` code to use async/await
=> Refactor Login frontend component to be functional

nginx.conf
Progress towards #691 
This is initial work to be able to use `SSO` with `HTTPS`.
This PR makes sure that `POST` requests sent from a client don't turn into `GET` requests due to a [301](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/301) response in our `nginx.conf`. For that, [307](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/307) will be used instead.
> The only difference between 307 and 302 is that 307 guarantees that the method and the body will not be changed when the redirected request is made. With 302, some old clients were incorrectly changing the method to GET: the behavior with non-GET methods and 302 is then unpredictable on the Web, whereas the behavior with 307 is predictable.
Also, `login.telescope.cdot.systems` now redirects to the correct route.
=> Fix: Change response from 301 to 307 and redirect request to the right route

src/backend/data/feed.js, src/backend/data/post.js, src/backend/data/stats.js, src/backend/feed/processor.js, src/backend/feed/queue.js, src/backend/feed/worker.js, src/backend/index.js, src/backend/utils/storage.js, src/backend/utils/wiki-feed-parser.js, src/backend/web/graphql/index.js, src/backend/web/planet/views/planet.handlebars, src/backend/web/routes/feed.js, src/backend/web/routes/planet.js, src/frontend/src/components/Login/Login.jsx, src/frontend/src/components/TextArea/TextArea.jsx, test/feed-processor.test.js, test/feed.test.js, test/fixtures.js, test/post.test.js, test/posts.test.js, test/wiki-feed-parser.test.js, tools/add-feed.js
Fixes #716, #665
This is a WIP to remove duplicated feed info such as `author` and `site` from a Post, and replace it with the id of a `feed`.  For example:
```
curl -H 'Accepts: application/json' http://localhost:3000/posts/00107ba358
{
"id": "00107ba358",
"title": "Part 3: ZFS Setup",
"html": "<p>...</p>",
"published": "2019-12-18T04:43:05.000Z",
"updated": "2019-12-18T04:43:05.000Z",
"url": "https://ebraublog.wordpress.com/2019/12/18/part-3-zfs-setup/",
"guid": "http://ebraublog.wordpress.com/?p=58",
"feed": "4f53e7478d"
}
curl -H 'Accepts: application/json' http://localhost:3000/feeds/4f53e7478d
{
"id": "4f53e7478d",
"author": "Eric Brauer",
"url": "https://ebraublog.wordpress.com/category/CDOT/feed/",
"etag": "W/\"1e7899a6c0d9861dcc15f2434092f4d3\"",
"lastModified": "Thu, 13 Feb 2020 …
```
=> Remove author, site from Post, add feed id

src/backend/feed/processor.js
#624, which was closed by #726
Implements the functionality to make the feed processor 'back off' from delayed feeds, which somehow ended up disappearing from PR #724.
_A big thank-you to @c3ho, who discovering that this functionality was missing from the original PR!_
=> Follow-up to PR #726: complete feed processing delay implementation

src/backend/web/routes/feeds.js, test/feeds.test.js
This will allow us to connect our front end and back end to post the data to add the feeds to the master list.
=> fix #707 adding post route for /feeds

src/frontend/gatsby-config.js, src/frontend/package.json, src/frontend/src/pages/myfeeds.js
Addresses #730 - Pick a React component library as our base UI toolkit 
Resolves #725 - Prototype the Add Feed view in React 
- Addresses #730 by completing our frontend's installation of MaterialUI with [`gatsby-theme-material-ui`](https://www.gatsbyjs.org/packages/gatsby-theme-material-ui/#webfonts). The remainder of the MaterialUI installation was previously done by @miggs125.
- (It is worth noting that, by default, the installation of `gatsby-theme-material-ui` enforces some global styling changes to the frontend, e.g. changing the default font to Roboto. This default styling [can be overwritten](https://www.gatsbyjs.org/packages/gatsby-theme-material-ui/#webfonts), if we'd prefer.)
- (AFAIK, we're keeping #730 open for the purposes of discussion.)
- Resolves #725 by adding a 'My …
=> Complete Gatsby MaterialUI installation plus 'Add Feeds' page wireframing

src/frontend/gatsby-config.js, src/frontend/package.json
Fixes #697 
This is actually pretty confusing to use and I've only had success with getting the data as a StaticQuery instead of a Page.  To test changes, use `npm run develop` and navigate to http://localhost:8000/__graphql. 
There should now be a checkbox called `telescope` on the left hand side. Once you click on that you'll find all the other queries we have set up. The `telescope` is like a wrapper. The great thing is, you can build your query in there and then export it using `Code Exporter`. Make sure when you export you change the dropdown from `Page Query` to `StaticQuery`
One thing to watch out for is that when you get the data, its an object, so to get at the data that I want in my above query(title) I have to do something like `JSON.stringify(data.telescope.getPosts)`
=> Connect GraphQL to Telescope

src/frontend/src/pages/myfeeds.js
Fixes #745 
Connected this to the back end, I had to repurpose the `+` button to add feeds for now! Sorry @Silvyre. 
Easiest way to test this is to just change the index.js under pages to display `myfeeds` component. To add a feed use the `+` button after inputting name and feed info, make sure devTools is opened prior to clicking the button so you can evaluate the response from the server. A `409` error means your feed already exists, to get around it just modify some of the characters for the blog url.
=> Add Feeds needs to be now to be connected front end to back end 

.release-it.json, docs/release.md
1. Fixes #704
This updates our release-it config to not try and publish to `npm`, and removes the `--dry-run` instructions, since they don't work.  I've also updated the docs to have the person running this pull the latest tags so the changelog will work (it's looking for changes since the last tag, and if you don't have it, you don't get a changelog).
If we want to test this, we could do a 0.7.1 release.  It might be good to get #781 merged first, though.
=> Fix #704 - update docs, settings for release

src/frontend/src/components/Post/telescope-post-content.css
1. Fixes #767
I've adjusted our styles for `<pre>`, `<code>`, and combos of the two.  I tried two approaches to inline code, and don't know which I like better (currently I left it dark):
Which one do you like better?
=> Fix #767: Adjust styles for <pre> and <code> in posts

src/frontend/src/components/Post/Post.jsx, src/frontend/src/components/Posts/Posts.jsx
I've tried reducing the width of the posts, so that we have fewer words per line.  I also reduced some font sizes in the heading to make it work better.
Compare with these:
- https://medium.com/@REAS/collecting-in-the-age-of-digital-reproduction-ab0640a42fe6
- https://www.newyorker.com/sports/sporting-scene/the-blockbuster-video-game-that-wants-to-make-america-whole-again?utm_source=twitter&utm_brand=tny&mbid=social_twitter&utm_social-type=owned&utm_medium=social
- https://www.nytimes.com/2019/11/04/science/voyager-2-interstellar-solar-wind.html
- https://longreads.com/2019/11/07/california-burning/
I think going any wider makes it hard to read, as your head/eye has to travel to take in the whole line.
See my notes in https://github.com/Seneca-CDOT/telescope/issues/339.
=> Reduce width of posts to match other sites

src/frontend/package.json, src/frontend/src/components/Post/Post.jsx, src/frontend/src/components/Post/syntax-highlight.js
@Silvyre got me thinking about this during class today, and it turns out to be possible!  This uses [highlight.js](https://highlightjs.org/) to do automatic language detection and syntax highlighting.
I've enabled all the languages I think we typically see at Seneca, but if you want others added, we can do that too.
=> Add automatic syntax highlighting for <pre> post elements

src/frontend/src/components/Post/Post.jsx
This increases the amount of text we can see on mobile, reducing padding around the post.  I think the reduced space is also nice for larger sizes, too, but let me know if you disagree.
=> Fix post padding for mobile

src/frontend/src/components/ScrollToTop/ScrollToTop.jsx, src/frontend/src/theme.js
Fixes #793 
Changes primary color used in `theme.js` to `telescope-blue` as I call it, which is `#a4d4ff`. Can be changed to whichever is preferred.
MDDPI-Screen
HD Phone Screen
=> fixes: utilizes telescope-blue as primary color, makes FAB larger

package.json, src/backend/web/app.js
Fixes #669 
Implemented helm.js to hide 'powered by' when you do a `curl -I` to the website, the header should not contain the line anymore.
=> Add Helmet js to disable "Powered-By" in response header

src/frontend/src/components/Post/Post.jsx, src/frontend/src/components/Post/telescope-post-content.css
This plays with the colours in the heading and text of links in posts, which I want to connect more closely to our colour theme:
=> Improve colours for links, text in heading on post

src/backend/data/post.js, test/post.test.js
Fixes #757 
- Posts missing a publication date will no longer be processed/displayed (with tests updated accordingly).
- If a post is missing a date of last update but has a publication date, its date of last update will be set to its publication date.
- (As a result, this PR rids Telescope of an infamous nuisance post...)
=> Fix #757: reject posts without publication date

Dockerfile
Fixes #825 
On my system with changes, the build time for a local docker instance after doing the first successful build (and thus caching dependencies) and modifying a line in the backend code as a test comes out to:
```
real	0m6.243s
user	0m0.375s
sys     0m0.064s
```
**Limitations  for  Docker caching**: any change to package.json and it's related dependencies will force a new container build. Source code changes otherwise should not trigger rebuild of cached containers.
=> fixes: ensures docker cache dependencies when package.js is not modified

docs/elasticsearch.md, docs/environment-setup.md
Closes #832 
Documentation for environment setup and usage.
=> Closes #832: Documentation for Full-Text Indexing(ElasticSearch)

src/frontend/src/components/Banner/Banner.css, src/frontend/src/components/Banner/Banner.jsx
Fixes #789, with a hint of Fixes #830 dashed in.
Further improves on font responsive sizing with @cindyledev help.
This references the `/stats/year` to display the total amount of words written in the current year. This is the first step in the stats component, with GitHub contributions stats being added next. Likewise, aware that on LowDPI screens it overlaps with main title. That will be corrected. Open to suggestions on that fix.
=> adds: post stats component to banner

src/backend/web/graphql/index.js
Closes #665 
Small PR that adds a new resolver to define how to deal with `posts`, a new added field to the `Feed` type definition in our `GraphQL` module. 
With this, it'll be possible to fetch all the posts related to a feed when using `getFeedById` or `getFeedByUrl` by simply adding `posts` (and subfields) to a query:
For testing, use one of the available methods to get feeds from telescope (`REST` or `GraphQL`), and select one id or url to be used with `getFeedById` or `gefFeedByUrl`, adding `posts` and subfields to the query as shown in the image above.
**Important**: It's better to let telescope run until all the feeds are processed before trying the new resolver. Querying Telescope too soon might result in an empty `posts` array since it'd mean that Telescope hasn't processed the …
=> Closes #665: Nested Queries in GraphQL

package.json, src/backend/web/app.js
Fixes #701 
- Installs the [`graphql-passport`](https://www.npmjs.com/package/graphql-passport) module, which enables us to apply our `passport.js` authentication functionalities to our GraphQL queries.
- **My testing method of choice:**
1. Check out this PR locally
1. Run `npm install`, installing the added `graphql-passport` module
1. Within `src/backend/web/graphql/index.js`, add `context` as the third parameter of a GraphQL resolver of your choice.
- e.g. The parameters of [`getPosts`](https://github.com/Seneca-CDOT/telescope/blob/master/src/backend/web/graphql/index.js#L126) would be updated as such: `(parent, { filter, page, perPage })` -> `(parent, { filter, page, perPage }, context)`
- (It is not necessary to make any changes to `typeDefs`)
1. Within the function body of your …
=> Add graphql-passport to Telescope

src/frontend/src/components/Banner/Banner.jsx, src/frontend/src/components/Header/Header.jsx, src/frontend/src/pages/search.js
Fixes #765 
This fix stops the Header from overlapping on top of the SearchBar in the Search Page and any future pages that will have the Header. The Hero Banner had an anchor that added extra space at the top so I removed it. 
Search Page:
Home Page:
=> Fixes #765 add toolbar mixin underneath Header bar

src/backend/data/stats.js
1. Fixes #858 
When we altered the way that feeds get stored on posts, we didn't update how the counting works in our stats.  This changes it so that instead of using the feed object itself, we use the feed author's name.
=> Fix #858: Use feed.author when counting post authors in stats

src/backend/utils/sanitize-html.js, test/sanitize-html.test.js
Fixes #813
Youtube / Vimeo videos now show up in the feed.
=> Fixes #813: Whitelist YouTube/Vimeo iframe elements in post content

src/backend/utils/sanitize-html.js
Fixes #837 
Thank you @Silvyre for investigating this issue, his fix suggestion was exactly the solution. This PR adds the `<del>` tag to our allowedTags so that 'strikeout' (Wordpress uses `<del>` for some reason) texts are displayed properly
=> Fixes #837 add del tag to allowedTags

.gitignore, docker-compose-staging.yml, docker-compose.yml
Closes #666 
This PR adds persistent storage for local and staging.
Right after deployment, redis will create a directory (if it's not there yet) and will store Telescope's data in a file (`appendonly.aof`). At launch, redis will load Telescope's data and will log a message:
For local, the directory created by redis will be in the Telescope directory, and it's been added to `.gitignore`.
For staging, the directory will be outside of `./telescope` so it won't get deleted when auto-deployment gets triggered by a merge to master.
**Testing**
- Launch Telescope and let it run for while.
- Once a good number of feeds have been processed, navigate to `localhost:3000` and take a look at the state of `index.html` (posts, number of contributors and words) .
- Stop Telescope and redis.
- Relaunch …
=> Closes #666: Add data volume to redis container

.release-it.json, package.json
Fixes #880
We filed an upstream bug after @Silvyre tried to run our release, and it put the assets in the wrong repo.  The [bug was fixed](https://github.com/release-it/release-it/commit/2ab8aaf060b7dc9d5e783e47cdfa415ee0e85320), so I've updated our version of release it and added a `pushRepo` for our GitHub Release section in the config.
After we land this, I'll get @Silvyre to do a 0.8.3 release to test it.
=> Fix #880: add pushRepo to github release step in release-it, update version

src/backend/web/app.js, src/backend/web/authentication.js, src/backend/web/routes/admin.js, src/backend/web/routes/auth.js, src/backend/web/routes/user.js
Fixes #775
- [] **UI**: Change which improves UI
While I was writing https://blog.humphd.org/not-so-simple-saml/ I re-read all of our SSO/SAML code and noticed a few things that still needed attention.  This cleans those up, and I *think* I'm not down playing with this.
To test this:
- start the `login` container, and any others you need to run the app locally
- build the front-end `npm run build`
- start the back end `npm start`
Now try testing the various ways that we do authentication and route protection.  There are at least 3 things worth mentioning.
1. Make sure you can still log in and log out as before.
2. Log out and try going to `/admin/queues`.  You should be redirected to a login page.  Log in and then it should immediately take you to the Bull Queue UI.  Hitting the Back …
=> More SSO cleanup

src/frontend/src/components/Banner/Banner.css, src/frontend/src/components/Banner/Banner.jsx
Fixes #872 
Makes `Banner.jsx` and `Header.jsx` responsive for various mediums. Tested using Firefox Responsive tool for:
- 720p
- iPhone SE
- Samsung Galaxy S9 
- 1080p
Styling / spacing etc all up for debate. Simply getting the discussion going in this PR.
Banner Improvements (WIP)
=> adds: responsive adjustements for banner component

docs/environment-setup.md, tools/autodeployment/deploy_stage.sh
After landing #871, Telescope kept serving a version of the front end that was 2 commits behind #871. The problem turned out to be the command used in autodeployment for deleting all the docker elements related to Telescope (`docker system prune -af`). This command doesn't get rid of volumes, which is what we're using to share data between containers. As a result, Telescope was serving an old frontend stored in a persistent volume on `dev.telescope.cdot.systems`.
To fix this, adding `--volumes` (as suggested [here](https://linuxize.com/post/how-to-remove-docker-images-containers-volumes-and-networks/)) to the command used in autodeployment will also remove all volumes and new ones will be created for every new deployment.
@raygervais helped me debug this and found out that the problem was …
=> Fix reusing volumes in staging deployment

src/frontend/src/components/Banner/Banner.jsx
Fixes #892 
This adds the same opacity transition trick used by the Banner background  to the Banner stats component. Makes the loading and API call less jarring to the user since text would simply appear and update the previously blank numeric values.
=> adds: fade-in transition for stats once loaded

docker-compose.yml, docs/login.md, env.example, env.staging, saml20-idp-hosted.php, simplesamlphp-users.php, src/backend/web/app.js, src/backend/web/authentication.js, src/backend/web/routes/admin.js
1. #709
This change adds support for Admin users.  I had to fix some other things along the way.  Here's what it does:
1. I had to fix how our simplesamlphp Identify Provider does its `nameID` for the fake users.  Previously we added a file to our docker container to create different users, and have their `profile` match what we get from Seneca.  The one thing we didn't do was tell the server to use the `email` as the `nameID`, so it was generating a random one each time.  I need that value to be stable, so I've added another file that does this in `saml20-idp-hosted.php` and mounted it in in the docker container.
1. I've added a new variable to the `env`s called `ADMINISTRATORS`.  This is a space-delimited list of users who are administrators.  You can use their email address or the …
=> Fix #709: add backend support for Admin users

src/backend/web/__mocks__/authentication.js, src/backend/web/authentication.js, src/backend/web/routes/feeds.js, test/feeds.test.js, test/lib/authentication.js
Fixes #734 
This adds a Jest mock for our SAML authentication strategy, allowing test code to login, login as an admin, or logout.
I've also added `protect` to our `POST /feeds` route, and updated the tests.
Any code for authenticated routes can use this.
=> Fix #734: add mock authentication for testing

env.example, env.staging, package.json, src/backend/utils/wiki-feed-parser.js, test/wiki-feed-parser.test.js
Fixes #702 
This PR adds a functionality that prevents Telescope from crashing when the feed list is not available. If CDOT wiki is down, Telescope will keep trying to fetch the list in intervals of a number of milliseconds that can be set in our `.env` (default value is 30 seconds).
Testing:
Testing this functionality is tricky since we can't control when the feed list is available. Because of that, we will start a little server locally and make telescope fetch the feed list from it.
Steps
- Once you're in the PR's branch, set `env.example` as your `.env`.
- In `.env`, set
- `FEED_URL_INTERVAL_MS=5000`
- `FEED_URL=http://localhost:4000/Planet_CDOT_Feed_List`
- Download the feed list from CDOT wiki:
- e.g. `wget https://wiki.cdot.senecacollege.ca/wiki/Planet_CDOT_Feed_List`
- Remove the …
=> Fixes #702: Unreachable feed list causes the feed queue to error and not recover

src/frontend/src/components/Login/LoggedIn.jsx
Fixes #914
This PR adds a means to navigate to the My Feeds component via a Header link. 
When a user is logged in, clicking on their username (within the Header) will now redirect them to the My Feeds page.
This change does not involve adding any additional elements to the (already-full) Header, which was a point a concern.
=> Fixes #914: link logged-in user's name to MyFeeds page

docs/gatsbyjs.md, env.example, package.json, src/backend/web/routes/index.js
Fixes #732
Cindy wanted to be able to use the Gatsby hot-reload dev server with our backend.  I've added a proxy middleware that does this if you set `NODE_ENV=development` and `PROXY_GATSBY=1` in your `.env`.  It will only work on a development box.
This should save people hours when developing the frontend and needing to quickly test changes without a rebuild.
It also supports logging in, which is awesome.
=> Add Gatsby dev server proxying (PROXY_GATSBY)

src/backend/utils/__mocks__/elastic.js, src/backend/utils/elastic.js
Part of #908, #919 
This adds a `deletePost()` method to our elastic client library.  It allows us to remove a post from the index.
One thing I'm not sure about is whether or not to refresh the index as part of doing this.  See https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/api-reference.html#_delete and  https://www.elastic.co/guide/en/elasticsearch/reference/7.x/docs-refresh.html:
> `refresh`:   'true' | 'false' | 'wait_for' - If true then refresh the affected shards to make this operation visible to search, if wait_for then wait for a refresh to make this operation visible to search, if false (the default) then do nothing with refreshes.
I've also updated the elastic mock to have more methods.  I haven't implemented a proper mock for `search()`, but we …
=> Add elasticsearch delete for posts, update elastic mock

src/backend/web/__mocks__/authentication.js, test/lib/authentication.js
For #955 we need to be able to get the `id` of the currently logged in user in our tests.  This is necessary for doing any redis/elastic stuff with the current user, since it's all based on `id`, and the `id` is a hash of their email.
=> Update test authentication to return user object with id

Dockerfile, docs/environment-setup.md
Fixes #936 
Having reinstalled Windows 10 Pro on the development system due to a crashed Linux build, I saw that getting Telescope running with the Unix-esque WSL engine had some semantic issues which W10 Pro could improve on. That being, using the edge (unstable) version of Docker desktop and the WSL-2 engine for container pass-thru, so that we don't need to install Docker in Ubuntu itself, or utilize Virtual-box.
I realized while trying to optimize the builds that we could cache the front-end builds for the back-end developers, meaning that if no git commit occurs or front-end code is changed, the build time is reduced from minutes to seconds in some cases. This bug was realized when I saw that we had removed some older dependencies which required tools and files which existed outside …
=> adds: Docker for WSL 2 / Windows 10 Pro and Front-end Caching Optimization

src/backend/data/feed.js, src/backend/data/post.js, src/backend/utils/__mocks__/elastic.js, src/backend/utils/storage.js, test/feed.test.js, test/storage.test.js
Part of #908 
Calvin's part - Changes to Redis, Feed, ElasticSearch to allow CRUD operations.
Deleting a feed causes the feed's posts in Redis + ElasticSearch to be removed as well.
=> Feed type should support delete, modify (delete + create)

.eslintrc.js, src/backend/data/admin.js, src/backend/data/user.js, src/backend/web/authentication.js
Builds on the `User` type, and adds an `Admin`.  I've connected it into our administration middleware, which runs after passport.js, but before the router.  Any user who is an admin will get automatically upgraded.
=> Extend User type and add Admin type

.eslintrc.js, package.json, src/frontend/package.json, src/frontend/src/components/MyFeedsPage/DeleteFeedDialogButton.jsx, src/frontend/src/components/MyFeedsPage/ExistingFeedList.jsx, src/frontend/src/components/MyFeedsPage/HelpPopoverButton.jsx, src/frontend/src/pages/myfeeds.js
Fixes #746
Fixes #760
Fixes #946
Fixes #746 by finalizing the implementation of buttons on the My Feeds page:
- Clicking on the `?` button of the My Feeds page now opens a [popover](https://material-ui.com/api/popover/) containing a helpful message.
- Uses [`material-ui-popup-state`](https://www.npmjs.com/package/material-ui-popup-state) (simplifies popover state management)
- Introduces form handling/validation via [`react-material-ui-form-validator`](https://www.npmjs.com/package/react-material-ui-form-validator).
- (One of the custom-defined validation rules uses the `valid-url` module, which was previously added to Telescope for use in our backend.)
- Calling `addFeed()` now causes a status message to be rendered to the page, indicating whether its fetch request to add a feed …
=> Fix #746, #760, #946: enhance the My Feeds page

src/frontend/package.json, src/frontend/src/components/SnackBar/SnackBar.jsx, src/frontend/src/components/SnackBar/index.js, src/frontend/src/pages/index.js
Fixes #791 
Adding a `setInterval` to the front end that will query telescope to see if the # of posts has changed.
It is currently set at 5 seconds as I'm still working on it. How it should ideally work:
1. The page is loaded: we get posts, total posts count AND start a timer. When we fetched for the total posts count, we assign it to two states `initNumPosts` and `currentNumPosts`.
2. Every 5s the attached timer will fetch for total posts count and assign that value to currentNumPosts.
3. At the return statement portion of `index.js` I have a conditional that will render the component `CustomizedSnackBar`. I set it so that as soon as the `CustomizedSnackBar` component is rendered it will trigger an alert `There are new post(s) available`.
I also updated the package `@material-ui/core` …
=> Add a way to receive updates when new posts are available

src/frontend/src/pages/myfeeds.js
Fixes #976
From #976:
> it would be nice if the component for adding a new feed was always at the top vs. the bottom. To get mine, I'd have to scroll all the way to the end of the existing feeds:
> 
> What if we move that to the top, and maybe put a little bit of empty vertical space between it and the existing feed list?
> 
> Most users will only have 1 or 2 feeds, so this won't be an issue for everyone. Nevertheless, I think having the place that you add new ones always be at the top would be good.
This PR simply moves the existing feed list to after the new feed form controls, such that the new feed controls are always by the top of the component.
Further styling concerns related to this PR or #976 may be addressed via #945.
=> Fixes #976: moves new feed form to above existing feeds list

src/backend/data/admin.js, src/backend/data/user.js, src/backend/web/__mocks__/authentication.js, src/backend/web/app.js, src/backend/web/authentication.js, src/backend/web/routes/admin.js, test/feeds.test.js, test/user.test.js
We added a bunch of code for user vs. admin routes, and didn't completely finish it, or fully integrate it.  We also didn't do proper test coverage for the admin side.
This fixes that, specifically:
- removes the `administration` middleware, and puts it in `passport.deserialize()`
- moves the administration account check into `Admin.isAdmin()`
- updates our authentication mock to properly support both user and admin accounts
- fixes a bug with how we serialize a user to the session, adding the `.isAdmin` property
- makes the `/admin/*` routes all require an admin account
- adds test for admins deleting a feed owned by a regular user
- adds tests for `/user/info` for users and admins
- adds tests for `/user/feeds` to make sure admins get all feeds vs. only ones they own
Much of this is …
=> Refactor admin code, add more tests

src/frontend/src/components/Footer/Footer.jsx, src/frontend/src/components/Header/DesktopHeader.jsx, src/frontend/src/components/Header/MobileHeader.jsx, src/frontend/src/pages/index.js
Fixes #817 
Initially meant to put this Footer underneath all the blog posts but I notice that after we hit the last blog post, it actually continues to load more blog posts so it doesn't make sense to put the footer there. This adds Footers to the bottom of the side drawer for both the DesktopHeader and MobileHeader.
=> Fixes 817 added Footer to DesktopHeader and MobileHeader

src/frontend/src/components/Post/Post.jsx
Fixes 799. This feature is not available on Safari or IE but supports by all other browsers.
To test:
Open Developer Tools-> Network-> IMG-> start scrolling the web page and see how resources loading while scrolling
=> Fix #799: add native lazy loading

.vscode/launch.json, docs/git-workflow.md
I updated our VSCode config so that we an debug Telescope from within VSCode.  This allows starting the server and attaching the VSCode debugging environment.
I wanted to add this so that people can debug things more easily from their editor, and without having to do anything difficult to get node debugging to work.
Here's an example of what it looks like.  I'm debugging the `/stats/year` route bug in #858, and I've clicked on "Run" in the VSCode debugger.  This started our backend, and then I set a breakpoint.  After that I hit the `/stats/year` route and it dropped me into the debugger, where I can step through code, inspect things, etc.
=> Add Telescope VSCode debug launch configuration + docs

package.json, src/backend/utils/elastic.js, src/backend/utils/wiki-feed-parser.js
Progress towards #990 
This removes the warnings related to elasticsearch 
```
/Users/humphd/repos/telescope/src/backend/utils/elastic.js
116:10  warning  Prefer await to then()  promise/prefer-await-to-then
```
and wiki-feed-parser
```
/Users/humphd/repos/telescope/src/backend/utils/wiki-feed-parser.js
59:10  warning  Prefer await to then()  promise/prefer-await-to-then
```
=> Fixed eslint warnings

src/backend/index.js
Addresses #920
Issue #920 lists two end-goals for our feed processing:
> 1. We need to keep downloading the wiki feed list regularly, so we can get updates
> 1. We need to stop using the wiki feeds as our feed list in the feed queue, and instead need to get our feeds from Redis
This draft attempts the first step towards the completion of the second stated end-goal: enqueuing Redis feeds _in addition to_ Wiki feeds for processing.
Once I can be sure that we have established a good starting point, here, I will seek guidance on any next steps involved.
I did note that the Wiki feed list is processed and saved to Redis _as part of_ the enqueuing process:
```
loadFeedsIntoQueue()
→ processWikiFeeds()
→ processFeeds()
→ updateFeed()
→ Feed.create()
→ Feed.save()
```
Since our end-goal is to: …
=> Process Redis feeds in addition to Wiki feeds

.vscode/launch.json, src/backend/web/routes/admin.js, tools/autodeployment/README.md, tools/autodeployment/env.example, tools/autodeployment/info.js, tools/autodeployment/package.json, tools/autodeployment/server.js
This updates the deployment server to do a few things:
1. adds a `/status` endpoint, so we can get info on what's happening (idle or building), what the duration of the build is, what the result of the last build was, etc.
1. fixes a bug where we would crash if someone tried to hit an endpoint other than the ones we expect (we needed a callback)
1. added logging for stdout and stderr
=> Add /status to deploy server, fix callback missing bug

src/frontend/src/pages/index.js
Part of #990 
Refactored our async functions existing outside of `useEffect()` hooks to use `useCallback()`. The only es lint warnings remaining are on line 84 and from my testing, adding the dependencies `post` or `nextPageLink` as recommended will cause the issue in #1018 
I kind of hate the front-end and its dependencies...
From what I understand:
1. `useEffect` line 108 is called every re-render
2. `useEffect` on line 113 is caused by either `getPostsCount`(async function) or change to `currentNumPosts`(state). This sets the current and initial # of posts to whatever the current # of posts in redis is
3. `useEffect` on line 127 should be caused by the callback on line 108? This causes it to start the timer to get the updated # of posts every 5 mins and set currentNumPosts to the new …
=> Fix eslint issues in index.js

src/frontend/src/pages/index.js
Fixes #1027 
Regression test:
1. Set line 131 to a more frequent number unless you want to check every 5 mins for the change. To make sure fixes didn't break current functionality
2. Flush redis db (`redis-cli flushall`)
3. Make sure you're using localhost:3000 for the backend
4. `npm run develop` + `npm run start`
5. Alert should appear on interval set as redis is being populated
To test bug fix:
1. run `npm develop`
2. go to `localhost:8000`, the alert shouldn't appear at the start anymore before posts load + unless there are actual new posts
=> Fixed snackbar appearing on page load

src/frontend/src/pages/index.js
#fixes #999 
Changes the intitial state of `endOfPosts`, which would display `'No more posts.  Your turn! Add your feed...'` if defaulted to true. Instead we default to false and allow the spinner to take priority in the render view.
=> fixes: shows the loading spinner first instead of "no more posts"

package.json, src/backend/data/post.js, src/backend/utils/syntax-highlighter.js, src/frontend/package.json, src/frontend/src/components/Post/syntax-highlight.js, test/syntax-highlighter.test.js
I want to start moving any processing that can be done in the backend out of the frontend.  First up, syntax highlighting.
It's a bit more complicated to do it in node, because the library requires a DOM.  I use JSDOM to extract the bits it needs, feed them in one-by-one, and then replace the content with marked up versions.
I've added some basic tests, and we can extend this as we see things we like or don't like happening, and add little fixes.
NOTE: I'm not removing the frontend code fully yet, only reducing how much it runs.  The new code will check to see if it needs to run the highlighter or not, and skip it if it's already been run.
I need the work @c3ho is doing in #1033 to land first, since I need all post content to be highlighted in the backend when we store it.  Then I can do …
=> Start moving syntax highlighting to the backend

nginx-production.conf, nginx-staging.conf
More work toward #1042, this alters our nginx config to add gzip compression for text types we serve.
For reference:
- https://docs.nginx.com/nginx/admin-guide/web-server/compression/
- https://www.digitalocean.com/community/tutorials/how-to-increase-pagespeed-score-by-changing-your-nginx-configuration-on-ubuntu-16-04
- http://nginx.org/en/docs/http/ngx_http_gzip_module.html
This should help further reduce the size of our transferred html, js, etc. on the network.
=> Enable gzip compression in nginx

src/backend/data/admin.js, src/backend/data/user.js, src/backend/web/__mocks__/authentication.js, src/backend/web/authentication.js
Fixes #982.  This adds back the `nameID` and `nameIDFormat` values we get from the Seneca IdP.  We need this to be able to properly do an IdP SLO Logout.
This is impossible to test until it lands on staging.  So I mostly need a code review here, and if someone could test it locally.
=> Fix #982: restore nameID to user info for logout requests

src/backend/web/authentication.js
This line got added for testing, but I don't think it's helping, and could potentially be causing our failure to logout.  Let's remove it.
=> Remove HTTP-Redirect auth request binding

src/backend/web/authentication.js
In https://github.com/bergie/passport-saml/blob/master/lib/passport-saml/saml.js#L228-L246, the `saml.js` backend needs `req.user.nameID` to exist. My fix in #1051 missed adding this, even though I did it in the mock.
This includes it.
=> Include nameID and nameIDFormat in req.user

nginx-production.conf, nginx-staging.conf
Fixes #1047
This tunes our nginx configs to use Linux and the hardware we have more efficiently.  It will run multiple worker processes instead of 1, and allow more connections per worker.  This also improves writes and how we poll in the kernel.
@manekenpix when we deploy this on staging, we should take a look at how the machine runs overall.
=> Tune nginx configs to run more efficiently

env.example, env.production, env.staging, test/posts.test.js
Fixes #1036
As part of #1042, we need to reduce the size of our DOM.  The easiest way to do this is to load fewer posts.  We have code to "load more" now, so we don't need so many at once.
This drops it down to 10.  We might be able to go lower still, but let's see how this performs.
=> Fix #1036: reduce number of posts loaded on startup

src/backend/data/post.js, src/backend/utils/html/dom.js, src/backend/utils/html/index.js, src/backend/utils/html/lazy-load.js, src/backend/utils/html/sanitize.js, src/backend/utils/html/syntax-highlight.js, src/frontend/src/components/Post/Post.jsx, test/dom.test.js, test/lazy-load.test.js, test/sanitize-html.test.js, test/syntax-highlight.test.js
This moves the `<img>` and `<iframe>` lazy loading out of the frontend and does it in the backend during feed processing.  I've refactored the backend HTML processing code to share some common bits (e.g., use the same JSDOM instance).  I've also added and updated tests.
I still want to test this more, but it's close I think.
=> Move img and iframe lazy loading to server

nginx-production.conf, nginx-staging.conf
We're not adding the necessary cache headers to our static files, and browsers don't know that they can cache them.  This adds default expiry info for different static types we serve.
See https://www.digitalocean.com/community/tutorials/how-to-implement-browser-caching-with-nginx-s-header-module-on-centos-7 for info on this.
=> Add expires header info to nginx

docker-compose-production.yml, docker-compose-staging.yml
This adds persistent storage for Elasticsearch.
As explained [here](https://discuss.elastic.co/t/elastic-elasticsearch-docker-not-assigning-permissions-to-data-directory-on-run/65812/3), the directory in the host that will store Elasticsearch's data needs to be owned by `1000:1000`.
Since setting up Elasticsearch is always difficult for contributors, and adding this feature to the development workflow could mean another headache that developers would have to deal with (not everyone knows how to change file permissions and/or ownership), I thought it'd be better if persistent storage would only be available for staging and production.
=> Add persistent storage for elasticsearch

nginx-production.conf, nginx-staging.conf, src/frontend/package.json, src/frontend/plugins/gatsby-plugin-top-layout/TopLayout.js, src/frontend/plugins/gatsby-plugin-top-layout/gatsby-browser.js, src/frontend/src/components/Banner/Banner.jsx, src/frontend/src/components/Post/telescope-post-content.css, src/frontend/src/components/ScrollToTop/ScrollToTop.jsx, src/frontend/src/pages/PageBase.js
This changes how we load the Roboto web font.  Instead of pulling it from Google, this installs it into our tree using the `typeface-roboto` package, which is how [Gatsby suggests you do it](https://github.com/gatsbyjs/gatsby/search?q=typeface&type=Code&utf8=%E2%9C%93).
I've also added caching info for web fonts to our nginx so they will get held at the browser and not need to be re-downloaded.
I've also removed all the duplicate CSS resets we had, fixed a typo with one of the Roboto instances (lower case r),
=> Move Roboto web font into our tree

src/frontend/plugins/gatsby-plugin-top-layout/TopLayout.js
I'm starting to work on webhint fixes, and one problem we have is that we have two `<meta name="viewport">` declarations.  This removes the second:
=> Remove second meta viewport declaration

nginx-production.conf, nginx-staging.conf
We need to define `utf-8` for our `content-type` headers when nginx serves content.  This adds it. See http://nginx.org/en/docs/http/ngx_http_charset_module.html.
=> Set charset to utf-8 in nginx

src/frontend/src/pages/index.js
Fixes #1060 
Created new state [update, setUpdate] to let when `getPostsCount()` should run (not at the beginning). Only the first `useEffect` (line 56) should run now at startup.
To test:
1. open up dev tools on chrome and go to `Performance` tab.
2. Press the record button and reload telescope page, stop as soon as posts load
3. Check if there are two fetch requests to telescopeUrl/posts
=> Stop loading /posts twice on startup

src/backend/data/feed.js, src/backend/web/routes/feeds.js, test/feed.test.js, test/feeds.test.js
Fixes #1030 
Allows admin users to "clear cache" for Redis through a put request at the route `feeds/cache`. This sets the `lastModified` + `etag` field to null.
Added a new PUT route - `feeds/cache/`
Added new function in `feed.js` - `clearCache()`
Added new tests to `feed.test.js`
Added new tests to `feeds.test.js`
Testing instructions:
**Requires local backend!**
1. Find an admin account
2. Use `redis-cli smembers t:feeds` to get a list of feedId and pick one of them
3. Use `redis-cli hgetall t:feed:(feedId)` to get info of all the fields for the feed, make sure the `etag` and the `lastModified` field is not null / populated
4. While logged in as admin, hit the route `telescopeUrl/feeds/cache`, this should clear the `etag` + `lastModified` fields in Redis and set it to `null`
5. Use …
=> Add UI for Admin to trigger reparsing all posts from feeds

nginx-production.conf, nginx-staging.conf
We don't set proper `Cache-Control` headers on the files built by Gatsby.  This tries to fix that.  I'm not 100% sure that I've done it correctly yet, and would like to try on staging, then tweak.
The docs for Gatsby outline what needs to happen: https://www.gatsbyjs.org/docs/caching
=> Add cache-control headers for Gatsby's files

src/backend/utils/html/fix-iframe-width.js, src/backend/utils/html/index.js, src/frontend/src/components/Post/telescope-post-content.css, test/fix-iframe-width.test.js
This adds a backend processing step for `<iframe>` elements to wrap them in a `<div>` that we can then style with CSS, and have the resulting videos occupy 100% of the available space.  Here's how it looks:
It uses the techniques described in https://css-tricks.com/fluid-width-video/#article-header-id-0.
Fixes #869.
=> Fix #869: wrap iframes and control their width

nginx-production.conf, nginx-staging.conf
Co-authored-by calvinho125@gmail.com
Co-authored by jquilon-barrios@myseneca.ca
Building on the work from https://github.com/Seneca-CDOT/telescope/pull/1072#issuecomment-619329389, this tries again to add `cache-control` headers for the static assets we server via nginx.
=> Add cache-control headers for static Gatsby content.

src/frontend/src/components/ScrollToTop/ScrollToTop.jsx
Fixes #1077 
- added zIndex of 1100 to ScrollToTop component. The ScrollToTop button will show on top of the Blog post header but underneath the side drawer when the side drawer is open.
https://material-ui.com/customization/z-index/
Before:
After:
=> Fixes #1077 added zIndex of 1100 to ScrollToTop

src/frontend/src/components/Post/telescope-post-content.css
Fixes #899. 
This PR will style img wdth to 100% and also style the figure tag. 
After investigation on the problem that is describe in issue #899 styling figure tag does not remove extra space under the figure tag. Moreover the extra space under the figure tag does not apply to it. This extra space comes with the paragraph element.
=> Fix #899: add image width and styling the figure tag in the post

src/frontend/gatsby-node.js
I added some error handling and build reporting for the Unsplash image download logic in our Gatsby build.  We failed a build last night, and it crashes, so I wanted to get a fix in while I still remembered.
I've also refactored the code a bit to make it more readable.
=> Add error handling, reporting to unsplash image download build step

nginx-staging.conf
Fixes #1093 
This fixes the bug that was causing to respond a request for `/legacy/planet.css` with 404.
=> Fixes #1093: 404 for /legacy/planet.css

nginx-production.conf
#1095 
This fixes the bug **in production** that was causing to respond a request for /legacy/planet.css with 404.
=> Fixes #1095: Add nginx /legacy fix to nginx-production.conf

src/frontend/gatsby-node.js, src/frontend/package.json, src/frontend/src/markdown-pages/about.md, src/frontend/src/templates/template.js
Closes #1104 
update gatsby package and fix graphql error in gatsby-node.js
Gatsby changed the way they do createPages for Markdown pages so this PR updates related files with slugs. Hopefully this fix works in dev and it wasn't just my machine.
=> Fixes #1104 fix error in building the frontend

.travis.yml
The new version of `redis` for windows on `chocolatey` causes `Travis` to fail. Since the project is [`no longer maintained`](https://chocolatey.org/packages/redis-64/), this PR changes our `Travis` config file so it now installs the previous version (the one that used to work right before `Travis` disappeared).
=> Use a specific version of redis for TravisCI

src/frontend/src/pages/index.js
Fixes #990, the `posts` and also `nextPageLink` dependency for `useEffect`
Part of #990, to test just run `npm run eslint` command
=> Fixes: #990: Look into eslint warnings

.vscode/launch.json
Closes #1092 
This modifies [`launch.json`](https://github.com/Seneca-CDOT/telescope/blob/master/.vscode/launch.json) to include test debugging. With the new settings, it's possible to choose between running and debugging one test (the one opened in the editor) or all of them (run sequentially like when running `npm run test`".
**Note**:
Running tests using VSCode debugger shows an `illegal access` error after completing all the tests.
More specifically:
```sh
node::inspector::Agent::ToggleAsyncHook Cannot toggle Inspector's AsyncHook, please report this.
```
This is a `nodejs` error, and according to their repo, it'll be fix in the next release this month (September 2020).
More info about this issue [here](https://github.com/nodejs/node/issues/27261).
=> Closes #1092: Add launch configuration for debugging tests

src/frontend/src/pages/index.js
Closes #992 
This replaces the `Material-UI` spinner component used in `index.js` with [the one created for our search page](https://github.com/Seneca-CDOT/telescope/blob/master/src/frontend/src/components/Spinner/Spinner.jsx).
=> Closes #992: Combine spinners from #985 and #937

nginx-production.conf
Fixes #1107
Changed proxy_pass from telescope_staging:3000 to telescope_production:3000 inside '/legacy'
I'm having a bit of trouble re-creating the `nginx` crash locally, some guidance would be great on that before merging. 
**Apologies for having a duplicate Pull Request, I had to remove the other commits, so I made a new fork.**
=> Fixes #1107, changed proxy_pass to telescope_production:3000

src/frontend/src/components/Banner/Banner.jsx
Added the 'Add yours' link onto the banner which redirects to /myfeeds
Closes #981 
If you are already signed in... when you click on 'Add yours' on the banner, a new tab opens up linking into /myfeeds.
However, If you are not signed in, a new tab opens directing you to the login page to sign in.
If there is anything I need to to fix or add, let me know! :)
=> Closes #981: Make "Add Yours!" link to /myfeeds

tools/autodeployment/deploy.sh
While monitoring the autodeployment server during #1142 merge, I saw that the [deploy.sh](https://github.com/Seneca-CDOT/telescope/blob/master/tools/autodeployment/deploy.sh) script failed because it was trying to access the telescope folder before cloning the repo, causing the whole process to crash. This fix makes sure the telescope repo is cloned before altering config files and/or launching telescope.
=> Fix autodeployment script after merging #1142

src/frontend/src/components/Banner/Banner.jsx, src/frontend/src/components/DynamicBackgroundContainer.jsx
Fixes #1079 
Aligns the scroll down button on the right and removes the empty space at the bottom of image
No changes to large screens:
Mobile view:
=> Fixes #1079: Align FAB button right on mobile

src/backend/data/feed.js, src/backend/utils/storage.js, src/backend/web/routes/feeds.js, test/feed.test.js, test/feeds.test.js, test/storage.test.js
Fixes #1071 
Adds feature to flag/unflag feeds by hitting the `/feed/:id/flag` route
Done:
Added functions to `storage.js` to flag/unflag
Added functions to `feed.js`
Added tests to `feed.test.js` and `feeds.test.js`
Added routes to `/feed`
**Two ways to test:**
Run my tests
_or..._ 
1. Find an admin account
2. Use `redis-cli smembers t:feeds` to get a list of `feedId` and pick one of them. Keep note of the # of feeds in `t:feeds`
3. While logged in as admin, hit the route `(telescopeUrl)/feeds/(feedId)/flag`. Please use the below screenshot as reference to test `PUT`/`DELETE` routes
4. Use `redis-cli smembers t:feeds` again after a `PUT` method. The count should be the previous # you got - 1
5. Verify the feed has moved with `redis-cli smembers t:feeds:flagged`. There should be one …
=> Add flag routes and function to backend

src/frontend/src/components/Banner/Banner.jsx, src/frontend/src/pages/myfeeds.js
Fixes #1155 
This change makes sure that `Add yours` takes users to the login page when the user is not logged in.
=> Fixes #1155: Route /myfeeds goes to blank page with user not logged in

Dockerfile, docs/environment-setup.md, tools/autodeployment/deploy.sh
fixes #1130 
Adds pre-building of Docker containers prior to spinning down environment, also doesn't destroy services so that we can switch within seconds to either environment. `Dockerfile` is updated to now leverage multiple containers for each dependency (frontend, backend) so that work between the two doesn't trigger a complete npm install chain. It's the small optimizations. 
*TODO*: Integrate into `deploy.sh` logic
```bash
Successfully built 7577b012e84b
Successfully tagged green_telescope:latest
Waiting...
Stopping blue Container
Stopping telescope_production ... done
Stopping blue_redis_1         ... done
Stopping blue_elasticsearch_1 ... done
Removing orphan container "blue_certbot_1"
Removing orphan container "blue_logrotate_1"
Removing orphan container "blue_nginx_1"
Removing …
```
=> adds: prebuild (blue/green) style deployment script

src/frontend/src/components/Post/telescope-post-content.css
Fixes #1199 adjusts svg icon sizes in post content so they're not taking up 100% width
=> Fixes #1199 adjusts svg icon sizes in post content so they're not 100% width

src/frontend/src/components/Posts/Posts.jsx, src/frontend/src/components/SearchPage/SearchPage.jsx
Fixes #1169 
This PR allows users to search posts again.
I tried to change as little code as possible for this PR, such as assigning the passed results from search as props and then assigning it to `posts`. `Load More Posts` button will not show anymore if we're searching posts.
=> Fixes #1169: Fix search posts

src/frontend/src/components/Post/telescope-post-content.css
Fixes #1172 
This PR reduces the size of the tracking pixels found in Medium.com blogs to 1px 1px
=> Fixes #1172 reduce tracking pixel size back to 1px 1px

src/backend/utils/html/sanitize.js, test/sanitize-html.test.js
Fixed #1203 
Added the `giphy.com` host to list of host for iframe gifs and added the test for it.
=> Fixes #1203: Added Giphy as an iframe host and added test

src/frontend/src/components/AdminButtons/AdminButtons.jsx, src/frontend/src/components/AdminButtons/index.js, src/frontend/src/components/Post/Post.jsx
Fixes #1088
Not sure if wiring up the buttons is part of this PR, I had use inline styling for the icons as I was not able to change the icon size or colour through the classes way. The PR can be checked in Vercel Deployment (I think). Otherwise it will require a running local backend + `npm run build` and logging in with user1 // user1pass. `npm run develop` will not work for this.
EDIT: I'm going to split this up into two parts, one for the icons and the next one for functionality(wiring up buttons + displaying a confirmation/popup message)
When not logged in / user is not admin
When logged in / user is admin
=> Fixes #1088: Add Icons for Admin to delete/flag a feed

src/frontend/src/components/Banner/Banner.jsx
Part of #1171.  This is a first-step toward fixing our horrible performance on page load.  I'm getting rid of the dynamic call to `/year/stats`, which I suspect of blocking our event loop while it resolves a billion promises.
We can add it back once we rewrite it to be efficient.
=> Remove call to /stats/year from frontend for perf

src/frontend/static/cached-wiki-feed-list.html
Looks like the wiki is down and not coming back up quickly.  Let's host a static version of the feed list until we can rip out the code that needs this.  Once this is on staging or prod, we can update our `FEED_URL` in the `.env` to point at the cached one.
This file location should allow Gatsby to copy the HTML unmodified into the static assets it creates, see https://www.gatsbyjs.com/docs/static-folder/
=> Add cached wiki feed list

src/backend/lib/queue.js
Fixes #1200
In the [Bull reference docs for Events](https://github.com/OptimalBits/bull/blob/develop/REFERENCE.md#events), the `paused` event does *not* receive a `job` argument, while the `resumed` event does:
```js
.on('paused', function(){
// The queue has been paused.
})
.on('resumed', function(job){
// The queue has been resumed.
})
```
This fix removes the `job` argument from the `paused` event handler.  I also fixed the messages for `paused` and `resumed` to correct some copy/paste errors.
To test this, you can set `LOG_LEVEL=debug` before running the server:
```sh
$ LOG_LEVEL=debug npm start
...
[ 2020-11-01 16:37:00.673 ] DEBUG (82471 on brightness.local): Job 2bd462f1ea completed.
[ 2020-11-01 16:37:00.674 ] DEBUG (82471 on brightness.local): Job b8df6086fe is active
[ …
```
=> Fixes #1200: TypeError: Cannot read property 'id' of undefined

docs/environment-setup.md
Fixes #1272 
In the environment setup document file, when setting up redis using WSL2, one of the steps involved the process of compiling and installing redis. The much more simpler method is to use the package manager of the linux distribution you use for installing redis. For example, using "sudo apt-get install redis-server" with an ubuntu distribution. The environment-setup documentation was therefore, updated to reflect this. 
For reference, this was the link with the installation issue [with installing redis](https://redis.io/topics/quickstart#installing-redis)
=> Fixes #1272: Redis link causing confusion in environment setup (Docs)

package.json, src/frontend/.babelrc, src/frontend/__mocks__/file-mock.js, src/frontend/__mocks__/gatsby.js, src/frontend/jest-preprocess.js, src/frontend/jest.config.js, src/frontend/loadershim.js, src/frontend/package.json, src/frontend/setup-test-env.js, src/frontend/src/components/ScrollToTop/ScrollToTop.jsx, src/frontend/src/components/Spinner/Spinner.jsx, src/frontend/test/Spinner.test.js
Part of #1145. What's in this PR?
1. Set up files required for testing
2. Provided tests for Spinner component
3. Changed jest config in package.json to ignore frontend test when run `npm run test`
I would like to provide details on what I did to set up testing environment for front end
1. I followed Gatsby documentation on [Unit Testing](https://www.gatsbyjs.com/docs/unit-testing/) and [Testing React Components](https://www.gatsbyjs.com/docs/testing-react-components/). And those extra files in the root folders as well as the `__mock__` folder are the result of it. 
2. In my test, I added the `data-testid` attribute to the component so I can use it to refer to specific part of the component for testing. And because of that I included the custom `.babelrc` file to customize the default …
=> Part of #1145: Added setup for frontend testing and Added test for Spinner component

src/backend/utils/indexer.js
Fixes #1259 
Reduces the amount results returned by full-text searching by removing fuzziness. Also allowing users to search by exact phrases.
Adding tests after people give feedback on this.
To test:
`curl http://localhost:3000/query?search="<searchTermHere>"` with a running local backend
feel free to pipe it to a file for verification by appending `> <fileName>.txt` to the end of the above command
or use PostMan
or run local backend + build frontend and use the search Posts function
`searchTermHere` should now support the following:
For example if I want to check posts containing the keyword `pandas` OR `c3ho`. I would use:
`curl http://localhost:3000/query?search="pandas+|+c3ho"`
to Test Exact Phrasing:
Linux
`curl http://localhost:3000/query?search='pandas+|+%22c3ho+for+carefully%22'` …
=> Allow searching for exact phrases

src/backend/utils/html/sanitize.js, test/sanitize-html.test.js
Fixes #1266 
* Modified `sanitize.js` to allow for `img` tags to use `data` uris as `src` so they can be successfully parsed and indexed by Telescope.
* Adds a test to ensure `data` uris are sanitized properly.
* Adds two more `http` and `https` schema tests for `img` tag with a data uri `src`.
* Adds `blockquote` `test` and `cite` sanitation.
Hey everyone!
As per issue #1266, this PR allows images which have a `src` `data` uri type to be properly indexed. It passes all the tests on my end thus showing that data uris are being allowed by Telescope.
I tried to ensure that this works as expected by purging my redis db via `docker exec -it telescope_redis_1 redis-cli flushall` but it seems that once a post is indexed, it is how it is and forever shall be the way it was initially indexed. So …
=> Fixes #1266: modifies sanitize.js to allow Telescope to parse img tags with data uris

docs/environment-setup.md
When users face an error `docker: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running? ` they can simply run `sudo dockerd` to start docker daemon and continue with the setup.
=> added a new line to start docker daemon

package.json, src/backend/web/routes/feeds.js, src/backend/web/validation.js, test/feeds.test.js
Fixes #1277 
In this PR, I have added the Ajv package to validate JSON input for REST API routes.  The particular route I have worked with was POST /feeds.
The JSON received by this route has the form
``` 
{
"user" : "...",
"author" : "...",
"url" : "..."
}
``` 
My logic to validate this is that all properties need to be string type and cannot be empty. Also, for url property, it needs to be a valid URL as well. 
I have also modify feeds.test.js on some tests to correspond with the new middleware added
=> Fixed #1277: Validate input on POST /feeds with Ajv

docs/environment-setup.md
The current instructions of Docker installation in `docs/environment-setup.md` might not work on certain Linux distributions. This PR appends a FAQ to solve the issue.
=> Fix: issue#1302 - "Malformed input, repository not added" error message while installing Docker on Linux mint

package.json
Fixes #1239 
This PR solves the issue of inconsistency when run coverage vs test.
Previously when run coverage, wike-feed-parser.test was failing with error “Async callback was not invoked within the 5000 ms timeout specified by jest.setTimeout”. When run test all the tests were passed.
The issue that causing the problem is the FEED_URL_INTERVAL_MS=200 that was missing in the coverage script.
```js
"test": "npm run jest",
"jest": "cross-env LOG_LEVEL=error MOCK_REDIS=1 FEED_URL_INTERVAL_MS=200 jest --",
"coverage": "cross-env LOG_LEVEL=silent MOCK_REDIS=1 jest --collectCoverage --",
```
After adding FEED_URL_INTERVAL_MS=200 to coverage script as follow:
```js
"coverage": "cross-env LOG_LEVEL=silent MOCK_REDIS=1 FEED_URL_INTERVAL_MS=200 jest --collectCoverage --"
```
Both tests producing …
=> Added FEED_URL_INTERVAL_MS=200 to coverage script to fix the failing test

Dockerfile
Closes #1261 
This adds the command line `COPY .env .` right after the package.json file is copied for each service, and removes the command line `COPY ./.env ./.env` in the Front-end Builder context. 
It solves the problem that the error "cannot find .env file" being thrown when doing the `docker-compose up --build`.
=> Fixes #1261: docker compose up --build doesn't see .env

src/frontend/src/components/Post/Post.jsx, src/frontend/src/components/Posts/Timeline.jsx
Fixes #1180 
I traced how the padding was being applied through Chrome developer tools. I saw that the default root `padding` was being applied meaning the posts have `padding` to the left and right and were not being overridden as expected. From the previous fix that was made I saw that root style was being overridden with a `padding` of 0 in posts.jsx but since the change in #1217 , timeline.jsx was created and that is where the issue stemmed from. I saw that the Timeline function was returning the wrapped array in a container that had the `className={classes.root}`. However custom overriding of the root style was not being called in "useStyles". 
<br /><br />
EDIT:
I believe this also fixed #1226 
I also ran `npm run test` and everything passed. Everything looks alright on my end.
Let …
=> fixes issue-1180 fixes the post padding for mobile devices found in timeline.jsx

src/frontend/src/components/Post/Post.jsx, src/frontend/src/components/Posts/Posts.jsx
From Issue #1220 
Added error handling for UX, includes:
1. Post fails to load
2. Post is loading
3. Timeline fails to load
=> Closes #1220: Better error/loading handling when posts can't be loaded

docker-compose.yml, env.example
Part of #1269
Submitting a new PR because previous one was reverted. When the previous one was merged, staging was failing to build due to #1261 I think. `docker-compose` command was failing because the env var for Kibana port could not be found.
I was thinking of Kibana ever since we added ElasticSearch, great to finally have it added. I had to also update our ElasticSearch image to 7.9.3 so it is compatible with the current version of Kibana.
To test:
1. make sure the extra lines from `env.example` are copied into your `.env` file
2. `docker-compose up redis elasticsearch kibana`
3. navigate to `http://localhost:5601`
You should see something like this afterwards
=> Add Kibana to Telescope

src/frontend/src/pages/error.jsx, src/frontend/src/theme.js
#1173. Change Telescope Theme to a light theme
Homepage
About page
My feed page
404 page
While I'am working on lighten the 404 page, I've found the homepage, about page, and my feed page also got lighter theme following my change. I've changed background and primary colour on 'theme.js' file. Please have a look at this colour change is whether what you or not and let me know if you want another colour theme.
=> Fixes #1173: Change Telescope theme to a light theme

src/backend/utils/html/index.js, test/fixtures.js, test/post.test.js
Fixes #1249 
The `description` of an article from an RSS feed holds the raw html for blog posts which can contain just whitespace in it's context(s) which should be invalid. This uses `jsdom` to turn the `description` into a fragment of html and checks if the context contains only whitespace.
=> Add check for empty descriptions to avoid empty blog posts

src/frontend/src/components/Banner/Banner.jsx, src/frontend/src/components/Header/DesktopHeader.jsx, src/frontend/src/components/Header/Header.jsx, src/frontend/src/components/Header/MobileHeader.jsx, src/frontend/src/components/Post/Post.jsx, src/frontend/src/components/Posts/Posts.jsx, src/frontend/src/components/ScrollAction/ScrollAction.jsx
Fixes: #1223
Fixes: 1223
*ScrollTop and ScrollDown becomes: ScrollAction (We had repeated code for up and down, now we have only one component)
*BackToTop becomes: BackToTopButton - No more coupling with ScrollTop
*Also updated to ES6 the code that I worked on. 
*Merge our two "sticky headers" on scroll (#1223)
=> Fixes #1223: Merge our two "sticky headers" on scroll

env.example, package.json, src/backend/utils/logger.js
Fixes #1268 
Connecting our logger to elastic so we can index logs too and have them show up in `localhost:<elasticPort>`. Your console/terminal should not be spammed anymore by the logging if this is enabled, it should all be redirected to ElasticSearch now.
I should be able to remove the need to put `elasticStream` inside `destination = pino.destination()` and just use it directly
according to the response https://github.com/pinojs/pino/issues/845
To test:
1. Set `PINO_ELASTIC=1` in `.env` or add the variable to your `.env`
2. `npm install`
3. `npm start`
4. navigate to `http://localhost:9200/_cat/indices?v`
You should now see a new index called `logs`
This was from an earlier version I was playing with:
There's a new index called `an-index`
Visualization will come in my next PR.
=> Connect Pino logger to ElasticSearch

src/frontend/src/hooks/use-telescope-contributor.js
Part of #1232
Should this PR get merged I will create a couple more issues related to this issue as [discussed here](https://seneca-open-source.slack.com/archives/CS5DGCAE5/p1605108742117300). 
This PR adds a React hook to the application that fetches a random Telescope contributor once on load in the about page. Once this PR is merged I will create one issue to get someone to display the information in the AboutFooter. and another issue to create some tests for the hook.
=> Add hook for getting Telescope contributors from GitHub

src/backend/utils/indexer.js
Issue #1224 
Changes search by author function to display the initial result (container that links to feed) and the addition of the timeline of their posts
works with with multiple persons with shared names, but is limited to max posts per page. For best results, search for author's full name.
=> Fixes #1224: Show all posts for an author sorted by date when searching by Author

src/backend/web/routes/posts.js, src/backend/web/validation.js, test/posts.test.js
Fixes #1311 
https://github.com/Seneca-CDOT/telescope/issues/1311
The validation will check the length of the parameter 'Id' in posts. In this issue, I only applied it to GET /posts/:id but it could be applied to any posts url with id param.  Normal id length is 10 and the reason why I used the length check is the id value is encoded by hash algorithms and sliced to 10 characters.
=> ReOpen: Fix#Issue 1311 - validate GET /posts/:id route using Express Validator

package.json, src/backend/web/validation.js
This PR introduces `express-validator` to validate POST/feeds instead of using `Ajv`. This PR does not include tests as the tests for this route have already been done. 
Fixes #1326
=> JSON body validation of POST /feeds from Ajv to express-validator

src/frontend/src/components/SearchBar/SearchBar.jsx, src/frontend/src/components/SearchPage/SearchPage.jsx
Issue #1260 
Changed the search-bars input field to allow autocomplete from a given data set. Addition css was added to get the new input to match the previous style, all old functionality seems to be intact.
Currently it is not linked to a data set, but I am planning to open another issue to add the backend support needed after this. 
To test the code you can add some options to the data list, when done they should appear below the search bar as you type.
=> Fix #1260 Updated search-bar input to allow autocomplete

.prettierrc
We ran into a weird issue where Prettier was not seeming to use some of our values which are implicit defaults.  This sets all prettier options explicitly.
=> Be more explicit with prettier config

src/frontend/src/components/SearchBar/SearchBar.jsx, src/frontend/src/components/SearchHelp/SearchHelp.jsx, src/frontend/src/components/SearchHelp/index.js
Fixes #1276
Adds a ButtonIcon in the SearchBar component that allows users to hover over and see how to properly query while searching for posts. This pull request is related to #1275 [![Image from Gyazo](https://i.gyazo.com/e551919ced5612adb5639e91625b786a.png)](https://gyazo.com/e551919ced5612adb5639e91625b786a)
Test Suites: 26 passed, 26 total
Tests:       165 passed, 165 total
Snapshots:   0 total
Time:        11.03 s
=> Added guide in UI to help users write queries when searching Posts

src/frontend/src/components/AboutFooter/AboutFooter.jsx, src/frontend/src/components/GitHubContributorCard/GitHubContributorCard.jsx, src/frontend/src/hooks/use-telescope-contributor.js
Fixes #1355 
I have went ahead and added a new component for the GitHub Contributors using the custom hook from #1330. I was given an example from the Node.js site and took some ideas from it, and made changes to make the Card to better fit into the telescope project visually. I am not sure if we're planning to add more elements to the footer, but in case if we plan to do that in the future, I have decided to have the card positioned on the left for now and leave the center/right empty (unless it's on a small screen device).
View on mobile:
View on PC:
=> Fixes issue-1355: Display Contributor in Footer of About Page

src/backend/web/routes/query.js, src/frontend/src/components/SearchPage/SearchResults.jsx
Fixes #1279 
This PR attempts to address the bug involving an incorrect response status being sent in circumstances not already covered, such as when elasticSearch is shut downed. As this fix also affects the UI on the front-end, this PR also attempts to update the front-end UI to put informative message to the user that the post could not be retrieved. 
An example of the correct API response that should be sent:
=> Fixes #Issue 1279: Better errors for failures with Search and ElasticSearch

src/backend/web/routes/feeds.js, src/backend/web/validation.js, test/feeds.test.js
* added express validation for PUT /feeds/:id/flag
* added test case invalid id param for PUT /feeds/:id/flag
This pull request address #1307 which I have added express validation to the PUT /feeds/:id/flag. Added a new rule for feed id param validation to validation.js. In the routes/feeds.js the PUT /feeds/:id/flag now used this new validation. Two tests have been added to test the validation of the query param id. One test for character length of 9 and another test for the character length of 11.  Two tests might be redundant since validation only allows for a character length of 10. Did not write a test case for success since there is already a test case for a successful response. It would be redundant to write another test case as it would be the same test case since I cannot test id …
=> Fixes Issue #1307 query param validation for PUT /feeds/:id/flag

src/frontend/src/components/Banner/Banner.jsx
Fix #1426 
Add a CSS to the div with id "back-to-top-anchor". Back To Top Button now move to the proper position.
=> Fix Scroll To Top button doesn't move to correct position

src/frontend/src/components/GitHubContributorCard/GitHubContributorCard.jsx
Fix #1424 
Fixed font colours in GitHub Contributor component. Replaced the colour to the same "white" as the rest of the footer.
Removed unnecessary import and variable.
Fixed a linter error.
Thanks for your consideration!
=> Fix issue-1424 : Fix colours in GitHub Contributor component

src/frontend/src/components/SearchPage/SearchPage.jsx
fix #1271 
Added Back to Top Button on the search page. A Back To Top button now shows up when you have a long search result on the search page. 
Added the css to move Back To Top Buttle to the top of the webpage. Please advise the position if you think that is better than move to the top. 
Thanks for your consideration!
=> Fix issue-1271 : Add BackToTopButton in searchPage

src/frontend/src/components/Posts/LoadAutoScroll.jsx
Fixes #1410 
Changed the function name from LoadMoreButton to LoadAutoScroll
Changed onScroll to onClick
=> Issue #1410 Changed function name to LoadAutoScroll

docker-compose.yml, src/backend/lib/elastic.js, src/backend/lib/redis.js, src/backend/utils/url-parser.js, test/fixtures.js, test/url-parser.test.js
#1442 
Tested the docker build and it was succes full
=> Error: Unable to parse elastic URL "http://elasticsearch:9200" and/or PORT "9200" #1442

src/backend/utils/logger.js
Fixes #1448 
Now when logging to console, the log messages will look pretty again.
Could someone also test the pino-elastic logging as well for this and make sure it is also working? I tested it, but it was inconclusive for me.
Steps to test fix:
1. in the `.env` file set `LOG_LEVEL` to `info`
1. `docker-compose up redis elasticsearch`
1. `npm start`
Check info messages in terminal tab. They should look pretty now (just like before)
To regression test:
1. in the `.env` file set `LOG_LEVEL` to `info` and set `LOG_ELASTIC` to 1
1. `docker-compose up redis elasticsearch`
1. `npm start`, there should be no logging appearing in terminal tab anymore as they're directed to elasticsearch now
1. navigate to `http://localhost:9200/_cat/indices?v` You should see two rows and under the `indexes` …
=> Fixed logging format

src/frontend/gatsby/src/components/SearchPage/SearchPage.jsx
Fix #1464 
Scroll To Top button on the search page now work properly on mobile version. 
To check this, Open telescopes in mobile version, click on the search icon to navigate to the search page.
Scroll the page down until the button shows, and then click the button.
=> Fix issue 1464:  Scroll To Top button on the search page does not work on mobile version

package.json
No Issue was created
While I was using docker and docker used npm install there was a high security issue as follows
I ran npm audit
and then I ran the fix and the issue was fixed which was updating passport-saml from 1.5.5 to 2.0.2
This update does not break our current saml login flow
=> fixed npm high security error

src/frontend/gatsby/src/components/Post/Post.jsx
Fixes #1449
decrease the z-index of the header, and make it lower than z-index of the hamburger menu.
=> Issue-1449: Fix Post header overlap (z-index) issue with hamburger menu.

.github/workflows/node-js-ci.yml
Fixes #1336
only run `test-ci` when the os is `ubuntu`
=> Fixed triple-reporting lint issues

src/backend/web/routes/index.js
This fixes the path the `public` folder when served by the backend (locally, it doesn't affect `dev` or `prod`),
This only shows up when running telescope only using `docker`, or when trying to access the front-end using port 3000 instead of 8000.
=> Fix: specify gatsby in the path to the front-end's public folder

src/frontend/gatsby/src/templates/template.js
Fix #1371
In About page, when we scroll down, half of the page will be blank now. It looks weird. So, I want to make the pictures sticky.
=> Fixes issue-1371: Make the picture sticky in About page-renew the pull request #1372

.eslintrc.js, src/frontend/next/package.json
This installs Material-UI in the next folder and updates the .eslint file to not give us issues when importing TS files. I'm creating this PR because some PRs for the Next meta issue I've seen have installed material-ui in the wrong folder or not installed at all. Hopefully this remedies that issue.
=> Install Material-UI in next + update .eslint for src/frontend/next

src/frontend/gatsby/src/components/SearchInput/SearchInput.jsx
This pr adds internal padding on search input area to stop the text from going beyond the area covered by the adornment.
=> Fix #1476: Add internal padding on searchInput to solve overlap problem

.eslintrc.js, src/frontend/next/src/pages/_app.tsx, src/frontend/next/src/pages/_document.tsx
Fixed #1549 
For those JSS that generating class names at run time like MUI, Next renders different class names on server vs client. In this PR, I have modified the _app.tsx and _document.tsx following the recommended example on MUI's website as well as how to do it with Next. More information can be found below.
References:
https://material-ui.com/guides/server-rendering/
https://github.com/mui-org/material-ui/tree/master/examples/nextjs
=> Fixed #1549: Modified _app and _document to ensure matching styling between client and server

src/frontend/next/package.json, src/frontend/next/src/components/SnackBar/SnackBar.tsx
Fixed #1538 
I have modified the SnackBar component to be written in TS. I made some changes to the component to accompany using `handleClose` in the close button. The `onClose` property is not required because it is simply prevent us to close snackbar when we clickaway. Simply remove `onClose` does the same thing.
For reference, you can try what I mentioned above in this playground.
https://codesandbox.io/s/material-demo-forked-qe0kl?file=/demo.js
=> Ported SnackBar component

src/frontend/next/src/components/SearchInput/PostSearchInput.tsx
This PR fixes #1542 
This PR is created to address the porting of the Telescope Front-end from Gatsby to NextJS. As part of that transition, this PR handles the porting of the PostSearchInput component, as per #1542
=> [next] Fixes #1542 - Porting PostSearchInput to Next

src/frontend/next/src/theme/theme.ts
Fixed #1386 
I simply added the `theme.ts` file with consideration for darkmode to be implemented in the future. At the moment, the file looks similar to the `theme.js` in Gatsby because initially we wanted to follow MUI default theme structure (more detail can be found in #1390). However, there was some concern from @humphd before about the meaning of some theme attributes that might not be as clean as we want and in PR #1414 , @abhaseen actually made custom theme files. At the moment, the PR has not been merged so I was following the previous design. If later on, we set on a structure then we can adjust it.
=> Fixes #1386: set up Theme src/frontend/src/theme.js in Next

src/frontend/gatsby/src/components/Login/Login.jsx, src/frontend/gatsby/src/components/Post/Post.jsx, src/frontend/gatsby/src/components/Posts/LoadAutoScroll.jsx, src/frontend/gatsby/src/components/Posts/Posts.jsx
Fixes #1227 
@ceterisp has originally worked on issue #1227 in https://github.com/Seneca-CDOT/telescope/pull/1391. I have looked at the warnings Eslint used to throw and there wasn't anything related to https://github.com/Seneca-CDOT/telescope/pull/1391/files#diff-53149432e2cca92090a6cb3603c9570f20ebf6546280484ece66ab937794283bR79. All of the warnings should be addressed in this pr. Therefore, when merged, I'd suggest closing https://github.com/Seneca-CDOT/telescope/pull/1391
=> [1227] Fixed Eslint warnings

src/frontend/next/package.json, src/frontend/next/src/components/HelpPopoverButton.tsx
Closes #1547 
Porting HelpPopoverButton from Gatsby to NextJS. Process was pretty straight forward. To test, I also rendered this on `index.tsx`.
Steps to test:
1) Open src/frontend/next/index.tsx
2) Add this to import statements: `import HelpPopoverButton from '../components/MyFeedsPage/HelpPopoverButton';`
3) Render component `<HelpPopoverButton />` in `index.tsx`
`package-lock.json` was modified as I had to run `npm install --save material-ui-popup-state`.
=> [next] Fixes #1547: Ported HelpPopoverButton from Gatsby to Next.js

src/frontend/next/src/components/SearchInput/AuthorSearchInput.tsx
Fixes #1541
This PR ports over the `AuthorSearchInput` component to Next.JS.
**_However I have a few concerns I'd like to run by everyone before we merge this:_**
- I'm currently getting an ESLint error: `A control must be associated with a text label.eslint(jsx-a11y/control-has-associated-label)` when I remove `/* eslint-disable jsx-a11y/control-has-associated-label */` from the top of the file.
- FYI: The original Gatsby version of this component also disabled this rule.
- I've never heard of `<datalist>` before so upon a quick google it seems like we're doing everything right, as `<input>` has a list of `search-suggestions` which matches the `<datalist>`'s `id`, but ESLint is still screaming. 
- If the input is enclosed by the `datalist` tag, the error goes away (but it doesn't look …
=> [next] Fixes issue-1541: Ported AuthorSearchInput component to Next.JS

src/frontend/next/package.json, src/frontend/next/src/styles/globals.css
This PR addresses item 5 of #1548 
This PR addresses item 5 of #1548 
- Install highlight.js on NEXT's frontend
- import highlight.js CSS to global css
=> [next] Issue 1548 item 5: Install highlight.js and import highlight.js CSS to global css

src/frontend/next/src/components/SearchInput.tsx, src/frontend/next/src/components/SearchInput/SearchInput.tsx
Fixes #1500 
Port SearchInput to NEXT.js
=> [next] Issue 1500 - Port SearchInput to NEXT.js

src/frontend/next/src/components/DeleteFeedDialogButton.tsx
Fixes #1539 
This PR address #1539, which is the porting of the DeleteFeedDialogIcon button to next from gatsby. It is part of #1316 which is the transitioning of the telescope frontend.
=> [next] Fixes #1539: Porting DeleteFeedDialogButton to Next

src/frontend/next/src/components/SearchBar.tsx, src/frontend/next/src/components/SearchInput/SearchInput.tsx
Fixes #1470 
I don't know if we need to merge something else related to our styles and theme or if I need to work on this particular style, but this is the result that I'm getting followed by the messages on the console.
```
Warning: Prop `className` did not match. Server: "MuiSvgIcon-root makeStyles-infoButton-11" Client: "MuiSvgIcon-root makeStyles-infoButton-12"
in svg (created by ForwardRef(SvgIcon))
in ForwardRef(SvgIcon) (created by WithStyles(ForwardRef(SvgIcon)))
in WithStyles(ForwardRef(SvgIcon)) (created by ForwardRef(InfoOutlinedIcon))
in ForwardRef(InfoOutlinedIcon)
in ForwardRef(InfoOutlinedIcon) (at SearchHelp.tsx:68)
in ForwardRef(Tooltip) (created by WithStyles(ForwardRef(Tooltip)))
in WithStyles(ForwardRef(Tooltip)) (created by WithStyles(WithStyles(ForwardRef(Tooltip)))) …
```
=> [next] Issue 1470 - Port SearchBar to NEXT.js

README.md
@raygervais is going to transfer responsibility of the Netlify next.js builds to me.  I've setup a new Netlify project for Telescope under my account.  This adds a Badge to our README for build status.  The URL for our next.js build of `master` is:
https://telescope-next.netlify.app/
I've put that info in the top-comment for #1316 as well.
@raygervais, you can turn off your Netlify project.  Thanks for getting this started!
=> Update README with Netlify badge for next.js builds

netlify.toml, src/frontend/next/next.config.js
Fixes #1589
We need to set the NEXT_PUBLIC_API_URL in Netlify as well as locally.  This sets it in the netlify.toml file.
=> Fix #1589 - make sure that NEXT_PUBLIC_API_URL is set locally and in Netlify

src/frontend/next/src/components/Posts/Post.tsx
Fixes: #1597 
After porting post component to next, the `variant-"p"` in the element of author name was missing. Which cause the issue of incorrect css style (see the picture below)
However, when I tried to add this `variant="p"` back to the author element, I got a typescript error saying that this is overloaded and is not a match.
```
"owner": "typescript",
"code": "2769",
"severity": 8,
"message": "No overload matches this call.\n  Overload 1 of 2, '(props: { component: ElementType<any>; } & { align?: \"left\" | \"right\" | \"inherit\" | \"center\" | \"justify\" | undefined; children?: ReactNode; color?: \"inherit\" | \"initial\" | ... 5 more ... | undefined; ... 5 more ...; variantMapping?: Partial<...> | undefined; } & CommonProps<...> & Pick<...>): Element', gave the following …
```
=> Fix #1597: [next] post banner has incorrect style

.github/workflows/node-js-ci.yml
Added extra node versions (13.x and 14.x) to Github Actions. As the current node LTS is 14.15.4, we should be updating our testing to account for that. I didn't add 15.x because of previous mentions of it being problematic. 
It's actually up in the air to decide if we still want to test for 12.x and 13.x @humphd
=> Added more node versions to GH actions for testing

src/frontend/next/src/components/BackToTopButton.tsx, src/frontend/next/src/theme/lightTheme.ts
Fixes: #1596
The ~~ScrollToTop~~ `BackToTopButton` control in the posts timeline has a few issues:
1. the colours don't match what Gatsby has (white vs. black)
1. clicking the icon doesn't scroll the page
- [x ] **Bugfix**: Change which fixes an issue
1. the colours don't match what Gatsby has (white vs. black):
- Update the color to white.
1. clicking the icon doesn't scroll the page:
- No action is needed. `BackToTopButton`needs an anchor to scroll(This anchor will be in the `Banner`). If you add an anchor with the id that the component uses as a target, it will scroll until it. I created a div with the id to reproduce and test it. Please check the image.
=> [next] Fixes: 1596 - ScrollToTop issues

src/frontend/gatsby/src/components/Posts/LoadAutoScroll.jsx, src/frontend/next/src/components/Posts/LoadAutoScroll.tsx
Fixes #1595 
After landed the PR: https://github.com/Seneca-CDOT/telescope/pull/1573 created a bug inside our `LoadAutoScroll`'s useEffect both for our Gatsby and Next. This PR will fix the warning issue and fix all of our infinite scroll problems for Gatsby and Next (homepage and search page).
- [] **Quality**: This PR builds and passes our npm test and works locally
=> Fixes: 1595 - [next] Infinite Scrolling of Posts is broken (All of our infinite scrolls were broken)

src/backend/web/app.js
I hit a bug today trying to proxy our next.js frontend via the backend:
```
react-refresh.js?ts=1611939499696:24 Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".
at Object../node_modules/@next/react-refresh-utils/runtime.js (react-refresh.js?ts=1611939499696:24)
at __webpack_require__ (webpack.js?ts=1611939499696:873)
at checkDeferredModules (webpack.js?ts=1611939499696:46)
at webpackJsonpCallback (webpack.js?ts=1611939499696:33)
at webpack.js?ts=1611939499696:1015
at webpack.js?ts=1611939499696:1023
```
This is caused by our CSP settings in dev, which weren't allowing `unsafe-eval` for `script-src` which the webpack dev server requires.
To test …
=> Allow proxying next's webpack dev server (add unsafe-eval CSP for script-src) via backend

src/frontend/next/next.config.js, src/frontend/next/package.json, src/frontend/next/src/pages/about.mdx
Fixes #1463
Been trying to research how to render an `md` file with NextJS, and AFAIK NextJS renders `md` files differently than Gatsby. Upon researching this further I found this neat library which not only renders `md` files, but allows you to inject JSX (TSX) code directly into the `md` file in question. When styling/MUI is finished for next, styling the about page should be nothing short of jovial.
Furthermore, I think the MDX lib pairs really nicely with how NextJS automagically creates routes based on present files in the `pages` directory. All I had to do was place the `.mdx` file alongside otherside the `.tsx` (_currently only `index.tsx`_) files and it renders @ `localhost:8000/about` out of the box.
I also had to create a next config file (_see: `next.config.js`_) to be able to …
=> [next] Fixes #1463 - re-re-implements the About page w/ nextjs

src/frontend/next/src/components/AdminButtons.tsx
=> fix #1494: Port adminbutton to [next]

src/frontend/next/src/components/SEO.tsx, src/frontend/next/src/config.ts, src/frontend/next/src/pages/_document.tsx
Fixed #1508  
I modified SEO component to be written in TS
=> Fixed #1508: Ported SEO component to NextJS

src/frontend/next/src/components/AdminButtons.tsx, src/frontend/next/src/components/Login/LoggedIn.tsx, src/frontend/next/src/components/Login/LoggedOut.tsx, src/frontend/next/src/components/Login/index.tsx, src/frontend/next/src/components/MyFeeds.tsx, src/frontend/next/src/components/UserProvider.tsx, src/frontend/next/src/config.ts, src/frontend/next/src/hooks/use-authorization.ts, src/frontend/next/src/interfaces/index.ts, src/frontend/next/src/pages/myfeeds.tsx
Fixes #1629
This follows the suggestions of the next.js docs on doing statically rendered site authentication.  I've also extended it a bit to add the concept of a user vs. an admin.
First, we have 4 types that a "user" can be at runtime:
- `null` - we either don't know anything about them, or don't have the info (yet)
- `User` - we know whether they are logged in or not, nothing more (e.g., we don't have their user info yet)
- `AuthenticatedUser` - we know that they are logged in for sure, and their name, email, id
- `AdminUser` - we know that they are authenticated AND that they are an admin
In components/pages, you decide which one you want to use, based on your needs.  So if you only care about whether or not the user is logged in, you use `useUser()`:
```
const user = useUser();
// …
```
=> Fix #1629: improve next.js auth handling

src/frontend/next/src/components/SearchResults.tsx
Fixes #1546 (Port SearchResults to NextJS)
Fixes #1458 (Update error styling for failed search)
Closes #1512 (The original 1458 issue was worked on by @sonechca and his resulting PR's work was essentially merged into this one and updated)
This PR ports SearchResults component from Gatsby to NextJS. This PR also includes an update on the search error styling.
Notable changes are the removal of the `loading` variable from `const { data, size, loading, setSize, error } = useSWRInfinite(//...)`  
`loading` is now declared as `const loading = !data && !error;`
`className={classes.root}` attribute was removed from `<Box className={classes.root} boxShadow={2} marginTop={10}>` since `classes.root` doesn't exist (*Typescript complained whereas in the original JSX file this was not an issue*). 
CSS …
=> [next] Fixes #1546: Ported SearchResults to NextJS and fixed styling on search error

.github/workflows/release.yml, .npmrc
Fixes #1301
Rebased and updated https://github.com/Seneca-CDOT/telescope/pull/1527. This PR adds an automated release workflow for GitHub Actions. It would allow us to create a new release by running [`npm version`](https://docs.npmjs.com/cli/v6/commands/npm-version) (**DON'T RUN THIS CODE UNLESS YOU WANT TO MAKE A PRODUCTION RELEASE**):
```
npm version minor -m "Release 1.6.0" 
git push upstream master
git push upstream 1.6.0
```
The workflow would also run the same checks as our `node-js-ci` workflow (test, lint, prettier) and generate a changelog to be included in the release.
- commits that follow the pattern will be added to the corresponding sections in the release note. All other commits will be added under 'Other Changes` section. …
=> [CI/CD] Fixes #1301: Created automated release workflow

.eslintrc.js
Closes #1396 
This removes the `Prefer async/await to callback' rule from our `.eslintrc` file. After merging this, we shouldn't see more warnings related to this issue when running tests.
=> linter: remove 'Prefer async/await to callback' rule from .eslintrc

netlify.toml
Whenever a PR is merged and no changes were made to `next`, our badge reports a `failed` build. This happens because `netlify` detects that no changes were made to the `next` front-end and cancels the build, and for some reason it considers this a failed attempt.
This bug [has been reported](https://community.netlify.com/t/status-badge-incorrectly-shows-failing-when-deploy-is-auto-cancelled/7316/3), and it seems that the solution to avoid this behavior (for now) is to force a build even when no changes were made to the `next` front-end.
This PR makes the necessary changes to our `netlify.toml` to force the `next` build.
=> netlify: force rebuild with every merge to avoid 'failed' message in badge

src/frontend/next/src/pages/search.tsx
Fixes #1438 
Recreating PR, previous PR was changed to port the Spinner only.
I had to add null typing to some of the other components to accommodate this PR
This ports the SearchPage from Gatsby to Next
=> Port SearchPage from Gatsby to NextJS

src/frontend/next/src/components/Header/DesktopHeader.tsx, src/frontend/next/src/components/Header/MobileHeader.tsx, src/frontend/next/src/components/Header/index.tsx, src/frontend/next/src/pages/_app.tsx
Fixes #1446. It is a rework of the #1516 PR.
Translated DesktopHeader.js, MobileHeader.js and Header.js to TS. 
You can check how it works if you go to the `frontend/next` and run `npm run dev`. This will build the Next version of the frontend - and here you can check out how the banner works by trying to click "Home" and "About" and "Search" buttons in Desktop and Mobile versions (For Mobile press F12 in Chrome).
=> refactor(next): Fixed #1446 - Migrated headers to Next.js and TS

src/frontend/gatsby/src/components/MyFeedsPage/DeleteFeedDialogButton.jsx
Closes #1439 
This removes `autofocus` from [DeleteFeedDialogButton](https://github.com/Seneca-CDOT/telescope/blob/master/src/frontend/gatsby/src/components/MyFeedsPage/DeleteFeedDialogButton.jsx) to deal with:
```sh
warning ESLintError: 
telescope/src/frontend/gatsby/src/components/MyFeedsPage/DeleteFeedDialogButton.jsx
83:13  warning  The autoFocus prop should not be used, as it can reduce usability and accessibility for users  jsx-a11y/no-autofocus 
```
All the other warnings in #1439 have been fixed.
=> Closes #1439: Fix eslint warnings from Gatsby build

.eslintrc.js
This removes the `Prefer await to then()` rule from our `.eslintrc.js`.
Also, a description for `'react/jsx-uses-vars': 'error'` was added (there wasn't any before).
=> fix(linter): remove 'Prefer await to then()' rule

src/frontend/next/package.json, src/frontend/next/src/pages/_app.tsx
Fixes: #1672
The font on the PR #1667 before and after the fix:
BEFORE:
AFTER:
=> Fixes: 1672 - [next] Investigate bugs related to Fonts.

src/frontend/next/src/components/Banner.tsx, src/frontend/next/src/components/BannerDynamicItems.tsx, src/frontend/next/src/components/DynamicImage.tsx, src/frontend/next/src/styles/globals.css
Fixes #1616 
Fixes #1554 
Fixes #1553
=> Porting Banner to Next [1616]

.npmrc
Fixes #1534 
and closed #1617 due to the branch being outdated
As of npm7.x, Peer Dependencies has had an overhaul, causing some of our dependencies not properly installing if a user runs `npm install`. This is a band-aid fix to use the legacy Peer Dependencies, until we fix the issue for forwards compatibility. 
This is a final version of #1617, as this PR is rebased.
More Information on the Changes of Peer Dependencies can be found [here](https://github.com/npm/rfcs/blob/latest/implemented/0025-install-peer-deps.md)
=> Fixes #1534, Added Legacy Dependencies Check

src/frontend/next/src/components/SearchResults.tsx
=> Fix #1420 - site crash when no post found

src/frontend/next/package.json
This PR bumps version of @types/node. Ran `npm test` and checked the project locally.
=> chore: bump @types/node from 14.14.8 to 14.14.28 in src/frontend/next

src/frontend/next/package.json
Related to #1592 
This PR bumps @types/react to 16.14.4.
=> chore: bump @types/react from 16.9.51 to 17.0.2 in src/frontend/next

src/frontend/next/package.json
Related to #1592 
This PR bumps `react-material-ui-form-validator` from 2.1.2 to 2.1.4. Tested locally in feed url input field.
=> chore: bump react-material-ui-form-validator from 2.1.2 to 2.1.4

src/frontend/next/package.json
Related #1592 
This PR bumps `react-use` from 15.3.8 to 17.1.1 in src/frontend/next.
=> chore: bump react-use from 15.3.8 to 17.1.1 in src/frontend/next

package.json, test/syntax-highlight.test.js
Related to #1592 
This PR bumps version of `highlight.js` from 10.4.1 to 10.6.0 in the root package file and updates the test.
=> chore: bump highlight.js from 10.4.1 to 10.6.0

.github/dependabot.yml
Fixes #1647 
Refactored Dependabot config file. Number of steps taken to avoid spamming our CI quotas:
- removed Gatsby package file from being monitored. Dependabot will not check for outdated depednencies at `/src/
frontend/gatsby`
- set the `open-pull-requests-limit` to `1` for each of the 3 remaining package files. That would bring us to a maximum of 3 Dependabot PRs open at a time
- disabled automatic rebases: `rebase-strategy: 'disabled'`. This will prevent Dependabot from rebasing each of its PRs whenever it gets outdated. We will rebase manually when we are ready to merge each pr. That would avoid having extra CI runs.
- I and @yuanLeeMidori are taking care of manually updating all of our outdated dependencies in https://github.com/Seneca-CDOT/telescope/issues/1592. Once it is …
=> refactor(ci): refactored Dependabot configuration

package.json, src/backend/feed/queue.js, src/backend/web/routes/admin.js
Fixes: #1588 
Related: #1592 
bull-board 0.9.0 has highlight version 9 dependency. To fix issue #1588, we need to update bull-board.
=> Fix: issue 1588 - Update bull board and highlight.js dep

src/frontend/next/src/components/Header/DesktopHeader.tsx
Fixed #1776 
Toggle theme icons rendered correctly now especially with dark mode preffered. Try to choose dark mode then refresh the page. Before it would show the `moon` icon, now it correctly show the `sun` icon
=> Fixed#1776: Fixed inconsistent render of the toggle theme icone when dark mode is chosen on client.

src/frontend/next/src/components/Header/MobileHeader.tsx, src/frontend/next/src/components/Login/LoggedIn.tsx, src/frontend/next/src/components/Login/LoggedOut.tsx
It relates to #1750. it fixes the LoggedIn, LoggedOut and MobileHeader button text colours. 
Changed the colour description to ContrastText where it needed to be changed. Also removed some redundant code (from item class, it did not do anything).
=> #1750 - fixed Login component display in Dark Mode

src/frontend/next/src/components/Header/DesktopHeader.tsx, src/frontend/next/src/components/Header/MobileHeader.tsx
None.
**This PR will remove the button that toggles our themes. 
I just commented on the code that renders the toggle button on our Headers. Because we can't ship a theme that doesn’t work to our production. 
It's just a band-aid. Given that the problem was not solved and we are less than 24h from our release.**
=> Band aid 1.7 remove dark theme from 1.7

package.json, src/backend/utils/html/remove-empty-paragraphs.js, test/remove-empty-paragraphs.test.js
Fixes #1189, and also added a check for the 0-dot braille character (Unicode Hex: 2800).
This was originally posted in #1696, however the branch became very outdated, along with some rebase problems. 
This PR uses only 1 module instead of multiple modules.
For the `<br>` removal, I had to split the work in half, as there's an issue with DOM not properly cutting the extra `/n` values.
=> Fixes #1189, Added Space Removal for Paragraphs

src/frontend/next/src/pages/error.tsx
Fixes #1468 
Closes #1506 (Old PR for same issue)
This PR takes over and continues the work of #1506 to port the error page from Gatsby to Next.js. 
Set your URL to `/error`. 
**For example,** if I am running Telescope on `localhost:8000`, then my full URL will look like `http://localhost:8000/error`.  
To see default status code messages (400-405), add `?status=CODE` to `http://localhost:8000/error` where `CODE` is a number from 400-405. 
**For example:**  `http://localhost:8000/error?status=404` will result in displaying status code 404 and message 'We could not find what you were looking for!'
Note, codes out of this range will still be displayed and also it will default to message 'Something went wrong!'. 
To see custom messages, add `&message=MESSAGE` to …
=> Fixes #1468: Port error page from Gatsby to Nextjs

src/backend/feed/processor.js, src/backend/feed/worker.js, src/backend/lib/shutdown.js
Fixes #1252 
So, I wanted to make this PR to discuss what needs to be changed for the Backend's logger. 
I've done an audit and added comments to the code on what I personally think needs to be changed, and why. 
I would really like some feedback/discussions so that what we change will be useful, and won't omit any data when debugging Telescope.
* `shutdown.js`
[There ](https://github.com/Seneca-CDOT/telescope/blob/c7a532038950ea2d039a8de8682046300b30db10/src/backend/lib/shutdown.js#L18)seems to be a lot of `error` functions being invoked when the service is shutdown. We parse the error into the logger, and mention that the shutdown was not graceful & dirty. Is it possible to move this into debug? 
* `processor.js`
-[Inside](https://github.com/Seneca-CDOT/telescope/blob/c7a532038950ea2d039 …
=> Fixes #1252, Added Comments for Logger Discussion

.eslintrc.js, .prettierignore
We had a few things to clean up in our eslint/prettier configs with the changes after we dropped gatsby:
- change how it gets the react version to `'detect'` from a fixed version number
- fixed the path to the tools/ directory (it's not in src)
- added the public path back, since next uses it as part of the source code (Gatsby didn't)
=> Fix eslint and prettier for repo updates

src/backend/utils/html/index.js, src/backend/utils/html/remove-devto-fullscreen.js, test/remove-devto-fullscreen.test.js
This is a temporary fix until https://github.com/forem/forem/pull/11268 lands upstream, which removes the nodes from the parsed content before we store it.
=> Temporary fix for dev.to RSS bug https://github.com/forem/forem/pull/11268

src/web/src/components/GitHubContributorCard.tsx, src/web/src/pages/layouts/MDXPageBase.tsx
Fixes #1780 
After @chrispinkney styled the About page, the colouring of the GitHub Contributor Card changed. 
At the same time, @tonyvugithub pushed a PR that changed the colour palette, so now all the colours are a bit different from what we had in Gatsby #1811. 
There is still a need to fix the styling, so with the new colour palette I propose a new view of the GitHubContributor card:
Our [online](https://telescope.cdot.systems/about) version: 
Also, I had to go to `MDXPageBase.tsx` and change the way the colours were declared for the theme - otherwise, the text in the `GitHubContributorCard` was dark-blue.  MDX sets the rule "p = colour", so it is impossible to control the set the text colour of internal components manually - it is controlled by Parent `MDX` component. 
**So I also …
=> Fixes #1780 - make GitHub Contributor Card styling consistent

src/web/next.config.js
Fixes #1795 
First of all, the problem was not in NGINX. 
The bug can be explained in the following way: 
When we did a request to `/search` and  `/about`, NGINX was not able to find those, because in the static (built) version of the frontend that NGINX had we had `/search.js` and `/about.js`, not `/search/index.js` and `/about/index.js`. 
So NGINX was following this instruction: `try_files $uri $uri/ @proxy;` and, after not being able to find the needed pages, sent the request to the Backend. The Backend replied with an error handler, and because the Next.js app was not running (nobody started it yet) - the `/error` page request went back to Backend, and again, and again, and again.
What I and @humphd and @manekenpix did to fix this is: we changed the way Next.js built a static version …
=> Fixes #1795 - added trailing slash to next.config.js

src/web/package.json, src/web/src/components/Banner.tsx, src/web/src/components/BannerDynamicItems.tsx, src/web/src/components/Posts/index.tsx, src/web/src/pages/_app.tsx, src/web/src/pages/error.tsx, src/web/src/pages/layouts/MDXPageBase.tsx, src/web/src/styles/telescope-post-content.css, src/web/src/theme/index.ts
Fixed #1856 
In this PR, I have updated the theme object so everything using MUI component will have Spartan font styling now. I have also removed `@fontsource/roboto` packages as i don't think we need it anymore after this merged. The rest of the changes are simply remove `fontFamily: 'Roboto'` on all components.
=> Change MUI typography font to Spartan

src/api/config/certs.yml, src/api/env.production, src/api/env.staging, src/api/production.yml
Closes #1705
Currently, telescope has a microservice ([certbot](https://github.com/Seneca-CDOT/telescope/blob/9788288925ba547633c219441e8519a41c2a8585/docker-compose-production.yml#L77)) in its `docker-compose-production.yml` that takes care of our SSL certificates. With this PR, `traefik` will have access to those certificates so [`TLS`](https://www.networkworld.com/article/2303073/lan-wan-what-is-transport-layer-security-protocol.html) can be enabled for all the microservices.
**Note**
`Traefik` can generate and renew certificates automatically, but since there are pieces in telescope that are not part of `traefik` and need to have access to the certificates, I thought it'd be better to keep this task outside of the microservices workflow for now. This can be changed in the future. …
=> Closes #1705: Add Let's Encrypt to Traefik Microservices router

.github/dependabot.yml
Fixes #1799
Added Dependabot configurations for Dockerfiles, GitHub Actions, and more package.json files in our repository. Tested on my forked repository, you can see that all of them appeared under https://github.com/birtony/telescope/network/updates
Even though this PR limits each package ecosystem to only 1 open PR at a time and sets Dependabot to make checks on each once a week, it can potentially lead to Dependabot creating 9 PRs at once. Although with automatic rebases turned off, that would mean 9 CI runs/preview deployments, I am not sure if it can exhaust any quotas of ours. I am also not sure if we can limit Dependabot in any other way unless we switch to using npm workspaces (#1778). @humphd, please, advise.
=> Added Dependabot config for Docker, GitHub Actions, and more npm packages

src/web/src/components/Banner.tsx, src/web/src/components/BannerDynamicItems.tsx
No open issue
This PR will prevent that our sidebar overlaps the texts on our Banner.
Until we have a new banner for 2.0.
=> Banner 1.8

src/web/src/components/Posts/Post.tsx, src/web/src/components/Posts/PostAvatar.tsx, src/web/src/components/Posts/PostInfo.tsx
Before GitHub integration or till we get the image from author, we need a temporary avatar to replace the current blank circle.
Fixes: #1855 
This `PostAvatar` component takes name or img source (currently, I set img to optional because we don't have any image to pass). Ideally, if the img source is provided, it should display the image; if the img is not provided and the name is provided, it'll generate initials as an avatar.
=> Fix issue #1855: add temporary avatar

docker/docker-compose.yml
Typo in how we are defining the port for Traefik for the POSTS service (cc @HyperTHD).
=> Use POSTS_PORT vs. IMAGE_PORT in docker-compose

package.json
@chrispinkney and @tonyvugithub have both hit the issue where `npm run services:start` fails on Windows with `.` is not a recognized command.  This fixes it.
=> Make services scripts work on Windows

config/env.development, config/env.production, config/env.staging, docker/docker-compose.yml, package.json, src/api/feed-discovery/.dockerignore, src/api/feed-discovery/Dockerfile, src/api/feed-discovery/README.md, src/api/feed-discovery/jest.config.js, src/api/feed-discovery/package.json, src/api/feed-discovery/src/index.js, src/api/feed-discovery/src/lib.js, src/api/feed-discovery/src/router.js, src/api/feed-discovery/src/server.js, src/api/feed-discovery/test/lib.test.js, src/api/feed-discovery/test/router.test.js
Fixed #1645 
Followed the layout of image microservice to add the feed discovery service. The service will return a list of potential feed urls if the user provided a valid blog url
Unit Tests
=> Added Service for Auto Discovery of Feeds for URLs

docker/development.yml
This PR exposes `Redis`' and `Elasticsearch`'s ports in development (we removed this in #1706)
For testing, simply start docker in development mode:
- `docker-compose --env-file config/env.development up --build`
or
- `npm run services:start`
and then run Telescope: `npm start`.
Telescope should be able to find `redis` and `elasticsearch`.
=> Fix: expose ports in development

config/env.development, docker/development.yml, docker/docker-compose.yml, docs/docker.md, src/api/auth/src/routes.js, src/api/auth/test/e2e/auth-flows.test.js, src/api/auth/test/e2e/index.html, src/api/auth/test/manual/script.js, src/api/readme.md, src/web/src/components/AuthProvider.tsx
Fixes #1942 
Fixes #1943 
It turns out that some versions of Docker on Windows can't do custom DNS resolution to things like `api.telescope.localhost`.  I was using this to make it easier to remember all the names of the services we run, but since we can't, I'm switching to use `localhost` and port numbers.
The only service I haven't changed is Elasticsearch which @manekenpix is doing in #1933.  We need to use 9200 in development for elasticsearch vs. `elasticsearch.localhost`.
=> Fix #1943: Remove Docker localhost.* DNS for Windows development

Dockerfile, config/env.staging, docker/production.yml, src/web/src/config.ts
I'm working on getting our authentication system moved from the 1.0 back-end to the new auth microservice.  Our SSO has been updated for staging by ITS, and now we need to make some adjustments to the config, build, and front-end code.
This fixes a few issues with ENV variables for staging, uses `AUTH_URL` in our Docker build for the front-end, and passes the value through to next.js, so we can hit the right end-point in staging/production.
I've also included all the various URLs we have for Vercel, so we can test things there against our backend.  NOTE: PR previews will not work, since we get a different sub-domain (and therefore different origin) on each build.  I've only been able to do this for stable URLs (e.g., whatever we merge to `master`).
cc @HyperTHD, this is another good …
=> Configure staging/Vercel to use new auth service

config/env.development, config/env.production, config/env.staging, src/api/feed-discovery/README.md, src/api/feed-discovery/src/server.js, src/web/next.config.js, src/web/src/components/AuthProvider.tsx
@manekenpix and @HyperTHD noticed a few bugs in the way the staging auth fix was being done.  This corrects the problems by properly defining the `AUTH_URL` for next's build, and using it in the `AuthProvider`.
=> Use proper AUTH_URL values in next.config.js and AuthProvider

tools/autodeployment/deploy.sh
Co_authored-by: Ray Gervais <raygervais@hotmail.ca>
Fixes #1959 
This PR changes the way a blue or green deployment is detected.
The solution was provided by @raygervais, and I tested it on the staging server.
=> Fixes #1959: Blue/Green deployment only does blue deployments

.github/workflows/node-js-ci.yml, .github/workflows/release.yml
The e2e tests can fail if the docker containers don't shut down cleanly:
```
[Jest Process Manager] http-server stopped.
> @senecacdot/telescope@1.8.0 services:stop /home/runner/work/telescope/telescope
> node bin/services-stop.js
Stopping image          ... 
Stopping auth           ... 
Stopping feed-discovery ... 
Stopping posts          ... 
Stopping traefik        ... 
Stopping elasticsearch  ... 
Stopping login          ... 
Stopping firebase       ... 
Stopping redis          ... 
Stopping posts          ... done
Stopping auth           ... done
Stopping image          ... done
Stopping feed-discovery ... done
Stopping login          ... done
Stopping firebase       ... done
Stopping redis          ... done
Stopping elasticsearch  ... done
Stopping traefik        ... done
Removing …
```
=> Don't wait for services shutdown in CI for e2e tests

src/web/public/robots.txt, src/web/src/components/SEO.tsx, src/web/src/config.ts, src/web/src/pages/_document.tsx, src/web/src/pages/about.mdx, src/web/src/pages/myfeeds.tsx, src/web/src/pages/search.tsx
Related to #1607 
In this PR, I am trying to improve our SEO. I have followed [Open Graph Docs](https://ogp.me/), [Facebook's Guide to Sharing for Webmasters](https://developers.facebook.com/docs/sharing/webmasters), [Twitter's Cards Markup Overview
](https://developer.twitter.com/en/docs/twitter-for-websites/cards/overview/markup) and [MetaTags.io](https://metatags.io/). In terms of the image used for the OG/Twitter tags, according to https://metatags.io/, the image's recommended size is 1200x628 pixels. We do not currently have such a logo size, so I've used the closest one and tested it with metatags.io. It looked pretty well to me, so I am not sure if there is a need to create and store another image.
Once merged, we will be able to use https://cards-dev.twitter.com/validator and …
=> Added new keywords, robots.txt, optimized meta tags 

src/backend/lib/config.js, src/backend/web/routes/admin.js, src/backend/web/routes/index.js
Our tests have a lot of spam in them from various console.logs, and it makes trying to read and debug them a lot harder than it needs to be.
This turns off non-critical logs so we can focus on the pass/fail info.  Here is what they look like now:
@yuanLeeMidori this might make it easier for you to debug that unhandled promise rejection.
<details>
<summary>New Log Output</summary>
$ npm test
> @senecacdot/telescope@1.8.0 pretest /Users/humphd/repos/telescope
> npm run lint
> @senecacdot/telescope@1.8.0 lint /Users/humphd/repos/telescope
> npm run eslint
> @senecacdot/telescope@1.8.0 eslint /Users/humphd/repos/telescope
> eslint --config .eslintrc.js
> @senecacdot/telescope@1.8.0 test /Users/humphd/repos/telescope
> npm run jest
> @senecacdot/telescope@1.8.0 jest …
=> Reduce test log spam

src/web/src/components/ThemeToggleButton.tsx
Fixed #1985 
Changed the tool tip message of `ThemeToggleButton` when hovering to "Toggle Light/Dark Theme"
=> Fixed tool tip message for ThemeToggleButton

tools/autodeployment/package.json, tools/autodeployment/server.js
Every time I run `npm install` I see this:
```
> @senecacdot/telescope@1.8.1 install:autodeployment /Users/humphd/repos/telescope
> cd tools/autodeployment && npm install
audited 257 packages in 2.968s
8 packages are looking for funding
run `npm fund` for details
found 3 vulnerabilities (2 moderate, 1 high)
run `npm audit fix` to fix them, or `npm audit` for details
```
I decided to fix it.  I've update the deps, and removed the unnecessary body-parser dep (it's built into express now).
=> Update autodeployment deps, remove body-parser

src/web/package.json, src/web/src/components/AuthProvider.tsx
This adds another layer of security to our login flow.  When a user initiates a login, we generate a random string in the browser, store it in localStorage, then pass it on the login redirect as a query param.
The auth service stores it, and does the login SAML flow.  When the callbacks come back, it gets that value out of the session and returns it to the browser.  The browser compares that to what's in storage, and if they match, it's clear that the user initiated the login.  Otherwise, something weird is happening (e.g., redirect with token from another site), and we ignore it.
=> Fix #1872: pass state with login flow

src/web/src/config.ts, src/web/src/pages/_document.tsx
Fixes #1992
Related to #1607
This PR adds a full path to the image, including the domain, to the `og:image` and `twitter:image` meta tags. Besides, it also adds the image alternate for the `og` tag (I only found out it was a thing after using [Facebook Sharing Debugger](https://developers.facebook.com/tools/debug/)).
=> Added missing domain to the image url

src/api/status/package.json, src/api/status/src/server.js
Part of #1936.
This adds proper cache headers to the status service:
- static assets are cachable for 1 year
- /status API calls are not cachable
https://web.dev/http-cache/#flowchart is a useful chart for understanding this.
I also fixed a small bug to allow starting the server with npm.
=> Add Cache-Control to status service

jest.setup.js, src/api/auth/jest.config.e2e.js, src/api/auth/jest.config.js, src/api/auth/jest.setup.js, src/api/posts/jest.setup.js
This PR closes #1926 
First of all, sorry @yuanLeeMidori for taking your issue and fixing it. 
This PR adds env.development to our base jest.setup.js file. Since this file is included in the jest.base.js which is used in all services tests, this removes the need to use dotenv to include this env file in all tests separately. e2e tests were also fixed to work. All other jest.setup.js files in any of our services directories were removed, or in the case of the posts service, only a single line to include MOCK_REDIS was kept
=> Modified base jest setup to use env.development

src/web/src/styles/telescope-post-content.css
Fixes #1791
Fixes #1412
I piggy-backed off of @huynguyez 's solution that he posted in issue #1791 ([see here](https://github.com/Seneca-CDOT/telescope/issues/1791#issuecomment-784429056)) and just added an extra line `vertical-align:50%;` to center the inline images.
| Before |
| :---: | 
| ![Capture4](https://user-images.githubusercontent.com/48869737/110953539-7aa33400-8315-11eb-85ca-e2329e484127.PNG) |
| After | 
| :---: |
| ![Capture3](https://user-images.githubusercontent.com/48869737/110953642-9c9cb680-8315-11eb-9a46-9430ff14805b.PNG) |
=> Fixes #1791: Handling with inline img

src/web/src/pages/about.mdx, src/web/src/pages/layouts/MDXPageBase.tsx
Closes #1963
This is a very basic touchup to style the about page. It applies a minor padding fix to about page. I also moved `<AboutFooter>` outside of `<MDXPageBase>` as it was incorrectly being styled as a child.
The about page was looking mighty janky with the new sidebar in UI 2.0.
=> Minor About Page CSS Touchup

src/web/src/components/Posts/Post.tsx, src/web/src/components/Posts/PostAvatar.tsx, src/web/src/components/Posts/PostInfo.tsx
Previous issue #1973
Previous PR #2006 
The link of avatar of desktop was linked to post url, instead of blog url in the previous PR. This PR changes the link to blog instead.
=> Correct avatar link in postInfo and rename avatar prop

src/web/src/components/SearchHelp.tsx, src/web/src/components/SearchPage.tsx
Implements and closes #1807 
As per the new 2.0 UI Design, I have re-styled the search helper. See pictures below:
| Web |
| :---: |
| ![Capture2](https://user-images.githubusercontent.com/48869737/110947189-d5389200-830d-11eb-9e24-ed690662ad61.PNG) |
[Web Design Reference](https://user-images.githubusercontent.com/60857409/108666981-6acac980-74a6-11eb-8ab1-a721f0e246f6.png)
| Mobile |
| :---: |
| ![Capture1](https://user-images.githubusercontent.com/48869737/110947046-a7ebe400-830d-11eb-99fc-a4147c384b0b.PNG) |
[ Mobile Design Reference](https://user-images.githubusercontent.com/60857409/108667182-a1a0df80-74a6-11eb-9788-419a0baf6185.png)
See #1804 for complete design reference. Currently, the SearchHelper component is static - I think that it should be handled within the …
=> Fixes #1807: [UI 2.0] SearchHelp

src/web/src/components/SearchBar.tsx
Fixes: #2009
For #2009
I change the color of hovered search bar for dark mode to improve user accessibility, Please let me know if you have different thought of the color choosing, thanks!
=> Change color for search bar in dark mode

src/web/src/components/Posts/Post.tsx
Fixes: #2003
I check the contrast ratio of our link in dark mode, both visited and unvisited link are not level AAA. (Current unvisited link color with background color has 6.68 which is only AA level)
Therefore, not only the visited link color that was mentioned in the issue #2003 , I also change the color of the unvisited link to meet AAA requirement. And, since the visited link color for light mode is a bit reddish purple, I change the visited link color in dark mode from grey to something red-purple-ish as well.
Please let me know if you have other thoughts about the color :smiley: 
Before
After
=> Improve user accessibility of link to AAA

src/web/src/styles/telescope-post-content.css
Fixes #2002 
Simple and small CSS addition in our `styles/telescope-post-content.css` to *undo* the centring of the text within the post when it comes to the content within a table.
| Before |
| :---: |
| ![issuepic](https://user-images.githubusercontent.com/427398/111876558-a48fd280-8975-11eb-8062-e203328c5327.png) |
| After |
| ![tablestuff](https://user-images.githubusercontent.com/48869737/112541517-dcd64d00-8d89-11eb-9376-b3630cdcec44.PNG) |
=> Fixes #2002: Don't center table contents in figure

babel.config.js, package.json, src/web/jest.config.js, src/web/package.json, src/web/src/components/Logo.test.tsx, src/web/src/components/__snapshots__/Logo.test.tsx.snap, src/web/tsconfig.jest.json
Fixes #1970 
Added initial setup for Jest Snapshot testing. According to https://github.com/vercel/next.js/issues/8663, we need to use `"jsx": "react"` compiler for running Jest Snapshot tests properly.
=> Added initial setup for Jest Snapshot testing

config/nginx.conf.template, docker/production.yml
Closes #1744 
- [] **Bugfix**: Change which fixes an issue
This PR adds [portainer](https://www.portainer.io/) to `docker-compose` in production.
Originally, I thought about adding `portainer` _behind_ `traefik`, but that would prevent users from checking Telescope if/when `traefik` is down, so I decided to _hide_  `portainer` behind `nginx` (route `/portainer`).
To avoid having to set up an account at first launch, I added the possibility of storing a password in a text file (which could easily live in our staging and production servers), and `portainer` will read the file during deployment.
=> Closes #1744: Explore using Portainer to allow admins to manage docker containers

src/web/src/components/Posts/PostInfo.tsx
Fixes #1955 
My name was being broken at the hyphen. I added a line of code to replace all instances of a normal hyphen within the author's name with a [non-breaking hyphen](https://www.toptal.com/designers/htmlarrows/punctuation/non-breaking-hyphen/). 
| Before |
| :---: |
| <img width="201" alt="Screen Shot 2021-03-15 at 8 59 02 PM" src="https://user-images.githubusercontent.com/60857409/111312117-5dcc7080-8635-11eb-83b7-1d600a3bc482.png"> |
| After |
| ![image](https://user-images.githubusercontent.com/48869737/112551887-2ded3d80-8d98-11eb-9a31-6a1df8f02254.png) |
It was [mentioned](https://github.com/Seneca-CDOT/telescope/issues/1955#issuecomment-800256159) in the original issue that a possible fix was to expand the author section, especially since there are other authors with even …
=> Fixes #1955: Replace normal hyphen with a non-breaking hyphen

config/env.development, config/env.production, config/env.staging, docker/development.yml, docker/production.yml, src/api/users/README.md, src/api/users/jest.config.e2e.js, src/api/users/package.json, src/api/users/src/services/firestore.js
Closes Issue #1932 
This PR adds the required environment variables for the Users MS to prod's Docker file. I added some test values and `console.log`'d them after running `docker-compose --env-file config/env.production up --build` and they all displayed just fine. Users should be set up and ready to go once we finally create a Firebase project for Telescope (_don't quote me on this._)
I also hardcoded an environment variable (`process.env.FIRESTORE_EMULATOR_HOST = 'localhost:8088'`)in `firestore.js` which allows developers to test locally when using `npm run services:start firebase` and `cd src/api/users && npm run dev` together. This environment variable is only injected when running in dev mode.
To be completely honestly, it's hacky but I couldn't get get the dev version of the users …
=> Closes Issue #1932: Added environment variables to prod's Docker file

config/env.development
When we need to run the services connected with our backend ( `npm start` ) the connection with elasticsearch is not established because on our `env.development` file the elastic search port line is commented.
=> env.development fix: ELASTIC_PORT was commented.

docker/production.yml
This changes the path to the mapped directories used for the `portainer` and `users` services in `production.yml`. Instead of having everything in `config`, I think it's better to have separate directories.
Also, I added to `volumes` the name of the file where the settings for `firestore` are stored. It seems that mapping only the directory is not enough, it needs the name of the file.
=> Fix path issus in production

src/web/src/styles/telescope-post-content.css
When I recommended `PT Serif`, I had seen it on Time.com, where they also use a bit more space between the letters.  I think this is a nice look, for example: https://time.com/5951490/covid-fourth-wave/
This duplicates the look for our text.
=> Increase letter-spacing for telescope-post-content

package.json
I've been writing a bunch of e2e tests, and wanted a way to run only a few of them over and over again using `--watch`.  This adds support for it.
=> Add jest:e2e-watch script

src/web/next.config.js, src/web/package.json
Updates our front-end web deps, and opts into the [new webpack5 stuff in next 10.1](https://nextjs.org/blog/next-10-1#3x-faster-refresh) for faster builds.
=> Update web deps + webpack version to 5

docker/production.yml, src/backend/utils/indexer.js
[This change](https://github.com/Seneca-CDOT/telescope/commit/4536030133ae9390abcffc1c7cbdc027a0d16ed6) in `Timeline` is the reason why search doesn't work with `vercel`. The `posts` microservice send a full url to the front-end, but the search feature in the old back-end only sends `/posts/{id}`. This is a temporary fix until the search microservice is ready (#1802).
I tested this on our staging server and the search page works for all the rebased PRs.
=> Fix search page for vercel.

src/web/src/components/Posts/Post.tsx
Fixes #1975 
This essentially decorates `<section class="telescope-post-content">` with the blogging host platform name.  
**For example**, if the URL is `https://roycedev.medium.com/spending-the-weekend-thinking-575bcf535e58` it will extract **only** the `medium-com` and decorate the section class, like so:  `<section class="telescope-post-content medium-com">`  
**Another example:**  
This will allow greater CSS customization with each post since each blogging platform styles their blogs/layout differently.
In reference to  the BlogSpot issue (#2039), we can fix it by styling **only** BlogSpot images to not be inline.
1. View the changed files for syntax/logic errors and possible changes/suggestions
2. View Vercel deployment OR pull this pr onto your local machine via `gh pr checkout` …
=> Fixes #1975: Decorate each post with a class that matches the blog host platform

docker/production.yml
In Satellite we have `isAutenticated()` middleware that depends on a service knowing some info about our JWT setup.  Also, we're [adding the ability for a service token to be created in each service](https://github.com/Seneca-CDOT/satellite/pull/10), which means we need to share even more details with the services.  To do this, we expect environment variables to be set in Satellite.  Previously we weren't doing this, but this PR adds them in.
Future services will also require this (FYI @c3ho for Parser and @izhuravlev for Search).
We were also missing some `NODE_ENV=production` variables, which I've added.  They will always need to be `production` in production, so it's best to do it in the docker-compose file vs. the env.
Finally, I've stubbed out (with comments) the APM values we'll …
=> Expose JWT_ISSUER, JWT_AUDIENCE, and SECRET env vars to all services

src/web/src/components/Posts/Post.tsx, src/web/src/pages/layouts/MDXPageBase.tsx, src/web/src/theme/index.ts
Fixes: #2048 
Related to: #2047 
Before: 
After:
Basically, they're now using the same colors as posts, both light mode and dark mode. Please let me know if you prefer original colors for light mode about page.
=> Add link colors to palette; change link color in dark mode about page

src/web/src/components/AuthProvider.tsx, src/web/src/pages/myfeeds.tsx
Fixes #2000
@humphd In this PR I have fixed the error when we log out from /myfeeds by allowing relative `redirect_uri` and add Telescope base URL to it.  However, there's another problem, when we call `logout()`, before the logout URL is reached, `myfeeds` component re-renders because `user` is now undefined, and it redirects us to login and cancels the logout request. I couldn't come up with an easy solution to prevent this. I was wondering if you can help me with this issue?
=> Fixes #2000 redirect URL error

src/web/src/components/SearchProvider.tsx, src/web/src/components/SearchResults.tsx
Fixes #2062 
I landed #2046 to create a search context. There was a bug I didn't catch where it would create a request on every entered letter instead of just waiting until the user press the enter key or clicks the search button. 
I included the textParam as a value in the SearchProvider which will ensure that SearchResults.tsx uses that property instead of text. Since the text value gets updated everytime a letter is entered, it would fire the async request to search for a post.
=> Fixes: #2062: Search bar fires a request on every entered letter

src/web/package.json, src/web/src/components/Banner.tsx
Fixes #2042
- This solution is limited. It only works if you scroll and release your touchpad or mouse wheel. It won't work if you keep scrolling (overriding the scroll trigger). I will try to improve this later. 
- The page will scroll down to the timeline on passing `100px` threshold, and scroll up on passing `height of banner - 50px`  thresold.
=> Fix #2042 - Add scroll-snap like behaviour on landing page

src/web/src/User.ts, src/web/src/components/BannerButtons.tsx
This updates our JWT parser to get the user's name, authorization roles, and avatar image URL (if present) from the access token.  It depends on #2058 for the changes to the JWT payload.
One thing this will also add is the ability to do this:
```js
const { user } = useAuth();
if(user?.isAdmin) {
// do stuff for an admin
}
if(user?.isRegistered) {
// do stuff for a Telescope user who isn't an admin
}
if(user) {
// do stuff for a Seneca SSO user, who hasn't registered yet
}
```
=> Rework User to use proper JWT payload data

Dockerfile, config/env.development, config/env.production, config/env.staging, docker/production.yml, src/web/next.config.js, src/web/src/components/AuthProvider.tsx, src/web/src/components/SEO.tsx, src/web/src/config.ts, src/web/src/pages/error.tsx
@PedroFonsecaDEV let me know about a bug locally with login/logout.  Currently, the auth redirect logic is using the Telescope 1.0 API backend URL (http://localhost:3000) as the front-end, but when you run the front-end on http://localhost:8000 it breaks.
This adds a new variable to our environment, `WEB_URL`, allowing us to explicitly set the URL where our front-end is hosted.
=> Fix login on localhost, add WEB_URL env variable support

jest.config.base.js, jest.setup.js, test/jest.config.js, test/jest.setup.js
Currently we are silently mocking `fetch()` in all of our tests.  This was necessary in the old tests, but with the new e2e tests, microservivces need to be able to communicate with each other in test cases.
This alters our Jest setup so that the old Telescope 1.0 tests still get mock-fetch, but we don't do it automatically for new tests (any test that needs it can add it, like we now do in `test/jest.setup.js`).
I've also moved the env logic to the base config, and removed the need for any setup in the base configs.  This way, sub-projects can define their own setup with out also pulling in the base.
Thanks to @manekenpix and @chrispinkney who helped me figure this out after pulling my hair out all day.
=> Fix how we mock fetch in Jest

config/simplesamlphp-users.php, src/api/auth/src/authentication.js, src/api/auth/src/routes.js, src/api/auth/src/token.js, src/api/auth/src/user.js, src/api/auth/test/e2e/auth-flows.test.js, src/api/auth/test/token.test.js, src/api/auth/test/user.test.js, src/web/src/User.ts
I was talking with @PedroFonsecaDEV about the signup form, and realized that we'll need to include more user details from the Seneca profile in the initial access token for the signup flow.  This adds the following (NOTE: I'm using names [standardized by OpenID](https://openid.net/specs/openid-connect-basic-1_0.html#StandardClaims) for how you include this data in a token):
- `sub` - I switched this to the actual hashed email value, so we don't need to include the hashing function in the front-end
- `email` - I added this, since we wouldn't have the email otherwise (I was on `sub`)
-  `given_name` - the user's first/given name(s)
- `family_name` - the user's last/surname(s)
In the front-end, you can use `useAuth()` and get back a `user` instance that will have `.email`, `.firstName`, …
=> Update access token with more user details for front-end

config/env.staging, src/api/auth/package.json, src/api/auth/src/middleware.js, src/api/auth/src/routes.js, src/api/auth/src/util.js, src/api/auth/test/util.test.js
I want to support testing authentication on staging, which requires that we allow wildcard URLs for Vercel.  This adds support for limited wildcard matching on origins that we'll allow the auth service to use when redirecting a user back with a token.
I split the middleware out into its own file, which is why it looks like I touched more than I did.
NOTE: for this to work fully in preview PRs, we'll also need #2098 to land for the `WEB_URL` fix.
=> Allow Vercel preview PR URLs for auth redirects on staging

tools/migrate/.gitignore, tools/migrate/README.md, tools/migrate/migrate.js, tools/migrate/package.json
Co-authored-by: Josue <manekenpix@users.noreply.github.com>
Closes #2083
This tool fetches legacy users from the planet feed wiki list, parses them, and dumps to a JSON file for later use (in the parsing service).
1. `gh pr checkout 2096`
2. `cd src\api\users\tools\migrate`
3. `npm install`
4. `npm start`
The users are dumped to `src\api\users\tools\migrate\legacy_users.json`
=> Closes #2083: Migrate legacy accounts away from wiki

src/web/next.config.js
My Vercel fix is once again wrong, and now breaks local dev:
```
Using NEXT_PUBLIC_WEB_URL=https://http://localhost:8000
```
This will allow `http://` prefix for local dev.
=> Don't assume https:// for WEB_URL

src/web/src/components/Banner.tsx, src/web/src/components/NavBar/index.tsx, src/web/src/pages/_app.tsx, src/web/src/pages/about.mdx, src/web/src/pages/index.tsx, src/web/src/pages/layouts/MDXPageBase.tsx, src/web/src/pages/search.tsx
Fixes: #2041
This PR is to remove the navbar from the new banner (#2078); only shows the navbar when the user scrolls to where the posts (timeline) is on the top of the screen. In other word, navbar will only show when there is no banner on the screen.
=> Only show navbar when scrolls to post

.eslintrc.js, src/web/package.json
Fixes #2118
Configures `eslint-plugin-jest`. See the following screenshot of the `/src/web/src/components/Logo.test.tsx` file, no warnings anymore:
=> Added Jest plugin to Eslint config

tools/autodeployment/package.json
Running `npm install` fails with security vulnerabilities in the autodeployment server.  Updating `pm2` fixes.  There are some other updates we could take, but they require API changes I don't have time to do right now.
This clears our security issue.
=> Update autodeployment deps to clear netmask security vulnerability

package.json, src/web/package.json, src/web/src/components/AboutFooter.test.tsx, src/web/src/components/Logo.test.tsx, src/web/src/components/__snapshots__/AboutFooter.test.tsx.snap, src/web/src/components/__snapshots__/Logo.test.tsx.snap
With using [`@testing-library/react`](https://www.npmjs.com/package/@testing-library/react), I was able to create a snapshot test for the `AboutFooter` component, which didn't work with `react-test-renderer`. I suggest that we switch to the first one instead.I have also added `jest-update` script to launch tests and update any outdated snapshots.
=> Switched to react testing library for FE tests

.eslintrc.js, docker/development.yml, docker/docker-compose.yml, docker/production.yml, jest-playwright.config.js, jest.config.base.js, package.json, src/api/auth/jest-playwright.config.js, src/api/auth/test/e2e/auth-flows.test.js, src/api/users/src/routes/users.js, src/api/users/test/e2e/users.test.js
This adds *authentication* (makes sure the user has a valid JWT token) and *authorization* (makes sure their token matches what we expect per route) middleware from Satellite to the Users service.  It depends on https://github.com/Seneca-CDOT/satellite/pull/12 for some changes to the `isAuthorized()` middleware in Satellite.
I'm adding middleware to all of the routes, but it's different in each case:
- `GET /` this can be done only by an admin or another microservice (e.g., Parser service).  A regular user can't request this, nor can an anonymous, unauthenticated user.
- `GET /:id` this can be done by the user who owns the data (e.g., I can request my own data),  or by an admin or another microservice.  A user can't request someone else's data, nor can an anonymous, unauthenticated user. …
=> Add auth middleware to Users service

src/api/auth/package.json, src/api/auth/src/index.js
I was waiting for Redis to get added to Satellite before I could do this, and now that it's here, I'm switch our auth service to use Redis-backed session storage in production.  Similar to [what we do now in the back-end](https://github.com/Seneca-CDOT/telescope/blob/c385eaae08d20f806d4b1ef6363b81c8fc5f4a60/src/backend/web/app.js#L58).
=> Use Redis for auth service session storage in production

src/api/auth/test/token.test.js
Fixes #2138, setting the expected iat claim time to be less than **or equal to** now, which fixes the extremely rare case that the token is issued and the test run at the same second.
=> Fix #2138: iat should be less than or equal to now

src/api/auth/test/e2e/auth-flows.test.js, src/api/auth/test/e2e/signup-flow.test.js, src/api/auth/test/e2e/utils.js, src/api/users/package.json, src/api/users/src/routes/users.js
We're getting really close to being able to support login + signup in the microservices.  I wanted to get a complete e2e test written that would allow us to see if it's working properly.
This test won't pass yet, since it requires a few more pieces (authenticated routes, #2058, etc).  However, I wanted to get it written before I forgot and while I had time.
=> Add e2e test for signup flow in auth + user services

src/web/src/components/Banner.tsx, src/web/src/components/BannerButtons.tsx, src/web/src/components/Posts/index.tsx, src/web/src/components/TelescopeAvatar.tsx
No open issue.
This is a minor update to our UI:
**1:** `<TelescopeAvatar>`  size changed in `<BannerButtons>`.
**2:** Updated `<TelescopeaAvatar>` to receive blog and link to it (optional). 
**3:** Removed some extra spaces from our UI:
Removed `padding-top` for Desktop and mobile from `postsWrapper` rendered by <Posts>
**4:** Banner Button ScrollDown: Is back to work. So users can use the `scroll-snap` if available (@DukeManh  is working on it) or use the button.
=> Minor UI update

src/api/status/src/services.js
I notice that the Users service is [always down in the status service](https://dev.api.telescope.cdot.systems/v1/status).  I checked why, and I was missing an 's'.
=> Fix typo in users URL for status service

docker/development.yml, jest-playwright.config.js, jest.config.e2e.js, package.json, src/api/auth/jest.config.e2e.js, src/api/auth/package.json, src/api/auth/test/e2e/auth-flows.test.js, src/api/auth/test/e2e/blog.html, src/api/auth/test/e2e/signup-flow.test.js, src/api/auth/test/e2e/utils.js, test/test-web-content/auth.html, test/test-web-content/blog.html, test/test-web-content/feed.xml, test/test-web-content/index.html, test/test-web-content/manual-auth/index.html, test/test-web-content/manual-auth/script.js
Debugging the new signup flow with @PedroFonsecaDEV and @DukeManh last night made me realize I should expand the signup e2e test to better match what we do in the front-end.
I'm not 100% sure if this will work on all platforms, since I have to use http://host.docker.internal vs. http://localhost in the test.  I want to see how it performs on CI.
=> Update auth tests to more closely match signup requirements

docker/docker-compose.yml
We've updated the Auth service to talk to the Users service, so we need to make sure that the Users service starts when we start Auth in docker.
=> Add users container to depends_on for auth docker service

src/api/parser/src/index.js
This updates the parser service so that only authenticated Telescope users (e.g., vs. the general public or Seneca-only users) can see the Bull-Board UI.  I don't think it's smart to expose this to the world, but it's probably OK to let our users see it, since they might want to hack on Telescope with us, and this way they can help debug if job's aren't happening correctly.
See the docs on how Satellite's middleware works, if you're not familiar with this: https://github.com/Seneca-CDOT/satellite#middleware
=> Add authorization middlware to parser service

Dockerfile, docker/production.yml, src/api/search/src/routes/query.js, src/api/search/src/search.js, src/web/next.config.js, src/web/src/components/SearchResults.tsx, src/web/src/config.ts
This PR closes #2014 
Now that the search service is functional and merged, we can finally work towards moving it to the front-end. This PR addresses that by adding the search service related arguments to the Dockerfile, the production.yml file, the next.config.js file, the config.ts file, and finally the relevant components that make requests to this endpoint. One bug in the search service is preventing this from working and so I'll need to address that before this PR is ready for review.
=> Fixes #2014: Adds search service to the front-end

src/web/src/components/Posts/Post.tsx
fixes  #2157.
This PR fixes the alignment of the post's content.
I painted the background to make it easier to visualize in the screenshot.
Before:
After:
=> fixes  #2157 - Align post content on mobile under 600px 

docker/development.yml, docker/docker-compose.yml
We need a few tweaks to our environment for the Search service.  The search service needs to be able to talk to Elasticserach via the Docker network, so the domain name has to be the `elasticsearch` container vs. `localhost`, or it can't reach outside of its own container.  Also, we need to do this in all configurations, not just in dev or production, so I've moved it to `docker-compose.yml`.  Finally, we need to expose the `POSTS_URL` to the environment of the search service, so that it can construct URLs.
=> Fix docker environment for search service

src/web/src/components/Posts/PostInfo.tsx
UPDATED 
Closes #1995 
- only show it clear on mouse hover, less distraction on both sides while reading
- add marginBottom to make 'sticky author info box' jump earlier (ugly to see both author close together on scrolling)
Update:
with Left align in blog content, the info section placed on the right doesn't seem right. It's better on the left of the blog instead: 
The vertical separator bar is unnecessary and made it looks just unsightly in modern day design, or if you guys wanna keep it, leave it thin and use lighter color.
or remove it and add more margin between blog content (example for Medium)
ALso about the Navigation menu, no matter what color you use, it will never pops out at first load + banner image in the current design. 
My suggestion: Return it back to horizontal top, …
=> CSS changes to author info section

src/web/src/components/SearchPage.tsx, src/web/src/components/SearchProvider.tsx, src/web/src/components/SearchResults.tsx
Fixes #1983 
Previously, as soon as you hit the submit button the SearchHelp would disappear. The only way to get the SearchHelp to appear again would be to refresh the page.
It would be beneficial if the SearchHelp would appear when the User's search returned no results (case A) or if the search bar was empty (case B).
This is better logically speaking since in those two additional scenarios we can assume that the User either failed their search or are about to search for something, both of which would benefit from seeing the SearchHelp. That is what this PR accomplishes.
Read more [here](https://github.com/Seneca-CDOT/telescope/issues/1983)
1. Search `validation.js` (it should return a timeline of posts)
- scroll all the way to the end to check if the `SearchHelp` component truly …
=> Fixes #1983: Improve SearchHelp logic

src/api/auth/src/routes/logout.js
Fixes #2162
If the SAML logout fails, we currently send a 500 and don't redirect back to the front-end.  This isn't a great user experience, and always redirecting back again is probably the better move.
=> Don't crash on SAML logout error, log and redirect

tools/autodeployment/deploy.sh
This PR fixes the way volumes, containers and images are removed during a deployment.
Previously, remaining containers/volumes/images were removed after the new deployment was completed, but some testing showed that it didn't always work. With this change, unused elements are removed after building the new version of telescope, but before launching it.
=> Fix: Remove remaining volumes/images/contaniers in every deployment

docker/production.yml, src/web/next.config.js, src/web/package.json, src/web/src/components/AuthProvider.tsx, src/web/src/components/BannerButtons.tsx, src/web/src/components/PopUp.tsx, src/web/src/components/SignUp/FormFields/CheckBoxInput.tsx, src/web/src/components/SignUp/FormFields/TextInput.tsx, src/web/src/components/SignUp/FormFields/index.tsx, src/web/src/components/SignUp/Forms/BasicInfo.tsx, src/web/src/components/SignUp/Forms/GitHubAccount.tsx, src/web/src/components/SignUp/Forms/Overview.tsx, src/web/src/components/SignUp/Forms/RSSFeeds.tsx, src/web/src/components/SignUp/Forms/Review.tsx, src/web/src/components/SignUp/Forms/index.tsx, src/web/src/components/SignUp/Schema/FormModel.tsx, src/web/src/components/SignUp/Schema/FormSchema.tsx, src/web/src/components/TelescopeAvatar.tsx, src/web/src/config.ts, src/web/src/interfaces/index.ts, src/web/src/pages/signup.tsx
Fixes #1643 
Co-authored-by: @PedroFonsecaDEV 
Co-authored-by: @Meneguini 
Co-authored-by: @DukeManh 
This PR adds the `signup` page. The style and the design still need to be polished, but we believe that we need to land this feature on our staging serv so we can test with our users (us). 
The styles of the page will be fixed in follow-ups.
=> SignUp Page

src/web/src/components/Posts/Post.tsx
Fixes #2001
I've thought about how to improve the visual break between posts. I've looked at how Instagram separates their infinite timeline of posts and it turns out that they don't (unlike tumblr). I think that the easiest solution would just to simply give it more space, see below:
https://user-images.githubusercontent.com/48869737/114341111-fe278f00-9b26-11eb-857c-7494dfe24f7f.mp4
From my reasoning, the next post's title looks like a subtitle for the current post is because the spacing is basically equal and the user struggles to identify who the title belongs to. By adding more space between, it'll be easier to see the title belongs to the post below rather than the previous post above. 
Let me know if we want a more drastic design change to improve the visual break or if the gap …
=> Fixes #2001: Added bottom padding to improve visual break

src/web/src/components/Banner.tsx
Fixes #2112 
This PR fixes our issue regarding the NavBar not showing up after triggering the scroll-snap or the scroll-down button on our landing page. 
To test it, please use the Vercel deployment.
=> Fix Banner Observer and NavBar rendering when using snap-scroll or scroll down button.

src/web/src/components/GitHubContributorCard.tsx, src/web/src/components/Posts/Timeline.tsx, src/web/src/components/SearchResults.tsx, src/web/src/theme/index.ts
Fixes: #2049 
Fixes: #2168 
Current contributor card in about page (dark mode) doesn't meet AAA rating in WCAG. I change the color to make it meet the requirement.
**Before**
**After**
-----
The messages in search result, "No more posts" and "No results found" has same font and background color, which makes it invisible. I change the font color to make it visible. Please let me know if you have other suggestion of the color choosing, appreciate it.
**No more posts**
**No results found**
=> Improve contrast ratio in contributor card and search results message

Dockerfile
This PR closes #2186 
When the signup flow was demoed today, the discovery-feed portion was failing. An undefined url was returned. I suspect this was because the FEED_DISCOVERY_URL, was not defined in the Dockerfile, despite being defined in the docker-compose.yml, and web related stuff. I added the feed discovery url to the dockerfile as a result.
=> Fixes #2186: Signup Flow fails with feed-discovery

src/web/src/components/AdminButtons.tsx, src/web/src/components/Posts/Post.tsx
This PR fixes #2155
This PR changes the grid distribution to fit better the `author`.
It also changed the margin of the `AdminButtons` to fit better when visible.
Before: 
After:
=> Fixes # 2155: Improved postInfo grid size to fit bigger names on mobile

src/web/src/components/Posts/Post.tsx, src/web/src/components/Posts/PostAvatar.tsx, src/web/src/components/Posts/PostInfo.tsx, src/web/src/components/SignUp/Forms/GitHubAccount.tsx, src/web/src/components/SignUp/Forms/Review.tsx
Fixes #2169
Changes the PostAvatar `blog` prop to be named `url`. 
Changes how the PostAvatar is rendered: if there is no url, then PostAvatar is rendered without an `<a>` element wrapped around it.
Pull this branch for testing, go to `components/Posts/Post.tsx` in VSCode (or your editor of choice) and scroll to the bottom - put a `<PostAvatar name="FirstName LastName" />` element somewhere that it can be rendered and seen. 
You should see an Avatar with the initials "FL" and it should also be unclickable (since their is no url prop)
Now add the prop `url="Test"` to the `PostAvatar` (e.g. `<PostAvatar name="FirstName LastName" url="Test"/>`
You should see that same Avatar now be clickable (if clicked it will give you Telescope's 404 because it is an invalid url).
=> Fixes #2169: Rename blog prop to url in PostAvatar, deal with optional value

src/api/auth/src/routes/logout.js
=> removed commented out line in src/api/src/routes/logout.js#l51 issue #2193

package.json, src/web/package.json
We can't seem to get CI to pass with what looks like a failed npm cache.  I'm trying to disable it.
=> Update all deps related to Babel

src/web/src/components/Banner.tsx, src/web/src/components/BannerButtons.tsx
No opened issue.
We had a regression on our mobile `BannerButtons` when the `SignUp` page landed. 
This PR fixes this regression.
=> Fix banner buttons on mobile

src/web/src/components/Posts/Post.tsx, src/web/src/components/Posts/PostInfo.tsx
- Reduced marginLeft of elements and width of PostInfo on screens
bigger than 'lg' [PonstInfo.tsx]
Co-authored-by: PedroFonsecaDEV
This PR fixes #2201 
- Reduced `marginLeft` of elements and the width of the `root` in the `PostInfo.tsx`
- Changed the `Post.tsx breakpoints` from 1200px to 1205px
Together, these changes eliminated the overflow.
Before:
After:
=> This PR adresses #2201: Extra width causing horizontal overflow

src/web/src/components/AdminButtons.tsx, src/web/src/components/Posts/PostAvatar.tsx, src/web/src/components/SearchBar.tsx, src/web/src/theme/index.ts
Fixes: #2047 
This PR is the last clean-up for gathering the use of dark mode palette.
=> Update dark mode palette

.github/workflows/node-js-ci.yml, .github/workflows/release.yml
Fixes #2120 
Added CPU calculation to optimize concurrency setup for jest tests for our CI and Release workflows.
=> Added CPU cores calculation for determining the number of concurrency workers

package.json
Currently, whenever we run `npm version ...` to create a release, the unit tests are run.  This wastes time, and also requires the local dev env to be properly set up, which isn't really necessary to create a tag.
Passing unit tests doesn't mean the commit is good, as you need to run e2e tests as well.  Also, before we tag a commit on `master`, it has to have passed a) in the PR CI checks; and b) when it lands on `master`; and c) when we build it for staging.  If we've let a failed commit make it all the way through those stages, something is wrong already.
=> Don't run unit tests on npm version

package.json, src/api/parser/package.json, src/api/posts/package.json
Fixes vulnerability on `normalize-url`.
please check: https://github.com/Seneca-CDOT/telescope/security/dependabot/package.json/normalize-url/open
=> normalize-url vulnerability fix

config/nginx.conf.template
This PR changes the `nginx` config file so [Let's Encrypt](https://letsencrypt.org/) can validate our API domains (`dev.api.telescope`, `api.telescope`) using [their challenges](https://letsencrypt.org/docs/challenge-types/) (the current settings in our `nginx` config file only allow host domain validation).
=> Fix: Modify nginx config file to renew api host certificate

src/web/src/pages/layouts/MDXPageBase.tsx
Fixes #2284
This PR removes the extra margin at the top of the about page, caused by an `h1` element.
=> Fixes #2284: Margin-top in About page

src/web/next-env.d.ts, src/web/next.config.js, src/web/package.json
Closes #2265
This PR bumps `next.js` to version v11.1.0 and `typescript` to v4.3.5 (suggested version for nex.js 11).
The main reason is [this alert](https://github.com/Seneca-CDOT/telescope/security/dependabot/src/web/package.json/next/open). We can try to take advantage of the `next.js` new features in future iterations.
=> Closes #2265:  Update to next.js v11 + bump typescript to v4.3.5

package.json, src/api/auth/package.json, test/jest.config.js
This bumps `passport-saml` to version 3.1.2 to get rid of [this depandabot alert](https://github.com/Seneca-CDOT/telescope/security/dependabot/package.json/passport-saml/open).
=> chore: bump passport-saml to v3.1.2

.github/workflows/node-js-ci.yml, .github/workflows/release.yml, src/backend/data/feed.js, test/feed.test.js
Closes #2210 
This adds `nodejs v16.x` to our CI build matrix, It also fixes one of the `feed` tests (the test was passing with a warning in v14, but in v16 it was failing).
=> Closes #2210: Add node 16 to our CI build matrix

config/env.production, config/env.staging
Fixes #2332.
This does two things to help avoid marking (probably) valid feeds as invalid when they fail for some reason (e.g., temporary network outage):
1. Increases the backoff delay to 10 minutes
2. Increases the number of retries to 10
What this means is that if a feed fails, we'll do the following:
1. Try again in 10 minutes
2. Try again in 30 minutes
3. Try again in ~1 hour
4. Try again in ~2.5 hours
5. Try again in ~5 hours
6. Try again in ~10 hours
7. Try again in ~21 hours
8. Try again in ~1.7 days
9. Try again in ~3.5 days
10. Try again in ~7 days
11. Try again in ~14 days
12. Try again in ~28 days
After a month, I think it's safe to assume this site is not coming back online, and we can mark it invalid.
=> Increase backoff attempts/delay before marking feed invalid

docs/environment-setup.md
When I try to install redis using my newly installed WSL2, the installation was not succedded since my WSL2 have not updated yet. Running `sudo apt update` will get your WSL2 update so I think adding it in the doc might help other newly contributors as well.
=> Adding sugestions to install WSL2 and it packages in environment-setup.md

package.json, src/api/feed-discovery/test/middleware.test.js, src/api/feed-discovery/test/router.test.js
=> chore: bump babel-jest to 27.3.1

.gitpod.yml, config/env.gitpod, docker/docker-compose.yml, docker/gitpod.yml, docker/production.yml
Fixes #2393
https://www.gitpod.io/docs/getting-started#start-your-first-workspace
=> Initial Gitpod configuration

docker/development.yml, docker/docker-compose.yml, docker/gitpod.yml, docker/production.yml, src/api/parser/src/index.js
The parser service is crashing on staging due to #2345.  It's actually not really ready for use yet (#2111), so we're going to disable it until it's ready.  Once we finish the code and tests, we can revert this.
=> Disable parser service until we fix #2111

src/web/src/components/Posts/PostAvatar.tsx, src/web/src/components/Posts/Users.tsx, src/web/src/components/TelescopeAvatar.tsx
I wanna say this PR should close #2442 
This PR addresses how the user component was linking to user's github pages. It originally used `window.open()`, instead of an href which is typically how this is done. This PR fixes that. This PR also adds a tooltip title to the user icons, as well as the Telescope Avatar icon as well to keep consistency.
<a href="https://gitpod.io/#https://github.com/Seneca-CDOT/telescope/pull/2447"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Fixes #2442: Fixes linking of users icon, and adds title to users and telescope avatar icons

src/web/src/components/Posts/PostAvatar.tsx, src/web/src/components/Posts/PostInfo.tsx
#2446
All the new Github links that we added open in a new page but clicking on the blogger's name or the date opens links in the current.
<a href="https://gitpod.io/#https://github.com/Seneca-CDOT/telescope/pull/2459"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fixes issue-2446

src/api/status/public/index.html, src/api/status/public/js/build-log/api.js, src/api/status/public/js/build-log/check-for-build.js, src/api/status/public/js/build-log/index.js, src/api/status/public/js/build-log/terminal.js, src/api/status/public/pages/build.html, src/api/status/src/server.js
Closes #2415
On /build.html, periodically fetches build status and shows build logs (if any) using [xterm](https://xtermjs.org/).   
To test locally, change to `<base href="/" />` inside build.html and run start script. The site is on `localhost:1111/pages/build.html`.
Xterm UI should show up. In the dev console, `/status` is requested periodically. 
<a href="https://gitpod.io/#https://github.com/Seneca-CDOT/telescope/pull/2455"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Fix #2415: add live build logs in status dashboard

src/api/status/src/server.js
This PR closes #2462 
We were having CSP errors with regards to fetching build logs from our autodeployment server via the status service. This PR addresses that by adding the env variable for the autodeployment server to the `connect-src` helmet rules defined in our status service.
<a href="https://gitpod.io/#https://github.com/Seneca-CDOT/telescope/pull/2463"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Fixes #2462: Adds API_URL env var to connectSrc for status service

src/api/status/public/css/telescope-dashboard.css, src/api/status/public/index.html, src/api/status/public/js/github-stats.js, src/api/status/src/server.js
Fixes #2417 
This PR adds GitHub stats for Telescope and Satellite.
Stats available: yearly/weekly number of commits, weekly lines added/removed and latest contributor.
<a href="https://gitpod.io/#https://github.com/Seneca-CDOT/telescope/pull/2466"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=>  Add GitHub stats to the status dashboard

package.json, src/backend/utils/html/syntax-highlight.js, test/process-html.test.js, test/syntax-highlight.test.js
Fixes #2457 
- Modified our highlight syntax function
- Adjust test case
The current way of doing it causing some weird bug. 
`highlightAuto()` seems to run an encode to change value to escape character.  And when we have our data with preset syntax-highlight `span`. It is converting weirding.
For example:
```html
<pre class="hljs language-bash"><code><span class="o">&amp;&amp;</span></code></pre>
```
Will convert to
```html
<pre class="hljs language-bash xml"><code class="hljs language-bash"><span class="hljs-symbol">&amp;</span>amp;<span class="hljs-symbol">&amp;</span>amp;</code></pre>
```
I upgraded to the latest version, it kind of fixed itself but some didn't.
Finally solution was to change to use this https://highlightjs.readthedocs.io/en/latest/api.html#highlightelement
That will …
=> Fix escape character

src/backend/utils/html/index.js, src/backend/utils/html/remove-empty-paragraphs.js, test/remove-empty-paragraphs.test.js
Fixes #2479 
- The current version does not call the function from `remove-empty-paragraphs.js` in `src/backend/utils/index.js`
- There is a edge case that blog post that contains `<p><br><p>`
- Change the function to catch if `<p>` contains empty `<br>` 
- Invoke the function from `remove-empty-paragraphs.js` in `src/backend/utils/index.js`
- Add unit test on `remove-empty-paragraphs.test.js`
<a href="https://gitpod.io/#https://github.com/Seneca-CDOT/telescope/pull/2481"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Fixes 2479: Remove paragraphs with only a br inside

config/nginx.conf.template
fixes #2383 
This allows us to redirect from the /deploy route to the port 4000 servers, this way we don't have to recall which port the logs and status are running on. 
<a href="https://gitpod.io/#https://github.com/Seneca-CDOT/telescope/pull/2485"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> 2383- Added redirect for port 4000 in nginx

src/api/posts/src/index.js, src/api/status/public/index.html, src/api/status/public/js/api.js, src/api/status/public/js/feed/index.js
Fix #2419
Add feeds count for status dashboard. I ran docker and used `localhost/v1/posts/feeds` to test it out. And I also have to add cors to expose headers in posts service
<a href="https://gitpod.io/#https://github.com/Seneca-CDOT/telescope/pull/2471"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Fixes #2419: show feeds count on status dashboard

src/api/status/env.local, src/api/status/src/server.js
Allow specifying a <code>/v1/status</code> path prefix for development
=> Improve local development set up of status dash

src/web/src/components/Banner.tsx
fixes #2423
This PR adds the sets a state for the student quote, so that when you scroll on the page, it doesn't grab a new quote to display.
=> issue-2423: Added state to store student quote

package.json, src/backend/web/app.js
- Removed body parser from package.json.
- In /src/backend/web/app.js I removed the use of body parser and replaced it with express.
=> Issue 2504 Switch to express.json() vs. body-parser in backend

src/api/status/public/js/build-log/api.js, src/api/status/public/js/build-log/index.js, src/api/status/public/js/pages/build.js, src/api/status/public/pages/build.html
Fixes #2486
- Fix build log doesn't parse the data correctly, so it always returns false (i.e. no on-going build).
- Change files structure to align with other scripts.
- Change autodeploymentUrl in public/js/buildl-log/api.js
```diff
- const autodeploymentUrl = (path) => `//${location.hostname}:4000/${path}`;
+ const autodeploymentUrl = (path) => `//dev.api.telescope.cdot.systems:4000/${path}`;  
```
- Allow all src in src/server.js
```diff
-         connectSrc: [
-          "'self'",
-          '*.fontawesome.com',
-          `${host.replace(/(^\w+:|^)\/\//, '')}:4000`,
-          '*.github.com',
-        ],
+ connectSrc: ["'self'", "*"]
```
- Go to /src/api/status.
- Run `npm run dev`
- Go to pages/build.html
- Build log only shows up if there is an on-going build
=> Fix #2486: build log for autodeployment is not working

src/api/auth/package.json, src/api/auth/src/authentication.js, src/api/auth/src/middleware.js, src/api/auth/test/e2e/signup-flow.test.js, src/api/auth/test/e2e/utils.js, src/api/parser/package.json, src/api/parser/src/feed/processor.js, src/api/parser/src/parser-queue.js, src/api/status/src/services.js, src/api/users/test/e2e/utils.js
Fixes #2240 
Drop all node-fetch to use fetch from satellite
=> Fixes #2240: drop node-fetch in apis

src/web/src/components/GitHubContributorCard.tsx, src/web/src/components/Posts/Post.tsx, src/web/src/components/Posts/index.tsx, src/web/src/components/SearchBar.tsx, src/web/src/pages/error.tsx
Fixes #2550 
- Changed <code>justify</code> to <code>justifyContent</code> to needed files.
- Note: In development, my change did not break anything and the site still worked.
=> Changed justify to justifyContent instead

src/api/status/public/index.html
Closes #2566 
The totals post card is nested inside the total feeds card so the HTML looks weird. And the element for total posts is deleted so the JS for it fails
=> Fixes #2566: total posts card should display properly

src/api/posts/src/routes/feeds.js, src/api/posts/src/storage.js, src/api/posts/test/feeds.test.js
Fixes #2412 
This is PR for issue- #2412: adding GET /feeds/invalid.  I have added the route in posts/src/routes/feeds.js file and new methods to get invalids keys from Redis in posts/src/storage.js. I have not modified the Redis database code in https://github.com/Seneca-CDOT/telescope/blob/master/src/backend/utils/storage.js as prof David mentioned. 
I have not written the unit tests for this but I tested it in local and the GET /feeds/invalid returned the expected result. 
Thank you for reviewing and please let me know if I am on the right track.
=> Issue 2412  GET /feeds/invalid

src/api/status/public/css/terminal.css, src/api/status/public/pages/build.html
Fixes #2534 
Add `1rem` padding to build log terminal.
=> Add padding to build log terminal

.prettierignore, .prettierrc, package.json
We have a few prettier issues on `master`:
1. we shouldn't be running lint on pre commit, it's messing with prettier.  I think this is what is messing up people's prettier commits, since eslint and prettier are fighting each other
2. we are using deprecated prettier config
3. we aren't ignore generated workbox scripts
=> Fix prettier-check issues on master

.github/workflows/node-js-ci.yml, .github/workflows/release.yml, .gitignore, .gitpod.Dockerfile, .gitpod.yml, .husky/pre-commit, .npmrc, config/env.development, docs/environment-setup.md, docs/git-workflow.md, docs/redis.md, docs/remote-development/aws-cloud9.md, docs/remote-development/vscode-ssh.md, docs/reports.md, docs/staging-production-deployment.md, package.json, pnpm-lock.yaml, pnpm-workspace.yaml, src/api/parser/readme.md, src/api/posts/README.md, src/api/readme.md, src/api/search/README.md, src/api/status/README.md, src/api/users/README.md, src/api/users/env.local, src/web/src/components/Posts/ShareButton.tsx, test/test-web-content/manual-auth/index.html
Initial work for #1778
This PR changes the package manager from `npm` to [`pnpm`](https://pnpm.io/). pnpm is faster and uses less disk space.
To try this locally:
- clone the telescope repo to your computer (do not use your current local copy of telescope)
- install pnpm: `npm install -g pnpm`
- run: `pnpm install`
=> Replace npm with pnpm

src/api/status/public/css/terminal.css
issue #2519:
The terminal port can't auto fit the height because the Browser can't get the size of the container.  So I edit the terminal.js file and get the window's width and height, then calculate the row height and column width based on these data.
If the user has more than one screen, just refresh the screen, the terminal window will fit the new screen.
**Before:**
**After:**
=> edit terminal.js to full height of view port

src/api/status/public/js/build-log/check-for-build.js
Fixes #2539 
As David has mentioned in the issue, `read()` is only called once so the log stuck.
https://user-images.githubusercontent.com/52666982/144975015-aa462511-10fa-4dd3-b0e0-205957d3e11e.mp4
- Go to /dashboard/build.html
- Ask @humphd or @manekenpix to trigger a build
- The terminal should print a bunch of text, then stop, then print again (sometimes it can take a while).
=> fix: build-log should read till end of stream

src/api/status/public/index.html, src/api/status/public/js/pages/dashboard.js, src/api/status/public/js/serviceStatus.js, src/api/status/src/server.js
Fixes #2418 
- Add API route to get all health information
- Update dashboard to display the status information
- Add function to fetch and display to dashboard 
https://user-images.githubusercontent.com/58233223/144141115-6b10b87a-919b-4b55-8a86-d70fd3f8dae5.mp4
=> Add API status to the new dashboard

src/api/status/src/server.js
Related #2418 
Because staging/prod adds `/v1/status`, the URL for fetching turns into `/v1/status/v1/status/status`
Used `PATH_PREFIX` to fix that issue.
- In development (local), route will be `PATH_PREFIX/status`
- In staging/prod, route `/status`
=> Fix fetch status url for staging/prod

.gitpod.Dockerfile
Closes #2564 
As highlighted in #2564, a smaller, more optimized image for gitpod can be created rather than using the default `workspace-full` which contains a lot of tools that we are not using. So, I've added a custom `.gitpod.Dockerfile` using the [`gitpod/workspace-base`](https://github.com/gitpod-io/workspace-images/blob/master/base/Dockerfile) image. 
Installed the following on top of the `base` image:
- Node
- [typescript](https://www.npmjs.com/package/typescript), [yarn](https://www.npmjs.com/package/yarn) and [pnpm](https://www.npmjs.com/package/pnpm)  packages
- Docker
Verified the installation by building and running the image locally:
=> Using workspace-base to create a custom gitpod env image

src/web/src/components/SearchInput/AuthorSearchInput.tsx, src/web/src/components/SearchInput/SearchInput.tsx
This PR closes #2554 
When entering any text into search, it should keep focus so that you can continue entering your search text. The <code>autofocus</code> attribute is not recommended by ESLint, unless the page is mainly used for searching, as it is in this case. See [The accessibility of HTML 5 autofocus](https://brucelawson.co.uk/2009/the-accessibility-of-html-5-autofocus/).
=> #2554 Search page re-renders on entering input 

pnpm-lock.yaml, src/api/posts/package.json, src/api/posts/src/queue.js, src/api/posts/src/routes/feeds.js, src/api/posts/test/feeds.test.js
This fixes #2414 
This is draft PR for issue #2414. 
I added a new file `queue.js` that creates and exports a new Bull client with `redis` client connection required from [posts/src/redis.js](https://github.com/Seneca-CDOT/telescope/blob/master/src/api/posts/src/redis.js). I also added a new GET route `feeds/info` to return the queue's information, for now I'm trying to return the number of jobs in the queue. 
I tested the route by running `npm run services:start`, `npm start` first and running `http://localhost/v1/posts/feeds/info` in Postman. However, I haven't got the expected response, please let me know if I'm on the right track!
The response I got was a long loading screen until Bad Gateway
=> Added a Bull client, and a route /feeds/info to query queue's info

src/web/src/components/Banner.tsx, src/web/src/components/Posts/GitHubInfo.tsx, src/web/src/components/Posts/Post.tsx, src/web/src/components/Posts/PostInfo.tsx
This fixes some accessibility issues of Telescope
- Use `<time>` for date data
- Fix `<li> cannot be descendant of <li>` warning
- Make banner quote `h2`,   directly followed `<h1>Telescope</h1>`
=> Fix some accessiblity issues

docker/production.yml
Related #2553
Since staging using `production.yml`, env `POSTS_URL` wasn't exposed which lead to not being able to fetch total post and feed in the dashboard.
Fix by adding `POSTS_URL` env for status services in `production.yml`
=> fix docker production env for status services

src/api/posts/src/storage.js, src/backend/utils/storage.js
Fixed #2569 
I got the 2/3 of the issue that we are having, handling invalid feed. In this PR I have replaced all the `\n` with whitespace `' '`. Adding a `ttl` so as the `invalid` blog post will be expire in 7 days. I have test through `redis-cli` after I `flushall` the old invalid key and using `ttl (invalid key)` it return the associate expired time which is 7 days.
=> Handling invalid feed

src/api/status/public/js/build-log/api.js, src/api/status/public/js/build-log/build-header.js, src/api/status/public/js/build-log/check-for-build.js, src/api/status/src/views/builds.hbs
Fixes #2416 
- Added scripts for fetching and rendering build-header
- Added html template for build-header
- Imported build-header to run on load
To test the feature locally, do the following:
- Change `autodeploymentUrl` in `public/js/buildl-log/api.js`
```js
const autodeploymentUrl = (path) => `//dev.api.telescope.cdot.systems:4000/${path}`;  
```
- Allow all `connectSrc` in `src/server.js`
```js
```
- Change `current` to `previous` inside `src/api/status/public/js/build-log/api.js`
```js
export const checkBuildStatus = async () => {
try {
const res = await fetch(autodeploymentUrl('status'));
if (!res.ok) {
throw new Error('unable to get build info');
}
const data = await res.json();
if (!data.current) {
return { building: false };
}
return {
building: true, …
```
=> added live build status to Telescope dashboard:

src/api/posts/test/feeds.test.js, src/api/status/src/js/queue-stats.js, src/api/status/src/server.js, src/api/status/src/views/partials/jobCountCard.hbs, src/api/status/src/views/status.hbs
This fixes issue #2414 which is also a follow up of PR #2541 
- Added `jobCountCard.hbs` to display jobs in feeds queue in the backend 
- Added to `src/api/status/src/js` a new file `queue-stats.js` to fetch queue's information using posts API `posts/feeds/info`
- Added `*` or `http://localhost/v1/posts/feeds/info` to `connectSrc` in [server.js](https://github.com/Seneca-CDOT/telescope/blob/master/src/api/status/src/server.js)
- Change the fetch url in `queue/index.js` to `http://localhost/v1/posts/feeds/info`
- Run `pnpm run services:start posts` in root folder and `npm run dev` in `api/status`, you'll get `feeds/info` initial response 
- (Optional) Run all services `pnpm run services:start` and `pnpm start` to start the backend feeds queue. Reload to see changes …
=> Added jobs count to dashboard

src/api/search/.dockerignore
No issue was made for this PR
While debugging an issue with my search service not starting due to a file access, I realized that the `Dockerfile` in our search service was checking the `node_modules` folder, something that shouldn't be happening. This PR adds a `.dockerignore` file to the search service so that when building the search service, the files/folders that should be ignored are ignored.
=> Added .dockerignore file to search service

src/api/parser/src/data/post.js, src/api/posts/src/data/post.js, src/backend/data/post.js, src/web/src/components/Posts/Post.tsx
Fixes #2628. This PR  handles the exception of `new URL` with try-catch. Some blog URLs are relative paths and therefore not valid.
The search page won't crash anymore but clicking on the relative URLs directs us to the 404 not found. I'd like hear if we should handle this somehow or is it ok.
Example blog having invalid URL: https://telescope-5ab9u0wbz-humphd.vercel.app/search/?text=alex%20wang&filter=author
=> Handle invalid blog url

src/web/src/components/Banner.tsx
Fixes #2646.
The bug happens because we generate a random quote at https://github.com/Seneca-CDOT/telescope/blob/323abdffe1c3b288d4928bfe25113f99b56e604a/src/web/src/components/Banner.tsx#L108. 
Because NextJS tries to pre-render stuff, first, a random quote is generated once at build time, and once when the page loads. Now the new quote is updated to the visual elements of the page but not the `href` of the `<a>` tag which is still the pre-rendered one. I am not sure why the `href` is not updated.
In this fix, I put the random quote to a state, and generate it once the banner component is loaded. I could also generate it in the `useState` initializer but the initializer might be invoked twice because of  [React development strict mode](https://reactjs.org/docs/strict-mode.html).
=> Fix student quotes mismatch quote urls

src/web/src/components/Posts/Post.tsx
Fixes #2568 
The post info overflow the post container if the post text wasn't long enough.
I set the root to `display: flow-root` so it will makes sure everything will stay in that post container.
=> Fix post info to not overflow

src/api/status/src/server.js, src/api/status/src/views/partials/commitCard.hbs, src/api/status/src/views/partials/jobCountCard.hbs, src/api/status/src/views/partials/totalFeedCard.hbs, src/api/status/src/views/partials/totalPostCard.hbs
Fixes #2616.
Apply formatting to numbers to the dashboard. The formatting is a decimal separator for all the numbers that may require one.
=> Format numbers with decimal separator in dashboard

docs/release.md
Fixes #2644 
This PR updates the release docs to use `pnpm` instead of `npm`. It also removes the section about running `npm outdated` before each release.
I haven't found any issues when using `pnpm version` so this should be the correct way of creating a new release.
=> Fixes #2644: Update release docs to use pnpm

src/api/status/public/js/build-log/api.js, src/api/status/src/server.js, tools/autodeployment/README.md
Fixes #2521.
Update the consumer code for the status dashboard to present a more developer-friendly URL: from https://dev.telescope.cdot.systems:4000/status to https://dev.telescope.cdot.systems/deploy/status AND
https://dev.telescope.cdot.systems:4000/log to https://dev.telescope.cdot.systems/deploy/log.
Co-Authored-By: Qiwen Yu <yvaineyuu.0201@gmail.com> (AKA @Qiwen-Yu)
=> Change auto deployment links

pnpm-lock.yaml, src/api/auth/package.json, src/api/feed-discovery/package.json, src/api/image/package.json, src/api/parser/package.json, src/api/planet/package.json, src/api/posts/package.json, src/api/search/package.json, src/api/status/package.json, src/api/users/package.json
This changes the [Satellite](https://github.com/Seneca-CDOT/satellite) version from `1.17` to `1.x`.  We manage Satellite ourselves so it's safe to not pin it and let ppm install the latest minor/patch if any.
=> Use the latest satellite version

src/web/src/components/Posts/Post.tsx
Fixes #2583
The original PR that this is related to can be [found here](https://github.com/Seneca-CDOT/telescope/pull/2624). The original author has moved on from the project. The only thing holding this up from being integrated is a rebase.
I have rebased, tested, and would like some re-reviews before merging.
=> Title container overflow fixed

src/api/posts/src/data/post.js, src/api/posts/test/posts.test.js, src/backend/data/post.js, src/backend/feed/processor.js, test/fixtures.js, test/post.test.js, test/test_files/humphd-yt-channel.xml
#1026, since this issue has a lot of features involved, this PR will not cover all of them.
This PR focuses on the backend for tracking and processing feeds of video channels.
The frontend is addressed in PR #2596.
=> Add backend and API functionality for uploaded videos

src/api/status/public/js/build-log/api.js, src/api/status/public/js/build-log/build-header.js, src/api/status/src/views/builds.hbs
fixes #2622 
- Made the message more clear if there is no current or previous build
- Displaying the previous build if there is one and there is no current build
- No current or previous build
- No current build but there is a previous build
- If there is a current build
From the root directory
- Fetch these links <code>https://dev.telescope.cdot.systems/deploy/status</code> or <code>https://telescope.cdot.systems/deploy/status</code> instead of  <code>autodeploymentUrl('status')</code> in the<code>checkBuildStatus()</code> in <code>src/api/status/public/js/build-log/api.js</code>
- Copy the chosen link above to the array of <code>connectSrc</code> in <code>src\api\status\src\server.js</code> so that it won't have error related to CSP
- <code>cd ./src/api/status</code> and <code>pnpm run …
=> Improved build log page for issue 2622

release-changelog-builder-config.json
Fixes #2645 
According to the build logs for [Release 2.4.0](https://github.com/Seneca-CDOT/telescope/runs/4721341052?check_suite_focus=true), 220 merged PRs were accounted for.
The easiest fix is to increase the `max_pull_requests` option in the [`release-changelog-builder-config.json`](https://github.com/Seneca-CDOT/telescope/blob/master/release-changelog-builder-config.json)
However, I have been trying, but have failed, to understand how it got to 220 merged PRs.
Trying to [query merged PRs during the time frame](https://github.com/Seneca-CDOT/telescope/pulls?q=is%3Apr+merged%3A2021-11-09T03%3A53%3A05.000Z..2022-01-05T23%3A08%3A48.000Z+) provided by the log only comes up with 80 PRs
[Querying for all closed PRs](https://github.com/Seneca-CDOT/telescope/pulls?q=is%3Apr+closed%3A2021-11-0 …
=> increase max_pull_requests to 250

pnpm-lock.yaml, src/web/package.json, src/web/src/components/Posts/Post.tsx, src/web/src/interfaces/index.ts
#1026: This will address the front end implementation for viewing videos in Telescope
Display videos on the main timeline, processed by feed of a YouTube channel. This depends on PR #2581 to display any videos at all.
=> Show videos in the main timeline

src/api/status/env.local, src/api/status/public/js/build-log/build-header.js, src/api/status/src/server.js, tools/autodeployment/builds.js
This is a follow-up to the build log cache PR I just merged.  I have a few bugs still in it:
- we need to connect back to the `/deploy` route of the web host vs. api host, so that CSP won't block it.
- we need to deal with the build being null, and show the error
I also cleaned up a path in the build server logic.
=> Fix CSP error and build log crashes in dashboard

docker/docker-compose.yml, src/api/status/env.local
I'm back with a config fix.  The status service needs to access the `WEB_URL` env var, which means I need to expose it to the container.  I've also removed the `API_HOST`, which we don't use any more, and updated the dev env variables.
=> Fix WEB_URL env config for status service

src/api/search/src/bin/validation.js, src/api/search/src/routes/query.js, src/api/search/src/search.js
This PR closes #2110 
This PR Is aimed to help make search queries more flexible. What I have done here is I looked into Elasticsearch so that we can further query different fields we have indexed in Posts. I looked at the data presented back by Elasticsearch and realized we have more fields we can use to search: 
- post
- title
- author
- date published
This PR allows for us to query all of this on the backend, with search and Elasticsearch. 
Additionally, this query seems to be more promising than the original query for the post/author search. We should eventually use the query provided here, as the `zero_terms_query: 'all',` means that if that field is not provided, to search without it. This means we can use this query to search for one, two, three... or all fields, acting the same …
=> added advanced search query for elasticsearch

src/api/search/src/bin/validation.js
This PR fixes #2698
I removed the inline conditional statement to determine which validation rules to use and replaced it with a function which will return the rules.
Once we complete the refactor in #2618, we can remove the change or keep it depending if we want the route search types. 
I removed the inline conditional statement to determine which validation rules to use. 
The rules are not required for advanced search because we have not implemented any of the work yet and will be reintroduced in the refactor #2618 
Because previously this slipped up - I will go through this thoroughly to provide why this should work:
1. delete redis-data file if it exists
2. `cp config/env.development .env`
3. `docker-compose --env-file ./config/env.development up --build search elasticsearch redis …
=> 2698: Remove advanced search validation breaking production search

.github/renovate.json
Only allow node-fetch <3.0
- Refer to #2705, we don't want to go to node-fetch 3.0 because it's ESM module only. 
Expand Renovate's schedule to every weekend.
- We don't know when Renovate triggers dependencies check on our Repo. Only when Renovate happens to work during the current time window setting, `before 3 am every Monday`, PRs are allowed to be created. This is too small, and last week, Renovate failed to work in the schedule and didn't make any PRs.
=> Renovate: disallow node-fetch >= 3.0 and increase renovate schedule

src/api/feed-discovery/test/router.test.js
Fixes #2675.
This PR adds a test case to ensure that the feed discovery microservice works with YouTube URLs.
=> Add YouTube channel test case for feed discovery service

src/web/src/components/Posts/Post.tsx
This PR prevents the sidebar from sticking to the top on Safari when scrolling down.
https://user-images.githubusercontent.com/53121061/150895118-70fef2f6-a585-487b-aac5-79edf97b6de7.mov
=> Fix sidebar Safari css bug

src/api/status/public/js/build-log/build-header.js, src/api/status/src/views/builds.hbs
Fixed #2542 
- Delete animated-indication.css
- Delete duplicate result and duration column in builds.hbs
- Delete datetime-calculator.js and it usage
- Loading animation added
- Adding progress column and showing build progressing animation
Co-authored-by: Tengzhen <tengzhenzhao@gmail.com>
To test the feature locally, do the following:
- Change `autodeploymentUrl` in `src\api\status\public\js\build-log\check-build-status.js`
```js
const autodeploymentUrl = (path) => `//dev.telescope.cdot.systems/deploy${path}`;  
```
- Allow all `connectSrc` in `src\api\status\src\server.js`
```js
```
To trigger a build manually trigger [redeliver](https://github.com/Seneca-CDOT/telescope/settings/hooks/189238170/deliveries) one of the build which merged to `refs/heads/master` …
=> Rendering build duration 

docker/docker-compose.yml, docker/production.yml, src/api/readme.md
=> All the Elastic APM code from our docker/compose files, envs, logging, Satellite, docs, etc., is cleaned.

pnpm-lock.yaml, tools/autodeployment/builds.js, tools/autodeployment/package.json, tools/autodeployment/server.js
Fixes #2695
I noticed a bug with the way I was caching the build logs: the cached contents get erased the first time they are requested.  So it was working the first time, but not on the second, third, ... request.
This switches the log cache to use an LRU stream cache, see https://github.com/LaurentZuijdwijk/streaming-cache.
It also lets us hold on to more build logs from the past based on git sha.
=> Switch autodeployment server to use streaming cache for build logs

tools/autodeployment/builds.js
Fixes #2719.
Follow-up on https://github.com/Seneca-CDOT/telescope/pull/2695#issuecomment-1020760044.  This sends the `code` for a build, no matter what it is.
=> Always send a build's code as part of /status info

src/api/status/public/js/build-log/check-build-status.js
Fixed #2747 
You can review the `regex` [here](https://regex101.com/r/nIin6v/1)
=> Fixing wrong build status url

src/web/src/components/Posts/ExpandIcon.tsx, src/web/src/components/Posts/GitHubInfo.tsx, src/web/src/components/Posts/GitHubInfoMobile.tsx, src/web/src/components/Posts/Post.tsx, src/web/src/components/Posts/PostAvatar.tsx, src/web/src/components/Posts/Repos.tsx, src/web/src/components/Posts/ShareButton.tsx
Fixes #2373 
This continues the work from #2491 
- This PR continues the work from PR #2491 
- Added borderBottom for accordion/header
- Added expand icon to hint users
- Changed a bit CSS to make publish data and expand icon look better
- Changed flex display to `row`, `wrap` for `repos` information
https://user-images.githubusercontent.com/58532267/150660356-0a466877-0387-4469-969f-f1a925a1a061.mp4
https://user-images.githubusercontent.com/58532267/150660358-2de17ba7-5a5e-49da-9f3c-d8323848b1d7.mp4
=> Add GitHub information in mobile view. 

src/mobile/package.json
I tried @menghif's work on `src/mobile` locally, and it works!
While I was playing with it, I noticed that the deps need to be updated.  We also have a `node-fetch` issue like before with 2.6.6 that still needs to be fixed somehow.
=> Bump expo deps in src/mobile

src/web/src/hooks/use-preferred-theme.ts
Fixes #2672, this adds the default state to 'useMedia' hook call because otherwise the browser will fall back to false when server-side rendering which might not match the client's state.
https://github.com/streamich/react-use/blob/master/docs/useMedia.md#reference
=> Add a default state to useMedia hook

src/api/sso/Dockerfile
I'm testing #2743 locally, and on my M1 Mac, I can't get the auth service's Dockerfile to build.  The alpine base image is missing Python for me, so the build fails.
This reworks the Dockerfile to do things in stages/layers:
- **base**: we use a full `node:lts` base to do our build, and copy in the `package.json`
- **development**: if we want to ever test the container in dev mode, this will do it.  We won't use this in production
- **production**: installs all deps in production mode for use in Alpine (Linux musl x64)
- **deploy**: copies the build production deps out and grabs the source code, runs the server.
This strategy means we end up with a very small image, but start with a full one for the build.
=> Rework auth Dockerfile so it builds on M1

tools/autodeployment/builds.js
Fixes #2515 
* Added `Cache-Control: no-cache` to build status response header. 
I'm not sure if the `Cache-Control` header is added to the response. In `http://localhost/v1/status/build`, checking the network tab, I don't see the `Cache-Control` header in the `Response Headers`
To run build log locally, change autodeploymentUrl in src\api\status\public\js\build-log\check-build-status.js
```js
const autodeploymentUrl = (path) => `//dev.telescope.cdot.systems/deploy${path}`;  
```
Allow all connectSrc in src\api\status\src\server.js
```js
```
=> Added Cache-Control to build status header

.github/workflows/deploy-feed-discovery-image.yaml
Fixes #1743 
This is my second draft of this after attempting to use a different workflow in a [previous iteration](https://github.com/Seneca-CDOT/telescope/pull/2775). I have tried multiple different ways to try and get the buider to go into a sub directory instead of using the Dockerfile in the root with varying results 
I think the version in this PR is the proper way to go about it, but it's not supported yet 
I could be wrong but I'm not sure what else to try.
=> 2nd draft for Registering an Image

.github/PULL_REQUEST_TEMPLATE.md
Fixes #2786 
Most of us are new to telescope, or new to some areas of telescope. Most of us want to review PRs  but have no idea how. I added a section to have contributors add the steps to reproduce their fix, or build their new features. This will allow us to have more reviewers and ship code faster.
=> Issue 2786 - Added steps to test in template for PRs

.gitpod.yml, src/web/src/components/AuthProvider.tsx, src/web/src/pages/signup.tsx
This fixes the signup page crash due to `useEffect` infinite loop in 'SignUp.tsx'
=> Fix signup page crash

.gitpod.yml, config/env.development, docker/docker-compose.yml, docker/supabase/.gitignore, docker/supabase/dev/data.sql, docker/supabase/dev/docker-compose.dev.yml, docker/supabase/docker-compose.yml, docker/supabase/volumes/api/kong.yml, docker/supabase/volumes/db/init/00-initial-schema.sql, docker/supabase/volumes/db/init/01-auth-schema.sql, docker/supabase/volumes/db/init/02-storage-schema.sql, docker/supabase/volumes/db/init/03-post-setup.sql, pnpm-lock.yaml, src/api/sso/env.local, src/api/sso/package.json, src/api/sso/src/supabase.js
Part of #2555. This adds a Supbase self-hosted instance to Telescope.
Note: This pr also fixes the `SignUpPage` crash bug mentioned in #2676. @nguyenhung15913 , you can take a look at `AuthProvider` here as a starting point of your PR.
1. Go to the Supabase service
```
cd src/api/supabase
```
2. Copy the env vars
```
cp .env.example .env
```
3. Start
```
docker-compose up
```
4. Go to [localhost:8910](http://localhost:8910) to visit the Dashboard
1. Do all the steps above
2. Uncomment Sign Up link in `BannerButtons` in https://github.com/Seneca-CDOT/telescope/blob/81775c41845a34455b5fd9dde65cbe231d14d79b/src/web/src/components/BannerButtons.tsx#L111-L120
3. In `/src/api/auth/src/middleware.js`, replace line 92 to 110
https://github.com/Seneca-CDOT/telescope/blob/81775c41845a34455b5fd9dde65 …
=> Self host Supabase service

src/api/search/jest.config.js, src/api/search/jest.setup.js, src/api/search/test/query.test.js
This PR fixes part of the #2621
initial setup files for the search tests.
So far it only has 1 simple test and it test the status if no params are given. More test will be added:
- testing the number of results return.
- testing for status return of 200 and 503.
- testing for giving part of the params.
- testing for max page number
- testing for author filter
To run it: `pnpm test search`
=> initial setup for search test

pnpm-lock.yaml, src/web/package.json
Fixes #2793 
After mdx-js latest update, there was some issues in our repository. After we read the docs and added mdx-js/react it seems to be stable.
- run pnpm i in root
- Build in src/web
- should build... and not show any errors.
=> Fixes #2793: Added mdx/react to web

.prettierignore, src/web/public/styles/github-dark.min.css, src/web/public/styles/github.min.css, src/web/src/components/Posts/Post.tsx, src/web/src/hooks/use-preferred-theme.ts, src/web/src/pages/_document.tsx, src/web/src/styles/globals.css, src/web/src/styles/telescope-post-content.css
Fixes #2377.
All code blocks that the Telescope back-end sends us are annotated with highlight.js classes, so the front-end has to provide the stylesheet that defines these.
Since the stylesheet is global, we have to link both stylesheets for light and dark theme, and disable either depending on the current theme.
=> Adapt syntax highlighting on dark theme

src/web/src/components/GithubInfoProvider.tsx, src/web/src/components/Posts/Commits.tsx, src/web/src/components/Posts/GitHubInfo.tsx, src/web/src/components/Posts/GitHubInfoMobile.tsx, src/web/src/components/Posts/Issues.tsx, src/web/src/components/Posts/Post.tsx, src/web/src/components/Posts/PullRequests.tsx, src/web/src/components/Posts/Repos.tsx, src/web/src/components/Posts/Users.tsx, src/web/src/hooks/use-githubInfo.ts
This PR addresses #2379 
As part of #2379, We needed a way to reduce the amount of duplicate code used in our github info related components. This PR creates a new custom hook that deals with maintaining the amount of props we were passing into the github info components. As such, there's 0 props on all the components except for the users component since it needs the avatarSize prop to adjust for the user icon size. I've also left the smaller function that uses a regex to sort out the urls since they all differ between the github info components. I can add them into the hook if needed.
The custom hook is wrapped inside the "Posts" component since it's the main component all the other components live inside and thus will be the only ones that need access to the context values provided.
=> POC for #2379: GithubInfo Custom Hook to remove duplicate Github Info code

package.json, pnpm-lock.yaml, src/backend/data/post.js, test/post.test.js
Fixes #2679 
Make Youtube link clickable by wrapping `<a>` tag . 
At the `root` directory remove `redis-data`
```
rm -r redis-data
```
Rebuild images and wait for `redis` to cache the feeds
=> Make Youtube link clickable

config/rss-bridge/config.ini.php, config/rss-bridge/whitelist.txt, docker/docker-compose.yml, docker/production.yml
#2728 This PR sets up the microservice that will provide the Twitch RSS feed
This PR adds a 3rd party microservice, which generates RSS feeds of Twitch channels. This will be used further to close #2728.
* `pnpm run services:start` -> builds the service
* Go to `localhost:3123` -> a webpage of `rss-bridge` should appear
* Write a Twitch user name 
* Press the `Atom` button
* You should be able to download/preview the feed generated from the Twitch channel
=> Set up rss-bridge service

src/api/sso/Dockerfile
My docker build of the sso service is failing on macOS with M1, and I think it's due to the platform/arch stuff.  I have no idea how it worked before when I wrote this!
Not critical for 2.6.
=> Fix SSO Docker build on M1

docker/docker-compose.yml, src/api/status/env.local, src/api/status/src/server.js, src/api/status/src/views/partials/header.hbs
Fixes #2804 
We've added a bunch of terrible hacks to deal with the static asset routing on the status service, where you needed to prefix things with `/v1/status` in the frontend and backend.
A better solution is to add a redirect to the Traefik router, to serve the page from `/v1/status/` (trailing slash) which allows all the relative links to resolve properly.
With this, I can remove all the hacks.
We can land this in 2.7 if it's not doable in 2.6, it's not critical.
=> Fix routing in Traefik for status server, remove hacks in express

docker/production.yml
I had this indented 1 tab stop too far, so it was being interpreted as part of the elasticsearch service definition.
=> Fix docker/production.yml so it validates

src/web/src/components/Posts/GitHubInfo/Commits.tsx, src/web/src/components/Posts/GitHubInfo/GitHubInfoMobile.tsx, src/web/src/components/Posts/GitHubInfo/Issues.tsx, src/web/src/components/Posts/GitHubInfo/PullRequests.tsx, src/web/src/components/Posts/GitHubInfo/Repos.tsx, src/web/src/components/Posts/GitHubInfo/Users.tsx, src/web/src/components/Posts/GitHubInfo/index.tsx, src/web/src/components/Posts/Post.tsx
#2380 
The GitHub components are mixed with other files in the folder `.\src\web\src\components\Posts` and it's starting to look messy. Move all the GitHub components to the folder `.\src\web\src\components\Posts\GitHubInfo` to organize it.
1. `pnpm install`
2. `pnpm services:start`
3. `pnpm start`
4. Go to `localhost:8000`
5. Each Post should still have their GitHub components.
=> Reorganize GithubInfo componment

src/api/sso/Dockerfile
We're breaking the build on production with the version of `tini` not being found.  @HyperTHD had the same issue on Windows, but it doesn't happen on CI or my local machine.
I've removed the version number, so it should use whatever version is available.
=> Don't specify tini version, which breaks on some setups

config/env.development, config/env.production, config/env.staging
This forces docker to prefer [`buildx`](https://docs.docker.com/buildx/working-with-buildx/) when building with `docker-compose`. I've only tested on macOS.
Not critical for 2.6.
=> Use buildx in docker-compose

docs/turborepo.md
Fixes #2737 
This PR adds initial documentation for Turborepo.
=> Add Turborepo docs

pnpm-lock.yaml, src/api/dependency-discovery/env.local, src/api/dependency-discovery/package.json, src/api/dependency-discovery/src/dependency-list.js, src/api/dependency-discovery/src/index.js, src/api/dependency-discovery/src/router.js, src/api/dependency-discovery/src/server.js, tools/pnpm-deps-gen.sh
Fixes #2738 
The service offers a single route: `/projects`, where it returns a list of all project names that Telescope depends on. The service uses a text file to load this information. The file is named `deps.txt`. The one I have copied there is for testing purposes, so that you don't have to run the tool if you can't.
The tool that generates this file is a one-line `bash` script, which calls `pnpm list` and does some stream processing to reduce the information needed.  The tool can be found in the `tools` folder. Since this is a `bash` script, Windows users cannot test it. A PowerShell script may be necessary.
As of right now, this service is not integrated completely with Docker. To start it up, you have to do the following:
1. `pnpm install` to get all dependencies
2. Navigate to …
=> Set up back end to recollect information from pnpm

src/api/status/public/js/build-log/build-header.js
Closes #2818 
**Changelog**
- Change after to sha in build-header
Previously, the local can connect to staging for /deploy, but now it's CORS blocked. YOLO.
=> fix: build log should always show log

src/mobile/App.jsx, src/mobile/app.json, src/mobile/package.json
Added for issue #2731 
Changing the back ground color of the splash screen and doing a quick check to see if it work on all the phone OS
https://user-images.githubusercontent.com/43376325/152470626-b1a99f78-7df2-4ed1-8043-518f66283d9a.mp4
=> Change splash screen background color

src/api/status/public/js/build-log/terminal.js, src/api/status/src/views/builds.hbs, src/api/status/src/views/layouts/main.hbs
Fixes #2842
We resize the height of the terminal for the build log in the dashboard by resizing it with the API offered by `xterm.js`.
1. Get the changes from the branch
2. Install dependencies (`pnpm install`)
3. Run the dashboard (`cd src/api/status && pnpm dev`)
=> Resize terminal depending on window height

.npmrc
During reviews, I often need to ask people to pin their dependencies.  Instead of using `^1.2.3` we want `1.2.3`.  This [updates our `.npmrc` to set a `save-prefix` of nothing](https://pnpm.io/npmrc#save-prefix).
=> Update .npmrc to not add ^ to package versions

src/docs/docusaurus.config.js
Docusaurus footer needs to be updated, fixes #2881
Modify the Footer:
- Added new labels for links, that successfully directs to proper site when clicked.
- Changed Footer's Copyright label
- Changes made passes local test, with screenshot attached below and no updates on documentation as the documentation is still being worked on at the moment. 
With Environment Set up to direction to see where the change has been added: 
- Clone the Telescope repository
- Install pnpm globally: npm install -g pnpm
- Install the dependencies: pnpm install (this will also install the dependencies in the Docusaurus website)
- Change directory to src/docs (this is where all the code lives for our Docusaurus website): cd src/docs
- Start the app: pnpm start
- Visit localhost:4631 in your browser.
- Scroll …
=> modify footer ~add links, and changed copyright label

src/api/status/public/js/build-log/build-header.js, src/api/status/src/views/builds.hbs
Fix #2761 
Adding commit messgae in build header for better information about the build
- Change `autodeploymentUrl` in `src\api\status\public\js\build-log\check-build-status.js`
```js
const autodeploymentUrl = (path) => `//dev.telescope.cdot.systems/deploy${path}`;  
```
- Allow all `connectSrc` in `src\api\status\src\server.js`
```js
```
-Change directory tp `api` service and run the front end
``` 
cd src/api/status
pnpm dev
```
=> Fix #2762: Indicate better build information in build-header

src/docs/docs/contributing/CONTRIBUTING.md
Noticed that `Environment Setup documentation` link was pointing to a markdown file that no longer exists.
=> Fix link to Environment Setup documentation

src/docs/docs/tools-and-technologies/react-native.md
fixes #2767 
I was not able to launch expo-cli so easily on my PC so I wrote better instructions for Windows. The link provided says the environment variables are only required for MacOS and Linux users but that is not the case, so I outlined all the steps to do that part. 
- This ones simple so please just review my steps and see if they make sense. Let me know if you have a different experience on windows. 
- If you go to files changed, then click the 3 dots for the file, select view file and then scroll down you can see how it will look in the read.me format on the docs. This will help review.
=> Fixes Issue-2767: Windows installation steps to use expo-cli with android studios

.gitpod.yml
This makes gitpod run workspace init scripts in parallel (pnpm install + docker build + docker pull) because one doesn't depend on the result of another, and thus saves us some time.
=> Run gitpod init scripts in parallel

src/web/src/components/Banner.tsx
Currently, the link to `planet` in our `Banner` component when telescope is deployed locally points to `localhost:3000/planet`, and it should be `localhost:8000/planet`.
This PR changes to base url used in the link. 
- Check out the branch used in this PR
- Install dependencies `pnpm i`
- Copy `config/env.development` to `.env`
- Run `pnpm dev`
- Go to `localhost:8000`
- Make sure he `planet` link points to `localhost:8000/planet`
- Copy `config/env.staging` to `.env`
- Run `pnpm dev`
- Go to `localhost:8000`
- Make sure the `planet` link points to `dev.telescope.cdot.systems/planet`
=> [Fix] Use correct base url for planet link

pnpm-lock.yaml, src/api/dependency-discovery/package.json, src/api/feed-discovery/package.json, src/api/image/package.json, src/api/parser/package.json, src/api/planet/package.json, src/api/posts/package.json, src/api/search/package.json, src/api/sso/package.json, src/api/status/package.json, src/api/users/package.json, tools/autodeployment/package.json
Fixes #2934 
- Changed all the Satellite version `^1.x` in the `package.json` of our microservices to `"latest"`, then ran `pnpm install`
- This will pickup the newest Satellite versions whenever `pnpm install` is ran. 
- Whoever releases Satellite will also have to also run `pnpm install` in Telescope to get the updates
- All tests passed locally
- Telescope was able to start locally
variables are added/changed or an explanation of why it does not(if applicable)
=> Changed from '^1.x' to 'latest' for Satellite dependencies

src/api/search/test/query.test.js
Part of #2621 
Needed so we could progress in advanced search
- `pnpm test search`
- Currently the `LOG_LEVEL` is set to default `debug` in  [config/env.development](https://github.com/Seneca-CDOT/telescope/blob/a48182b5f2541290e6b264c401fb1231ad2cd38c/config/env.development#L207). Can also consider adding `LOG_LEVEL` to `error` or `silent` to the `jest.setup.js` file in the Search microservice locally for a test experience with less logs.
- running `pnpm install` did not get me the new Satellite version needed for mocking ElasticSearch. I ran `pnpm update @senecacdot/satellite` in the Search directory. It changed some of the lines in `package.json` in Search and `pnpm-lock.yaml` in root. I'm not sure for the lines that changed from `'@senecacdot/satellite': ^1.x` to …
=> Add unit tests for /advanced query routers

docker/docker-compose.yml, tools/autodeployment/builds.js, tools/autodeployment/deploy.sh, tools/autodeployment/env.example
Fixes #2799 
This is my attempt at getting the ball rolling for issue #2799.
From what I can tell, adding the `GITHUB_TOKEN=` to the `env.example` will auto-populate the GitHub token.
I then expose that token in the Docker-compose by adding it to the top level `environment`
The thing I am least certain of is my attempt to use the token in the `deploy.sh` file. I am fairly sure that is wrong, but I'm not sure what exactly needs to happen, or how to test it. 
@manekenpix had to take down staging in order to test this.
=> Adding GitHub token into all env files

src/api/dependency-discovery/jest.config.js, src/api/dependency-discovery/jest.setup.js, src/api/dependency-discovery/package.json, src/api/dependency-discovery/src/dependency-list.js, src/api/dependency-discovery/src/router.js, src/api/dependency-discovery/test/dependency.test.js
Fixes #2826 
- Add test to `dependency-discovery` service, and healthcheck of the service to `status`
- `pnpm install`
- `pnpm test src/api/dependency-discovery`
=> Created test for dependency-discovery service

src/api/status/public/js/build-log/check-for-build.js, src/api/status/public/js/pages/build.js
Fix #2773 
Checking the `sha` of the build and stop re-rendering if we have the same `sha` displayed in the `build log` and the `build header` already
=> Stop the dashboard UI from stutter by checking the build sha

config/env.development, config/env.production, config/env.staging, docker/docker-compose.yml, docker/production.yml, src/api/dependency-discovery/.dockerignore, src/api/dependency-discovery/Dockerfile, src/api/dependency-discovery/README.md, src/api/dependency-discovery/env.local, src/api/dependency-discovery/src/server.js
Fixes #2830 
This PR addresses the dockerization of the most recent added service, `dependency-discovery`. It also adds the necessary code to start it via `docker-compose`.
2. You may start `dependency-discovery` by doing the following steps:
2.1. If you only want the service itself:
2.1.1. `cd src/api/dependency-discovery`
2.1.2. `docker build . -t telescope_dependency_discovery_svc:latest`
2.1.3. `docker run -p 10500:10500 telescope_dependency_discovery_svc:latest`
2.2. If you want to start it via `docker-compose`:
2.2.1. `pnpm run services:start` or `pnpm run services:start dependency-discovery`
=> Dockerize dependency-discovery

src/api/search/jest.setup.js, src/api/search/test/query.test.js
#2621 
Adding tests for the normal search function.
The test has cover all of the normal search function.
`pnpm install`
`pnpm test search`
=> add testing for normal search

src/api/status/src/services.js
Fixes #2935 
As per #2829, we will add status endpoints for two of the three new services we have added to Telescope. 
This somewhat depends on #2830 to be finished, but I suppose we can agree the endpoint to be `/dependency-discovery`. If we need to change it, we shall do so.
This one is difficult to test correctly, since it mostly depends on the either staging or production. The status dashboard does not access the status of the microservices started locally.
=> Add rss-bridge and dependency-discovery statuses

config/env.production, config/env.staging, config/nginx.conf.template, docker/docker-compose.yml, docker/production.yml
We are trying to figure out how to organize our various URLs and domains.  We have:
- Web app at `telescope.cdot.systems`
- API servers at `api.telescope.cdot.systems`
And we have a growing set of "admin" apps: web apps that our developers need to access, separate from our web/api.
Trying to mix the "admin" apps into the current nginx/traefik web+api structure is proving difficult.  We use a path-based routing system vs. an sub-domain routing system, and it's causing problems with web apps that assume they live at the `/` of the web server.
I want to move our admin apps to their own sub-domains: `<admin-app-name>.telescope.cdot.systems`.  I wanted to try this with Portainer first, since we already run it in staging/production, and should be able to test.
This change updates our [Traefik …
=> Move Portainer behind Traefik instead of nginx

config/nginx.conf.development.template, config/nginx.conf.template, src/web/Dockerfile
Fixes #2835 
There has been some discussion in the issue itself about how to tackle this. As requested by @humphd I have made a PR to get some help figuring this out.
> Using `USER nginx` should work. What does it show when you do this? Can you put the whole Dockerfile up somewhere so I can test with you?
Yesterday when I was trying this, I was getting an error message saying something like `the nginx user was not fond`. Today, when I went to replicate the error I get this message now when I run a `pnpm services:start` 
Switching into the web folder `cd src/web` and then running a `docker build .` produces a similar error
- checkout the pr `gh pr checkout 2944`
- the project should build without error
=> Reduce size of web service using nginx stable-alpine

tools/autodeployment/package.json, tools/migrate/package.json
Fixes #2974 
This should stop `pnpm publish` from publishing these packages to npm.
=> Set packages to private:true so they don't get published by pnpm

tools/autodeployment/deploy.sh
Fixes #2975
This PR removes the `-x` option in our deploy script to avoid printing commands' details before they're executed.
More info [here](https://www.gnu.org/savannah-checkouts/gnu/bash/manual/bash.html#The-Set-Builtin) (option `-x`).
Latest build was run after removing the `-x` option. Go through the build log to see if the build log only displays command's output.
=> Fixes #2975: GITHUB_TOKEN showing in logs

.github/workflows/mobile-deploy.yml, src/mobile/metro.config.js, src/mobile/package.json
Fixes: #2732 
Added missing dependency for mobile deployment.
Enable cache for Expo to reduce the time of downloading Expo. [see](https://github.com/expo/expo-github-action#configuration-options)
At the same time fixing dependencies version issue based on `expo doctor` command. [see](https://docs.expo.dev/workflow/expo-cli/#info)
Removed `metro.config.js` since dependencies `require('@rnx-kit/metro-resolver-symlinks'); `and `require('@rnx-kit/metro-config'); `causing issue during deployment. And also those wasn't require for our app to run.
=> fix mobile deployment

src/api/status/public/js/build-log/build-header.js
Currently, the build header is stuck loading in `production`
The problem is that the build header tries to extract the commit message that will be displayed from a prop (`head_commit.message`) that doesn't exist in the payload received from the `autodeployment` for releases. (it exists for regular merges to master).
This is a temporary fix, we should change the `autodeployment` server to send only one type of payload, regardless of event type.
This was already tested in production
=> [Fix]: Build header doesn't display build info in production

.vscode/settings.json, src/web/.eslintrc.js
This is a partial fix for #2970.  We need to use the correct name for our plugin (fully qualified), and we also need to tell the VSCode eslint plugin about pnpm and our packages.
I think we probably need an `.eslintrc.js` file in every sub-project, even if it only uses `extends` so vscode can find the config file.
=> Fix eslint and eslint vscode for src/web

docker/production.yml
In #2782, the `logrotate` service was removed, but we forgot to remove the volume used in our docker flow.
This PR removes this volume.
N/A
=> [Fix]: Remove unused volume

docker/production.yml
https://dev.portainer.telescope.cdot.systems/ gives "Bad Gateway" from nginx, because Traefik is routing to the wrong port in the Portainer container.  I'm using 80, but it's really 9000.
There's no way to test this except to do it on staging.
=> Use port 9000 vs. 80 for portainer router

tools/collect-dependencies.js
Fixes #3006 
This may fix the issue, however, I am not sure that it will completely fix it. The issue that @manekenpix showed is related to the output being too big so it cannot hold it in the buffer. This PR just increases the maximum size of the buffer.
The reason I am unsure that these two errors are linked is because the error happens before writing to the file, however, the file itself looks like it was truncated and did not receive any output.
1. Get my changes
2. You can run the script with `node tools/collect-dependencies.js -- -o src/api/dependency-discovery/deps.txt`.
We might need to test the `preversion` script. I would need some assistance for this.
=> Increase buffer size for the dependency script

pnpm-lock.yaml, src/docs/.eslintrc.js, src/docs/package.json, tools/eslint/package.json
Fixes #2970 
Before when we ran `pnpm lint`, we get only lint our tree and the Next.js frontend
```
PS C:\Users\lecin\Documents\repo\telescope> pnpm lint   
> @senecacdot/telescope@2.7.1 lint C:\Users\lecin\Documents\repo\telescope
> pnpm turbo run lint
• Packages in scope: @senecacdot/autodeployment, @senecacdot/eslint-config-telescope, @senecacdot/feed-discovery-service, @senecacdot/image-service, @senecacdot/planet-service, @senecacdot/posts-service, @senecacdot/search-service, @senecacdot/sso-service, @senecacdot/status-service, @senecacdot/telescope-frontend, dependency-discovery, migrate, parser, telescope-docs
• Running lint in 14 packages
@senecacdot/telescope-frontend:lint: cache hit, replaying output ea6f907d061ff4ab
@senecacdot/telescope-frontend:lint: …
```
=> Fixes #2970 add eslint configurations to Docusaurus and play together with turborepo's linting

config/nginx.conf.template, docker/production.yml
Fixes #3018.  This moves the Portainer routing back under nginx.  I'm not going to fight with Traefik over web socket connections.
The web socket connections are there so that we can shell into containers via the browser.
I can't really test this without trying on staging.
=> Handle portainer routing in nginx

config/nginx.conf.template
I thought I'd fixed the Portainer web socket access, but it looks like it's still broken:
```
containerConsoleController.js:173 WebSocket connection to 'wss://dev.portainer.telescope.cdot.systems/api/websocket/exec?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJhZG1pbiIsInJvbGUiOjEsInNjb3BlIjoiZGVmYXVsdCIsImV4cCI6MTY0NTc0NzA5Mn0.1RA-RvuwVMxH-k6zI1ZaDf27o-W7vuxFHXD1UL3Onp0&endpointId=1&id=f8160161d5e950783cac991551448f34fb8a92686265daa5c22476a49fe6ea55' failed
```
I think the issue is that you need to use HTTP 1.1 vs. HTTP 2 for the web socket connection upgrade to work.
=> Use HTTP 1.1 for Portainer /api/websocket route

.github/renovate.json, pnpm-lock.yaml, src/api/dependency-discovery/package.json, src/api/feed-discovery/package.json, src/api/image/package.json, src/api/parser/package.json, src/api/planet/package.json, src/api/posts/package.json, src/api/search/package.json, src/api/sso/package.json, src/api/status/package.json, tools/autodeployment/package.json
Could potentially fix #2959 
Changed the `rangeStrategy` of Satellite on Renovate to `bump`
As discussed in #3049 , and [documented here](https://docs.renovatebot.com/configuration-options/#rangestrategy)
I then changed all the Satellite dependencies from `1.26.0` to `^1.26.0`, and then ran `pnpm install`
After the merge, we might be able to re-trigger the Renovate dependency scan, and see if Satellite will show up as a dependency. After that, we can manually click on the Satellite checkbox on the dependency dashboard, instead of having to run `pnpm update -r --latest @senecacdot/satellite`, and create PRs ourselves.
=> update Satellite rangeStrategy to 'bump' for Renovate

src/docs/docusaurus.config.js, src/docs/i18n/es/docusaurus-plugin-content-docs/current/overview.md, src/docs/i18n/fr/docusaurus-plugin-content-docs/current/overview.md, src/docs/i18n/ru/docusaurus-plugin-content-docs/current/overview.md, src/docs/i18n/uk/docusaurus-plugin-content-docs/current/overview.md, src/docs/i18n/vi/docusaurus-plugin-content-docs/current/overview.md, src/docs/i18n/zh-cn/docusaurus-plugin-content-docs/current/overview.md
fixes: #2922 
Setup [i18n](https://docusaurus.io/docs/i18n/tutorial) for docusaurus, I only put languages that we are going to translate based on the table of this issue https://github.com/Seneca-CDOT/telescope/issues/2962
**Note: Only the overview page is overwritten, the rest is gonna stay in English**
Option 1: Run build
- `cd src/docs`
- `pnpm build && pnpm serve`
Option 2: Run dev
- `cd src/doc`
- `pnpm start -- --locale <LOCAL_CODE>` e.g. `pnpm start -- --locale fr`(For the french version)
https://user-images.githubusercontent.com/58233223/155567489-90c05c83-6e4a-4e4a-a54a-241d724a1900.mp4
=> Setup i18n for docusaurus

pnpm-lock.yaml, src/web/package.json
I fat-fingered and messed up #3054 and didn't want to bug Renovate bot to fix my mistake so here is a manual PR to update @types/node to v16.11.26.
=> chore(deps): update dependency @types/node to v16.11.26

src/docs/docs/tools-and-technologies/nextjs.md
Fixes #2938
This PR fixes the missing colours for the palette in the docs and reorganizes it with tabs for Light and Dark mode.
- Change directory to /src/docs: `cd src/docs`
- Start the server: `pnpm start`
- Visit `localhost:4631` in browser
=> Fix colour palette in docs

.gitpod.yml
Since we've recently removed the User service in favor of Supabase, we've cleaned most if not all traces of it in the repo.
I've been using gitpod quite a bit, so I noticed that the config file hasnt been modified to reflect the above change.
just a small change to amend it
=> remove user service deployment from gitpod yml

.github/renovate.json
Fixes #3107
This PR tells Renovate bot to ignore the `src/mobile` directory. Our React Native app needs specific versions of some dependencies to run properly so we do not want Renovate bot working in `src/mobile`.
=> Fixes #3107 Set Renovate bot to ignore `src/mobile` directory

package.json, src/api/image/package.json, src/api/status/package.json, src/docs/package.json, src/web/package.json, turbo.json
Fixes #3125
This PR adds `clean` scripts to allow us to delete `node_modules` and build outputs from our docs, next.js frontend and status board by running `pnpm clean` in the root directory. The `clean` script uses `pnpm`'s [recursive](https://pnpm.io/cli/exec#--recursive--r) method to prune `node_modules` installations for all packages and adds a `clean` step to our Turborepo's pipeline. Turborepo will through all our `package.json`'s provided by `pnpm-workspace.yaml` and find all the `clean` scripts then runs them. This PR adds `clean` scripts to the following:
- root
- src/api/image (updated because the original script uses the `del` cmd so it only works on Windows) 
- src/api/status
- src/docs
- src/web
To reiterate: 
https://github.com/Seneca-CDOT/telescope/blob/430f7715c3345f4f8ab6d …
=> Fixes #3125 add `clean` scripts to delete node_modules and build outputs

docker/docker-compose.yml
Fixes #1365 
The AOF file would get corrupted during a power outage. During recovery, the redis-server would not be able to read this corrupted file, and thus end the process, making the container service unavailable.
Instead, when a power outage occurs, redis shall use the dump.rdb file, which works fine for our current use case.
2. Wipe out any existing `redis-data` folder.
3. Create a new `redis-data` folder by turning the necessary services for the backend to fill in any posts (`pnpm run services:start` and then `pnpm start`)
4. Shut down all services and backend after filling the database
5. Truncate the `appendonly.aof` file to a considerably shorter length (use `truncate` command in linux and macOS)
6. Run `redis` container only (`pnpm run services:start redis`) …
=> Opt-out of appendonly mode in redis

src/api/planet/src/index.js
In a recent update, [express-handlebars](https://github.com/express-handlebars/express-handlebars) has change the way it needs to be imported/required. Because of this change, our `planet` service crashes at launch:
```sh
/telescope/src/api/planet/src/index.js:9
app.engine('handlebars', expressHandlebars());
^
TypeError: expressHandlebars is not a function
```
This PR changes the way `express-handlebars` is required in the `planet` service, according to their [documentation](https://github.com/express-handlebars/express-handlebars#usage).
=> [Fix]: Use proper way to require express-handlebars

src/api/status/public/css/terminal.css
Fixes Issue #2952 
This PR will add some extra padding for the content inside the build log in terminal. The picture below is currently `1rem`
- Change `autodeploymentUrl` in `src\api\status\public\js\build-log\check-build-status.js`
```
const autodeploymentUrl = (path) => `//dev.telescope.cdot.systems/deploy${path}`;
```
- Allow all `connectSrc` in `src\api\status\src\server.js`
```
connectSrc: ["'self'", "*"],
```
- Change the current directory to `api` service: `cd src/api/status`
- Run `pnpm dev` and go to `localhost:1111` on your browser
=> Fixes #2952: Add extra padding to the content in build log in terminal

src/docs/docs/api-services/api.md, src/docs/docs/api-services/auth.md, src/docs/docs/api-services/feed-discovery.md
#203 (this one documents the `feed-discovery` service only)
This PR expands the documentation for the `feed-discovery` service.
The structure used in similar to the [GitHub REST API docs](https://docs.github.com/en/rest).
2. Go to the docs (`cd src/docs`)
3. Start docusaurus locally (`pnpm start`)
=> Write feed-discovery documentation

pnpm-lock.yaml, src/docs/docusaurus.config.js, src/docs/package.json
Fixes issue #2960 
This PR is going to set up [Mermaid](https://github.com/sjwall/mdx-mermaid) for our Docusaurus. The picture below is a sample to proof that Mermaid is working in our docs
- Change the current directory to `src/docs`: `cd src/docs/`
- Run `pnpm start`
- Go to `localhost:4631` on the web browser
=> Setup Mermaid for Docusaurus

pnpm-lock.yaml, pnpm-workspace.yaml, src/satellite/.eslintrc.js, src/satellite/package.json, src/satellite/src/create-error.js, src/satellite/src/index.js, src/satellite/src/redis.js, src/satellite/src/satellite.js, src/satellite/test.js, tools/eslint/index.js
Fixes #3144 
This PR fixes ESLint configuration for Satellite and fixes ESLint errors.
`pnpm i`
`pnpm lint`
=> Configure ESLint for Satellite and fix ESlint errors

pnpm-lock.yaml, src/api/dependency-discovery/.eslintrc.js, src/api/dependency-discovery/package.json, src/api/dependency-discovery/src/dependency-list.js, src/api/dependency-discovery/test/dependency.test.js
Fixes #3154 
This PR sets up the eslint configuration for the `dependency-discovery` service. It also fixes current eslint issues that occurred when running the linter.
2. Checkout my branch (`git checkout issue-3154`)
3. Ensure you have the proper dependencies installed (`pnpm install`)
4. Run `pnpm lint`.
=> Set up ESLint for dependency-discovery

src/docs/docusaurus.config.js
Fixes #2926 
This PR will add the sitemap plugin for Docusaurus, and it will create sitemaps so search engine crawlers can crawl our docs website more accurately.
Based on the [docs](https://docusaurus.io/docs/api/plugins/@docusaurus/plugin-sitemap): 
> This plugin is always inactive in development and only active in production because it works on the build output.
Because of that, right now I am not sure how to test this one locally yet.
=> Add sitemap to Docusaurus

src/api/parser/src/data/post.js, src/web/src/components/Posts/Post.tsx
Fixed #2941 
Ignore `img` tag when `linkify`
At the `root` directory remove `redis-data`
```
rm -r redis-data
```
Rebuild images, `pnpm services:start` and wait for `redis` to cache the feeds
=> Ignore img tag when using linkifier

docker/production.yml
This will have production/staging prefer the image on docker.cdot.systems instead of building from source.
=> Use docker.cdot.systems image for feed-discovery in production

.npmrc, pnpm-lock.yaml, pnpm-workspace.yaml, src/mobile/package.json
fix #3191
By default, available packages listed in pnpm-workspaces are linked to node_modules instead of being downloaded from the registry to save space.
This adds an option to make pnpm to use Satellite on npm vs the package.
=> [satellite]: use Satellite from npm registry

.github/workflows/e2e-tests-ci.yml
In order for the Docker layer caching to work, we need to use the `buildx` Docker plugin.  This adds it to our e2e tests so that we can pull cached layers from our docker.cdot.systems registry that were created by CI.
When I do this locally with `buildx`, I can see the cached layers being used for some of the build steps:
```
...
#7 [auth] image:pull token for docker.cdot.systems
#7 DONE 0.0s
#6 importing cache manifest from docker.cdot.systems/image:buildcache
#6 DONE 1.0s
...
```
=> Set up buildx before running containers in e2e tests for caching

tools/collect-dependencies.js
Fixes #3181
Since `replaceAll` is only used in nodejs v15 or above, and npm uses nodejs v14 (for some reason that I do not know), it is impossible to use `replaceAll`.
2. Change to my branch
3. Remove `postversion` command from the package.json, or modify it so that it pushes the changes to your fork (`git push origin master`).
4. Run `pnpm version 2.8.1 -m "Version 2.8.1"`.
After this, the `deps.txt` should have project names.
=> Use `replace` instead of `replaceAll`

.github/workflows/continuous-delivery.yml, .github/workflows/release.yml
I was using the `/deploy` URLs for the deploy webhook, but testing tonight with @manekenpix makes me think that it's not handling the redirect properly.  So I'm going to try changing it to use the actual webhook URLs at port 4000.
=> Switch deploy webhook URL to deal with redirects

src/api/image/src/index.js
Fixes #3212 
This PR changes the cross origin resource policy (CORP) in the image service so images can be fetched by both our servers' front-end or a locally deployed instance of our front-end
Run the front-end locally but using `staging` as back-end (`staging` is currently running with the changes in this PR).
1. Make `env.staging` your `.env` file
```sh
cp config/env.staging .env
```
2. Run the front-end
```sh
pnpm dev
```
Your hero banner image should be loaded.
=> Fixes #3212: Banner image failed to load because CORS violation

pnpm-lock.yaml
We've made the decision to not link local packages, both Satellite and Eslint.
=> Don't link local package

docker/supabase/docker-compose.yml, pnpm-lock.yaml, src/api/sso/jest.config.e2e.js, src/api/sso/package.json
We discovered that the `postgres` db container that Supabase runs needs a long time to become ready, even after Docker says that the container is up.  If we run our tests during this time, they will fail.  This explains why they sometimes fail and sometimes are OK.
This change will have our e2e tests wait on the postgres db to become actually ready (able to handle a connection).
We will need to leave the postgres port open for local dev, but close it in production for Supabase.
Fixes #3031
=> Wait on postgres to become ready before running sso e2e tests

package.json, src/api/dependency-discovery/package.json, src/api/image/package.json, src/api/status/package.json, src/docs/package.json, src/mobile/package.json, src/satellite/package.json, src/web/package.json
According to Turborepo, this is a [Pro Tip](https://turborepo.org/docs/features/caching)
Adds [TIMING=1](https://eslint.org/docs/1.0.0/developer-guide/working-with-rules#per-rule-performance) to track performance of individual rules. If we ever see a 0% on a rule that means we're not using that rule at all so it should be removed. We currently don't have anything that is 0% so we are using all the rules we've added
Sample result table from our Next.js app.
```
@senecacdot/telescope-frontend:lint: Rule                              | Time (ms) | Relative
@senecacdot/telescope-frontend:lint: :---------------------------------|----------:|--------:
@senecacdot/telescope-frontend:lint: prettier/prettier                 |  5011.008 |    48.9%
@senecacdot/telescope-frontend:lint: …
```
=> add TIMING=1 to eslint scripts

.npmrc, pnpm-lock.yaml, src/web/package.json
Related to #3208
This does not fully close the issue because it only covers `src/web`
- adds `auto-install-peers=true` to `.npmrc` in root so whenever we add dependencies in the future, it will automatically install any missing peer dependencies
- installs `webpack` because it is listed as a missing dependency
3. Checkout my branch: `git checkout issue-3208`
5. You should not see:
```
src/web
├─┬ babel-loader
│ └── ✕ missing peer webpack@>=2
├─┬ terser-webpack-plugin
│ └── ✕ missing peer webpack@^5.1.0
└─┬ next-pwa
├─┬ clean-webpack-plugin
│ └── ✕ missing …
```
=> Fixes #3208 add auto-install-peers, install missing deps in src/web

src/mobile/package.json, src/mobile/src/App.jsx, src/mobile/src/components/Banner/Banner.jsx, src/mobile/src/navigation/Navigation.jsx, src/mobile/src/screens/AboutScreen.jsx
Fixed #2859 
Add the `About` page to our mobile app
1. Open my PR in Gitpod
2. `cd src/mobile`
3.  Run `pnpm start`
4. Refer to mobile docs on choosing testing device
https://user-images.githubusercontent.com/43376325/157895685-41f9050d-91d3-4bbf-ae29-a62948e3dc51.mp4
=> About page and fixing some ESLint problems by import react package

.github/workflows/e2e-tests-ci.yml, bin/services-pull.js, docker/docker-compose.yml, docker/supabase/docker-compose.yml, package.json, src/docs/docs/api-services/api.md, tools/services.js
I want to see if I can force `docker-compose` to use BuildKit and the caching behaviour we want for our image builds.  This might not work, I need to test in CI.
=> Use BuildKit with all Docker build commands for cache

src/api/image/src/lib/photos.js, src/api/image/src/routes/image.js, src/api/image/test/image.test.js, src/web/src/components/Banner.tsx, src/web/src/components/BannerButtons.tsx, src/web/src/components/BannerDynamicItems.tsx, src/web/src/components/DynamicImage.tsx, src/web/src/pages/index.tsx, src/web/src/pages/signup.tsx, tools/eslint/index.js
Fixes #2925
- Add loading banner image background by displaying a tiny 40px wide image (minimal loading time) and transitioning  in the main 2000px wide image (long loading time) when it finishes loading 
- Add fallback gradient banner background
- Fix inconsistent image src, request a specific photo versus a random image chosen by the backend
- Pull this change locally
- Run server: 
```
cd src/api/image && pnpm dev
// in another terminal
cp config/env.staging .env
// change IMAGE_URL in .env
IMAGE_URL=http://localhost:4444
// Run the frontend
pnpm dev
```
- to see that a gradient background is shown first, followed by a placeholder image, and then the high resolution image.
- If you are not able to see the difference, your internet is probably too fast, good. Go to the Network tab, …
=> feat: Banner image placeholder and fallback background

docker/development.yml, docker/docker-compose.yml, docker/production.yml
This reduces elasticsearch's memory usage in development by 50%:
```sh
$ docker stats --no-stream
CONTAINER ID   NAME            CPU %     MEM USAGE / LIMIT     MEM %     NET I/O        BLOCK I/O    PIDS
96f7cd128f72   elasticsearch   0.89%     567.6MiB / 9.718GiB   5.70%     46MB / 501kB   0B / 182MB   81
```
I don't think we can go lower than this, based on docs I've been reading today.  I've also removed the requirements to not use swap in development, since we don't care about speed as much as memory footprint.
Part of #3241.
=> Reduce memory usage for elasticsearch in development

package.json, pnpm-lock.yaml
Fixes #3208
- installs `jest-circus`, `jest-environment-node`, `jest-runner`, `redis-commands`, `typescript` because they are listed as missing peer dependencies
3. Checkout my branch: `git checkout issue-3208-d`
5. You should not see:
```
 WARN  Issues with peer dependencies found
.
├─┬ jest-playwright-preset
│ ├── ✕ missing peer jest-circus@>=26.6.3
│ ├── ✕ missing peer jest-environment-node@>=26.6.3
│ └── ✕ missing peer jest-runner@>=26.6.3
├─┬ ts-jest
│ └── ✕ missing peer typescript@">=3.8 <5.0"
└─┬ ioredis-mock
└── ✕ missing peer redis-commands@1.x …
```
=> Fixes #3208 install missing peer deps in root

tools/autodeployment/webhook.js
USAGE: Fixes #3205 && Fixes #3189 
This PR is an attempt to use our new `DOCKER_DEPLOY_TAG` that I made in a [previous PR](https://github.com/Seneca-CDOT/telescope/pull/3265). We want to use it to trigger the proper deploy build from our autodeployment server. 
This PR will need to be tested in staging
=> Updating autodeployment webhook to use custom "deploy" tag

.github/workflows/continuous-integration.yml, .github/workflows/pnpm-lock-check-ci.yml
Fixes #3311 
This PR adds a new CI check to make sure that the `pnpm-lock.yml` is never broken.
Let the CI run, I guess...
=> Add pnpm lock file check to CI

tools/collect-dependencies.js
Fixes #3276 
In Windows, pathnames are separated by backwards slash. Since the regex cannot find a match, the script would produce an empty file.
Thus, we modify the regex to avoid this.
If you are in Windows (not WSL), please run the following steps:
2. Run the command `node tools/collect-dependencies.js -- -o deps.txt` from the project root
3. Verify that the `deps.txt` is not blank.
=> Count for \ in regex

docker/development.yml, docker/docker-compose.yml, docker/gitpod.yml, docker/production.yml, src/api/parser/Dockerfile
Fixes #2111 
- Revert all commented parser's docker code
- Add code to fit in with recent docker changes
- Rework parser's docker file to better practice
- go to `localhost:8000` AND THAT'S ALL YOU NEED, NO `pnpm start`
=> Dockerize Parser service

src/docs/.dockerignore, src/docs/Dockerfile
Fixes #1668
- Remove development part
- `cd src/docs`
- `docker build -t docs:test .`
- `docker run --rm -p 80:80 docs:test`
- Go to `localhost`
=> Refactor Dockerfile docs

pnpm-lock.yaml, src/api/dependency-discovery/package.json, src/api/dependency-discovery/src/dependency-list.js, src/api/dependency-discovery/src/github.js, src/api/dependency-discovery/src/router.js
Fixes #2827 
This PR adds the whole GitHub issue thing to collect issues that are considered newcomer friendly.
This doesn't use Redis, at all. I tried to use Redis at first, but it seems that using it is somewhat redundant when the `githubInformationRequestor` is used. The reason I use this is to minimize the number of requests as possible when there are concurrent requests to the same resource. If we program this naively, when there are two or more requests really close to each other, all of those requests will ask essentially the same information, and thus we would be wasting requests.
I will file a couple of issues to address some stuff that have to be changed:
- use Redis instead of a *requestor*, this would imply some rewriting of the whole service, probably.
- use a GitHub Key for …
=> Get GitHub issues from dependency repo

docker/supabase/volumes/db/init/05-github-schema.sql
Fixes #3215
This PR adds a new table schema to Postgres to store the GitHub data we will scrape from the posts.
1. Pull the changes.
2. Start the services (`pnpm run services:start`).
3. Go to `localhost:8910`.
4. Head over the default project and then find the database tables. There should be tables named `github_users`, `github_repositories`, and `github_issues`.
=> Add GitHub schema to Postgres

src/web/app/src/components/GenericInfoProvider.tsx, src/web/app/src/components/Posts/GitHubInfo/Commits.tsx, src/web/app/src/components/Posts/GitHubInfo/GitHubInfoMobile.tsx, src/web/app/src/components/Posts/GitHubInfo/Issues.tsx, src/web/app/src/components/Posts/GitHubInfo/PullRequests.tsx, src/web/app/src/components/Posts/GitHubInfo/Repos.tsx, src/web/app/src/components/Posts/GitHubInfo/Users.tsx, src/web/app/src/components/Posts/GitHubInfo/index.tsx, src/web/app/src/components/Posts/Post.tsx, src/web/app/src/components/Posts/YouTubeInfo/YouTubeInfoMobile.tsx, src/web/app/src/components/Posts/YouTubeInfo/index.tsx, src/web/app/src/components/YouTubeInfo.tsx, src/web/app/src/hooks/use-genericInfo.ts
Fixes #2680
This PR adds the front-end for the YouTube banner information. Currently, there are two values that always show negative. This will be addressed in a future PR involving the back-end.
You can view the changes in vercel autodeployment, however, you can do it locally too.
1. Pull my changes.
2. Use the staging configuration (`cp config/env.staging .env`)
3. Start the front-end (`pnpm dev`)
4. Find the earliest post that is a YouTube video (you can search for the one in the screenshots).
=> Add the YouTube banner information for desktop screens

src/api/search/src/bin/validation.js, src/api/search/src/routes/query.js, src/api/search/src/search.js, src/api/search/test/query.test.js, src/backend/utils/indexer.js
- Add author autocomplete settings for indexer.js in backend
- refactor Search service to work with new indexing
- create new search query for author autocomplete
- add supertest as a dev-dependency to pass ESLint
Fixes #1417 
also a part of issue #3225 (no new tests are added just yet)
- In the legacy `backend`, I've added `settings` and `mapping` for the `posts` index to use [edge n-gram](https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-edgengram-tokenizer.html) for author autocomplete
- Because we couldn't specify `type` on index creation, I've refactored the `Search` service and tests to work with the new indexing. The current search query is not affected by this new change. `pnpm test search` would pass all tests.
- To get author autocomplete suggestions, I've …
=> Implement Author Autocomplete (legacy backend and Search)

.github/workflows/docker-build-and-push.yml
The front-end build for nginx needs the `GIT_COMMIT`, but we aren't passing it in with the build args to Docker.  This adds it.
=> Include github.sha for GIT_COMMIT in build args for CD

tools/autodeployment/deploy.sh
Our `deploy.sh` autodeployment script needs to be updated for pulling vs. building our containers, now that we have the registry.  This switches the build to use [pull](https://docs.docker.com/compose/reference/pull/) instead.
=> Update deploy.sh to pull vs. build images

src/api/status/public/js/build-log/build-header.js
After making changes to our `autodeployment` server, the build header stopped displaying status and total duration of current build, This PR fixes that issue.
- Checkout the branch used for this PR.
- Make sure the build page fetches data from an autodeployment server [here](https://github.com/Seneca-CDOT/telescope/blob/7e9e2b89e884ac040f6dce2d24c248ae51943971/src/api/status/public/js/build-log/check-build-status.js#L44).
- You might need to add the `autodeployment` server's URL to helmet [here](https://github.com/Seneca-CDOT/telescope/blob/7e9e2b89e884ac040f6dce2d24c248ae51943971/src/api/status/src/server.js#L36).
- Navigate to the build page and make sure the build header displays the correct information about the current build.
=> Fix: display buid status and total duration

src/mobile/src/components/Footer.jsx, src/mobile/src/components/GitHubContributorCard.jsx, src/mobile/src/screens/AboutScreen.jsx
Fixes #3203 
- Added Footer for about screen
- Github API was not added so the contributor card still remains static
=> Footer for About Screen of React Native mobile app

config/env.development, config/env.production, config/env.staging, docker/supabase/docker-compose.yml, docker/supabase/supabase-development.yml, docker/supabase/supabase-production.yml
We had a meeting today about things that need to happen for Supabase to get put into production. One of them was to fix how we do volumes for postgres in dev vs. staging/prod.
I've created override files for dev and prod environments, which disable ports and fix the location of persistent volumes we mount.
We need to do the `secrets.env` before we can land this, but I hope @manekenpix and I can do that soon.
=> docker-compose for Supabase in dev/prod

Dockerfile, docker/docker-compose.yml, src/api/dependency-discovery/Dockerfile, src/api/feed-discovery/Dockerfile, src/api/image/Dockerfile, src/api/parser/Dockerfile, src/api/planet/Dockerfile, src/api/posts/Dockerfile, src/api/search/Dockerfile, src/api/sso/Dockerfile, src/api/status/Dockerfile, src/web/app/Dockerfile, src/web/docusaurus/Dockerfile
I can't build our images anymore on my M1 (ARM) laptop.  This changes things to use a larger node image (with build tools like Python) for installing deps, then copies the deps over to an `-alpine` image that's smaller (no build tools, etc).
I've also removed the manual `tini` stuff, and added `init: true` instead, which does this automatically in Docker engine.
I also fixed the `PORT` stuff, since we might as well use the right port naming.
=> Update Dockerfiles for M1

.github/workflows/docker-build-and-push.yml, .github/workflows/release.yml, config/env.development, docker/docker-compose.yml, docker/supabase/docker-compose.yml, src/api/sso/env.local, src/web/docusaurus/docs/contributing/staging-production-deployment.md, tools/autodeployment/README.md, tools/autodeployment/deploy.sh
This is needed for #3098, #3361 (which @TueeNguyen needs to land manually again).
In this PR, I'm updating our code to use the new secrets @manekenpix and I are adding to staging and production.  I'm going to give the secrets to @manekenpix separate to this PR, for obvious reasons.  Here, I'm doing the following:
1. Update the `anon_key`s we use in staging and production.  These had to be regenerated, since I changed the `JWT_TOKEN` we use.
2. Added a note about how to generate new Supabase keys
3. Removed all uses of `SECRET`, which we don't use anymore (we use `JWT_SECRET`)
4. Removed from env vars that got added to Kong, which @Kevan-Y and I don't think are required.
5. Updated our autodeployment `deploy.sh` script to use two additional env files.  NOTE: these files do **not** live in …
=> Rework configs, docker, envs, CI/CD for production secrets

pnpm-lock.yaml, tools/migrate/README.md, tools/migrate/env.example, tools/migrate/feed.js, tools/migrate/package.json, tools/migrate/to_json.js, tools/migrate/to_supabase.js
Fixes #3359.
This modifies the current `Migrate` service to migrate the Planet Feed List to Supabase.
Ideally, we only need to run this once on production and start managing all feeds there.
Once the production database is populated, I think we can use it for development as well because the `feeds` table has RLS rules that allow reading to all users and deleting/updating for feed owners.
=> Migrage planet feed list to supabase script

docker/production.yml
Fix for redirect URL for oauth2-proxy not set properly (`redirect_uri=http://dev.supabase.telescope.cdot.systems/dev.supabase.telescope.cdot.systems/oauth2/callback`). 
- Changed to `'--redirect-url=/oauth2/callback'`
- Added  '--force-https=true' to have https instead of http.
=> Fix oauth2-proxy config

config/nginx.conf.template, docker/production.yml
In the previous PR https://github.com/Seneca-CDOT/telescope/pull/3378, oauth2-proxy crashed the Nginx, because of `--force-https=true`.
- Removed `--skip-auth-regex=/forms/*` deprecated and not needed 
- Removed `--force-https=true` (Not needed, can use our Nginx to put the correct protocol)
- Set `--cookie-secure` to true, we want this to be secure 
- Set `--reverse-proxy` to true, to tell this services is under a proxy
- Removed `--redirect-url` since it will automatically, using our domain.
=> Fix nginx config for oauth2-proxy

src/web/docusaurus/docs/api-services/api.md, src/web/docusaurus/docs/getting-started/environment-setup.md, src/web/docusaurus/docs/getting-started/vscode-ssh.md, src/web/docusaurus/docs/tools-and-technologies/login.md, src/web/docusaurus/docs/tools-and-technologies/pino.md, src/web/docusaurus/docs/tools-and-technologies/renovate.md, src/web/docusaurus/docusaurus.config.js
Fixes #3048
- `cd ./src/web/docusaurus`
- `docker build -t docs:prod .`
=> Fix docusaurus broken links

docker/supabase/docker-compose.yml, docker/supabase/supabase-development.yml, docker/supabase/supabase-production.yml
Yesterday @DukeManh, @Kevan-Y and I tried to insert all the feeds into Supabase on staging.  We found that our `service_role_key` wouldn't work, and even our `anon_key` won't pass verification.  The issue is that we are hard-coding the keys into our `kong.yml` config: https://github.com/Seneca-CDOT/telescope/blob/master/docker/supabase/volumes/api/kong.yml#L6-L12
These need to match the keys we use on staging and production.
I've created new `kong.yml` files for staging and production, and sent to @manekenpix to add to the servers.  Once those are in place, we can do this change.
@manekenpix, please confirm that the paths I have used for production match what you do with these files (I think I'm right, but it's untested).
Fixes #3381.
=> Update how kong.yml is used to configure Supabase in dev vs. prod

docker/development.yml, src/api/parser/src/parser.js, src/api/parser/test/e2e/parser-flow.test.js
Fixes #3369 
Fixes #3369 
* Use blog from test-web-content,
* Change invalid urls 
* Specify jest.mock() to return a mock function
- `pnpm i`
- stop the parser container before running the test
- `pnpm jest:e2e src/api/parser`
=> Improve parser's e2e test

src/api/status/src/views/partials/sidebar.hbs
closes #3380
Adds staging/production links for Portainer and Supabase on our status page sidebar
- `pnpm services:clean`
- `pnpm services:start status`
- Navigate to `localhost:1111`
- `cd src/api/status`
- `pnpm install`
- `pnpm dev`
- Navigate to `localhost:1111`
Check sidebar for new links
=> added portainer and supabase prod/staging links to sidebar

src/api/dependency-discovery/src/__mocks__/dependency-list.js, src/api/dependency-discovery/test/dependency.test.js
Fixes #3331
This PR adds some test cases to the route `/github/:project/` in the `dependency-discovery`.
I don't think you need to test this locally, just let CI do the checks for you 😉 
However, if you insist:
1. Get my changes,
2. Run the tests for only the service so that it is faster (`pnpm run jest dependency.test.js`).
=> Add initial tests for /github/:project

src/api/parser/src/utils/indexer.js, src/api/parser/test/feed.test.js
extension of #3301 
moves autocomplete indexing to `Parser`
```
rm -rf redis-data
docker-compose --env-file ./config/env.development up --build redis elasticsearch posts traefik search nginx planet parser
```
- Wait for re-indexing
- author autocomplete query will now work at http://localhost/v1/search/authors/autocomplete/
- `pnpm test src/api/parser` will pass
I am not sure if staging still runs the backend and if it will affect indexing on staging.
=> Autocomplete indexing in Parser

src/api/search/test/query.test.js
fixes #3225 
Add unit tests for autocomplete query
`pnpm test search`
=> Add author autocomplete query unit tests in Search

.github/workflows/release.yml
This PR extends the regex in CD to allow for release tags like `3.0.0-alpha`.
=> Modify regex in CI to allow prerelease

Dockerfile
Our legacy backend containers keep restating due to missing `package.json` in the last stage where we run the container
Logs of the issue:
```plain
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, open '//package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 
npm ERR! A complete log of this run can be found in:
```
- Add ` ackage.json` to the last stage.
=> Fix docker legacy backend

.github/workflows/docker-build-and-push.yml, src/db/.dockerignore, src/db/Dockerfile
This adds a `Dockerfile` to `src/db` so that we can run the Prisma migrations on staging and production via Portainer in a new container.  This will build and push a new image every time we push to `master` or create a new `tag` for production.
On Portainer, we would create a new container, and specify the correct `DATABASE_URL` environment variable to use for the given environment (staging/production):
This needs to be tested, but it's a start.
=> Fix #3435 - Dockerize src/db

package.json, pnpm-lock.yaml, src/api/sso/.dockerignore, src/api/sso/Dockerfile
Fixes #1668
- Use a smaller base image
Image is a bit bigger because we install the pnpm package
```bash
❯ docker images | grep refactor/sso
refactor/sso                                    new                d31f703b6c2b   18 seconds ago       132MB
refactor/sso                                    old                02baf2192da0   2 weeks ago          135MB
```
- Go to `http://localhost/v1/auth/healthcheck`
=> Refactor Dockerfile sso

config/env.production, config/env.staging
The SSO service crashes over and over because it's missing the `SUPABASE_URL` environment variable.  This adds it for staging and production, now that it exists.
=> Add SUPABASE_URL to staging/production envs

.github/workflows/continuous-integration.yml, .github/workflows/eslint-ci.yml, .github/workflows/unit-tests-ci.yml, package.json, src/api/dependency-discovery/package.json, src/api/feed-discovery/package.json, src/api/image/package.json, src/api/parser/package.json, src/api/posts/package.json, src/api/search/package.json, src/api/sso/package.json, src/mobile/package.json, src/web/app/package.json, turbo.json
Fixes #3351 
This PR changes `pnpm test` to use Turborepo and adds support for Turborepo's cache in CI eslint and unit-tests.
The downside of this is not seeing all the green check marks when running tests locally, so I have left the option to run tests without Turborepo by running `pnpm jest`.
For CI I am using a GitHub Action that builds a local server (on port 9080) where Turborepo goes to look for the cache. To make it work, a `TURBO_SERVER_TOKEN` needs to be added to the repo.
If this is successful, we will be able to do the same for our e2e tests.
Resources:
[Custom Remote Cache](https://turborepo.org/docs/features/remote-caching#custom-remote-caches)
[TurboRepo with github artifacts ](https://github.com/marketplace/actions/turborepo-with-github-artifacts)
`pnpm test`
=> Use Turborepo for tests and add turbo cache for CI eslint and unit-tests

.github/workflows/docs-ci.yml, .github/workflows/mobile-deploy.yml
Fix fallout from #3458.  We need to pass the `server-token` into our workflows in more places to fix https://github.com/Seneca-CDOT/telescope/actions/runs/2154847106/workflow, etc.
=> Add missing server-token to ci workflows

.github/workflows/continuous-integration.yml, .github/workflows/docs-ci.yml, .github/workflows/eslint-ci.yml, .github/workflows/mobile-deploy.yml, .github/workflows/unit-tests-ci.yml
Fixes #3466.  I'm changing the name, in case that's part of it (e.g. reusing a name across the secret and arg value).
=> Rename server-token to turbo_server_token

.github/workflows/eslint-ci.yml, .github/workflows/unit-tests-ci.yml
I don't think we're allowed to pass a `secret` into an `input` value.  This accomplishes it (or tries to, not sure it will work) by doing it via an environment variable.
If this fails, I'll move it out of secrets--it's just an opaque string.
=> Use Turbo Server Token secret via environment variable

src/db/Dockerfile, src/db/package.json, src/db/prisma/migrations/20220409140003_add_rls_policy_new_tables/migration.sql
fix #3408 
Adds read level functionality, and restricts altering and updating for all users (github-* tables, and quotes table)
- navigate to http://localhost:8910
- check tables for new RLS policies
=> Add RLS for new Supabase tables (Github, Quotes)

pnpm-lock.yaml, src/db/prisma/migrations/20220412180736_add_id_to_feeds/migration.sql, src/db/prisma/schema.prisma, tools/migrate/package.json, tools/migrate/to_supabase.js
Fix #3462
Added migrations to add a URL `hash` column generated by Satellite to the Feeds table.
To add a field to the existing DB, we'll need:
1. First migration to add the field in the table with a default value of `""`
2. Run `to_supabase` script to add hash ids for each row
3. Second migration to drop the default hash id to make it mandatory
=> Add URL hash id to Feeds table

docker/docker-compose.yml, pnpm-lock.yaml, src/api/planet/env.local, src/api/planet/package.json, src/api/planet/src/planet.js, src/api/planet/src/util.js, src/web/app/src/config.ts
Fixes #3463.  This updates the `planet` service to use Supabase for the feeds info vs. Redis (cc @TueeNguyen, you can steal my code for getting author names for the parser, and @DukeManh is going to turn this into a stored procedure in the future).
I've also removed the unneeded `feedsUrl` and `userFeedsUrl` from the front-end.
@JerryHue After this I'm not sure if anything is using `posts/feeds` anymore.
=> Fix planet to use Supabase, remove feedsUrl/userFeedsUrl from front-end

.github/workflows/continuous-integration.yml, .github/workflows/docs-ci.yml, .github/workflows/eslint-ci.yml, .github/workflows/mobile-deploy.yml, .github/workflows/unit-tests-ci.yml
New plan: I'm not going to use a secret here, because I can't get it to pass through to the linked action.  The `server-token` just has to be a unique string per-run, so the `github.sha` is perfect.
=> Use git sha as token for Turbo Repo (no secrets)

.prettierignore, pnpm-lock.yaml, src/github-url-parser/dist/extract-github-info.d.ts, src/github-url-parser/dist/extract-github-info.d.ts.map, src/github-url-parser/dist/html-to-urls.d.ts, src/github-url-parser/dist/html-to-urls.d.ts.map, src/github-url-parser/dist/index.d.ts, src/github-url-parser/dist/index.d.ts.map, src/github-url-parser/dist/parse-github-url.d.ts, src/github-url-parser/dist/parse-github-url.d.ts.map, src/github-url-parser/dist/reserved-names.d.ts, src/github-url-parser/dist/reserved-names.d.ts.map, src/github-url-parser/package.json, src/github-url-parser/src/index.js, src/github-url-parser/src/reserved-names.js, src/github-url-parser/test/index.test.js, src/github-url-parser/tsconfig.json
I want to use the new github-url-parser module in the front-end, but it needs types defined. This adds type definitions for what I need.
See steps I followed in https://www.typescriptlang.org/docs/handbook/declaration-files/dts-from-js.html.
=> Add TypeScript types to github-url-parser for front-end use

src/web/docusaurus/docs/contributing/database-maintenance.md
Today on a call, we tested and documented how to maintain the database on staging and production.  I took notes in the wiki, and this moves it into our docs.
cc @manekenpix, @cindyledev so you're aware of this too.
=> Migrate https://github.com/Seneca-CDOT/telescope/wiki/Database-Maintenance to docs

tools/migrate/feed.js, tools/migrate/to_supabase.js
Change `tools/migrate` service to normalize feeds URL to avoid duplicates.
```
cd tools/migrate
cp env.example .env
pnpm to_supabase
```
=> Normalize and filter Planet feed urls

docker/supabase/backup/restore-backup.sh
Fixes #3497 
Instead of dropping the whole database and restoring the database (which happens when `--clean` and `--create` are both used), we just drop all the database objects, leaving the database clean, by only allowing the `--clean` flag.
1. Run the services (`pnpm run services:start`),
2. Go to the Supabase dashboard (`localhost:8910`),
3. Add several records to the `feed` table in the database.
4. Connect to the `pg-backup-cron-job` container with `docker exec -it pg-backup-cron-job sh`.
5. Create a back up with `/etc/periodic/daily/create-backup`. The dump file will be in `/var/opt/pg_dumps`, take a note of it.
6. Go back to the Supabase dashboard and remove a single record.
7. Go back to the container and run the command `./restore-backup <dump_file>`, where `<dump_file>` should …
=> Do not drop DB when restoring from backup

src/web/docusaurus/docs/tools-and-technologies/prisma.md
Write docs to Manage DB with Prisma
=> Add Telescope Prisma docs

src/web/app/src/components/SearchInput/SearchInput.tsx
Fixes #3443
Due to different font-size in `customInput` and `customInputText`, it makes the Search label text cut off.
Fixes:
- Change font size in `customInput` to match `customInputText`
1. `cp config/env.staging .env`
2. pnpm dev`
3. Go to the search page
=> Fix Search label text cut off

src/web/app/src/components/StarField.tsx
Fixes #3193.
This PR fixes the image flickering on the star field.
You can run in the deployment, but if you want to run on your PC:
1. Get my changes.
2. If you don't have them, I suggest you copy the staging configuration (`cp config/env.staging .env`)
3. Run `pnpm dev`
4. Go to `localhost:8000`
5. Go to the About page
No more flickering!
=> Fix image flickering on star field

src/web/app/src/components/SearchInput/SearchInput.tsx
Center the position of the search icon button on search page
Fix #3442
You can test the search page on the Vercel deployment of this PR
=> Fix search icon button position

src/web/docusaurus/docs/getting-started/vscode-ssh.md
Fixes #3516.  We can't link outside the src/web/docusaurus directory, or Docker can't resolve it.
=> Fix #3516: don't link outside src/web/docusaurus

src/web/docusaurus/docs/api-services/image.md
Fixes #3460 
This PR adds the documentation for the `image` service.
2. Go to the docusaurus directory (`cd src/web/docusaurus`)
3. Start up the web site (`pnpm start`)
=> Write image service docs

src/web/app/src/components/StarField.tsx
Fixes #3194 
This PR adapts the sizes of the star profile pictures in the star field so that they are proportional to the screen's width.
You can test in deployment, however, to test locally:
1. Pull my changes,
2. Copy the `staging` configuration (`cp config/env.staging .env`)
3. Run with `pnpm dev`
=> Resize stars depending on screen width

src/web/app/src/components/Posts/CopyButton.tsx, src/web/app/src/components/Posts/ShareButton.tsx, src/web/app/src/components/Posts/Timeline.tsx
Fixes #3356 
This PR refactors the functionality (and styling!) of the copy button used in both the share feature and the code block feature.
You can test on deployment, however, you can test locally by:
1. Pulling my changes
2. Get the configuration from staging (`cp config/env.staging .env`)
3. Start the front-end (`pnpm dev`)
=> Refactor copy button

pnpm-lock.yaml, src/web/docusaurus/docs/overview.md, src/web/docusaurus/package.json, src/web/docusaurus/src/components/StarField.jsx, src/web/docusaurus/src/components/StarField.module.css
#3407 (this PR just adapts the Star field component)
This PR adapts the `StarField` component found on the component to Docusaurus. The deletion of the component can be done when moving the entire `About` page to docusaurus.
1. Pull the changes
2. Run `pnpm i` (because there are new packages to be added to the docusaurus package).
3. Go to the docusaurus workspace (`cd src/web/docusaurus`)
4. Start the docusaurus app (`pnpm start`).
5. If you go to overview, you should be able to see the star field.
=> Adapt star field to docusaurus

src/api/status/public/css/telescope-dashboard.css, src/api/status/src/views/partials/commitCard.hbs, src/api/status/src/views/partials/contributionCard.hbs, src/api/status/src/views/partials/jobCountCard.hbs, src/api/status/src/views/partials/totalFeedCard.hbs, src/api/status/src/views/partials/totalPostCard.hbs, src/api/status/src/views/status.hbs
Reorganize the cards to remove the empty space on the right.
Change the icons' colours to have a more consistent look (The current black, blue and green are used randomly and don't have any meaning).
Remove the "Telescope" text from all the cards since it is now redundant.
Fix #3395
1. cd src/api/status
2. pnpm dev
3. view the server at localhost:1111
=> Reorganize status cards

src/web/app/src/components/SearchBar.tsx, src/web/app/src/components/SearchInput/AuthorInput.tsx, src/web/app/src/components/SearchInput/SearchInput.tsx
Improve the styling of Autocomplete input and search page in general
Fix #3444, fix #3427
You can test the search page on the Vercel deployment of this PR
=> Improve Autocompete styling

src/web/app/src/components/SearchBar.tsx, src/web/app/src/components/SearchInput/SearchInput.tsx
Wrap search inputs in HTML `form` element to trigger search on enter.
Fix #3434 
You can test the Vercel deployment of this PR
=> Trigger search on enter

jest-playwright.config.js, src/api/sso/test/e2e/signup-flow.test.js
Trying to disable Chromium in e2e tests until we fix #3504.
=> Disable e2e tests in Chromium until we fix #3504

.github/workflows/docker-build-and-push.yml, .github/workflows/release.yml
After https://github.com/Seneca-CDOT/telescope/pull/3487 merged. I noticed the fetch for fetching dependencies URL was not correct. 
Fix: 
- Added the missing dependency_discovery_url in CD
=> Add missing dependency_discovery_url in CD

.github/workflows/eslint-ci.yml, .github/workflows/unit-tests-ci.yml
This PR adds the `-team` flag as per recommendation: https://github.com/felixmosh/turborepo-gh-artifacts/issues/6#issuecomment-1105721055
We will be able to see if this works after it's been merged.
=> Add --team flag to turborepo command

src/web/docusaurus/docs/api-services/status.md
#3291 Only the status part
Documentation for the status service. It is the first draft and is open to edits.
- `cd src/web/docusaurus`
- `pnpm start`
- localhost:4631
- Click on Docs tab
- Click on API services, then `Status`
- Read the content. Does it make sense? Can it be better?
No tests for just docs. Prettier was okay with this.
No need for screenshots for just text.
=> Status service documentation

docker/development.yml, src/api/parser/env.local, src/api/parser/src/data/feed.js, src/api/parser/src/index.js, src/api/parser/src/parser.js, src/api/parser/src/utils/__mocks__/supabase.js, src/api/parser/src/utils/storage.js, src/api/parser/src/utils/supabase.js, src/api/parser/test/e2e/parser-flow.test.js, src/api/parser/test/feed-processor.test.js, src/api/parser/test/feed.test.js, src/api/parser/test/post.test.js, src/api/parser/test/storage.test.js
Fixes #3464 
- Any flagging or invaliding feeds functions will use Supabase instead of Redis
- Remove `invalid` and `flagged` feed related functions in `storage.test.js`
- Create `supabase.js` to handle invalidating and flagging
- Change imports in other files
- Create supabase mocks and fix tests
- ` cd src/db`
- `cp env.example .env`
- `pnpx prisma migrate dev`
- `cd ../../tools/migrate`
- `cp env.example .env`
- `pnpm to_supabase` to put all the feeds into supabase for parser to fetch
- Let `parser` run for a minute and go to `http://localhost:8910/project/default`
- Check column `invalid` of `feeds` table, you will some of them are true. Or use table filter to see
- `pnpm migrate`
- Stop `parser` container if running
- Remove all feeds …
=> Update Feed in parser service to talk to Supabase instead of Redis

src/web/docusaurus/docs/api-services/auth.md
#3291 Only the sso part 
Possibly, 
Fixes #2955 
However, for that specific issue I would want to describe SAML-2 part in a separate document, or add SAML-2 information to this doc later. 
Describes the step by step process of auth. It is the first draft and is open to edits.
- `cd src/web/docusaurus`
- `pnpm start`
- localhost:4631
- Click on Docs tab
- Click on API services, then `Authentication and Authorization`
- Read the content. Does it make sense? Can it be better?
No tests for just docs. Prettier was okay with this.
No need for screenshots for just text.
<hr />
Might need to be updated with Supabase information and whatever is in #3030 . If this gets merged, please make sure to add an issue to describe #3030 in documentation somewhere.
=> SSO service documentation

src/api/sso/src/middleware.js
Fix #3560 by adding `onConflict` option to tell Supabase to update existing feeds that has a UNIQUE `id` constraint.
https://supabase.com/docs/reference/javascript/upsert
=> Fix unique feeds id constraint error

src/web/app/src/components/BannerButtons.tsx
A `background-color` showed up when hovering the mouse over the banner buttons. 
Before:
After:
The button border wasn't changing its colour when hovering the mouse over the `Sign up` button.
Before:
After:
=> Improve <BannerButtons> styles

src/web/docusaurus/docs/api-services/parser.md
=> Remove colon

.github/workflows/e2e-tests-ci.yml, pnpm-lock.yaml, src/api/feed-discovery/package.json, src/api/sso/jest.config.e2e.js, src/api/sso/package.json
Wait for `login` container to be ready
.
Fix #3504 
I can reproduce this e2e test failure consistently locally by running the e2e test right after spinning up the containers. So one of the containers must be not ready and make the test fail.
In #3504, following my suggestion, @humphd has tried to debug the `test-web-container` but found nothing suspicious. 
I now realized it's the `login` or `test-saml` container that's not ready for tests.
I couldn't figure out why it takes so long to start up. The repo of the container itself has not been maintained for 4 years https://github.com/kristophjunge/docker-test-saml-idp.
For now, we can wait for the container to be ready before running tests. 
Here's the log of the container.
```
[Fri Apr 29 02:44:36.458976 2022] [ssl:warn] [pid 1] AH01906: …
```
=> Wait on SAML login to be ready

pnpm-lock.yaml, src/api/planet/package.json
Recently build started to fail to see https://github.com/Seneca-CDOT/telescope/runs/6430056538?check_suite_focus=true
Probably it's due that `eslint` is not in the `package.json` for Planet services. 
Fix: 
- Add `eslint` to Planet services.
=> Add eslint to Planet service

src/mobile/app.config.js
Our latest mobile app build doesn't have any `env` so it cannot fetch anything.
Fix:
- Change default environment file to use `.env.development`
=> [React Native] Change default environment file

src/api/search/src/search.js, src/api/search/test/query.test.js, src/web/app/src/components/SearchInput/AuthorInput.tsx
- Fixed 3290 - posts not sorting by date
- Fixed 3517 - limit author autocomplete search query results
- Fixed search results not matching full author names
- Renamed result properties for better readability
Fixes #3290 
Fixes #3517 
Posts are once again sorted by published date from newest to oldest
Author autocomplete search query results are limited to 10 at the back-end and not the front-end.
Before update:
After update:
Originally there was a bug when searching the full name of an author. For example, searching for "Roxanne Lee" would return results with both "Roxanne" `OR` "Lee" as the author, resulting to 91 results. Now it will return results of both "Roxanne" `AND` "Lee" with the correct 12 results.
Before update:
After update:
- `pnpm test` passes all tests
- run and build …
=> Fixed 3 small search service bugs

jest.config.js
Fixes #3643 
As mentioned in the issue, this will allow the `pnpm jest` script to run without crashing. 
A follow-up issue will be written.
- `pnpm jest`
=> Remove front-end from jest projects

src/api/parser/src/utils/supabase.js
Fixes #3660 
I used my old pal `console.log` to see the structure of the feeds that we were pulling from the db.
Turns out there wasn't any `display_name` property with each `feed` object.
```terminal
data structure is: 
[
{
wiki_author_name: 'David Humphrey',
url: 'http://blog.humphd.org/tag/seneca/rss',
telescope_profiles: null
},
{
wiki_author_name: null,
url: 'https://dev.to/feed/rclee',
telescope_profiles: { display_name: 'Roxanne Lee' }
}
]
```
Testing locally is a bit complicated.
1. I changed [src/db/seed/feeds.json](https://github.com/Seneca-CDOT/telescope/blob/master/src/db/seed/feeds.json) to have only 1 feed (for simple testing purposes)
```js
[
{
"url": "http://blog.humphd.org/tag/seneca/rss",
"user_id": null,
"wiki_author_name": "David Humphrey",
"html_url": null,
"type": …
```
=> Get correct display_name for feeds

src/api/parser/src/utils/html/syntax-highlight.js
Fixes #3182 
Fixes #3635 
This PR changes the config for `higjlightjs` to disable displaying the warning for unescaped html.
- Run locally
- Assert that messages about unescaped html are not displayed.
=> Closes #3182, #3635: highlight.js reports unescaped HTML

src/web/app/src/components/BannerButtons.tsx
Fixes #3658 
This PR fixes the uses [webUrl](https://github.com/Seneca-CDOT/telescope/blob/538ed2b2457754462d270c97480109760072d3e8/src/web/app/src/config.ts#L5) as opposed to a hardcoded url for the `About us` link.
- Run locally
- Assert that using different `env` files in [config](https://github.com/Seneca-CDOT/telescope/tree/master/config) to create a local `.env` changes the base `url` used in the `About us` link.
=> Fixes #3658: About Us button in all environments redirect to the Docusaurus site in staging

src/web/docusaurus/docusaurus.config.js
Fixes #3445 
BugFix
Fixed the link to the Telescope documentation, the previous link was going to docusaurus documentation
=> Link to Telescope documentation fix

src/api/parser/src/data/post.js
Fixes #3652 
Added parsing for missing titles from posts that are given to us as an `{ '$': { type: 'text' } }` object
1. Change [feeds.json](https://github.com/Seneca-CDOT/telescope/blob/master/src/db/seed/feeds.json) to have the single feed for easy testing.
```js
[
{
"url": "http://compiledsprawl.blogspot.com/feeds/posts/default/-/open-source",
"user_id": null,
"wiki_author_name": "Matthew Grosvenor",
"html_url": null,
"type": "blog",
"invalid": false,
"flagged": false,
"id": "a394d88c0e"
}
]
```
2. Clear redis cache, do db migrations
3. Blog post will appear on the main page and in search
=> Add parsing for missing title given as [Object]

pnpm-lock.yaml, src/satellite/package.json, src/satellite/test.js
Part one of two for #2913
We need to update and release ElasticSearch and ElasticSearch-Mock in Satellite before we can update it in Telescope.
Using `8.4.0`, as it is the latest stable version on `npm`
***Please note***
Telescope runs fine locally, all the docker containers will build, all the posts will show, and search will function as usual.
`Satellite` tests will pass.
However, `Search` tests will break, which is caused from ES-mock being very confused in our monorepo.
But, `Search` tests will work fine again once Telescope is using the new Satellite, with the new ES and ES-mock.
=> Update Satellite ES to 8.4.0, ES-mock to 2.0.0

docker/docker-compose.yml, pnpm-lock.yaml, src/api/dependency-discovery/package.json, src/api/feed-discovery/package.json, src/api/image/package.json, src/api/parser/package.json, src/api/parser/src/utils/indexer.js, src/api/parser/test/indexer.test.js, src/api/planet/package.json, src/api/posts/package.json, src/api/search/package.json, src/api/search/src/search.js, src/api/sso/package.json, src/api/status/package.json, tools/autodeployment/package.json, tools/migrate/package.json
Fixes #2913
Updates ElasticSearch to 3.4.0 (from Satellite 1.28.0)
Notable changes -
1. [ES 8.0 introduced security settings](https://www.elastic.co/guide/en/elasticsearch/reference/current/security-settings.html#general-security-settings)
2. [The returned value of API calls is the body and not the HTTP related keys](https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/8.0/changelog-client.html#_the_returned_value_of_api_calls_is_the_body_and_not_the_http_related_keys)
Built and works for me locally. Autocomplete also works.
=> Update ElasticSearch 8.4.0

src/web/app/src/components/BannerButtons.tsx
This PR fixes #3614. When signed in locally, hovering over a user's avatar in the banner buttons displays the tooltip outside the user's avatar. 
This PR  replaces the existing `margin` prop in `ButtonTooltip` with the `marginTop` property in the banner buttons tooltip, so it is displayed outside the avatar upon hovering. The value of `marginTop` is consistent with the `padding` value of `NavBar` tooltip. 
- Run Telescope locally  _with_ the changes introduced in this PR
- Hover over the avatar in banner buttons to see the updated positioning of the tooltip
=> Fixes #3614 by adding marginTop prop

src/api/parser/src/utils/indexer.js, src/api/parser/test/feed.test.js, src/api/parser/test/indexer.test.js
The `search()` function in `indexer.js` had been moved to the `Search` service a long time ago, and is no longer used anywhere else in our code.
- Everything builds locally and runs as normal
- `pnpm jest`, `pnpm test`, passes all tests
=> Refactor- remove unused `search()` from `indexer`

docker/docker-compose.yml
`Traefik` [ended support for v2.6](https://doc.traefik.io/traefik/deprecation/releases/) and the end of May of this year. This PR upgrades the version of the image we use to v2.9.1.
- Run telescope locally
- Assert that everything works as expected
=> chore: upgrade traefik image to v2.9.1

src/api/parser/src/data/feed.js, src/api/parser/src/utils/storage.js, src/api/parser/src/utils/supabase.js, src/api/parser/test/feed.test.js, src/api/posts/src/data/feed.js, src/api/posts/src/storage.js, src/web/app/src/components/Posts/Post.tsx, src/web/app/src/components/Posts/PostAvatar.tsx, src/web/app/src/components/Posts/PostInfo.tsx, src/web/app/src/components/SignUp/Forms/GitHubAccount.tsx, src/web/app/src/components/SignUp/Forms/Review.tsx, src/web/app/src/interfaces/index.ts
Fixes #3565
This PR add changes to send the `github` username of a telescope user (if stored) to the frontend and use it to display the user's `github` avatar in posts.  
- Run supabase locally and use the `db:init` script to add feeds to the database.
- Using the supabase dashboard, create rows in the `telescope_profiles` table with valid `github` usernames and link them to users in the `feeds` table by using the same id in `telescope_profiles->id` and `feeds->user_id`. 
- Run the rest of telescope.
- Assert that posts by users with a stored `github` username display the user's `github` avatar, and the user's initials when there's no `github` username stored.
=> Fixes #3565: Post user avatar not using proper GitHub image

package.json, pnpm-lock.yaml, src/api/dependency-discovery/package.json, src/api/feed-discovery/package.json, src/api/image/package.json, src/api/parser/package.json, src/api/planet/package.json, src/api/posts/package.json, src/api/search/package.json, src/api/sso/package.json, src/api/status/package.json, src/db/package.json, src/github-url-parser/package.json, src/satellite/package.json, src/web/app/package.json, src/web/docusaurus/package.json, tools/autodeployment/package.json, tools/eslint/package.json, tools/migrate/package.json
Currently, if we run `pnpm clean` in the root directory, it does not delete the `node_modules` directory in root as expected. 
The two commands for the `clean` script do very much the same thing, which is to delete directories and files
```
// package.json
"scripts": {
...
"clean": "pnpm turbo run clean && pnpm -r exec rm -rf node_modules",
...
}
```
1. `pnpm -r exec rm -rf node_modules` deletes only `node_modules` directories in our pnpm workspaces. There are a total of 18 workspace projects (including root)
2. `pnpm turbo run clean` runs all the `clean` scripts in the following directory:
- `src/web/app` (telescope-frontend)
- `src/web/docusaurus` (telescope-docs)
- `src/api/status` (status-service)
- `src/api/image` (image-service)
That's right. There are only four packages with the …
=> Update `pnpm clean` script to include root directory and missing packages

pnpm-lock.yaml, src/api/status/package.json
Fixes #3720 
So the upgrade of xterm v5 dependencies in #3718 broke our build log page in the dashboard. Downgrading it back to v4 should fix the issue.
=> Downgrade xterm dep as a bandaid fix for status dashboard build

src/mobile/package.json
This PR updates `moment.js` from 2.29.3 to 2.29.4 to fix the vulnerability described [here](https://github.com/Seneca-CDOT/telescope/security/dependabot/13).
=> chore: update moment.js

src/web/docusaurus/docs/getting-started/environment-setup.md
Fix #3692 by including information on properly seeding the database in the `environment-setup` file.
This PR adds information on how to seed `PostgresSQL` locally for testing purposes properly. 
- check the updated `environment-setup` file.
=> Fixes #3692 by adding database info to `environment-setup` file

src/web/app/src/components/SignUp/Forms/Review.tsx
Fixes #3611 
The RSS links on sign-up review page can be rather long and cause text overflow, so this PR turned them into snippets that will display the full text on hover. Overflow text is shorten with ellipses.
**Changes on `src/web/app/src/components/SignUp/Forms/Review.tsx`:**
- add `title={feedUrl}` to the RSS links in Blog RSS and Twitch/Youtube Channel RSS, to show text on hover
- added `RssContainer` and `RssContent` class for CSS
- assign `RssContainer` class to each RSS item, and wrap the actual RSS URL in  `RssContent` class `<span>`, to handle overflow
- fix typo from `Twich` to `Twitch` 
- add max width to `blogRSS` class's CSS to limit text length for overflow handling
Test this by going through the sign-up process to view the review page.
To see more comparable result with …
=> Fixes #3611: Make RSS on Sign-up review page into snippets with hover display

src/web/app/src/components/DependenciesTable/Row.tsx
Fixes #3535 
Updated the CSS for the dependency page table to make dependencies stand out more:
- Increased font size for dependency names
- Changed font family to Spartan
- Also changed the color of the border separating dependencies so it is not as bright in dark mode
No tests were added since this is a small css change.
Current:
Updated:
- Run telescope locally
- Navigate to /dependencies
- Check the updated styles for dependency names and the border for both light theme and dark theme
=> Improve Dependency Page CSS

src/web/app/src/theme/index.ts
Fixes #3747 
Changed the color of the links presented on the blogs from purple, to the original blue used globally on the net. 
Please see below for unvisited colors: 
Dark mode: 
Light Mode:
Note: Visited links remain the same as below:
1. Run `pnpm i`
2. Copy .env for front-end `cp config/env.staging .env`
3. `pnpm dev` to start
4. Change between light and dark mode make sure the links look as per attached images(blue font)
=> Issue 3747: Fixed all links use purple, even if not visited

src/web/app/src/components/SignUp/Forms/RSSFeeds.tsx
Fixes #3687 
During the signup process, after the user enters their blog URL and clicks Validate Blog, it shows a list of possible feed URLs. 
If only one feed URL is returned, it should get selected automatically
- Follow the setup instructions to setup login (if testing locally)
- Navigate to telescope homepage, and click on sign up
- Follow the prompts until you reach the Blog URL form
- Enter a Blog URL for which only one Feed URL exists and click 'Validate Blog'
- Check that Feed URL is automatically selected
- Repeat the above with a Blog URL for which there are multiple feed URLs and click 'Validate Blog'
- Check that no feed URL is automatically checked
=> Auto select feed if only one exists

src/web/app/src/components/SearchHelp.tsx
Fixes #3750 
On the search page, description of how to use search uses different font. Font family was changed to the same font as other elements use.
Before:
After:
1) `npm install`
2) Go to '\telescope\telescope\src\web\app\src\components\SearchHelp.tsx'
3) Scroll down to 'list' item
4) Font is change to be __Spartan__  and font size changed to 1.5rem.
=> change font and font size of list item

src/web/app/src/components/SignUp/Schema/FormSchema.tsx
Fixes #3607 
This PR adjusts the Sign-Up Form validation schema in `FormSchema.tsx` to allow for more than one blog/RSS feed to be selected.
Currently, you can only add one URL to be validated which contradicts the sign-up instructions. However, as I stated in this [comment](https://github.com/Seneca-CDOT/telescope/issues/3607#issuecomment-1315690787), the Channel Selection part of the sign-up form does not have the same issue even though they use the same `<RSSFeeds>` component.
The cause of this issue is due to the Blog URL and Channel URL having different validation schemas in `FormSchema.tsx`.
```typescript
// Third step we collect the user blog and the RSSfeeds from it.
object().shape({
[blogUrl.name]: string().url().required(blogUrl.requiredErrorMsg),//<--Invalid URL error with more …
```
=> Adjusted Sign Up Flow to allow for more than one blog URL to be selected

src/web/app/src/components/SignUp/Forms/Review.tsx
Fixes #3755. 
The issue is about a magic number being used for the max-width of `blogRSS` class `<div>`, as a follow-up to PR##3743. `300px ` was used as part of the PR to solve text overflow without basing the number on surroudning code. This PR is to make sure the number used for max-width is based on a parent element.
Upon further investigation, the size of nearby `<div>` don’t have a fixed width, except the `signUpContainer` class `<div>` (the blue background), which has `510px` as default width. Most use percentages instead.
Therefore, to base the `px` based max-width of `blogRSS` class `<div>` on surrounding elements, I have decided to use `306px`, as a representation for 60% of the `510px` width of the parent element.
The `senecaBlogInfo` class `<div>`  (containing full name, …
=> Fixes #3755 :Base blogRss class's max-width to a parent element

src/web/app/src/components/BannerButtons.tsx
This PR adds `search` and `dependencies` to the hero space (top right corner). This way, it'll match what we have in our `navbar` and users won't have to scroll down to force the `navbar` to show up and have access to `search` and/or `dependencies`.
Logged in user:
Logged out user:
- Checkout the branch used for this PR
- Run `docker-compose --env-file config/env.development up  --build`
- Assert that the 2 new elements added to the banner section match the style and behaviour of the other elements in the same section.
=> Add search and dependencies to banner buttons

.vscode/settings.json
This PR removes the line in our `settings.json` where `pnpm` was set as the project's package manager.
This line was causing the `vscode` extension for `eslint` to fail for some users:
My guess is that it's related to using [nvm](https://github.com/nvm-sh/nvm) instead of a traditional `nodejs` installation. The `vscode` repo has [an issue about this](https://github.com/microsoft/vscode/issues/148903), and it seems that a [solution that seems to work](https://github.com/microsoft/vscode/issues/148903#issuecomment-1153099390) is what's added in this PR.
- Check if this issue affects you by checking the output window (not the terminal) in `vscode`. If you see the error message, this affects you
- Check out the branch used in this PR
- Assert that linter errors are detected in `vscode`.
=> fix: remove package manager from vscode settings

src/api/posts/src/routes/posts.js, src/api/posts/test/posts.test.js, src/web/docusaurus/docs/api-services/posts.md
This is a reopened PR to close [#3615](https://github.com/Seneca-CDOT/telescope/issues/3615)
In this PR, an extra query param expand is added to the URL /posts in posts services.When expand=1, there will be extra data of author, title, and publishDate returned.When expand does not equal 1, or expand does not present in the request, the request will return the data like before.
Load the posts page in the react-native app, and observe if the extra fields of data are returned by `/posts`. This requires the react-native app to add "expand=1" to its request query params of `/posts` as well.
Here's what does the request and data look like.
=> Fixed issue #3615(Reopen)

src/web/app/src/components/BannerButtons.tsx
Fixes [#3758](https://github.com/Seneca-CDOT/telescope/issues/3758)
UI: Fix issue regarding wrong hyperlink for "About Us"
The value provided for the hyperlink of the "About Us" on the navigation bar was pointing to an already publicized version of itself instead of the component it has within the repository, this is shown from the image below
Once the value has been changed, you can see the the hyperlink now points at the actual component of repository, as seen from the image below
1) Start the developer's tool of your local repository
2) Look fo the "React Component" section, and click the "Select Element" Icon
3) Click on the "About Us" section, and view the `href` to see if the value is "/docs/overview/"
=> Fixing 'About Us' wrong hyperlink

src/web/app/src/components/SignUp/Forms/BlogFeeds.tsx, src/web/app/src/components/SignUp/Forms/RSSFeeds.tsx
USAGE: #3646 
This PR addresses one of the issues raised in the issue.
The issue was that some users experience confusion between a blog URL (blog's root HTML) and select the RSS (blog's feed XML) during sign-up. This PR adds 2 sentences to the prompt to clarify the difference, in `src\web\app\src\components\SignUp\Forms\BlogFeeds.tsx`. 
Test this by going through the sign-up process to view the Blog Feeds page.
During testing, you can use test account `user1` with password `user1pass`.
You can enter any Github account name to get through the page before this page.
=> Add clarification to differentiate between the blog URL and the RSS(feed URL) during sign-up

.github/workflows/e2e-tests-ci.yml, package.json
Our e2e tests are failing because the dependencies needed for playwright are not installed, This PR tries to address the issue following what's recommended by microsoft [here](https://github.com/microsoft/playwright-github-action#-you-dont-need-this-github-action).
Unfortunatelly, github actions is ignoring my changes in this PR, so I'm going to merge this and see if the fix works.
=> tests: fix e2e

src/web/app/src/components/SignUp/Forms/RSSFeeds.tsx
Fixes #3610 
The issue raised a point about twitch channel confirmation during sign-up being confusing to users, because the UI doesn't show actual the twitch link(s) for users to confirm. This PR changes what's shown for twitch channel confirmation on that page.
Change:
Add a function `parseFeedUrlByType` to parse the fetched twitch URL(s) to be the correct one(s), in `src/web/app/src/components/SignUp/Forms/RSSFeeds.tsx` .
More code can be added to the function to parse other types of fetched links in the future, if needed.
If I'm missing something, please let me know.
Test this by going through the sign-up process to view the channel page.
During testing, you can use test account `user1` with password `user1pass`.
You can enter any Github account name and blog URL to get through the …
=> Parse twitch feed URL for sign-up confirmation

src/api/feed-discovery/src/middleware.js, src/api/feed-discovery/src/util.js, src/api/feed-discovery/test/router.test.js, src/api/feed-discovery/test/util.test.js
Resolves #3689 
Currently, only a blog URL can be given during signup. Based on this URL, the feed discovery service returns a list of feed URLs.
This has been updated so a feed URL can also be given. The feed discovery service will check if the given URL is a feed URL, and simply return it back.
This URL is checked by performing a get request and comparing the content type header against a list of valid feed URL content types. The list of valid content types is similar to the one used by the `getFeedURLs` method.
- **Currrent:**
- **Updated:**
- Run telescope locally, including the login sso
- Log in using one of the fake user accounts listed [here](https://telescope.cdot.systems/docs/tools-and-technologies/login)
- When prompted, click on sign up
- Follow the prompts until you get asked …
=> Allow feed URL to be given during sign up

src/web/app/src/components/SignUp/Forms/BlogFeeds.tsx, src/web/app/src/components/SignUp/Forms/ChannelFeeds.tsx, src/web/app/src/components/SignUp/Forms/GitHubAccount.tsx, src/web/app/src/components/SignUp/Forms/RSSFeeds.tsx, src/web/app/src/components/SignUp/Forms/Review.tsx, src/web/app/src/components/SignUp/Schema/FormModel.tsx, src/web/app/src/components/SignUp/Schema/FormSchema.tsx, src/web/app/src/interfaces/index.ts, src/web/app/src/pages/signup.tsx
Fixes #3608
The original sign-up process requires users to tick multiple checkboxes to confirm ownership of each account entered. This PR streamlines the process to remove the checkboxes and instead show a line of confirmation text on the review page.
Users can now go to next page without being required to tick the checkboxes.
List of code changes:
- Delete `agreement` field from `RSSFeedsFormProps` and `RSSFeeds`, in `src\web\app\src\components\SignUp\Forms\RSSFeeds.tsx` 
- Delete `agreement` field from `src\web\app\src\components\SignUp\Forms\BlogFeeds.tsx` and `src\web\app\src\components\SignUp\Forms\ChannelFeeds.tsx`
- Delete `githubOwnership`, `blogOwnership`, and `channelOwnership` fields from `SignUpForm` in `src\web\app\src\interfaces\index.ts` 
- Delete `githubOwnership`, …
=> Streamline ownership confirmation during sign-up

src/api/feed-discovery/src/util.js, src/api/feed-discovery/test/router.test.js, src/api/feed-discovery/test/util.test.js
Resolves #3688 
The feed discovery services can return feed URLs that are not relevant. One such example is the wordpress.com's comments feed: `https://blog.wordpress.com/comments/feed`.
We want to filter out the irrelevant URLs for four hosts - `dev.to`, `medium.com`, `wordpress.com`, `blogspot.com`.
This PR adds filters to remove the following:
- wordpress comments feed
- wordpress json oembed feed - Wordpress already returns an `rss+xml` feed url. So, we skip the `json+oembed` feed url
- blogspot.com `service.post` url - There are two other feed urls for `atom+xml` and `rss+xml` which are returned
- Ensure you have login component running locally
- Go through the sign up process until you reach the blog URL form
- Test different blog URLs from different hosts and check if the feed URLs …
=> Filter out irrelevant feed URLs

src/web/docusaurus/docs/tools-and-technologies/login.md
This PR does not have a related issue
Fixed  `docker-compose` command typos in the login documentation in the following places:
It should be `--build` instead of `-build`
- Run telescope locally
- Navigate to the documentation by clicking on the `ABOUT US` button on the home page
- Under `Tools and Technologies`, navigate to `Login`
- Scroll down to the `Running an SSO Identity Provider` section
- Check if the typos have been fixed
=> Fix login document docker-compose command typo

src/api/sso/src/index.js
Fixes #3567
There is a 400 we sometimes get because the cookie that is sent to us with the post binding from Azure AD is sometimes blocked since it is from a different origin/site. Enabling sameSite 'none' should hopefully fix this. By default sameSite is set to 'Lax' which sometimes block incoming cookies from other sites such as the request AD makes to our callback.
This is all outlined nicely in the following document David found https://web.dev/samesite-cookie-recipes/#unsafe-requests-across-sites. 
>This pattern is used for sites that may redirect the user out to a remote service to perform some operation before returning, for example redirecting to a third-party identity provider. Before the user leaves the site, a cookie is set containing a single use token with the expectation …
=> Changing Cookie to be sameSite none

src/satellite/src/app.js
Fixes #3792 
I am trying to find a way to make the new cookie settings work, perhaps this might be a step in the right direction.
=> set trust for first proxy when env is prod

config/nginx.conf.template
This PR adds the required route for the [let's encrypt challenge](https://letsencrypt.org/docs/challenge-types/) so all the certificates for the domains used by `telescope` can be renewed.
N/A
=> fix: add route for let's encrypt challenge

pnpm-lock.yaml, src/api/sso/package.json, src/api/sso/src/authentication.js
Fixes #3790 
This PR removes the deprecated [passport-saml](https://www.npmjs.com/package/passport-saml) in favour of [@node-saml/passport-saml](https://www.npmjs.com/package/@node-saml/passport-saml).
- Run telescope
- Assert that sign up and sign in work as expected
=> Fixes #3790: Deprecation of passport-saml

docker/development.yml, docker/docker-compose.yml, docker/production.yml, src/api/Dockerfile, src/api/dependency-discovery/Dockerfile, src/api/feed-discovery/Dockerfile, src/api/image/Dockerfile, src/api/parser/Dockerfile, src/api/planet/Dockerfile, src/api/posts/Dockerfile, src/api/search/Dockerfile, src/api/sso/Dockerfile, src/api/status/Dockerfile, src/db/Dockerfile, src/web/Dockerfile
This PR add changes to take advantage of the recent changes made to `docker.cdot.systems` [here](https://github.com/DevelopingSpace/docker.cdot.systems/pull/12). 
N/A
=> feat: fetch third party images from docker.cdot.systems

package.json
1. Automatically close the issue when this PR is merged
USAGE: Fixes #3837
Changed node engine to 18 and above instead of 16
=> Bump node engine version from 16 to 18

.github/workflows/docker-files-validation.yml
Closes #2812 
This PR adds validation for our `docker-compose` files.
N/A
=> Closes #2812: Validate docker-compose files in
