.gitignore
Fixes #13: Included common dependencies, testing, production and other files that do not need to be tracked.
=> Initial commit for .gitignore

src/feed-queue.js, src/feed-worker.js, src/index.js
HI everyone~
I Just add error catching in the readFile function for the enqueueFeedJobs function call.
Pls review and let me know what you think.
Thank you.
=> add error catch in readFile function

.eslintrc.js, src/dialogue.js
Fixes for #106 
Corrected lint errors for dialogue.js
=> Fixes #106: ESLint errors in dialogue.js

.dockerignore, Dockerfile, docker-compose.yml
I think this was meant to land in `master`, was originally #65.  I've created a new PR so we can move it to `master`.
=> Adds Docker files

.travis.yml, test/feed-queue.test.js
Fixes #43, CI/CD pipeline for Travis.
Edit: The pipeline is working as expected, we need to fix our tests because they are not exiting clean.
=> - CI/CD Travis (#43)

index.html, planet.css
h1c was converted from custom tag to custom class to ensure HTML5 std
fixes #117
=> bugfix (planet.css): changed custom class

.eslintrc.js
updated the eslint env to include the current environments we are using.
=> Fix #119 - update eslint with environments currently used

src/frontend/index.html
*  Using google translate I was able to add a script that allowed the text on the page to translated to any language.
* code could be found on https://gtranslate.io/
* Scroll down on the page and you will find prices
* click download on the one that is free
*  A popup box will appear, click on the tab Html and it will display the sample code.
=> Update Index for Issue 81

src/text-parser.js, test/text-parser.test.js
=> Fix #75: Added Fragmentation to HTML to text Parser

test/github.test.js
GitHub tests are failing so this disables them until #208, #225 are dressed.
=> Skip tests until mocked response is implemented

package-lock.json, package.json, src/word-counter.js, test/word-counter.test.js
Fixes #17: This function utilizes [wordcount](https://www.npmjs.com/package/wordcount) as suggested by @humphd in https://github.com/Seneca-CDOT/telescope/issues/17#issuecomment-549649707
=> Fixes #17: Implemented basic word counter & test

test/feed-parser.test.js
=> Adding additional tests to the feed parser test

docs/CONTRIBUTING.md
=> Update CONTRIBUTING.md to specify starting Redis

docs/CONTRIBUTING.md, docs/logging.md, src/count-blog-domain.js, src/lib/logger.js
fixes #275 Moved source file and updated ```require()``` and documentation.
=> move utils/logger.js to src/lib/logger.js, update code and docs

docs/CONTRIBUTING.md
I've seen people get a bunch of this wrong, and wanted to try and help them get the workflows right by adding better docs.
This updates our CONTRIBUTING docs to include:
- workflow for git and github
- more clarity on how to run tests, fix things with eslint
- dealing with updates in `package.json` and `package-lock.json`
See if you think I've covered everything.  If there are other things I didn't mention that you think are important, let me know.
=> Update CONTRIBUTING with more workflow info

package-lock.json, package.json, src/sanitize-html.js, test/sanitize-html.test.js
=> Fixes Issue 18: Sanitize HTML from feed posts (XSS, script, etc removal)

test/github.test.js
Progress towards #268 
Added 3 more tests to cover cases in which the URL passed to the github fetching tool are not valid.
=> Added test for invalid GitHub URLs

package.json, test/feed-parser.test.js
Getting this issue when running npm test, might be because I didn't configure my .env file yet. Otherwise big thank you to @manekenpix for his help on the issue.
```
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! telescope@0.0.1 jest: `cross-env MOCK_REDIS=1 jest`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the telescope@0.0.1 jest script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/calvinho/.npm/_logs/2019-11-21T00_49_59_000Z-debug.log
npm ERR! Test failed.  See above for more details.
```
=> Fixes #210, added nock package to mock network requests

test/feed-parser.test.js
Hi, it was brought to my attention there were two skips not removed during my PR for #210. Here is a PR with the two skips removed
=> Fixes #303, removed skip from tests

src/frontend/dialogue.js, src/frontend/index.html
Taking over from a failed git merge in #301.
=> Fix #221: dialogue.js updates

test/basic_analysis.test.js
Fixes issue #310. 
Before:
After:
=> Fix issue #310 - Remove unnecessary console message

src/backend/web/routes/index.js
Fixes #271 added express static middleware in src/backend/web/routes/index.js
=> Fixes #271 added express static middleware

src/frontend/index.html, src/login/login.html
Added connectivity with the main page and login, this allows the login project to be better integrated with the main project.
=> Connected index.html and login.html

src/login/usingPassport.js
1. Removed the log holding the access and refresh tokens
2. Added comment on what the callback function returns as a JSON object
For: #355
=> Fixes #355: Removed log with tokens

src/backend/index.js, src/backend/login/usingPassport.js, src/backend/utils/email-sender.js, src/backend/utils/inactive-blog-filter.js, test/basic_analysis.test.js
Fixes #204 , Updated backend to use logger
=> Fixes #204: Update backend to use logger

src/storage.js, test/storage.test.js
Added addPost() function using guid as unique key for each post and store posts as sorted set by published date.
Added getPost() by guid and getPosts() by range of dates.
Added test for testing above mentioned functions.
=> Fix issue 260 implement addPost and getPost

.prettierrc, .stylelintrc.js, package.json
This PR is trying to solve #326.
=> Fix issue #326: Integrate Stylint with Preittier

package.json, src/backend/web/routes/index.js, src/backend/web/routes/opml.js
Added a js file that has an opml generator to generate as an opml file to fix issue #64 
I had to export the objArray array is wiki-parser.js to access the rss urls and the processedPosts array to access the posts url and posts title. 
I am not sure if this is correctly so please correct me if i did this incorrectly.
=> fixed #64 added OPML generator

test/logger.test.js
I have added tests to make sure that logger functions exist. This pull request is a result of failure of logger.debug in Fix #306
=> Fix #309: Added tests for logger methods

src/backend/utils/extract-urls.js, test/extract-urls.test.js
Wrote a test case for extract-urls.
I plan to add more test cases for this in the future but I wanted to get this started now.
starts fixing : https://github.com/Seneca-CDOT/telescope/issues/167
=> Added test cases for extract-urls

package.json
This is working on fixing #417 
After updating hint to 6.0.0 and @hint/configuration-all to 2.0.0 there are tests failing.
=> Updated npm hint

src/backend/feed/worker.js, src/backend/post.js
I reworked #403 in class, rebasing on some other work we landed.  This is the cumulation of that work.  It probably can't land yet, since it uses too many instances of Chrome.  But we can use this as a start.
#388 is needed for this.  Fixes #259.
=> Fixes #259. Added Post class to store data for each post

src/backend/utils/spam-checker.js
After the text-parser.js was updated from having a run method to an async function, the spam-checker.js was still calling the run method and was not updated to call the function instead of the method. So for this pr, I have changed line 28 
From: 
```const noTagsDesc = await textParser.run(content.description);``` 
To:
```const noTagsDesc = await textParser(content.description);```
to call the function.
Fixes #419
=> Fixes #419 : Rewrote how to expose textParser in spam-checker.js

docs/CONTRIBUTING.md, src/backend/web/routes/index.js, src/backend/web/routes/server-sent-events.js
Fixes #314. 
The issue was broken down into 2 PRs. The client side can be found in PR #410  . 
The goal of this pr is to create a route that sends updates to the browser when there is a job completion.
=> Fixes #314: Server-side changes for server sent events

src/backend/index.js, src/backend/lib/shutdown.js
I added a few more cases to the shutdown logic, and refactored to make the code a bit cleaner, and better handle the exit code in the case of errors.
=> Refactor and cleanup shutdown logic, add more signals/events

.gitignore, .prettierignore, docs/CONTRIBUTING.md
We needed to run prettier over the project, since it looks like the `CONTRIBUTING.md` file got missed.  I did that, and also found some issues with our ignore patterns in the process.
@drwm-base can you take a look at what I did in `CONTRIBUTING.md`?  I might have gotten it wrong.
Also, we should add a step to our CI to test that prettier was run using the `--check` option.
=> Fix #464: fix formatting in CONTRIBUTING.md

src/backend/utils/email-sender.js, test/email-sender.test.js
Helps fix issue #313 
I restructured some of the code in email sender so the logic is broken up into more reusable chunks and easier to test.
=> Restructured emailsender and added tests

.github/PULL_REQUEST_TEMPLATE.md
**Issue**: #347 This issue is being worked on by myself and @UltimaBGD([PR#442](https://github.com/Seneca-CDOT/telescope/pull/442)) so whosever PR is merged last should be able to automatically close the issue.
**Type of issue**: Documentation/Template
A few PR's are being posted without enough details describing what is being done and why it is needed. This makes it difficult and more time consuming for reviewers to figure out specifically what is being done. 
With this PR it will make specific information mandatory for every PR and include some detailed notes for what a good PR should look like.
=> Issue 347 - pull request template

docs/Local_Login.md
=> Added SAML2 documentation for loging in locally

test/sanitize-html.test.js
Added more test cases for sanitize-html.
=> Fix#468 add test cases for sanitize-html

.github/PULL_REQUEST_TEMPLATE.md
Fixes #485 
Bug fix
As mentioned in #485 , the headings in the PR templates are not the same size and need to be changed so they are consistent. I've also added options for the Type of Change
=> Fixes #485 make headings the same size and update type description

tools/html-elements.js
This updates `html-elements.js` to use the changes that just landed on `master` for the `Post.byGuid()` method.  I've also added data on %s in addition to raw numbers:
```
$ html-elements
Processing 5386 posts...
Processing 191,922 elements...
1. <br> (67,859, 35.358%)
2. <p> (35,459, 18.476%)
3. <a> (19,236, 10.023%)
4. <div> (14,994, 7.813%)
5. <li> (8,574, 4.467%)
6. <td> (7,019, 3.657%)
7. <strong> (6,439, 3.355%)
8. <img> (6,168, 3.214%)
9. <pre> (3,942, 2.054%)
10. <code> (3,677, 1.916%)
11. <b> (3,135, 1.633%)
12. <em> (2,642, 1.377%)
13. <ul> (2,275, 1.185%)
14. <tr> (1,760, 0.917%)
15. <h3> (1,701, 0.886%)
16. <figure> (1,414, 0.737%)
17. <i> (1,337, 0.697%)
18. <h4> (1,087, 0.566%)
19. <blockquote> (982, 0.512%)
20. <ol> (529, 0.276%)
21. <hr> (444, 0.231%)
22. <table> (359, …
```
=> Update html-elements.js to use Post, add %

.gitattributes
Fix issue #515 
in `.gitattributes` file, mark `.png` files as binary so git does not try to convert line endings for them.
=> Fix #515: unable to discard working directory changes

package.json, src/backend/web/app.js
Closes #508 
Added [CORS](https://expressjs.com/en/resources/middleware/cors.html) to app.js so it'll work with all our endpoints.
=> Closes #508: Add CORS to REST API routes to support third-party access

src/backend/web/routes/login.js
#534 Issue This PR Addresses
1. Automatically close the issue when this PR is merged
USAGE: Fixes #534
The login was done hurriedly last time. and wasn't properly tested, it now works again!
There is no need for tests currently, as it would need to test. 
No screenshots needed/
Not applicable.
=> fix #534 proper login routes.

.circleci/config.yml, package.json, src/backend/feed/worker.js, src/backend/post.js, src/backend/utils/text-parser.js, test/feed-worker.test.js, test/text-parser.test.js
Fixes #439, #388, #488
This removes Puppeteer from our text parsing code.  We experimented with it, and it's very cool.  But the extra complexity it adds isn't worth the maintenance costs for our use case: plain text extraction is a nice-to-have feature, but not critical.
I've gone back to using JSDOM's text fragment parsing with `.textContent`.  It works well enough for our current needs.
In doing this work, I ran into a recurring problem with the feed worker tests.  A bunch of them will magically fail when you touch something related to the parser.  After spending a few hours on this, I've concluded that the tests aren't behaving properly, and aren't worth having.  I've ripped them out.  Here is what fails when I made my changes:
```
(node:27884) UnhandledPromiseRejectionWarning: …
```
=> Remove Puppeteer, return to JSDOM, fix failing tests.

docs/CONTRIBUTING.md
Fixes #39
This adds some notes about editor config, and where to find a plugin, if necessary.  I've also fixed a spelling mistake nearby.
=> Add notes on editor config, and fix a spelling mistake.

docs/project-board.md
Fixes #251 
The documentation written here is based on the columns in our 0.5 Release Project Board and all the labels we currently have. This PR is an attempt to convert #251 into something our team can use. The workflow described in the issue requires developers to manually move issues and pull requests around on the board but I believe we moved away from manually managing our issues and pull requests and have automated it in the 0.5 Release Project Board so I just documented what each column and label meant.
=> Fixes #251 added project board instructions

README.md
Fixes #554
This updates our README to be more clear about what Telescope is.  I've also removed a bunch of duplicate or outdated information from the README.
When we get our deployment docs updated, we should add a section in the README to link to those too.
=> Fix #554: update README with a better intro on what the project is

src/backend/data/post.js, src/backend/feed/processor.js, src/backend/feed/queue.js, src/backend/feed/worker.js, src/backend/lib/queue.js, src/backend/lib/redis.js, src/backend/lib/shutdown.js, src/backend/utils/email-sender.js, test/inactive-blog-filter.test.js
Fixes #549
This PR standardizes our naming in logs for **errors**. I renamed any **err** within the repository to **error**. I believe this is needed for the project because it helps everyone with finding errors, and it helps keep a standard style in the project. I decided that error would be a better name instead of err because it could help newer contributors understand the code better.
=> Standardized naming in logs for errors.

src/backend/web/routes/opml.js
Fixes #379 
Imports and implements feed-fetching functionality into the OPML module, such that accessing the `/opml` API endpoint now provides real feed data (instead of placeholder information).
To test locally, GET `localhost:3000/opml`
=> Fixes #379: add feed data to opml endpoint

.eslintrc.js
Fixes #593 
I added settings to the eslintrc file that specify the React version, to prevent the warning about React version not being specified
=> Fix #593 - Added react version to eslintrc file

env.example, src/backend/lib/redis.js
- [x ] **Bugfix**: Change which fixes an issue
Fixes the elusive 6739 to 6379, and stops duplication for port.
=> Fix 74 - Fixing ENV error

package.json
#627 
Fixes bug that causing failure to update npm in the src/frontend
=> Fixes #627: Updated postinstall

now.json, package.json
This adds the configuration files for Zeit Now, after this gets merged, whenever commits are pushed into a branch, automatic deployment will trigger.
=> Fixes #517 Automatic PR deployment for frontend using Zeit Now

src/backend/index.js
#673 
Commented out the on('fail') event for now.
=> Fixes #673 Telescope crashes at job failure

.npmrc, Dockerfile, src/backend/web/routes/index.js, src/frontend/gatsby-config.js, src/frontend/package.json, test/server.test.js
Initial work to fix #569 and #658 
This pr connects the / path in the server to the public folder in gatsby, this allows us to see what is on the front end. This will also attempt to make docker automatically build gatsby so we don't manually have to do it.
=> Point / to the gatsby public folder

docs/domains.md
Fixes #530 
This PR adds the staging and production domains, and original Planet URL to our docs. Feel free to let me know what other domains or URLs we should add. Maybe this can be morphed to add endpoints as well.
=> Fixes #530: Adding list of domains to docs

src/backend/index.js
Reverts Seneca-CDOT/telescope#676
=> Revert "Fixes #673 Telescope crashes at job failure"

src/backend/web/routes/planet.js
Fixes #660 
I put the the /planet/compare route out of its misery as our current planet has been decommissioned by Seneca
=> Fixes #660, removed /planet/compare route

env.example, src/backend/data/feed.js, src/backend/feed/processor.js, src/backend/utils/storage.js, test/feed.test.js
Fixes #624 
Implements and tests functionality that temporarily delays further processing of feeds after a failed processing attempt that resulted in an HTTP 429 (Too Many Requests) response.
The current implementation delays feed processing by ~15 seconds~ [an hour](https://github.com/Seneca-CDOT/telescope/pull/726#discussion_r379869189) in such a case.
_Thank you very much, @humphd, for your assistance in tackling this issue!_
=> Fixes #624: delay feed processing in response to rate limitation

src/frontend/src/components/Layout/Layout.css, src/frontend/src/components/Layout/Layout.js
This fixes #737
Removed the logo from under the hero banner, fixed the margin to improve user experience. The transition between the banner and main blog area is more smooth
=> Removed Logo

src/frontend/src/components/Layout/Layout.js, src/frontend/src/components/SearchBar/SearchBar.jsx, src/frontend/src/components/SearchBar/index.js
Fixes #721 
This is just the bare search bar component, no functionality yet. It's currently just floating around on the layout page until #739 gets approved or we find a better place for this somewhere else...
Worse is better...
=> Fixes #721 Search Bar Component

src/frontend/src/pages/search.js
This fixes #720 
Added a new empty page for search. This will allow other contributors to add their search components.
=> Added Search page

src/frontend/src/components/Post/Post.jsx, src/frontend/src/components/Post/telescope-post-content.css, src/frontend/src/components/TextArea/TextArea.css
Fixes #700 , fixes #710 
Improving readability. 
Constrain large images.
Updating the look of `pre` and `code` tags
=> Fix #700: Initial work on css and adjusting picture size

src/frontend/src/components/Layout/Layout.js, src/frontend/src/components/ScrollToTop/ScrollToTop.jsx, src/frontend/src/components/ScrollToTop/index.js
Fixes #731 
Allows you to scroll back to the top of the first post, underneath the hero banner.
=> Fixes #731 added scroll to top button

src/frontend/src/components/Post/telescope-post-content.css
Follow-up to PR #749
This is just a quick follow-up to PR #749, addressing some review comments made within:
- Constraints on images have been refactored, increasing their maximum width and preventing distortion
- WordPress emojis/smileys now display as expected (e.g. inline, text-sized, etc.)
=> Enhance PR #749: adjust image constraints, emoji sizes

src/frontend/src/components/AuthorResult/AuthorResult.jsx, src/frontend/src/components/AuthorResult/index.js
Fixes #722
WiP, but would like some feed back. Will fine tune other things so the avatar image will actually stay within the box. The expansion panel I don't know if I want to place it in the second column at the very bottom or to create a third column within the grid and just somehow move it to the very bottom.
=> Create author result component

src/frontend/src/components/Layout/Layout.js, src/frontend/src/components/SearchBar/SearchBar.jsx, src/frontend/src/pages/search.js
Fixes #751 
Moved the Search bar component from layout to /search and updated the css to look more like the design
=> Fixes #751 moved Search bar to /search and updated css

src/frontend/src/components/Banner/Banner.css, src/frontend/src/components/Banner/Banner.jsx
Closing #711
Added the version number to the bottom left of the hero banner. Based on the current state of the UI, I think it is the best spot for it.
=> Added version number

src/frontend/src/components/Login/LoggedOut.jsx, src/frontend/src/components/Login/Login.css
fixes #756 
Added css to the login component so that the login button better fits with the other elements in the header
=> Styled login button

src/frontend/src/pages/search.js
This pr is so the search is accessible, since it is currently being hidden. This is not a perfect solution for #765, but a way to at least be able to use the bar until a better solution is found.
This PR adds space between the header and the search bar.
=> Temp fix to prevent search bar being hidden

src/frontend/src/pages/myfeeds.js
Fixes #784 
Changed to use the custom hook
=> Use sitemetadata hook for telescope url

docs/environment-setup.md
=> Update Docs to reflect conflict when running different redis methods at once

src/frontend/src/components/Post/syntax-highlight.js
This PR addresses https://github.com/Seneca-CDOT/telescope/issues/798
Added 2 modules to the syntax highlighter
=> Added PHP and DOS modules to syntax highlighter

src/frontend/src/components/Banner/Banner.css, src/frontend/src/components/Banner/Banner.jsx
Fixes #778 
- Changed Hero Banner component to functional component
- Changed the svg button to a Material UI button
- ~~Made h1 to be responsive to xs, sm, md, lg screens. The word Telescope will adjust its font size based on the screen size. It will no longer overflow out of screen.~~
- Made h1 responsive using `vw`
- Scroll down button scrolls to the top of the first blog post
=> Fixes #778 Hero Banner update

Dockerfile
Fixes #825 
On my system with changes, the build time for a local docker instance after doing the first successful build (and thus caching dependencies) and modifying a line in the backend code as a test comes out to:
```
real	0m6.243s
user	0m0.375s
sys     0m0.064s
```
**Limitations  for  Docker caching**: any change to package.json and it's related dependencies will force a new container build. Source code changes otherwise should not trigger rebuild of cached containers.
=>  fixes: ensures docker cache dependencies when package.js is not modified #826 

src/backend/web/routes/index.js, src/backend/web/routes/query.js
Fixes #538 
I've used a bit of github's rules when searching, I'm still not sure how elastic search functions at the moment. @manekenpix mentioned its full text search, but I'm not sure if that includes operators as well such as `&&`, `||`, and `!`
TO TEST: use localhost:3000/query?search=SEARCHTERM feel free to use spaces in SEARCHTERM as express will handle the encoding/decoding of the spaces
For example `localhost:3000/query?search=open source` will automatically become `localhost:3000/query?search=open%20source`
Any SEARCHTERM longer than 256 chars will get an error.
=> Fixes #538 Expose search endpoint via web api

docs/graphql.md
=> Fixed double dash typo.

src/frontend/src/components/Post/telescope-post-content.css
Fixes #814 
- **Bugfix**: Change which fixes an issue
=> Fix #814: link overflow in mobile view

src/frontend/src/components/Header/Header.jsx, src/frontend/src/pages/about.js
Work for #804 
Added an about page and a button on the header to reach it. This is where all the about information will go. Since there is no design at the moment, at least some stuff can start to be added without cluttering the home page
=> Added about page

src/frontend/src/components/Header/Header.jsx
fixes #853 
Drawer now works, I added a link to search as a placeholder. It serves to showcase the functionality. Once #852 goes through, the about link could go in this drawer.
=> Clicking on the menu icon toggles the drawer

env.example, env.staging
Fixes #862 
This PR increases the number of posts shown on Telescope from 30 to 50.
=> Fixes #862: Increase number of blog posts on staging

src/frontend/src/components/Layout/Layout.js, src/frontend/src/components/SEO.js, src/frontend/src/pages/index.js, src/frontend/src/pages/search.js
fixes #827 
Added a component that uses Helmet for the title, and could be used in the future for more metadata information
=> Telescope has a <title>

.dockerignore, Dockerfile, tools/autodeployment/deploy_stage.sh
Fixes #885 
Copies .git to the final build, does some compression logic in attempt to reduce size.
=> adds: .git to final build for health check

src/frontend/src/components/Banner/Banner.css, src/frontend/src/components/Banner/Banner.jsx
Fixes #802 
This adds background image source generation from Unsplash Collections API. Currently leveraging 
the following collection: https://unsplash.com/collections/894/earth-%26-planets. Pulls images based on viewport width / height, in attempt to ensure image isn't scale oddly between devices. This also generates a unique experience for each device that you access Telescope on.
I plan on adding credit to the collection author before having this PR merged, along with optimization where possible.
=> adds: Dynamic Banner Images from Unsplash Collections API

docker-compose-staging.yml, nginx.conf, src/backend/web/routes/index.js
Closes #634 
This adds using nginx to serve Telescope's static content and caching Telescope's endpoints to reduce load on it.
=> Closes #634: nginx configuration for staging and production

env.staging
I have the wrong email address for Josue in the admin config on staging.  This fixes it.
=> Correct email address for Josue in ADMINISTRATORS on staging

src/frontend/src/components/SearchPage/SearchPage.jsx, src/frontend/src/pages/PageBase.js, src/frontend/src/pages/about.js, src/frontend/src/pages/index.js, src/frontend/src/pages/myfeeds.js, src/frontend/src/pages/search.js
Fixes #868
Removes references to our [`<Header>`](../tree/master/src/frontend/src/components/Header/Header.jsx) and [`<SEO>`](../tree/master/src/frontend/src/components/SEO.js) components from Gatsby Pages previously containing them, replacing them with a singular reference to those components within our `<PageBase>` wrapper component.
=> Fixes #868: factor Header, SEO into PageBase

src/backend/web/app.js
Co-authored: Calvin <calvinho125@gmail.com>
Fixes #934 
This PR exposes `X-Total-Count` using cors options. It's required for #931
=> Fixes #934: Allow custom headers to pass through CORS

package.json, src/backend/web/routes/posts.js
Replaced accepts module with req.accepts() so we don't need to directly maintain unnecessary dependency.
=> Issue-616: Replaced accepts module with req.accepts()

src/frontend/src/components/Header/Header.jsx
Fixes 913
Text Telescope is clickable and will bring user to home from any page
=> Fix 913: Make word Telescope clickable

src/frontend/src/components/Post/telescope-post-content.css
=> added font-family to telescope-post-content

src/frontend/src/components/Post/Post.jsx, src/frontend/src/components/Posts/Posts.jsx
Fixes #927 
Authors are now linked to their respective `feed.link` property
=> Expose feed link in frontend for a post

src/frontend/src/components/Header/DesktopHeader.jsx, src/frontend/src/components/Header/Header.jsx, src/frontend/src/components/Header/MobileHeader.jsx, src/frontend/src/components/Login/LoggedIn.jsx, src/frontend/src/components/Login/LoggedOut.jsx
fixes #860 
Mobile and Desktop now have different headers to best use their space
Desktop Header:
Mobile Header:
=> Mobile can access hamburger menu

src/frontend/src/components/Post/telescope-post-content.css
Fixes 929.
Telescope blockquote does not have any styling. This is a potential idea how it can be styled
=> Fix 929: Initial work on styling blockquotes

test/feeds.test.js, test/user.test.js
Fixes #955
Adds a _**skipped**_ test for each of the six scenarios outlined in #955 (concerning testing the `GET /user/feeds` and `DELETE /feeds/:id` API routes currently being developed by @Grommers00 and @manekenpix in https://github.com/Seneca-CDOT/telescope/issues/954).
All of these tests were appended to the existing [`feeds.test.js`](https://github.com/Seneca-CDOT/telescope/blob/master/test/feeds.test.js) file.
Once https://github.com/Seneca-CDOT/telescope/issues/954 lands, these tests should be unskipped.
=> Fixes #955: add tests for GET /user/feeds, DELETE /feeds/:id

src/backend/data/feed.js, src/backend/data/user.js, src/backend/web/authentication.js
Co-authored-by: David Humphrey <david.humphrey@senecacollege.ca>
Co-authored-by: Josue <josue.quilon-barrios@senecacollege.ca>
Automatically close the issue when this PR is merged
USAGE: Fixes #717  
This will add the user class for ease of access later on when we get myFeeds working. This is just a draft PR and not ready to be added yet.
=> fix #717 Adding user class

src/backend/web/__mocks__/authentication.js, src/backend/web/routes/feeds.js, src/backend/web/routes/user.js, test/feeds.test.js, test/user.test.js
Co-authored-by: Josue <josue.quilon-barrios@senecacollege.ca>
1. Automatically close the issue when this PR is merged
USAGE: Fixes #954
These are the routes that we have added for adding (update it), deleting and getting all feeds that belong to a user.
=>  Fix #954 REST API

Dockerfile, docs/environment-setup.md
Fixes #961 
Details can be found in #948
=>  adds: Docker for WSL 2 / Windows 10 Pro and Front-end Caching Optimization (V2)

src/frontend/src/components/Posts/Posts.jsx, src/frontend/src/pages/index.js
Fixes #972 
Re-adding title to home page. Moving code in #931 from index.js to Posts.jsx
=> Fixes #972 add title to Home page and move posts.length check into <Posts>

src/frontend/src/components/SearchBar/SearchBar.jsx, src/frontend/src/components/SearchPage/SearchPage.jsx, src/frontend/src/components/Spinner/Spinner.jsx, src/frontend/src/components/Spinner/index.js
Fixes #911 
Finishing up missing search functionalities:
- adding a spinner while waiting for results to load (Done)
- adding a way to search posts (Done)
- dropdown working properly and search responds to selected option (Done)
To test head on over to `{telescopeUrl}/search` and type your query in. Both options in the dropdown should work, when searching by authors, you'll get a spinner. I'm not sure if we'll need one for Posts
=> Finish Search Feature

src/backend/web/app.js, src/frontend/package.json, src/frontend/src/pages/index.js
Co-authored-by: James <james.inkster@live.ca>
Fixes #985 
Adds the load-more button at the end of the blog posts container, along with the loading feedback in the form of a spinner.
=> adds: load-more button concept

docker-compose-production.yml, env.production, nginx.production.conf, tools/autodeployment/deploy_stage.sh
Co-authored-by: James Inkster <James.inkster@live.ca>
Closes #907 
This adds settings for the production box. I'll keep this PR as `draft` until we can add Seneca SSO information for production.
- This will be done in #957 
- This will be added to this PR once we get the information needed from Seneca.
=> Closes #907: Setup production box for https://telescope.cdot.systems

env.production
This adds Seneca SSO information to our `env.production`.
=> Add Seneca SSO to env.production

src/frontend/src/components/MyFeedsPage/DeleteFeedDialogButton.jsx, src/frontend/src/components/MyFeedsPage/ExistingFeedList.jsx, src/frontend/src/pages/myfeeds.js
Fix #977
Fix #979
- As per #977, adding a feed to the My Feeds list was being slowed down by frequent re-rendering of the large ExistingFeedList component. This PR resolves this issue by [memoizing the ExistingFeedList component](https://github.com/Seneca-CDOT/telescope/compare/master...Silvyre:issue-977?expand=1#diff-2117800b114a1b4cfaa8fb1e262360eaR89).
- Minor fixes include:
- Moving some logic from the MyFeeds component into the child ExistingFeedList component
- Delaying form field validation until submission
- Replacing TextValidator elements within ExistingFeedList with simpler TextFields elements
- Clearing the blog feed URL form field upon submitting a new feed
- Various other changes mentioned in https://github.com/Seneca-CDOT/telescope/issues/979#issuecomment-613280576
- When a …
=> Fix #977, #979: improve performance of My Feeds page

src/frontend/plugins/gatsby-plugin-top-layout/TopLayout.js, src/frontend/src/components/Banner/Banner.jsx, src/frontend/src/components/Posts/Posts.jsx, src/frontend/src/components/ScrollToTop/ScrollToTop.jsx, src/frontend/src/components/SnackBar/SnackBar.jsx
Fixes #1002
- Resolves the two errors described in #1002 using the solutions discussed therein.
- Resolves an ESlint warning within `Banner.jsx`
- Replaced all instances of `<React.Fragment>` with its shorthand (`<></>`) across Telescope for consistency.
=> Fixes #1002: fixes JSX-related issues in Banner.jsx, Posts.jsx

src/frontend/src/components/SnackBar/SnackBar.jsx, src/frontend/src/pages/index.js, src/frontend/src/pages/myfeeds.js
Fixes #978 #980 
It will now render a SnackBar component with the passed property `message`.
Also updated myfeeds so that removing a feed will now cause it to re-render with the updated feeds.
To test:
1. login as user2/user2pass
2. go to telescopeUrl/myfeeds
3. add feeds, both success and error should appear
4. removing/deleting a feed should cause the alert to appear as well
=> Remove "feed added successfully" after some period + add alert for "removing feed"

src/frontend/src/pages/index.js
Progress towards #990
Fixed eslint react-dependency issues for /src/pages/index.js
=> Fixed eslint warnings in index.js

src/frontend/src/components/Post/Post.jsx
=> Fix 1010: extends lazy loading to iframe

src/backend/web/authentication.js, src/backend/web/routes/auth.js
ITS wants to do more testing of the SAML logout stuff, so I've restored what I did to finish 1.0.0.  We can land this on staging and do more testing while we figure it out.
=> Restore SAML SLO so we can debug on staging

src/frontend/src/components/Header/DesktopHeader.jsx, src/frontend/src/components/Header/MobileHeader.jsx
Fixes #984 
Make the word Telescope redirect to home on both desktop and mobile
=> Fixes 984 make word Telescope clickable

nginx-production.conf, nginx-staging.conf
This fixes #1044.  See my comments there for the help I need reviewing this.  Then we could try it on staging and see how it goes, compare to prod.
=> Enable HTTP2 in nginx

src/frontend/src/components/Banner/Banner.jsx, src/frontend/src/components/Header/DesktopHeader.jsx, src/frontend/src/components/Header/Header.jsx, src/frontend/src/components/Header/MobileHeader.jsx, src/frontend/src/components/HideOnScroll/HideOnScroll.jsx, src/frontend/src/components/HideOnScroll/index.js, src/frontend/src/components/Post/Post.jsx, src/frontend/src/components/ScrollToTop/ScrollToTop.jsx
Fixes #930 
Fixes the vertical spacing for post heading (I might have reduced it too much, please nit this in reviews)
@humphd has been asking for this but I didn't see an issue filed so here it is!. Post header now sticks to the top so we can see whose post it is. Very convenient for the long posts we've been getting recently.
For Desktop
For Mobile
Bugs introduced: 
- the scroll-to-top button now hides underneath the post headers for some reason, I've tried to set the header's zIndex to 200 so that it's lower than the button's zIndex of 300 but it didn't do anything.
- navbar also hides on scroll in other pages like the About page, not sure if we want that
Scope creep:
- changed gutter for ScrollToTop anchor from 64px to 1px
=> Fixes #930 Post header sticks to the top

tools/autodeployment/deploy.sh, tools/autodeployment/env.example, tools/autodeployment/server.js
This adds the unsplash client ID to the `.env` used by the autodeployment server.
=> Add unsplash client id to autodeployment process

src/frontend/src/components/Header/DesktopHeader.jsx, src/frontend/src/components/Header/MobileHeader.jsx
fixes #1062 
Added an aria-label to the search icons so they are more accessible
=> added aria-label to search icon

package.json
This updates `apollo-server-express` to version 2.14.2.
=> chore: update apollo-server-express to v2.14.2

src/frontend/src/components/Header/MobileHeader.jsx
The home button in the drawer (mobile version) is supposed to tak you to "/" when clicking on it, but currently it doesn't work.
This PR fixes that.
=> Fix home button in drawer for mobile version

src/frontend/package.json, src/frontend/src/components/AboutFooter/AboutFooter.jsx, src/frontend/src/templates/template.js
#969 
#970 
#967 
- Updated UI to the footer in the About page
- Replaced hardcoded year in the footer
- Added [MUI Stepper](https://material-ui.com/components/steppers/#text-with-carousel-effect) and convert one-panel design to two-panel design
- Resized carousel
Concept design from #896 
Desktop
Mobile
=> Fixes 969 970 967 About Page UI update (it looks nice now, please review)

Dockerfile, docker-compose-production.yml, docker-compose-staging.yml, env.production, env.staging, tools/logrotate/Dockerfile, tools/logrotate/crond.sh, tools/logrotate/logrotate.conf
Closes #683 
This adds a new container to the production/staging workflow to deal with large log files. The new container uses a tiny alpine image to run [logrotate](https://linux.die.net/man/8/logrotate) and deals with the log files generated by Telescope.
=> Closes #683: Deal with large logs on staging and production

src/frontend/src/components/Login/Login.jsx
Fixes #1009
Changed from Status Code 401, to Status Code 403 within Login.jsx
=> Fixes #1009 Switch to 403 from 401 for login failed check

docs/staging-production-deployment.md
Closes #680 
Documentation for staging and production deployment.
=> Closes #680: Add documentation for staging + production deployment

tools/autodeployment/env.example, tools/autodeployment/server.js
Closes #998 
This enables `HTTPS` on Telescope's autodeployment server. The changes in this PR were initially (and manually) added to both `dev` and `prod` right before `1.0.0` for testing, and can now be added to Telescope's repo.
=> Closes #998: Secure our autodeployment server

src/frontend/src/components/Post/telescope-post-content.css
fixes https://github.com/Seneca-CDOT/telescope/issues/1126
=> Reduces whitespace above and below the ol and ul lists

src/frontend/src/pages/myfeeds.js
Redirects the user to the login page when they visit /myfeeds if they are not logged in.
fixes https://github.com/Seneca-CDOT/telescope/issues/1137
The user goes to /myfeeds while they are not logged in and is then prompted by the following login page.
=> Fixes #1137: Change 404 page when not logged in on /myfeeds to login page

src/frontend/src/components/AuthorResult/AuthorResult.jsx, src/frontend/src/components/SearchBar/SearchBar.jsx, src/frontend/src/components/SearchPage/SearchPage.jsx
Fixes #839 
- Updates Interface to follow Material Design form spec, see screenshot below.
- Updates logic to submit on button click / enter.
*Resubmitting PR for that sweet Hacktober Participation.*
=> adds: Material styling to search and results components

src/frontend/src/components/Banner/Banner.jsx
Fixes https://github.com/Seneca-CDOT/telescope/issues/1128
Added the right positioning to the banner text.
=> Fixes #1128: Need margin on right-hand side of "Add yours..." message

src/frontend/src/components/Header/Header.jsx
Fixes #974 
className attributes removed.
=> Fixes #974: Remove className="..." from Header.jsx

docs/CONTRIBUTING.md
Was reading over `CONTRIBUTING.md` and noticed a link to a section which stated:  `Please look through the MVP Features listed below for inspiration.`. However, the section sadly does not exist on the page anymore. 
If this was made in error let me know please!
=> quick fix to CONTRIBUTING.md

src/frontend/src/components/Post/telescope-post-content.css
Fixes #1038 
Removed extra padding on code blocks, so the first line is no longer shifted
With padding:
Without padding:
=> Fixes #1038: Removed extra padding on code blocks

.github/workflows/node-test.yml
Closes #1008 
This adds GitHub Actions integration which does the an `npm install`, `npm run build`, and `npm run test-ci` against MacOS, Ubuntu, and Windows.
Example of output: https://github.com/raygervais/telescope/pull/3/checks?check_run_id=1212632972
```
2020-10-06T02:52:11.3462935Z ##[group]Run npm run test-ci
2020-10-06T02:52:11.3463266Z [36;1mnpm run test-ci[0m
2020-10-06T02:52:11.3499975Z shell: /bin/bash -e {0}
2020-10-06T02:52:11.3500283Z ##[endgroup]
2020-10-06T02:52:11.5482468Z 
2020-10-06T02:52:11.5483669Z > @seneca/telescope@1.2.0 test-ci /home/runner/work/telescope/telescope
2020-10-06T02:52:11.5484233Z > run-s prettier-check test
2020-10-06T02:52:11.5484427Z 
2020-10-06T02:52:11.8529933Z 
2020-10-06T02:52:11.8531620Z > @seneca/telescope@1.2.0 prettier-check …
```
=> adds: node-test.yml Github Actions workflow

env.example, env.staging
Fixes #988 
Remove all references to unused ENV variable.
=> chore(env): Remove blog inactive time variable

src/backend/utils/html/index.js, src/backend/utils/html/replace-entities.js, test/replace-entities.test.js
Fixes: https://github.com/Seneca-CDOT/telescope/issues/1091
This fix cleans up the code blocks within our posts at runtime to rid the source code of any HTML entity. If there is a better way I should have gone about implementing this fix please let me know!
Before the fix. Notice the encoded HTML entities within the code `&lt;` , `&gt;`, `&amp;`
After the fix.
=> Fixing code block entities

src/frontend/src/components/AuthorResult/AuthorResult.jsx, src/frontend/src/components/Banner/Banner.jsx, src/frontend/src/components/Footer/Footer.jsx, src/frontend/src/components/Header/DesktopHeader.jsx, src/frontend/src/components/Header/MobileHeader.jsx, src/frontend/src/components/Login/LoggedIn.jsx, src/frontend/src/components/Login/LoggedOut.jsx, src/frontend/src/components/Post/Post.jsx, src/frontend/src/components/Posts/Posts.jsx, src/frontend/src/components/ScrollToTop/ScrollToTop.jsx, src/frontend/src/templates/template.js, src/frontend/src/theme.js
#1173, this is the first step towards completely changing Telescope's Theme, it only touches the components used in the Home Page and Theme.js
The home page has been changed to match the new light theme design
=> Home page light theme implemented

test/query.test.js
Part of #1160 
I added a test for the query route. The only issue I'm having replicating mocking is having the actual search portion of the route fail.
You can test the PR with `npm test query`
=> Added query route tests

src/backend/web/app.js
Fixes #1166 
This changes our settings for development to allow `graphql`'s playground to load the necessary scripts for its playground
**Note** (from [Apollo's documentation](https://www.apollographql.com/docs/apollo-server/testing/graphql-playground/)):
> In development, Apollo Server enables GraphQL Playground on the same URL as the GraphQL server itself (e.g. http://localhost:4000/graphql) and automatically serves the GUI to web browsers. When NODE_ENV is set to production, GraphQL Playground (as well as introspection) is disabled as a production best-practice.
=> Fixes #1166: /graphql playground broken due to CORS issue

src/backend/index.js
Fixes #606 
differences between process event: [beforeExit](https://nodejs.org/api/process.html#process_event_beforeexit) and process event: [exit](https://nodejs.org/api/process.html#process_event_exit) is 'beforeExit' event can make asynchronous calls.
=> Fixes #606 switch from 'exit' event to 'beforeExit' in order to make asynchronos calls

docs/environment-setup.md
Fixes #1195
Add WSL2 as an approach to install Redis
=> fixes #1195 add WSL2 in the part of Redis installation

src/frontend/src/components/Login/LoggedIn.jsx
Fixes #1175 
This is not the most elegant fix but it does make the mobile view look better.
=> Fixes #1175 logged in formatting in mobile view

tools/autodeployment/deploy.sh
=> fixes: volume persistance error

src/frontend/src/components/ScrollToTop/ScrollToTop.jsx
Fixes #1206 
Removed old todo comment that was being unused in src/frontend/src/components/ScrollToTop/ScrollToTop.jsx
=> Fixes #1206: Removed old TODO comment

env.example
Fixes #952 
Moved the parentheses in the .env file, as described in the issue #952, to the lines above.
=> Fixes #952: Moved Parentheses to Line Above

docs/environment-setup.md, docs/gatsbyjs.md
Fixes #1183 
Updates the environment-setup doc to be more explicit, mentioning a running back-end + front-end running. I updated the `Finally:` section to also include instructions depending on whether the user ran `npm run develop` or `npm run build`
=> Fixes #1183: Update environment-setup docs

docs/CONTRIBUTING.md, docs/environment-setup.md, docs/redis.md
While spending some time exploring the files in `./docs`, I noticed that the `elasticsearch.md` (which was only created recently) was never linked to in any document, so I added it as a technology in the main `CONTRIBUTING.md` readme.
This might be intentional or maybe I missed something. If so, let me know please and thanks!
=> added elasticsearch.md reference to main contributing readme

src/backend/utils/html/remove-empty-anchor.js, test/remove-empty-anchor.test.js
Fixed #1190 
Added exclusiveFilter option to sanitizeHtml function in sanitize.js . The option removed anchor tags with no content in all headings.
**Before**
***
**After**
=> Fixes #1190: Remove empty anchor elements

docs/environment-setup.md, docs/gatsbyjs.md, docs/login.md
Fixes #1212 
Updating documentation to clarify `npm run build` is required to use login function
=> Fixes #1212 Update Document Regarding Login

src/frontend/src/components/ScrollToTop/ScrollToTop.jsx
This PR cleans up the residual code related to #1207.
Lines that are not being used anymore.
=> 1207 - cleanup code

src/frontend/src/components/Post/Post.jsx
Fixes **https://github.com/Seneca-CDOT/telescope/issues/1246**
styling css is now applied to the markup.
=> Fixes #1246: Syntax highlighter not working

docker-compose.yml, env.example
Part of #1269
I was thinking of Kibana ever since we added ElasticSearch, great to finally have it added. I had to also update our ElasticSearch image to 7.9.3 so it is compatible with the current version of Kibana.
To test:
1. make sure the extra lines from `env.example` are copied into your `.env` file
2. `docker-compose up redis elasticsearch kibana`
3. navigate to `http://localhost:5601`
You should see something like this afterwards
=> Add kibana to Telescope

src/backend/utils/__mocks__/indexer.js, src/backend/utils/indexer.js, test/feed.test.js, test/query.test.js
Fixes #1221
Since the text and score properties are not used after returning, they are removed.
=> Fixes #1221: Reduce amount of JSON sent from backend with query results

docker-compose.yml, env.example
Reverts Seneca-CDOT/telescope#1285
Issue with deploying on DEV environment, so reverting this for now
=> Revert "Add kibana to Telescope"

src/backend/lib/config.js
fix #1264 
Fix the bug that the setting of LOG_LEVEL in .env is not working properly. Even set `LOG_LEVEL=debug`, `npm start` still print as `LOG_LEVEL=info`. 
Remove `logger` dependency and replaced it to `Console.log()/error()` inside `lib/config.js`.
To test this, you can set `LOG_LEVEL=debug` in the .env, then run the server `npm start`.
```sh
[ 2020-11-04 17:55:58.805 ] INFO  (16544 on LAPTOP-LCOUFEIF): Loading all feeds into feed queue for processing
[ 2020-11-04 17:55:58.810 ] INFO  (16544 on LAPTOP-LCOUFEIF): Telescope listening on port 3000
[ 2020-11-04 17:55:59.335 ] INFO  (16544 on LAPTOP-LCOUFEIF): Connected to elasticsearch!
[ 2020-11-04 17:55:59.336 ] INFO  (16544 on LAPTOP-LCOUFEIF): Starting 1 instance of feed processor.
[ 2020-11-04 17:55:59.354 ] DEBUG (16544 on …
```
=> fix the bug set LOG_LEVEL in .env is not working

src/backend/utils/html/index.js, src/backend/utils/html/modify-pre.js, test/modify-pre.test.js
Attempts to fix #1250 
This PR adds to the number of code posts that get syntax highlighted. 
There are too many edge cases to cover here so I included the cases in this PR that have *most* of the syntax highlighting issues.
Here are some before and after photos of the fix..
Before...
And after...
Here is another Before....
And after...
This [Wordpress](https://nesabyte.wordpress.com/ ) blog seems to be the only problem case that wouldn't get fixed in this PR.
All of the code posts from the blog https://nesabyte.wordpress.com/ do not get fixed in this PR sadly, even though at a first glance, that blog seems to have the same edge cases as the above fixes.
I looked at all of the posts from the past 2 months and pretty much all of the problem edge cases that weren't getting fixed were coming …
=> Fix #1250: syntax highlighting for all empty <pre>

src/frontend/src/components/Header/MobileHeader.jsx, src/frontend/src/components/Login/Login.jsx
This fix fixes [issue-971](https://github.com/Seneca-CDOT/telescope/issues/971). Where the login button was not fully clickable when using the drawer for mobile or tablet view.
This PR fixes the mentioned issue by moving the `<ListItem>` wrapped around `<Login/>` from `MobileHeader.jsx` into `Login.jsx`. 
It adds a prop to `<Login/>` to pass the style of `<ListItem>`. Finally, it fixes the issue by adding the links for login and logout to ListItem. Any suggestions are welcomed.
=> Fixes #971: Where login button wasn't fully clickable

package.json, src/backend/web/routes/query.js, src/backend/web/validation.js, test/query.test.js
Fixes #1312 
- Added query validation for text and filter in GET/query using Express-validator.
-  Also added unit tests to ensure that it works.
=> Fix#1312 - validate query params for GET /query?text=<searchTerm>&filter=<filterBy> route

test/post.test.js
Fixes #1323 
I added some tests to post.test.js make sure we throw when an invalid date is passed. **Use to show line 29 needs a test
=> Fixes issue #1323 Added tests to make sure we throw when an invalid date is passed

.gitignore, src/backend/web/routes/posts.js, src/backend/web/validation.js, test/posts.test.js
refactored validation.js to reduce code duplication
added query params validation for /posts with unit testing
fixed testing isssues
=> added query params validation for /posts with unit testing

env.example, env.production, env.staging
Fixes #1351 
changed max posts per page to 5.
le name is shown
I changed the variable MAX_POSTS_PER_PAGE=5, from three different env file.
=> set MAX_POSTS_PER_PAGE=5

src/frontend/src/components/SearchBar/SearchBar.jsx
Fixes #1344 
Margin has been added under the search bar.
=> Issue-1344  Added margin after search bar

docs/logging.md
Added in trace, debug, warn, and fatal log levels.
This Pull Request Fixes#1265. 
This documentation clarifies all the possible uses of our logger, Pino. This will allow developers to quickly understand how to use our logger.
- [] **Tests**: This PR includes thorough tests or an explanation of why it does not
=> updated logging.md

src/frontend/gatsby-config.js, src/frontend/package.json, src/frontend/src/components/SearchBar/SearchBar.jsx, src/frontend/src/components/SearchPage/SearchPage.jsx, src/frontend/src/components/SearchPage/SearchResults.jsx
Fixes #1270 
* URL synchronizes with keyword when typing in search page. After being submitted, URL shows https://telescope.cdot.systems/search?q=keyword&f=author
* When someone browses to the URL https://telescope.cdot.systems/search?q=keyword&f=author, keyword and author are shown on the search box, click submit button to do a search.
=> Fixes #1270: let URL in sync with keywords to make searches sharable

tools/autodeployment/deploy.sh
Fixes #1340 
Added in a missing argument to the deploy.sh file in /telescope/tools/autodeployment/ that specifies a yml file for the docker-compose command on line 50. With this argument added in, docker-compose won't mix up the files docker-compose.yml and docker-compose-production.yaml anymore.
=> Fixed issue#1340 - added in missing parameter to specify a yml file

docker-compose.yml
Issue #1347 
Changed the ``SERVER_HOST`` as mentioned in the issue.
Changed it to ``KIBANA_HOST`` under ``kibana:`` in the  docker-compose.yml file
=> #issue 1347 | changed SERVER_HOST to KIBANA_HOST

src/frontend/src/components/Post/Post.jsx
This PR should fix the [issue #1089 - Add new feature of expanding the title after click](https://github.com/Seneca-CDOT/telescope/issues/1089). After clicking the title, the title will be expanded and can be collapsed by clicking it again. Here are the screenshots of clicking to expand or collapse the blog title.
on mobile device
on desktop
Please let me know if there is anything that I can improve, thank you!
=> Fix: issue#1089 - Feature Request: display full blog title after click

src/backend/web/routes/feeds.js, src/backend/web/validation.js, test/feeds.test.js
*Added validation rule and validateFeedsByID function
*Added function in module
*Edit feeds.js file with adding validatedFeedsByID function
*Added feeds test which check the id length
=> Added query params validation feeds/:id with unit test

docs/theme-and-colours.md
Correct the url to theme,js from previous commit.
=> Fixed incorrect url to theme.js

env.example, env.production, env.staging, src/backend/utils/indexer.js, src/backend/web/routes/query.js, src/backend/web/validation.js, src/frontend/src/components/SearchPage/SearchResults.jsx, test/query.test.js
Fixes #1222 and #1349 
Search results now infinitely load (through scrolling) in increments of 10 (MAX_POSTS_PER_PAGE)
=> Fixes #1222/1349 added paging functionality for search results

src/backend/web/routes/feeds.js, src/backend/web/validation.js, test/feeds.test.js
Fixes #1308 
This PR is meant to fix #1308 and does so by adding a validator from express-validator to the validation.js file and feeds.js file. It also adds tests to test if an id is too long or short. 
I spent a lot of time reviewing #1363 to make sure I was doing everything right and I noticed a discussion on whether or not we should use the [same rules](https://github.com/Seneca-CDOT/telescope/pull/1363#discussion_r525340973) for different checks because the Id is the same length between everything. I decided to make a new rule to future-proof the process but if it needs to be changed I can do that.
=> add param validation for delete feeds using express validator and unit tests

src/frontend/src/components/SearchPage/SearchResults.jsx
Using hard value results in this problem on mobile, fix https://github.com/Seneca-CDOT/telescope/issues/1406
=> Fix overflow problem

src/backend/web/routes/feeds.js, test/feeds.test.js
Fixes #1309 
Enhancement
Added Feed ID validation function in `/src/backend/web/routes/feeds.js`.
Added 2 test cases for that validation function in `/test/feeds.test.js`.
=> added param validation and tests

src/frontend/package.json, src/frontend/src/components/SearchBar/SearchBar.jsx, src/frontend/src/components/SearchInput/AuthorSearchInput.jsx, src/frontend/src/components/SearchInput/PostSearchInput.jsx, src/frontend/src/components/SearchInput/SearchInput.jsx, src/frontend/src/components/SearchInput/index.js
Co-authored-by: matthew stewardson <mstewardson@myseneca.ca>
Fixing up some git commit issues with original PR https://github.com/Seneca-CDOT/telescope/pull/1411.
=> Fix #1260: Added frontend support for autocomplete

src/frontend/src/components/SearchInput/SearchInput.jsx
=> fixes #1427: searching text param is missing in the input control

src/frontend/gatsby/src/components/SearchInput/AuthorSearchInput.jsx, src/frontend/gatsby/src/components/SearchInput/SearchInput.jsx
#1432 - Mouse hover on search textField makes border disappeared
Before we had the search text field's border disappearing when the mouse hovers on it, and the size of the inputs in the search bar didn't match. Follow screenshots: 
Before:
After:
=> Fix Issue1432: Mouse hover on search textField makes border disappeared

package.json, src/frontend/gatsby/package.json, test/syntax-highlight.test.js
This PR bumps [highlights.js](https://github.com/highlightjs/highlight.js/) version to `10.4.1` to fix a vulnerability found by Dependabot alerts.
=> Fix: upgrade highlight.js to version 10.4.1

netlify.toml, src/frontend/README.md, src/frontend/next/next.config.js, src/frontend/next/package.json
closes #1447 
Adds configuration which allows testing and previews of NextJS to be viewed via Netlify
=> adds: essential netlify.toml config file

docs/aws-cloud9.md, docs/environment-setup.md, env.example, tools/aws-ip.sh
I thought this would be nice to have for Windows users who are interested in developing Telescope using a cloud development environment.
=> AWS Cloud9 IDE Environment Setup Instructions

src/frontend/next/src/components/ScrollAction/ScrollAction.tsx
Fixed #1469 
I have modified the ScrollAction Component to be written in TS.
=> Ported ScrollAction component

src/frontend/next/src/components/GitHubContributorCard.tsx, src/frontend/next/src/hooks/use-telescope-contributor.ts
Fixed #1496  
In this PR, I have modified GitHubContributorCard component to be written in TS. I also got rid of all the folders for the rest of the components. Figured it's better to do it early rather than later when we have many more dependent components.
=> Ported GitHubContributorCard component 

docs/overview.md
Fixes #1535 - Added the initial project diagram to [overview.md](https://github.com/Seneca-CDOT/telescope/blob/master/docs/overview.md)
=> [1535] Updated docs to include initial project diagram

src/frontend/next/src/interfaces/index.ts
Fixes #1570 
This PR adds the Feed types to interfaces/index.ts, which will be used when porting over all feed related components over to next from gatsby
=> [next] - Add Feed types to list of interfaces #1570

src/frontend/next/src/components/Login/LoggedIn.tsx, src/frontend/next/src/components/Login/LoggedOut.tsx, src/frontend/next/src/components/Login/index.tsx
Fixed #1456 
Modified LoggedIn, LoggedOut and Login Components to be written in TS and use the new `useUser` hook. I also remove the `style` prop passed down from parent component and switch to `isMobile` prop instead.
=> Fixed #1456: Ported Login component to NextJS

src/frontend/next/src/pages/_app.tsx, src/frontend/next/src/theme/lightTheme.ts
Provided the theme object to the whole app in `_app.tsx` using `ThemeProvider`
=> Providing Theme object to the whole app

src/frontend/next/src/components/Posts.tsx, src/frontend/next/src/components/Posts/index.tsx
This will allow us to the main page with the right imports. 
change the Posts import
=> fix folder structure

src/frontend/next/next.config.js, src/frontend/next/package.json, src/frontend/next/src/pages/about.mdx
Fixes #1463
Been trying to research how to render an `md` file with NextJS, and AFAIK NextJS renders `md` files differently than Gatsby. Upon researching this further I found this neat library which not only renders `md` files, but allows you to inject JSX (TSX) code directly into the `md` file in question. When styling/MUI is finished for next, styling the about page should be nothing short of jovial.
Furthermore, I think the MDX lib pairs really nicely with how NextJS automagically creates routes based on present files in the `pages` directory. All I had to do was place the `.mdx` file alongside otherside the `.tsx` (_currently only `index.tsx`_) files and it renders @ `localhost:8000/about` out of the box.
I also had to create a next config file (_see: `next.config.js`_) to be able to …
=> [next] Fixes #1463 - re-implements the About page w/ nextjs

.prettierignore
#1593 Added /out into Prettier Ignore
Added `/out` into `.prettierignore`, this is necessary as currently, we're getting a bunch of unnecessary warnings from Prettier
[Screencapture of Prettier](https://i.imgur.com/OhRGxdn.png)
=> Fixes #1593, added /out into .prettierignore

tools/autodeployment/server.js
Co-authored-by: Calvin <calvinho125@gmail.com>
GitHub's webhooks send 3 POST requests whenever there's a new release. After some testing, I can confirm that our autodeployment server on `prod` crashes trying to process the 3 POST requests in parallel.
This PR filters out the requests that don't need to be considered.
Info about release's actions [here](https://docs.github.com/en/actions/reference/events-that-trigger-workflows#release).
=> Add filter to avoid processing more than one POST requests in a release

tools/autodeployment/deploy.sh
This adds additional clean up logic for both prod and dev environments so that we are removing additional docker images which are created during the multi-stage container process. Prior to this fix, @manekenpix and I confirmed that more docker images were being created vs deleted, which eventually adds up to all space in in the partition being used.
Adding the following segment allows us to target `<none>` containers which are not cleaned with the previous image purge process. Tested on dev environment with @manekenpix. 
```bash
docker rmi $(docker images -a | grep "^<none>" | awk '{print $3}') 2> /dev/null
```
=> fixes: older docker images which weren't tagged wouldn't be removed

src/frontend/next/src/components/BannerDynamicItems.tsx, src/frontend/next/src/components/DynamicImage.tsx
Fixes #1612
This PR ports the BannerDynamicItems component from Gatsby to NextJS. I used the `<Link>` component from NextJS and an anchor tag to style the actual link itself.
We do things differently in the [Footer](https://github.com/Seneca-CDOT/telescope/blob/master/src/frontend/next/src/components/Footer.tsx) component so I'm curious to see what others think about this change.
(@humphd) I also added in a mocked `<DynamicImage>` component (as `<BannerDynamicItems>` [relies on](https://github.com/Seneca-CDOT/telescope/issues/1492) `<DynamicImage>`). Let me know if you want me to remove that part too, just trying to avoid something screaming at me for as long as possible.
Simply import and render the component wherever you like (I rendered mine in `Banner.tsx`):
```TS
import …
```
=> [next] Fixes #1612 Ported BannerDynamicItems component from Gatsby to Next

src/frontend/next/src/components/UserProvider.tsx, src/frontend/next/src/hooks/use-authorization.ts
Fixes #1620 
The `useUser()` and `useAuthorization()` hooks weren't functioning correctly in all cases.  This fix deals with the various cases, and makes sure that we always pass the correct data for a User.
The easiest way to test this is to add a tiny bit of code to `src/frontend/next/src/pages/index.tsx`:
```diff
diff --git a/src/frontend/next/src/pages/index.tsx b/src/frontend/next/src/pages/index.tsx
index d2362ae..0059b6a 100644
--- a/src/frontend/next/src/pages/index.tsx
+++ b/src/frontend/next/src/pages/index.tsx
@@ -3,7 +3,12 @@ import Banner from '../components/Banner';
import BackToTopButton from '../components/BackToTopButton';
import Posts from '../components/Posts';
+import { useUser } from '../components/UserProvider';
+
const Home = () => {
+  const user = useUser();
+ …
```
=> Fix #1620: useUser() should always return a valid User object

src/frontend/next/src/components/DeleteFeedDialogButton.tsx, src/frontend/next/src/components/ExistingFeedList.tsx, src/frontend/next/src/interfaces/index.ts
This PR fixes #1544 
As part of #1316, this PR continues the porting of the telescope front-end to next.js from gatsby. This PR ports the, "ExistingFeedList" component. A slight modification was also made with the FeedHash type in order to ensure the component works. React.memo was not used here since it requires the use of a component that is of type "SFC" which has since been deprecated and replaced with FunctionalComponent, or FC, which we have decided not to use. Read about that [here](https://stackoverflow.com/questions/53885993/react-16-7-react-sfc-is-now-deprecated)
=> [next] Fixes #1544: Porting ExistingFeedList to Next.js

tools/autodeployment/package.json, tools/autodeployment/server.js
Closes #1604 
This adds the [official webhook event library from GitHub](https://github.com/octokit/webhooks.js) to our autodeployment server, and also adds `express` for consistency with the project (telescope's back-end uses `express`).
=> Closes #1604: Use octokit/webhooks.js in autodeployment server

src/frontend/next/package.json, src/frontend/next/src/components/ExistingFeedList.tsx, src/frontend/next/src/components/SnackBar.tsx, src/frontend/next/src/pages/myfeeds.tsx
Fixed #1491  
I have added all the typing required by TS
=> Fixed #1491: Port MyFeedsPage, see src/frontend/src/pages/myfeeds.js to NextJS

package.json
Fixes #1638 
This PR configures `npm version` to run prettier, eslint and tests locally. If successful, it will bump the version in `package.json` and commit. Finally, it will create a release tag and push both code and tags to `upstream master`. All that's needed to create a release is to run `npm version <new-version> -m "Release description"`. For more details, see [`npm version` docs](https://docs.npmjs.com/cli/v6/commands/npm-version).
=> [CI/CD] Fixes #1638: Configured npm version to run tests and push to upstream master

src/frontend/next/.gitignore, src/frontend/next/package.json
Fixed #1586 
Updated `next/package.json` so when run `npm run start` the production server run on port 8000 as in development instead of default port of 3000
=> Updated production server to run on port 8000 instead of default 3000

src/frontend/next/src/components/Posts/index.tsx
Fixed #1652 
The theme toggle button will be visible even in large screen. I also fixed it so the error container expands the full width if no posts load. 
To test this, simply open your next front end without running the backend locally. 
I am using a 32 inch monitor
=> Fixed#1652: Fixed theme toggle button disappear when there is error of loading posts

src/frontend/next/src/components/Header/DesktopHeader.tsx, src/frontend/next/src/components/Header/MobileHeader.tsx
=> Fix unclickable logo in [next] desktop and mobile header

package.json
Fixes #1684
As described in #1684, we do not need to use `release-it` anymore. This PR removes it from the list of dependencies. The release docs will be updated in https://github.com/Seneca-CDOT/telescope/pull/1650.
=> Fixes #1684: Removed release-it from dependencies

docs/release.md
Fixes #1632
This PR updates our [release documentation](https://github.com/Seneca-CDOT/telescope/blob/master/docs/release.md) to account for the recent introduction of the automated [release workflow](https://github.com/Seneca-CDOT/telescope/blob/master/.github/workflows/release.yml) (https://github.com/Seneca-CDOT/telescope/pull/1628 and https://github.com/Seneca-CDOT/telescope/pull/1648).
=> [Documentation] Fixes #1632: Updated release documentation

src/frontend/next/src/components/DynamicImage.tsx
=> Fix Banner image size in resolution over 1920px [issue 1683]

src/frontend/next/package.json, src/frontend/next/src/pages/_app.tsx, src/frontend/next/src/theme/index.ts
Fixes: #1686 
Currently we use deprecated fonts on our NEXT front-end. 
This PR will fix it and add the font that our UI 2.0 is going to use.
=> Fixes #1686 [next] Update deprecated Fonts.

.github/dependabot.yml
Fixes #1647 
As agreed during our meeting today, we are going to use Dependabot to keep our dependencies up-to-date. This config file will set it up to track four `npm` package files: `/`, `/src/frontend/gatsby`, `/src/frontend/next`, and `tools/autodeployment`. Refer to https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates for details on configuration settings.
=> Fixes #1647: Created config file for Dependabot

src/frontend/next/src/theme/index.ts
Fixed #1678 
I made change to `text` property in the theme mostly and keep primary and secondary the same. 
I put the title and icon color as `text.secondary` because I believe icon could be considered a type of text too. 
Please let me know if we need to update this. Don't really know what to do with `primary` and `secondary` now since we have a more minimalistic design.
=> Adjusted light theming color for UI 2.0

src/frontend/next/src/components/Banner.tsx, src/frontend/next/src/components/Header/DesktopHeader.tsx, src/frontend/next/src/components/Header/MobileHeader.tsx, src/frontend/next/src/components/Posts/Post.tsx, src/frontend/next/src/pages/search.tsx, src/frontend/next/src/theme/index.ts
Fixes: #1734 
This PR fixes the following issues:
- Remove hero image from search and other non-home pages ( @tonyvugithub I already fixed this problem here. )
- Some colour differences in our theme (e.g., nav header is a different blue)
- Height of navbar is wrong (#1734)
- Banner's Scroll Action position
=> Fixes: #1734 - Height of navbar is wrong + Color Theme (back to old one) + remove BANNER from non-home pages

src/frontend/next/src/components/Login/LoggedIn.tsx, src/frontend/next/src/components/Login/LoggedOut.tsx, src/frontend/next/src/components/Login/index.tsx
**Fixes #1663** 
**Also Fixes #1682 for LoggedIn and LoggedOut components**
_Mobile view_
_Desktop view_
Started with fixing inconsistent styling of the Login button component, but ended up fixing both Login and Logout components in both Mobile and Desktop. 
Please take a look at the Logout as well if possible.
=> Fixes #1663 - rewrote LoggedIn and LoggedOut components

src/frontend/next/src/components/SearchPage.tsx
=> Fix #1630 - triggering search via URL

src/frontend/next/package.json
This PR bumps version of [@next/mdx](https://github.com/mdx-js/mdx). Tested this update locally by checking the About page.
=> chore: bump @next/mdx from 10.0.6 to 10.0.7 in src/frontend/next

vercel.json
I'm adding a `vercel.json` config to try and:
- silence some of the GitHub PR spam from Vercel deploying PRs and branches (see https://vercel.com/docs/configuration#git)
- make the logs public so people other than me can see them when they fail (see https://vercel.com/docs/configuration#project/public)
=> Add vercel.json see https://vercel.com/docs/configuration

src/frontend/next/src/components/Posts/Timeline.tsx, src/frontend/next/src/components/SearchResults.tsx
Fixes #1415 
- Render empty when there's no search
- Add a spinner when the next page is loading
- Fix page crash when a search reaches the end
=> [SearchResults] - fix search results bugs  

src/frontend/next/package.json
Related to #1592 
This PR bumps the` next` version to 10.0.7.
=> chore: bump next version from 10.0.2 to 10.0.7 in src/frontend/next

src/frontend/next/package.json
This PR bumps `swr` from 0.4.0 to 0.4.2 in src/frontend/next. Tested by fetching posts, performing a search for posts/authors, accessing `My Feeds` page.
=> chore: bump swr from 0.4.0 to 0.4.2 in src/frontend/next

src/frontend/next/package.json
This PR bumps typescript from 4.1.2 to 4.1.5 in src/frontend/next.
=> chore: bump typescript from 4.1.2 to 4.1.5 in src/frontend/next

tools/autodeployment/package.json
This PR bumps `@octokit/webhooks` and `date-fns` dependencies in the auto-deployment server.
=> chore: bump @octokit/webhooks and date-fns

src/frontend/next/src/components/MyFeeds.tsx, src/frontend/next/src/components/Posts/Post.tsx, src/frontend/next/src/interfaces/index.ts
=> Fix #1753 - Link author name to their feed URL

src/frontend/next/src/components/SearchPage.tsx
=> Fix #1764 - Add mobile anchor on Search page

src/frontend/next/src/components/Header/DesktopHeader.tsx, src/frontend/next/src/components/Header/MobileHeader.tsx, src/frontend/next/src/components/ThemeProvider.tsx, src/frontend/next/src/components/ThemeToggleButton.tsx, src/frontend/next/src/hooks/use-preferred-theme.ts, src/frontend/next/src/interfaces/index.ts, src/frontend/next/src/pages/_app.tsx, src/frontend/next/src/pages/index.tsx, src/frontend/next/src/pages/myfeeds.tsx, src/frontend/next/src/pages/search.tsx
Fixed #1641 
- Move ToggleThemeButton to Header
- Persist preferred theme value to localStorage
=> Fixed #1641: Moved ToggleThemeButton to Header and persist preferred theme value to localStorage

src/frontend/next/src/pages/_document.tsx, src/frontend/next/src/pages/index.tsx, src/frontend/next/src/pages/search.tsx
Fixes #1655
When porting over the `<Search>` component, I noticed several inconsistencies with our `<Head>`, `<meta>`, and `<title>` tags:  we occasionally used a combination of them when really only the `<SEO>` component with a passed `<title>` was necessary. This PR aims to fix these small problems and hopefully iron out our SEO.
There should now only be one instance of `<title>` on each of our pages, along with the corresponding `<meta>` tags being rendered. I included some screenshots on how I tested this.
_(My [styled about page](https://github.com/Seneca-CDOT/telescope/pull/1769) already implements this fix, so when that lands it'll be fixed already.)_
1. Locally:
a. `gh pr checkout 1774` (download GitHub CLI [here](https://cli.github.com/)
b. `npm run develop:next`
c. Navigate to …
=> refactor(tidy up): Fixes #1655 - Removed unnecessary <Head>, <meta>, and <title> tags

src/frontend/next/src/markdown-pages/about.md, src/frontend/next/src/pages/about.mdx, src/frontend/next/src/pages/layouts/MDXPageBase.tsx
Fixes #1651
Fixes #1691
Hey Y'all,
I finally got around to styling the about page and implementing a basic PageBase for MDX documents. Let me know what you think.
Due to the "restrictive" nature of how MDX works there's no way to make an MDX document all that dynamic and exciting, (you can, it'd just be kind of messy) though that was never really the idea behind something like a markdown document in the first place.
The styling done here is basic yet pleasant (_or at least what I'd call pleasant_.)
This PR is not really a "draft" per se but it does need some work. I'm always looking for constructive criticsm so let me know what you think.
The idea I had for even utilizing MDX in the first place is that it allows us to inject JSX code directly into an MD file. Because of this we can simply …
=> style(port): Fixes 1651 - Styles the About page

src/frontend/next/src/components/SearchInput/AuthorSearchInput.tsx, src/frontend/next/src/components/SearchInput/PostSearchInput.tsx
=> fix:1784 - Post search input bug

src/frontend/next/src/styles/telescope-post-content.css
This PR takes over the old PR #1373 
Fixes: #1370 
Please leave comments about this css styling, thank you!
This is the current picture styling, which is not the natural size of the original blog.
This is using the natural size of the original blog post.
=> Fixes: #1370 Set picture in post as their natural size

Dockerfile
This removes dependencies needed in telescope's `Dockerfile` for building `gatsby`.
=> chore: remove gatsby dependencies from telescope's Dockerfile

docs/front-end.md, src/web/src/theme/index.ts
Fixed #1678 
Changed light theme color palette and updated doc to the new colors.
=> Adjusted Light Theming for UI 2.0 and updated front-end.md

src/backend/utils/html/sanitize.js, test/sanitize-html.test.js
Fixes #1815 
Some users may include spotify playlists in their blog posts. This gets included via an iFrame tag. We previously did not allow this, and they would not appear. This PR addresses that by including `open.spotify.com` to the list of allowed iFrame sources as well as `cdn.embedly.com` if it's used to embed any iframes from the list of allowed sources in the future. Tests were updated to account for this. For the latter link, refer to the final test within (https://github.com/Seneca-CDOT/telescope/blob/master/test/fix-iframe-width.test.js), since the latter link essentially allows an iframe embedded within an iframe. 
To test this, view the deployment link. The latest blog post from Pedro includes a spotify embedded playlist. You should be able to see it display correctly.
=> Fixes #1815: Spotify playlists within an iframe are not sanitized

src/web/src/components/Header/DesktopHeader.tsx, src/web/src/components/Header/MobileHeader.tsx, src/web/src/components/Header/index.tsx, src/web/src/components/Login/LoggedIn.tsx, src/web/src/components/Login/LoggedOut.tsx, src/web/src/components/Login/index.tsx
=> UI 2.0 Sidebar 1687 and fix: 1823 Log Out button 

src/web/src/components/Posts/Post.tsx
This is a quick fix for the `DateTimeFormatOptions` that's breaking the front-end build.
We'll probably have to look into this a bit more.
=> Fix for DateTimeFormatOptions issue

tools/services.js
This is a small fix to update which `env` file gets used when you run the `services:*` npm scripts.  Previously I used the `.env` in `src/api` or copied `env.development` there if it was missing.
I think this is a footgun that I'd like to remove so users don't end up with a config that won't run if they play with the `.env`.  If you run the tests or `services:*` scripts, it will use the **default** config we have.  If you want to do your own configs, you should also know how to use `docker-compose` to run it yourself.
I think this will avoid confusion.
To test this:
```
$ npm run services:start
$ npm run services:logs image
$ npm run services:stop
```
=> Always use src/api/env.development with npm services:* scripts

.github/workflows/release.yml, release-changelog-builder-config.json
Fixes #1794
This PR adds a new action to generate a release changelog. See https://github.com/mikepenz/release-changelog-builder-action for details. You can test this PR by merging it into your forked repository and making a release there. Just make sure to remove the main telescope's repository from the list of remotes and rename your fork to `upstream`. Then do `npm version patch -m "Testing relese changelog"` 
This is the changelog generated in [my fork](https://github.com/birtony/telescope/releases/tag/untagged-5a28aa0a2dddef5984dc):
=> Added new changlelog generator

src/web/src/components/SearchBar.tsx, src/web/src/components/SearchPage.tsx
Fixes #1808 
Changed background color of search page as screenshot below:
=> Changed searchPage background color [1808]

src/web/src/components/Header/DesktopHeader.tsx, src/web/src/components/Header/HeaderButton.tsx, src/web/src/components/Login/LoggedIn.tsx, src/web/src/components/Login/LoggedOut.tsx
This PR changes the style of the header buttons and adds a `tooltip` to display the name of every button when hovering over them.
Also, I saw that we were reusing the same code for every button so I created a `HeaderButton` component that takes props that are  unique for every button.
=> [UI 2.0] Change header buttons' style and refactor code

src/web/src/components/GitHubContributorCard.tsx, src/web/src/hooks/use-telescope-contributor.ts
=> Fixes #1841 - Fetch all contributors and fix contribution count plural

src/web/src/components/Posts/index.tsx
No open issue. 
Fix the horizontal scroll bar on Linux and Windows.
=> Fix the horizontal scroll bar on Linux and Windows.

src/web/src/hooks/use-telescope-contributor.ts
Fixes #1857 
This PR follows a request from @humphd to remove SWRInfinite to fetch a random contributor only one time.
=> Fix #1857 - Remove SWRInfinite and any type

src/web/src/components/Posts/Post.tsx
No open issue.
We were experiencing a vertical scroll bar in some posts. This PR will fix this bug.
Before:
After:
=> Fixes: BUG - vertical scroll bar on post

src/web/src/components/NavBar/index.tsx, src/web/src/components/Posts/Post.tsx, src/web/src/components/Posts/PostInfo.tsx, src/web/src/components/Posts/Timeline.tsx, src/web/src/components/Posts/index.tsx
Fixes: #1677 and #1688
After this PR, we will need to work on small issues polishing the new UI.
But here, our UI 2.0 has a solid skeleton supporting incoming improvements and Telescope's new features. 
To test it, please check the Vercel build.
=> Mobile version posts timeline post

src/web/src/components/SearchBar.tsx, src/web/src/components/SearchInput/AuthorSearchInput.tsx, src/web/src/components/SearchInput/PostSearchInput.tsx
Closes #1805
Closes #1806 
Changed styles for search bar as below:
=> Changed Search bar style for new UI [1805 - DESKTOP UI]

src/web/src/components/BackToTopButton.tsx, src/web/src/components/Banner.tsx
Fixes #1689 
In this PR I made the `BackToTop` button appear slightly higher on mobile UI and appear right under the Author info on desktop UI. 
I also remove the shadow and changed the `ArrowUp/DownKey` FontSize = 3rem (changes in `banner.tsx` are done only to make the buttons look the same)
Desktop Version: 
Mobile Version (iPhone X, Will test directly on my device after deployment as well):
=> Fixes #1689: port 'BackToTop' button to UI2.0

src/web/src/components/Posts/PostAvatar.tsx
=> Fix: issue 1919 - Center initials

src/web/next.config.js
@PedroFonsecaDEV noticed that we don't use the API_URL in `.env` anymore, this fixes that to support the current next build behaviour locally.
=> Use .env if present when building next.js

release-changelog-builder-config.json
=> Fixed typo in changelog configuration file

Dockerfile, docker/docker-compose.yml, docker/production.yml, src/api/posts/package.json, src/api/posts/src/data/feed.js, src/api/posts/src/data/post.js, src/api/posts/src/routes/posts.js, src/api/posts/test/posts.test.js, src/web/next.config.js, src/web/src/components/Posts/Timeline.tsx, src/web/src/components/Posts/index.tsx, src/web/src/config.ts
This PR closes #1946 
This PR adds our new posts microservice to the frontend. When running the frontend, it will make a request to the posts url based on what url it is in the .env, and load the posts into the frontend to be processed and read.
=> Updated front-end to use posts microservice

src/web/src/components/BackToTopButton.tsx, src/web/src/components/NavBar/index.tsx, src/web/src/components/Posts/Post.tsx, src/web/src/components/Posts/PostAvatar.tsx
No open issue.
This PR address small fixes on our UI:
*NavBar icons margin fixed
*Post.tsx clean up
*Post.tsx mobile avatar centralized
*BacktoTopButton position
*PostAvatar Desktop Size
=> Package UI 1.8.1

docs/front-end.md, src/web/src/components/Banner.tsx, src/web/src/components/BannerDynamicItems.tsx, src/web/src/components/DynamicImage.tsx, src/web/src/components/NavBar/NavBarButton.tsx, src/web/src/components/NavBar/index.tsx, src/web/src/components/Posts/Post.tsx, src/web/src/components/Posts/PostAvatar.tsx, src/web/src/components/Posts/index.tsx, src/web/src/components/ThemeToggleButton.tsx, src/web/src/theme/index.ts
Fixed #1960 
I brought back the Dark Theme as per request of @PedroFonsecaDEV . I also made a couple adjustments to tackle some minor CSS issues to make it look better
Light
Dark
=> Reactivated Dark Theme

src/web/src/components/SearchBar.tsx, src/web/src/components/SearchInput/AuthorSearchInput.tsx, src/web/src/components/SearchInput/PostSearchInput.tsx, src/web/src/pages/layouts/MDXPageBase.tsx, src/web/src/theme/index.ts
Fixes #1984 
In this PR I make changes to the display of the About and Search pages in Dark mode. 
About Before: 
About After: 
SearchBar Before: 
SearchBar After: 
The input text for the SearchBar changes its text colour depending on the mode as well.
Feel free to launch the deployment and play around with those pages.
=> Fix About and Search pages

docs/front-end.md, src/web/src/theme/index.ts
Fixed #1991 
Changed the background of site in light theme to #FFFFFF instead of #E5E5E5.
=> Changed site background in light theme to #FFFFFF

src/web/src/components/Posts/Post.tsx
=> Fixes #1977 - Set minimum post height

src/web/package.json, src/web/src/pages/_app.tsx, src/web/src/styles/telescope-post-content.css
Fixed #2010 
Updated font for post content to `PT Serif`
=> Updated PT Serif font for post content

src/web/src/components/AdminButtons.tsx, src/web/src/components/Posts/Post.tsx, src/web/src/components/Posts/PostInfo.tsx
Fixes: #1957
Currently, the user info (e.g. `isAdmin`) has not been shipped. Therefore, in order to test this PR, please go to `/src/web/src/User.ts` to change `isAdmin` value to return **true** instead.
=> Add Admin Buttons

src/web/public/googlee1d86717a49db532.html
Related to #1989
This is a temporary way to verify website ownership on Google Search Console, until @manekenpix can get the domain verification,
=> Added Google Search Console ownership verification

src/web/src/styles/telescope-post-content.css
Fixed #2044 
Corrected the font name in css file from `PT-Serif` to `PT Serif`. Also, changed the fallback font from `sans-serif` to `Serif`
=> Corrected PT Serif font's name

src/api/users/README.md, src/api/users/src/models/celebrateSchema.js, src/api/users/src/routes/users.js, src/api/users/test/e2e/users.test.js
Closes #1929
This PR paginates the get route in the users micro-service. The get route can now be used with a paginated front-end to request a specific number of users (defaulted to 5 at a time.)
I wrote a pretty basic test which demonstrates the functionality of this PR. I can always add more tests if required but I wasn't too happy with how hacky the code in tests file was getting. I'm up for suggestions.
1. `npm run services:start firebase`
2. `npm run jest:e2e /src/api/users/test/e2e`
or
1. `npm run services:start firebase`
2. Add `process.env.FIRESTORE_EMULATOR_HOST = 'localhost:8088';` to `src\api\users\src\services\firestore.js`
3. `cd src/api/users && npm run dev`
3. `POST` a bunch of generic users with different `id`s using postman (see below)
4. `GET` …
=> Fixes issue-1929: Paginated get route

src/api/posts/package.json
This picks up some security updates for the deps in the Posts service.
=> Update Posts service deps

src/api/users/package.json
Quite a few deps in the Users service need updating, so rather than wait on Dependabot to fix, I did it all at once.  We're getting ready to use Users in production, so now's a good time to get this up-to-date.
=> Update Users service deps

src/api/auth/package.json
We need to update the SAML passport strategy in the auth service to pick up a security fix.
=> Update auth deps

src/web/src/components/AboutFooter.tsx
Added paddingBottom on footer style class.
It contributes to #2084
=> fixed overlapping of footer due to navbar

src/web/src/styles/telescope-post-content.css
Fixes #2039 
Added custom styling for blogspot images
Small CSS addition to fix the thorn that is the BlogSpot issue (images being scaled down to fit inline for BlogSpot blogs). I have added CSS to style **only** the BS images with the new element decorators via `.telescope-post-content.is-blogspot img { ... }`
| Before |
| :---: |
| ![image](https://user-images.githubusercontent.com/48869737/113781479-c1126580-96fe-11eb-9caf-f1e644f5bd22.png) |
| **After** |
| ![image](https://user-images.githubusercontent.com/48869737/113781335-8e686d00-96fe-11eb-90d6-d00436abbcab.png) |
1. Check files changed for syntax errors and/or improvements to the code
2. View the deployment and quickly preview the homepage timeline for any possible visual styling bugs
3. Navigate to the search page
4. Search the …
=> Fixes #2039: BlogSpot images are scaled down the same as inline images

jest-playwright.config.js, jest.config.base.js
This PR closes #2016 
In my process to fix #2016, I accidently closed #2059 when fixing the git history of that branch that the PR was built upon.
This PR seeks to remedy this issue, and close 2016 once and for all. 
This PR adjusts our e2e timeout settings and our jest e2e settings to account for the github actions vm taking a decent amount of time to run the e2e tests and fail them on certain occasions.
How to test:
- Check the e2e tests here for this PR
- Grab the changes from this PR and run the e2e tests locally to ensure results are satisfied
=> Fixes #2016: Updated jest timeout and jest e2e timeout settings in playwright

src/web/src/components/BannerButtons.tsx, src/web/src/components/TelescopeAvatar.tsx
Fixes #2100 
This PR was a solution to solve the bug on my machine. 
It seems that for some reason MUI theme was causing the bug when used in the `Avatar` component. 
Tested on Chrome, Firefox and Safari. 
SAFARI(14.0.3):
FIREFOX(87.0 (64-bit)):
Chrome(Version 89.0.4389.114 (Official Build) (x86_64)):
=> Fix: Dark mode not being applied fully when user logs in

src/api/auth/package.json
=> Updated satellite semver in /src/api/auth/package.json

.github/dependabot.yml
Fixed #2124 
Added dependabot config blocks for `package.json` and `Dockerfile` for all microservices
=> Added dependabot configs for all services

src/web/src/components/NavBar/NavBarButton.tsx, src/web/src/components/NavBar/index.tsx, src/web/src/components/TelescopeAvatar.tsx
This PR fixes #1956
- Adds the `<TelescopeAvatar>` to the `<NavBar>`.
- Adds the logout functionality when the user clicks on the avatar.
- Adds the possibility of changing the `backgroundColor` and `color` of the `<TelescopeAvatar>`.
=> Issue 1956 - Add Avatar to the NavBar

src/web/src/components/Banner.tsx
Fixes #2149 
The landing page wasn’t displaying 100vh on mobile. This PR fixes this issue.
=> Fix landing page on mobile

src/web/src/components/SearchHelp.tsx
Fixes: #2051
Improve the color contrast and a bit of UI changes in search help.
**Before**:
**After**:
=> Improve color contrast in search help

src/web/src/components/Posts/Post.tsx
=> Remove outline on post title

src/api/users/jest.config.e2e.js, src/api/users/src/routes/users.js, src/api/users/test/e2e/users.test.js, src/api/users/test/e2e/utils.js
Co-authored-by: Josue <manekenpix@fastmail.com>
Fixes #2054
Fixes #2180 
This PR overhauls the unit tests for the users micro-service into proper e2e tests. The tests ensure that all the end-points are functioning as intended.
1. `gh pr checkout 2173` or checkout this branch if not using `gh`
2. `npm i`
2. `npm run services:start`
3. `npm run jest:e2e src/api/users/test/e2e`
=> Closes #2054: Fix users MS e2e tests

src/web/package.json, src/web/src/components/SignUp/Forms/BasicInfo.tsx, src/web/src/components/SignUp/Forms/GitHubAccount.tsx, src/web/src/components/SignUp/Forms/Overview.tsx, src/web/src/components/SignUp/Forms/RSSFeeds.tsx, src/web/src/components/SignUp/Forms/Review.tsx, src/web/src/pages/signup.tsx
Part of #2171 
This PR is fixing the most urgent problems related to the `SignUp` page styles.
=> Fix part of 2171 signup flow styles

src/web/src/components/Banner.tsx
=> Fix #2189 - Use correct font for version in header

src/web/src/components/PopUp.tsx
This PR fixes #2171
- Increased the `fontSize` of the `PopUp.tsx`
Before:
After:
=> This PR adresses #2171: Fix styles on SignUp page

src/api/feed-discovery/package.json, src/api/feed-discovery/src/middleware.js, src/api/image/package.json, src/api/image/src/routes/image.js, src/api/search/src/routes/query.js, src/backend/web/routes/feed.js, src/backend/web/routes/feeds.js, src/backend/web/routes/planet.js, src/backend/web/routes/posts.js, src/backend/web/routes/query.js, src/backend/web/routes/stats.js, src/backend/web/routes/user.js
This PR closes #1693
This PR closes #1928 
I've been wanting to close #1693 once we got our microservices fully launched, however, since the parser service won't be ready to launch yet, this issue is still relevant. I did an audit of all our asynchronous routes in our backend and had them all call the next middleware, passing in the error as well. Let me know if I missed any async routes and I'll update them quickly.
=> Fixes #1693: Audit of all asynchronous routes in backend folder

src/api/posts/README.md
Fixes #2229 
Fixed a typo from "Image Service to Posts Service" in the Readme file.
=> Fix: 2229 Updating  src/api/posts/Readme.md to fix typo

docs/git-workflow.md, package.json, tools/README.md
Fix #2224 
Removed links to add-feed link from tools/README.md , docs/git-workflow.md & package.json
=> Fix: 2224 Removed add-feed link from docs & package.json 

config/env.development, config/env.production, config/env.staging, docker/development.yml, src/api/users/README.md, src/api/users/env.local, src/api/users/src/server.js
User Service Port changed from 6666 to 7000
=> User Microservice Port from 6666 to 7000

src/web/src/components/BannerButtons.tsx, src/web/src/components/NavBar/index.tsx, src/web/src/components/Posts/Post.tsx, src/web/src/components/SearchPage.tsx, src/web/src/pages/_document.tsx, src/web/src/pages/index.tsx, src/web/src/pages/layouts/MDXPageBase.tsx
On an iPhone with notch, the bottom toolbar collides with the gesture pill. I really want to fix that so it's a more polished experience in mobile / PWA form.
=> fixes: iPhone padding insets in PWA

src/web/src/components/SignUp/Forms/Review.tsx, src/web/src/pages/signup.tsx
No open issue.
The idea of this PR is to make our code more readable, easy to understand.
=> Refactor  <Signup> Page code

src/web/src/components/ThemeProvider.tsx, src/web/src/theme/index.ts
It's seems there's been a change in `Material-UI`, and this change was causing our `dev` build to crash.
This PR fixes the issue.
=> Fix(front-end): change imports to prevent crashing while building

src/web/package.json, src/web/src/components/AboutFooter.tsx
Fixes #2278
What is happening: 
Running locally `npm i`, we install MUI version `4.11.3` while our CI/CD install MUI version `4.12.3`.
`4.11` and `4.12` versions have a different name convention regarding some MUI components we use(in this case, we are using their `<Grid>` component).
That's the reason why our snapshots are failing. 
I advise us to enforce MUI `4.11.3` instead of moving forward to `4.12.3` for now. 
Because: 
-Right now, we don't have enough people to cover our codebase and check if our front-end will render exactly as we expect with MUI `4.12.3`. 
-Since we only have two small snapshots tests in our front-end, and it will need a lot more tests, I don't see any reason to keep our CI/CD failing in those two snapshots for now. 
But we need to keep an eye on MUI because they …
=> Fix #2278: Classnames from snapshots created locally does not matches with the ones created on CI/CD.

src/web/src/components/BannerButtons.tsx
Bandaid solution until #2294 gets fixed.
=> Commented Sign up button as a bandaid solution

config/env.production, config/env.staging
USAGE: Fixes #2160 
This pull request fixes #2160 and removes unused env variables from traefik.
=> Closes #2160: Remove unused env variables

src/web/src/components/AuthProvider.tsx, src/web/src/components/SearchResults.tsx
This PR fixes 2 type errors that were causing the build process to crash:
```sh
./src/components/AuthProvider.tsx:105:58
Type error: Object is of type 'unknown'.
103 |   } catch (err) {
104 |     // TODO: should we do more in the error case?  If so, what?
> 105 |     console.error('Error parsing access_token from URL', err.message);
```
```sh
./src/components/SearchResults.tsx:66:12
Type error: Parameter 'u' implicitly has an 'any' type.
64 |   const { data, size, setSize, error } = useSWRInfinite(
65 |     (index) => (shouldFetch() ? prepareUrl(index) : null),
> 66 |     async (u) => {
```
=> fix: remove type errors to avoid crashing during build process

src/backend/utils/html/sanitize.js, test/sanitize-html.test.js
fixes #2306 
Allow embedded content from medium.com including Gist snippet.
=> Fix 2306: Allow embedded content from medium.com

tools/autodeployment/webhook.js
Closes #2312 
This adds a reference filter to our autodeployment server to make sure that deployments only take place when we push to master or when there's a new release.
=> Close #2312: Better filtering of GitHub webooks by autodeployment server

src/web/src/components/Posts/Timeline.tsx
=> [Timeline]: Fix margin issue

src/web/package.json
Fixes #2324 
This PR locks [react-icons](https://www.npmjs.com/package/react-icons) to `v4.2.0` until [this issue](https://github.com/react-icons/react-icons/issues/490) is fixed upstream
=> Fixes #2324: Cannot find module '../lib' from 'src/web/node_modules/react-icons/fa/index.js'

package.json
Fixes #2212
This PR removes `api:*` scripts in `package.json` file because they are no longer needed.
=> Fixes #2212 Remove api:* scripts if not needed

src/web/package.json
Closes #2329 
Bumped `react-icons` from 4.2.0 to 4.3.1
=> Closes #2329:  Update react-icons to v4.3.1

src/web/src/components/Posts/Commits.tsx, src/web/src/components/Posts/Issues.tsx, src/web/src/components/Posts/PullRequests.tsx
This PR closes #2374 
This PR adds additional information to indicate to the user where an issue or pull request comes from. Sentences are unoriginal, but the user will now know what repo an issue or PR comes from when hovering over the issue/PR number. 
This will also include the user as well
=> Closes Issue #2374: Include more details about issues and pull requests

src/web/src/components/TelescopeAvatar.tsx, src/web/src/theme/createPalette.d.ts, src/web/src/theme/index.ts
This PR closes #2449 
I added a border for telescope avatar, and the color does not stand out. 
<a href="https://gitpod.io/#https://github.com/Seneca-CDOT/telescope/pull/2450"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Fix #2449: add border for telescope avatar

src/api/status/src/server.js
Closes #2465 
Ran Prettier for the `src/api/status/src/server.js` file so we can pass CI
<a href="https://gitpod.io/#https://github.com/Seneca-CDOT/telescope/pull/2467"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Fixes #2465 fix prettier error in server.js file

docs/environment-setup.md
PR for issue [#2478](https://github.com/Seneca-CDOT/telescope/issues/2478)
The `environment-setup.md` had 2 incorrect links. It will not redirect you to the correct section.
<a href="https://gitpod.io/#https://github.com/Seneca-CDOT/telescope/pull/2484"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Fix broken links

src/api/auth/package.json, src/api/feed-discovery/package.json, src/api/image/package.json, src/api/planet/package.json, src/api/search/package.json, src/api/status/package.json, src/api/users/package.json
[issue-2438](https://github.com/Seneca-CDOT/telescope/issues/2438)- update the dependencies in package.json: 
Sharp: v0.29.1 -> v0.29.3
Nodemon: v2.0.7 -> v2.0.15
~~@senecacdot/satellite:  v1.16.0 -> v1.17.0~~ (Revert back the correct version from v1.17 -> v1.x)
Redo broken PR [#2438 ](https://github.com/Seneca-CDOT/telescope/pull/2482)
<a href="https://gitpod.io/#https://github.com/Seneca-CDOT/telescope/pull/2482"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
<a href="https://gitpod.io/#https://github.com/Seneca-CDOT/telescope/pull/2483"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> update sharp, nodemon and @senecacdot/satellite versions

src/web/src/components/NavBar/index.tsx
Fixes #2502 
- Added Index: 999 to navbar
https://user-images.githubusercontent.com/58233223/143072217-f77443b8-e2e8-4e35-bed5-af8b261c320e.mp4
=> Fixed navbar hides by post title header

src/api/status/public/index.html, src/api/status/public/js/github-stats.js
Fixes #2506 
Format:
```
(avatar) Luigi Zaccagnini 2dc6a97
```
=> Add commit link to latest contribution

docs/environment-setup.md
=> Fix broken link in docs

src/api/status/public/index.html
This PR fixes #2527 
- Remove duplication of the sidebar menu items.
=> menu duplication edited

package.json, src/api/parser/src/feed/worker.js, src/backend/index.js, src/backend/web/server.js, src/web/src/components/NavBar/NavBarButton.tsx
Manual upgrade of eslint-plugin-import from 2.22.1 to 2.25.3. #2544
=> bump eslint-plugin-import from 2.22.1 to 2.25.3

src/api/status/public/index.html, src/api/status/public/js/github-stats.js
This PR Closes #2507 
- Hide Dom element, if "Weekly Commits" is zero
=> issue#2507 solved

src/web/src/components/Posts/Post.tsx, src/web/src/components/Posts/PostInfo.tsx, src/web/src/components/Posts/ShareButton.tsx
=> Add share button for posts

src/web/src/student-quotes.js
I've pulled out some great quotes to add to our list while I was marking 0.2, 0.3.
=> Add more student quotes

.eslintrc.js, package.json
Closes #2533.
Plugin also added to Satellite through: https://github.com/Seneca-CDOT/satellite/pull/21
Adding [anti-trojan source plugin](https://github.com/lirantal/eslint-plugin-anti-trojan-source) to Telescope
=> Adding anti-trojan-source plugin to eslint

src/web/src/components/Posts/Post.tsx, src/web/src/components/Posts/Timeline.tsx, src/web/src/components/SearchResults.tsx
=> added post count in search

src/web/src/student-quotes.js
I loved this quote by @ycechungAI.
=> Add quote from Eugene Chung

docker/docker-compose.yml
Fixes #1897 
I update Elasticsearch version from 7.9.3 to 7.14.2 in docker-compose.yml file.
=> Upgrade Elasticsearch 7.14.2 in docker-compose.yml

pnpm-lock.yaml, src/web/package.json, src/web/src/components/Banner.tsx, src/web/src/components/Posts/Post.tsx, src/web/src/styles/telescope-post-content.css
This fixes some responsiveness issues in the frontend:
- Truncate post title at 2 lines
- Fluid post title
- Smaller code block padding on mobile
- Smaller code block and inline code font-size
before          |  after
:-------------------------:|:-------------------------:
before          |  after
:-------------------------:|:-------------------------:
=> Fix some responsive  issues

src/api/status/public/css/site.css, src/api/status/public/js/utils/toast.js, src/api/status/scss/material-dashboard/bootstrap/_toasts.scss, src/api/status/src/views/layouts/main.hbs, src/api/status/src/views/partials/_toast.hbs
Closes #2588 
- `toast.js` exposes a single method `showToast` to show different kinds of notifications to users.
- HTML and JS for toast are added globally to all the pages.
https://user-images.githubusercontent.com/52666982/145652785-6219434d-0b4e-4b9c-91e2-313382935de7.mp4
- Go to src/api/status/public/js/toast.js
- At the end of the file, invoke as many `enqueueToast` as you like
```js
// toasts.js
showToast("Hello world", "info");
showToast("Help!", "danger");
```
=> Fixes #2588: add helper to display toasts

docker/development.yml, docker/docker-compose.yml, src/api/status/env.local, src/api/status/src/js/feed-stats.js, src/api/status/src/js/github-stats.js, src/api/status/src/js/posts-stats.js, src/api/status/src/redis.js, src/api/status/src/server.js, src/api/status/src/views/partials/sidebar.hbs
Related #2553 
Fixes #2592
- Add `STATUS_URL`, `POSTS_URL`, `POSTS_PORT` environment for status microservice
- Using `STATUS_URL` to check if production or staging.
- Change fetch URL for the total post, total feed.
- Change sidebar root link from `/` to `/v1/status`
1. `pnpm run services:start`
2. Go to the link `http://localhost/v1/status`
1. `pnpm run services:start posts`
2. `cd .\src\api\status\`
3. `pnpm run dev`
4. Go to the link `http://localhost:1111/v1/status/`
5. Add cache for github info (cache for 10 min)
=> Fix fetch url between microservices + Fix sidebar root path links + cache github info

docker/docker-compose.yml
Fixes #2597 
Update Elasticsearch  from 7.14.2 to 7.16.1 in docker-compose.yml file.
=> Upgrade Elasticsearch to version 7.16.1

.github/workflows/e2e-tests-ci.yml, .github/workflows/eslint-ci.yml, .github/workflows/node-js-ci.yml, .github/workflows/prettier-ci.yml, .github/workflows/release.yml, .github/workflows/unit-tests-ci.yml
Closes #2602 
Created the following reusable workflows after refactoring `node-js-ci.yml` and `release.yml`:
- `.github/workflows/e2e-ci.yml`
- `.github/workflows/eslint-ci.yml`
- `.github/workflows/prettier-ci.yml`
- `.github/workflows/unit-tests-ci.yml`
Note: The repo URL for referencing the reusable workflow in `uses` is set to my fork as that is where the files currently reside. This will be changed to `Seneca-CDOT/telescope` once the pr is ready for a merge.
Running as expected after testing the runs on my fork:
=> Refactoring workflows to have reusable jobs

src/api/status/public/css/terminal.css, src/api/status/public/js/build-log/terminal.js, src/api/status/src/views/builds.hbs
Closes #2587 
Add a button to copy all the current content of the terminal to user's clipboard.
https://www.awesomescreenshot.com/video/6482705?key=d5fca93e575c13972ea6e453729c0817
- Add this line to `src/api/status/public/js/build-log/terminal.js`
```js
terminal.write(`Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia consectetur nihil dolore accusamus accusantium eius tempora, magnam, error inventore consequuntur quisquam, at unde fuga. Natus deleniti minus animi iure laudantium?
A
quae libero
inventore provident
quisquam,
suscipit corporis odit vero consequatur doloremque nam! Ea iusto deserunt fugit rem debitis, vero obcaecati, magni saepe ipsum incidunt ex, ad maiores unde asperiores.
Nobis quis a doloribus odit nulla aliquid sapiente velit, consequuntur molestiae illo …
```
=> feat: add button to copy content from dashboard terminal

pnpm-lock.yaml, src/web/package.json
Closes #2610 
Update `swr` to 1.1.1.
=> Fixes #2610: update swr to 1.1.1

src/web/src/components/AboutFooter.test.tsx, src/web/src/components/__snapshots__/AboutFooter.test.tsx.snap
Closes #2639 
This PR updates the year to 2022 in `AboutFooter` snapshot and mocks the Date function so we don't repeat the issue next year.
=> Update AboutFooter snapshot and mock Date function

.github/renovate.json
Follow-up of https://github.com/Seneca-CDOT/telescope/pull/2640#issuecomment-1004404158.
This overrides the range strategy of Satellite to `replace` to  replace the range with a newer one if the new version falls outside it, and update nothing otherwise.
https://docs.renovatebot.com/configuration-options/#rangestrategy
=> Make renovate use semver for Satellite

src/web/src/components/Posts/Users.tsx
This PR resolves #2627 
Just a simple naming change to how we represent multiple users/orgs when mentioned in a blog post. Delayed mainly due to taking it during the holidays and covid :( (Doing amazing right now though)
=> Fixed Issue #2627: Changed naming of Users to Users/Org

jest.config.base.js
Fixes issue #2642 -- Bumping up to __20 second times out.__
=> Bump up to 20s time out

src/api/status/src/services.js
Fixes #2663 
Add an status checks for the auto deployment server.
=> Add autodeployment server to the status checks

src/web/src/components/Banner.tsx
This PR adds a link to the planet version of Telescope
=> feat: add link to planet version of telescope

src/web/src/components/Banner.tsx
Fixes #2452 
Following the discussion in https://github.com/Seneca-CDOT/telescope/discussions/2448, this PR removes the scroll snap feature from the telescope homepage.
=> Fixes #2452: Remove scroll snap from homepage

.github/workflows/release.yml, docs/release.md
This fixes #2696 
- Removed unnecessary tests in `release.yml` to make releasing telescope faster. 
- Edited `release.md` to reflect on this change
=> Removed unnecessary tests in release.yml

src/web/src/components/Posts/PostAvatar.tsx
=> Remove any non alphabetical character from avatar initials

src/api/status/src/server.js
Hotfix for #2763 
Correct syntax of calling logger in the dashboard.
=> fix: logger should not crash the server on error

tools/autodeployment/builds.js, tools/autodeployment/webhook.js
Fixes #2697, possibly #2650? (cc @tcvan0707).
=> Better SHA extraction from GitHub webhook payloads

src/api/feed-discovery/README.md
I was asked to update the README file in feed-discovery in order to test the [PR I just merged](https://github.com/Seneca-CDOT/telescope/pull/2784)
=> Updated all `npm` in feed-discovery readme to be `pnpm`

src/api/status/public/assets/js/material-dashboard.min.js
Fixes #2691 
When you resize the window some of the css that's applied through javascript is looking for a value that's not there. To avoid the issue I used optional chaining. If the classList does not exists, it will not show the error and skip over it.
1. `cp config/env.staging .env`
2. `cd ./src/api/status`
3. `pnpm dev`
4. Navigate to [port ](http://localhost:1111/v1/status/build)
5. To replicate the issue, you resize the page here, please open your dev tools and navigate to console to check the error is no longer there.
=> Issue 2691 - Build dashboard error resizing

pnpm-lock.yaml, src/api/status/env.local, src/api/status/package.json, src/api/status/src/js/github-stats.js, src/api/status/src/js/octokit.js
Closes #2658 
- Setup octokit and plugins
- Replace `fetchGithubApi` with octokit
- Add `GITHUB_TOKEN` for octokit auth
- Run the dashboard at src/api/status
- All the stats should be the same as https://dev.api.telescope.cdot.systems/v1/status
=> Fixes 2658: Add octokit to dashboard

src/api/image/Dockerfile
Fixes: #2745
Changed our docker to use `pnpm` instead of `npm`
- `pnpm services:start image`
=> Change image microservices to pnpm

src/api/status/public/css/terminal.css, src/api/status/scss/material-dashboard/_navbar-vertical.scss, src/api/status/src/views/builds.hbs
Fixes #2611 
Make the build log more responsive by using flex.
https://user-images.githubusercontent.com/77639637/152198151-3c9eb3c3-9eb4-4c4f-91ab-cf80e2e7741c.mp4
Running dashboard front end
1. `pnpm i`
2. `cp config/env.staging .env`
3. `cd ./src/api/status`
4. `pnpm dev`
go to http://localhost:1111/build
or go to deployed version and navigate to the build log. You dont need to see a build, to see the changes.
=> Issue-2611: Responsive Build Log

src/web/src/components/Posts/GitHubInfo/Repos.tsx
Fixes #2778 
This PR fixes the the horizontal overflow for the desktop sidebar that was introduced by the addition of `display: 'flex'` used for the mobile view.
=> Fix horizontal overflow in sidebar

src/api/status/public/js/build-log/check-for-build.js
Fix #2815 
- Use `terminal.scrollToBottom()` to scroll to the bottom of the terminal to display new changes.
To run build log locally, change autodeploymentUrl in src\api\status\public\js\build-log\check-build-status.js
```js
const autodeploymentUrl = (path) => `//dev.telescope.cdot.systems/deploy${path}`;  
````
Allow all connectSrc in src\api\status\src\server.js
```
```
Go to `http://localhost/v1/status/build`
=> Make terminal scroll to bottom to display latest changes

.github/ISSUE_TEMPLATE/active-project.md, .github/ISSUE_TEMPLATE/new-project.md
Fixes #2802 
Adds a new template that will help documenting projects.
=> [Docs] Add template for an ongoing project

.github/renovate.json
Change renovate schedule to test if deleting `renovate/babel-monorepo` branch fixes #2852.
=> Change renovate schedule to after 6pm daily

.github/renovate.json
Reverts Seneca-CDOT/telescope#2872
Change back to `weekend`
=> Revert "Change renovate schedule to after 6pm daily"

pnpm-lock.yaml, src/docs/package.json
VSCode is unhappy with how we import these types.  This adds the type definitions.
=> Fix missing import of @docusaurus/types

src/docs/docs/getting-started/environment-setup.md
Fixes #2882 
This PR updates the environment-setup doc to separate install instructions by operating systems.
It also removes the table of content at the top.
Change directory to /src/docs: `cd src/docs`
Start the server: `pnpm start`
Visit [localhost:4631](http://localhost:4631/) in your browser
=> Use Docusaurus tabs for each OS in environment-setup

src/web/src/components/AboutFooter.tsx, src/web/src/components/__snapshots__/AboutFooter.test.tsx.snap
Fixes: #1608 
Since we cannot control the accessibility of blog posts, this PR improves the accessibility of our About page.
Based on Google Lighthouse, I fixed the following issues:
- [Links do not have a discernible name](https://web.dev/link-name/)
- [Heading elements are not in a sequentially-descending order](https://web.dev/heading-order/)
- [Tap targets are not sized appropriately](https://web.dev/tap-targets/)
The new Accessibility and SEO results on both Desktop and Mobile are now 100%:
=> Improve accessibility of About page

pnpm-lock.yaml, src/docs/docusaurus.config.js, src/docs/package.json
Fixes #2885
This PR adds the last update author and date of each doc
3. Checkout my branch: `git checkout issue-2885`
4. Install dependencies using pnpm in root (this will also install dependencies in src/docs: `pnpm install`
5. Change directory to /src/docs: `cd src/docs`
6. Start the server: `pnpm start`
7. Visit localhost:4631 in browser
8. Find any doc on the left-hand side and scroll down to the bottom to see the '_Last updated on **10/14/2018** by **Author**_'
=> Fixes #2885 add showLastUpdateAuthor and showLastUpdateTime to Docusaurus config

README.md
Fixes #2871
Because of #2869, all the links in the README.md were stale and invalid. This PR updates those links to the new location (`src/docs`).
There's no need to pull changes whatsoever, just check that the links in the README.md are valid.
=> Update README.md to link to new docs location

src/web/package.json
Fixes #2816 
reorganize properties in web/package.json
=> Fixes #2816 reorganize properties in web/package.json

src/api/sso/src/middleware.js, src/web/src/components/SignUp/Forms/GitHubAccount.tsx, src/web/src/components/SignUp/Forms/Review.tsx, src/web/src/components/SignUp/Schema/FormSchema.tsx, src/web/src/pages/signup.tsx
Fixes #2886 
- `docker-compose build sso nginx && docker-compose up -d`
-  Go to http://localhost:8000/ to sign up using a test account `user1`:`user1pass`
- Finish the registration flow and see the new user created in `http://localhost:8910/project/default/editor` -> `telescope_profiles`
=> SignUp: Update account registration request

.gitpod.Dockerfile
=> Remove installing pnpm from gitpod workspace init

src/api/status/public/js/build-log/check-build-status.js, src/api/status/public/js/build-log/check-for-build.js, src/api/status/public/js/utils/toast.js
Fixes #2718 
We use the `toast` utilities to display messages in the screen for feedback.
1. Get my local changes
2. Go to `src/api/status`
3. Start with `pnpm dev`
4. Go to `localhost:1111/build`
5. You should see a small yellow box that says something along the lines of "Build information missing".
=> Add alert toast

pnpm-lock.yaml, src/api/status/package.json, src/api/status/src/server.js, src/backend/web/routes/health.js
This PR closes #2854 
When looking at Telescope in development build, the git `sha` remained undefined, even though we fixed it for staging and production. The health route in the backend was the root cause, since it's the backend that's used as the `API` route in the local telescope build. This PR defaults the sha to point to the current commit on the master branch.
The link that points to the current `sha` should point to the current commit on master. It shouldn't have any specific sha hash, but should refer to master only.
=> Default health check to master in development

src/docs/docs/api-services/api.md, src/docs/docs/getting-started/environment-setup.md, src/docs/docs/tools-and-technologies/login.md, src/docs/docs/tools-and-technologies/pino.md, src/docs/docs/tools-and-technologies/renovate.md
=> Fixes #2943 fix broken links that prevent Docusaurus website from building

src/api/Dockerfile
Fixes #2803 
A draft version of how to have a base file in docker
Need feedback if I'm doing the docker thing correctly.
**Note:** CI will fail.
- `cd src/api/`
- `docker build --tag telescope-service-base  . ` (Create a image call telescope-service-base)
- Change a services like image ` src\api\image\Dockerfile`
```DockerFile
FROM telescope-service-base:latest as deploy
WORKDIR /ome/node/app
COPY --chown=node:node . /home/node/app/
RUN pnpm install --prod
CMD ["node", "src/server.js"]
```
- ` cd ../../` (back to root workspace)
- `pnpm services:start image` (It should start image services and use the local image called telescope-service-base)
=> Add base-install docker image

config/env.development, docker/development.yml, docker/supabase/docker-compose.yml, src/api/sso/test/e2e/utils.js
Fixes: #2791 
Expose kong to `v1/supabase`
- `gh pr checkout 2931`
=> Expose kong via Traefik

tools/autodeployment/deploy.sh
This injects a random UUID string as our JWT_TOKEN when we deploy.  It will mean that our JWT_TOKEN won't be empty when we launch the containers on staging and production.
Later, we should employ a better secrets management technique.
=> Use random UUID for JWT_TOKEN on every deploy

tools/autodeployment/deploy.sh
=> changed deploy script env variable JWT_TOKEN -> JWT_SECRET

src/docs/.dockerignore, src/docs/Dockerfile
Fixes #2865
As per Slack
> @TDDR: @cindyledev, no pressure, but will you be able to submit a PR today for the work you have done on https://github.com/Seneca-CDOT/telescope/pull/2942?
Note: This PR only Dockerizes Docusaurus, this does not touch any of the nginx requirements. We can file another issue to address the nginx requirement or help me get the nginx working in this PR.
3. Checkout my branch: `git checkout issue-2865`
4. Change directory to src/docs: `src/docs`
To run `development` layer of the docker container:
1. Build the container but only up to the `development` layer, name it `docs` and tag it as …
=> Fixes #2865 dockerize Docusaurus

src/backend/utils/html/sanitize.js, src/backend/web/app.js, test/sanitize-html.test.js
This PR closes #2897
This PR adds twitch to the list of sites that won't be sanitized by our html sanitizer. This should allow for posts that include twitch links to be viewed on telescope posts.
Simply check for any post that contains a twitch video included in their blog post. The most recent one was one by @sirinoks on February 11th, 2022 titled, "Telescope stream"
=> Added twitch to allowed sites to be sanitized

src/api/search/jest.config.js
=> Fix typo src.api to src/api

src/docs/docs/contributing/staging-production-deployment.md
Fixes #3036 
Added GITHUB_TOKEN to the deployment documentation
- make sure the document reads correctly
=> Updated deployment documentation to include GITHUB_TOKEN

src/docs/Dockerfile, src/docs/docusaurus.config.js
Fixes #3046
- add `RUN pnpm build` to the Production layer in the Docusaurus Dockerfile
- update the docusaurus config to ignore broken links. These broken links are causing `pnpm build` to throw, broken links are not a major problem so we can just ignore them. Once Docusaurus is accessible on staging/production, we will change the links to URLs to the docs instead of relative links to the file anyway.
3. Checkout my branch: `git checkout issue-3046`
4. Change directory to src/docs: `src/docs`
To run `development` layer of the docker container:
1. Build the container but only up to the …
=> Fixes #3046 Add pnpm build to Production layer in Docusaurus Dockerfile

pnpm-lock.yaml, src/api/dependency-discovery/package.json, src/api/feed-discovery/package.json, src/api/image/package.json, src/api/parser/package.json, src/api/planet/package.json, src/api/posts/package.json, src/api/search/package.json, src/api/sso/package.json, src/api/status/package.json, tools/autodeployment/package.json
Updates to pick up @rclee91's fix in https://github.com/Seneca-CDOT/satellite/pull/64.
=> Update Satellite to 1.26.0 in all packages

src/docs/docs/contributing/CONTRIBUTING.md
Fix #3091
Changed relative paths for Architecture and Develop on Gitpod to current ones.
- Go to my repo 
- Select 3091 branch
- Click on links for Architecture and Develop on Gitpod
=> Fix links for contributors documentation

README.md
Fixes #1726 
This PR adds a Renovatebot badge to our README.
1. Go to the `issue-1726` branch in my repo
2. You should be able to see the Renovatebot badge
=> Add Renovatebot badge

pnpm-lock.yaml, src/api/status/.eslintrc.js, src/api/status/package.json, tools/eslint/index.js
#2999 
The `ESlint` setting for dashboard has been move to it's sub-project.
1. 'pnpm install`
2. `pnpm lint`
=> Reconfig ESlint for dashboard sub-project

src/docs/docs/tools-and-technologies/nextjs.md
Fixed #3131
Missing import statement has been added, to fix the break when building. 
It was added in the `src/docs/docs/tools-and-technologies/nextjs.md` file
run `pnpm build` in `src/docs`directory
=> import Fragment from react

test/.eslintrc.js, tools/eslint/index.js
=> Reconfig Eslint for test sub-project

tools/autodeployment/README.md
Fixes #2546 
This PR updates the documentation detailing the new routes for the autodeployment server.
Nothing to test here... 👀
=> Update docs for autodeployment routes

pnpm-lock.yaml, src/api/dependency-discovery/package.json
This PR removes `workspace:` to use the `@senecacdot/eslint-config-telescope` package from the registry in CI.
=> Change eslint-config-telescope dependency from local to registry

jest.config.js
Fixes #3145 
This PR adds Satellite to `jest.config.js`.
=> Add Satellite to Jest config

src/docs/docs/tools-and-technologies/react-native.md
Fixed #3102 
Adding `expo upgrade` and `expo doctor` in `react-native.md` doc
=> Adding usefull Expo CLI in react-native.md

src/docs/docusaurus.config.js, src/docs/i18n/vi/docusaurus-plugin-content-docs/current/overview.md
Fixes #2962 and #2922 
This PR is a Vietnamese translation for the about page in Telescope.
- Change the current directory to `src/docs`: `cd src/docs`
- Run `pnpm start -- --locale vi`
=> Vietnamese translation for the About page

src/api/image/unsplash-photos.json
Fixes #2982.
I've added the (extremely small number of) images people posted in #2982.
=> Add new Unsplash images

src/satellite/src/satellite.js, src/satellite/test.js
Fixes #3148 
- Add shutdown() functions to Satellite.stop()
- Change Elastic mock to reinitialize beforeEach
=> Change stop method to close all db connections

src/api/search/src/bin/validation.js, src/api/search/src/routes/query.js, src/api/search/src/search.js, src/api/search/test/query.test.js, src/web/src/components/SearchResults.tsx
Fixes #2618 
In https://github.com/Seneca-CDOT/telescope/pull/2617 we added an advanced route. The advanced route is more flexible for search terms and capabilities. In this PR I changed the route used in the search results so that we use the new "advanced" route. In another PR I will clean up the regular search as we are now leveraging the more advanced route - and will be the main route meaning no more `/advanced` it will be `/`
- `cp config/env.development .env`
- `docker-compose --env-file ./config/env.development up --build search elasticsearch redis posts nginx planet`
1. Go to search and select author search an author - look in the network tab for dev tools, you will see the results coming from the new route.
2. Do the same with posts.
=> Fixes-2618: Refactor search routes

.github/workflows/deploy-feed-discovery-image.yaml, src/api/feed-discovery/README.md
Update push registry to use our docker.cdot.systems docker registry
=> Update push registry for feed-discovery CI

jest.config.base.js, jest.config.js, pnpm-lock.yaml, src/api/dependency-discovery/jest.config.js, src/api/dependency-discovery/jest.setup.js, src/api/feed-discovery/jest.config.js, src/api/parser/jest.config.js, src/api/posts/jest.config.js, src/satellite/jest.config.js, src/web/jest.config.js, test/jest.config.js
This has Satellite use our Jest config.
I've also turned-down the logging in tests.
Partially deals with #3175.
=> Integrate Satellite tests with jest config

docker/gitpod.yml
Fixes #3201 
[*holy-grail branch*](https://github.com/Seneca-CDOT/telescope/pull/3185) officially let Telescope pull the image from our Docker Registry
Adding this to `gitpod.yml` since the aws-ip.sh
https://github.com/Seneca-CDOT/telescope/blob/ca4b9133fa98f4bbfe7ce266247d07eb97c4f71e/tools/aws-ip.sh#L10
also uses the gitpod stuff
Follow [vscode-ssh.md](https://github.com/Seneca-CDOT/telescope/blob/master/src/docs/docs/getting-started/vscode-ssh.md) and you shouldn't hit the error
=> Fixes #3201 add feed-discovery image to gitpod.yml

pnpm-lock.yaml, src/api/image/.eslintrc.js, src/api/image/package.json
=> Set up ESLint for image service

tools/eslint/package.json
Update `@senecacdot/eslint-config-telescope` to pick up the latest changes.
=> Update @senecacdot/eslint-config-telescope to v1.0.1

src/api/status/.dockerignore, src/api/status/Dockerfile
```bash
❯ docker images | grep refactor/status
refactor/status                                 old                429d3bbd63d3   5 seconds ago       268MB
refactor/status                                 new                638e5f69af08   14 minutes ago      230MB
```
- `pnpm services:start status`
=> Refactor Dockerfile status

src/api/feed-discovery/.dockerignore, src/api/feed-discovery/Dockerfile
```bash 
❯ docker images | grep refactor/feed
refactor/feed-discovery                         old                9d6bb297c608   10 minutes ago      147MB
refactor/feed-discovery                         new                ad37fef3661a   12 minutes ago      148MB
```
- `cp .\config\env.development .env`
- Go to `localhost/v1/feed-discovery/healthcheck`
=> Refactor Dockerfile feed-discovery

src/api/posts/.dockerignore, src/api/posts/Dockerfile
```bash
❯ docker images | grep refactor/posts
refactor/posts                                  old                c91fc75d9311   22 minutes ago   164MB
refactor/posts                                  new                38493354c651   22 minutes ago   149MB
```
Option 1:
- `cp .\config\env.development .env`
- `pnpm start`
- go to `localhost:8000` to see post  or `localhost/v1/posts` to see post via API
Option 2:
- go to `docker\development.yml` 
- Add this below
```yml
posts:
ports:
- '5555:5555'
```
- `pnpm services:start posts`
- go to `localhost:5555`
=> Refactor Dockerfile posts

src/api/dependency-discovery/.dockerignore, src/api/dependency-discovery/Dockerfile
Fixes #1668
```bash
❯ docker images | grep refactor/dep
refactor/dependency-discovery                   old                d8f8d2d83153   2 hours ago      145MB
refactor/dependency-discovery                   new                96d9269317c7   4 hours ago      146MB
```
- `cd src/api/dependency-discovery`
- `docker build -t dependency-discovery:test .`
- `docker run --rm -p 10500:10500 dependency-discovery:test`
=> Refactor dependency-discovery dockerfile

src/api/planet/.dockerignore, src/api/planet/Dockerfile
```bash
❯ docker images | grep refactor/planet
refactor/planet                                 new                7cb26d3cca78   25 minutes ago       150MB
refactor/planet                                 old                4bc27dcd95d0   2 hours ago          148MB
```
- `cd src/api/planet`
- `docker build -t planet:test .`
- `docker run --rm --env-file env.local -p 9876:9876 planet:test `
=> Refactor Dockerfile planet

src/api/image/.dockerignore, src/api/image/Dockerfile
```bash 
❯ docker images | grep refactor/image
refactor/image                                  new                2a9dc04a8710   2 minutes ago    169MB
refactor/image                                  old                1155c517a2ba   5 minutes ago    206MB
```
- `cd src/api/image`
- `docker build -t image:test .`
- `docker run --rm -p 4444:4444 image:test `
=> Refactor Dockerfile image

src/api/search/.dockerignore, src/api/search/Dockerfile
```bash
❯ docker images | grep refactor/search
refactor/search                                 new                0558d43ff0a2   11 minutes ago   146MB
refactor/search                                 old                091a0944b2c5   13 minutes ago   142MB
```
- `pnpm services:start search`
=> Refactor Dockerfile search

pnpm-lock.yaml, src/docs/package.json
Related to #3208
- moves `devDependencies` underneath `dependencies` for better legibility
- installs `@algolia/client-search`, `@types/react`, `typescript`, and `unist-util-visit` because they are listed as missing dependencies
- downgrades `mermaid` from v8.14 to v8.11 because v8.14 is not the version `mdx-mermaid` needs.
3. Checkout my branch: `git checkout issue-3208-b`
5. You should not see:
```
src/docs
├─┬ @docusaurus/core
│ └─┬ react-dev-utils
│   └─┬ fork-ts-checker-webpack-plugin
│     └── ✕ missing peer typescript@">= 2.7"
├─┬ …
```
=> Fixes #3208 install missing deps in src/docs

pnpm-lock.yaml, src/api/posts/.eslintrc.js, src/api/posts/package.json
=> Set up ESLint for post service

pnpm-lock.yaml, src/api/posts/package.json
Related to #3208
- installs `redis-commands` because it is listed as missing dependency
3. Checkout my branch: `git checkout issue-3208-c`
5. You should not see:
```
src/api/posts
└─┬ ioredis-mock
└── ✕ missing peer redis-commands@1.x
Peer dependencies that should be installed:
redis-commands@1.x  
```
Note: Depending on your OS, you may or may not even see these warnings. I get these warnings using AWS EC2 Amazon Linux 2 AMI. Also if you do not see the errors on the `master` branch, try deleting the `pnpm-lock.yaml` file.
=> Fixes #3208 install missing peer deps in posts microservice

config/env.production, config/env.staging, docker/development.yml, docker/docker-compose.yml, docker/production.yml
USAGE: #3189 This is just the first part of the issue.
Still need to do the following in a separate PR :
This is the the first step for issue #3189. Will make separate issues for the remainder?
This is not testable yet due to needing environment variables passed.
=> Migrating to use docker.cdot.systems based images

pnpm-lock.yaml, src/api/parser/.eslintrc.js, src/api/parser/package.json, src/api/parser/src/utils/html/sanitize.js, src/api/parser/src/utils/wiki-feed-parser.js
=> Set up ESLint for parser service.

pnpm-lock.yaml
pnpm-lock was not updated, we need to keep it updated.
=> Updated pnpm-lock for releasing

src/docs/docs/overview.md, src/docs/i18n/vi/docusaurus-plugin-content-docs/current/overview.md
Fixes #3180 
This PR is going to update the Overview page of Telescope by removing broken links, and adding the alternative source for our Planet.
- Change your current directory to /src/docs: `cd src/docs`
- Run `pnpm start`
- Go to `localhost:4631` on your web browser
=> Update Telescope overview and remove broken links

.github/workflows/e2e-tests-ci.yml
- Add elasticsearch redis posts traefik to `e2e-tests-ci.yml`
=> Add more containers to E2e ci 

pnpm-lock.yaml, src/api/planet/.eslintrc.js, src/api/planet/package.json
=> Setup Eslint for Planet

pnpm-lock.yaml, src/api/search/.eslintrc.js, src/api/search/package.json
Fixes #3160 
pnpm install
pnpm lint
=> Setup Eslint for search

tools/autodeployment/webhook.js
Fixes #3189 
This is a follow up to PR #3285. After testing it on staging we found a few bugs. These are the fixes to those bugs.
=> Fixed bugs found in autodeployment after testing on staging

pnpm-lock.yaml, src/api/sso/.eslintrc.js, src/api/sso/jest.config.e2e.js, src/api/sso/package.json
Fixes #3155 
Fix the `Eslint` configuration for `SSO` files.
pnpm install
pnpm lint
=> Setup Eslint for SSO

pnpm-lock.yaml, src/api/feed-discovery/.eslintrc.js, src/api/feed-discovery/package.json, src/api/feed-discovery/src/middleware.js
#3161 
Setting up the `Eslint` for `feed-discovery` and fix some lint error.
Lint errors:
1. Dependencies not listed in package.json:
Fix: adding the dependencies to the `devDependencies` list. 
2. calling the `new` operator without assigning to a variable:
Fix: Created a function that will return the URL if the URL is valid, if not throws an error.
pnpm install
pnpm lint
=> Eslint for feed-discovery and fix lints

config/env.development, config/env.production, config/env.staging
#2979 
Since docker secrets require that we use docker swarm, the current solution for storing secrets is creating a seperate secrets.env file for staging/production.
env.development will still maintain secrets for development, but they have been removed from staging/production
=> Reorganize Secrets

src/api/planet/Dockerfile
=> Use node instead of pnpm in planet Dockerfile

tools/autodeployment/deploy.sh
Apparently we can't use multiple `--env-file` args to `docker-compose`.  This appends the secrets to the env file instead, like we do with a few other things.
=> Use single env-file in deploy.sh, append secrets instead

.github/workflows/docker-build-and-push.yml, config/nginx.conf.template
Fixes #3397 
This PR adds Docusaurus at `/docs` to `config/env.development` and fixes the job context in `.github/workflows/docker-build-and-push.yml`.
=> Add Docusaurus to production. Fix docker-build-and-push

src/api/parser/src/index.js, src/api/status/src/services.js
Fixes #3362 
- Run a Satellite instance to provide healthcheck route
- `pnpm install`
- `docker ps`
- Check for `telescope_api_parser`'s status
=> Run a Satellite instance to provide healthcheck route

src/web/docusaurus/docs/overview.md, src/web/docusaurus/docusaurus.config.js, src/web/docusaurus/src/css/custom.css, src/web/docusaurus/src/pages/index.js
Fixes #3396
This PR makes the following changes to the docs:
- Fix `/docs/docs` path.
- Make "Telescope Overview" the first item in the table of content.
- Disable languages that do not have translation yet to speed build time (We will re-enable them as the translations come in).
- Update docs colours to the Telescope palette.
=> Fix Docusarus path, update colours

src/api/status/src/services.js
Fixes #2829
This PR adds the remaining healthcheck filed in #2829, which is the healthcheck for the docusaurus web site.
1. Pull my changes.
2. Start the status services (`pnpm run services:start status`).
3. Check the index page; you should see a check for Docusaurus on green.
=> Add docusaurus healthcheck

.github/workflows/e2e-tests-ci.yml, .github/workflows/eslint-ci.yml, .github/workflows/mobile-deploy.yml, .github/workflows/pnpm-lock-check-ci.yml, .github/workflows/pnpm-publish.yml, .github/workflows/prettier-ci.yml, .github/workflows/unit-tests-ci.yml
=> Update pnpm version in CI

src/web/app/src/components/SearchBar.tsx, src/web/app/src/components/SearchResults.tsx
Fixes #3428 
Added the input UI for title in the advanced search tray. In addition, I added code to allow the search by title. 
1. `pnpm i`
2. `cp config/env.staging .env`
3. `pnpm run dev`
=> Issue 3428: Search by Title in Advanced Search

src/api/status/src/views/partials/contributionCard.hbs
#2961 
Adds cross origin attribute to img element to fix cross-origin-resource-policy
- `cd src/api/status`
- `pnpm dev`
- navigate to http://localhost:1111
=> Fix contributor card avatar in status service

src/web/app/src/components/SearchBar.tsx, src/web/app/src/components/SearchInput/SearchInput.tsx, src/web/app/src/components/SearchResults.tsx
Fixes #3394 thanks to @JerryHue 
This PR should allow us to submit search fields by hitting "enter" key on our keyboards.
There is a huge clash between this code and the autocomplete. I will submit this to remove the problem with the other fields(title/post), but need to collaborate with @rclee91 and figure out efficient way to make these inputs work with the autocomplete. 
`pnpm i`
`cp config/env.stage .env`
`pnpm run dev`
NOTE: There is no autocomplete for author
=> Searchbar on Enter

src/web/app/src/components/AboutPage.tsx
Fixes #3308 
Updated About us to explain what Telescope does, rather than focus in on what it copies. It's only a text change, no code, so things shouldn't break.
- `npm install`
- `cp config/env.staging .env`
- `npm run dev`
- Click on "About us" and see the changes!
Sorry this took so long, I had it ready on weekends but I was stuck on making a PR..
=> About us updated

src/api/sso/src/middleware.js, src/api/sso/test/e2e/signup-flow.test.js
#2909
Closed PR #3319  .Reopening it.
=> Test for using existing URL feed and fix feed typo

src/web/docusaurus/docs/api-services/posts.md
This PR closes #3293
This PR adds documentation for all routes for the posts service. Based on #1907, I decided not to include the feeds routes in the documentation. This can be added if needed however until documentation for the parser service is complete.
No testing required, simply leave feedback on whether I got everything here related to the posts service's routes
=> Resolves #3293: Posts Service Documentation

docker/supabase/supabase-development.yml, pnpm-lock.yaml, src/api/sso/package.json, src/api/sso/src/middleware.js, src/api/sso/test/e2e/row-level-policies.test.js, src/api/sso/test/e2e/supabase-util.js, src/db/prisma/migrations/20220412190044_drop_default_hash_id/migration.sql, src/db/prisma/migrations/20220412190951_add_unique_constraint/migration.sql, src/db/prisma/schema.prisma
Drop the default value for Feeds hash ids now that all feeds have an id
=> Drop default hash value

src/api/dependency-discovery/src/dependency-list.js, src/api/dependency-discovery/src/github.js, src/api/dependency-discovery/test/dependency.test.js
Fixes #3495
- Add issuesURL field for the GitHub issue URL in the return JSON of /projects/:namespace/:name route.
1. `cd .\src\api\dependency-discovery`
2. `pnpm dev`
3. Call the API at route `/projects/:namespace/:name?`
=> Add issuesURL field in /projects/:namespace/:name? route

src/api/parser/test/indexer.test.js
Fixes #3224 
Add unit tests for [src/api/parser/src/utils/indexer.js](https://github.com/Seneca-CDOT/telescope/blob/master/src/api/parser/src/utils/indexer.js)
`pnpm jest indexer`
=> Add unit tests to indexer.js in Parser

src/github-url-parser/package.json, src/github-url-parser/src/index.ts, src/github-url-parser/test/index.test.js
I need to make a few tweaks to the API.
=> Make parser arg optional, rename main function for github-url-parser

src/web/docusaurus/src/components/StarField.jsx
None. This fixes an issue with CD.
This PR dynamically imports the `p5.js` wrapper library because this is a browser-only library.
1. Get my changes
2. Go to the docs workspace (`cd src/web/docusaurus`)
3. Build the docs to make sure that the building works (`pnpm run build`)
4. Run the build (`pnpm run serve`)
=> Import p5.js dynamically on docs

src/api/search/README.md
fixes #3325
Updates `Search` service readme.
=> Update Search readme

src/web/docusaurus/docusaurus.config.js
Fixes #3403
This PR removes `showLastUpdateAuthor` and `showLastUpdateTime` to fix Docusaurus build errors.
- `pnpm i`
No errors during the Docusaurus build step:
```
#114 [telescope_api_nginx build-docs 4/4] RUN pnpm build
#114 45.06 ✔ Client: Compiled successfully in 42.70s
#114 47.85 ✔ Server: Compiled successfully in 45.40s
```
=> Remove showLastUpdate in Docusaurus

src/api/parser/src/data/post.js, src/backend/data/post.js, src/db/prisma/schema.prisma, src/web/app/src/components/SignUp/Forms/ChannelFeeds.tsx, src/web/app/src/components/SignUp/Forms/YoutubeTwitchFeeds.tsx, src/web/app/src/components/SignUp/Schema/FormModel.tsx, src/web/app/src/components/SignUp/Schema/FormSchema.tsx, src/web/app/src/interfaces/index.ts, src/web/app/src/pages/signup.tsx
Fixes #2843 - Work in progress
I originally planned with @tcvan0707 to add a Youtube and Twitch field under the Blog RSS page but it ended up looking crowded and difficult to understand.
This PR adds a new page in the signup flow for the 2 optional Youtube and Twitch fields.
- `cd src/db`
- `cp env.example .env`
- `pnpm migrate`
=> Add Youtube/Twitch sign-up page

src/api/sso/test/e2e/signup-flow.test.js
Until we solve #3504, let's disable this test
=> Disable failing e2e test until we solve #3504

src/web/app/src/components/AboutPage.tsx, src/web/app/src/components/BannerButtons.tsx, src/web/docusaurus/docs/overview.md
Fix #3407 
I have made an initial draft on changes that I might need to happen. Please kindly review and give me some idea to work on
- `npm install`
- `cp config/env.staging .env`
- `npm run dev`
- Click on "About us"
=> Changing About us navigation and update our Docusaurus about us

src/web/docusaurus/docs/api-services/dependency-discovery.md
Fixes #3540 
This PR adds documentation for the `dependency-discovery` service.
2. Go to `src/web/docusaurus/`
3. Build the docs `pnpm build`
4. And serve them over the web `pnpm run serve`
=> Add docs for dependency-discovery

docker/production.yml
- Remove `telescope` container from `nginx` depedencies
=> Remove nginx depending telescope

config/nginx.conf.template
- Removes nginx backend location reference
=> Remove backend location reference

config/env.production, config/env.staging
Fixes #3552
- Fix staging/production supabase config
=> Fix staging/production supabase config

src/web/docusaurus/docs/contributing/database-maintenance.md
=> Add production image tag

pnpm-lock.yaml, src/api/parser/package.json, src/web/app/package.json, src/web/docusaurus/package.json
Our builds are failing in our CI because of dependency issues. This PR fixes the issues
=> chore: fix dependency issues

pnpm-lock.yaml, src/api/dependency-discovery/package.json, src/api/status/package.json
Launching telescope locally with docker crashes due to a dependency error. This PR addresses fixes that error
- Checkout this branch
- Launch telescope using docker
=> chore: fix dependency issues for local deployment

docker/supabase/docker-compose.yml
Fixes #3645
Could be related to the change on Supabase side, since we are pulling the latest image. Now we might need to provide `SUPABASE_REST_URL`
see discussion: https://github.com/Seneca-CDOT/telescope/issues/3645#issuecomment-1238761872
Might be the solution for this, or not😅
Not sure if testable locally.
=> Add missing environment var

docker/supabase/docker-compose.yml
Fixes #3645
Changed `SUPABASE_REST_URL` env to be `${SUPABASE_URL}/rest/v1/`.
Last https://github.com/Seneca-CDOT/telescope/pull/3649, didn't worked. It was calling `http://localhost:8000/rest/api` which is wrong.
=> Fix SUPABASE_REST_URL

src/web/docusaurus/docs/getting-started/environment-setup.md
Removed reference to localhost:3000/posts in Environment Setup docs
Fixes #3656
Removed reference to localhost:3000/posts in Environment Setup docs
**Changed this:**
`Then visit localhost:8000 in a web browser to see Telescope running locally. localhost:3000/posts will show you the list of posts in JSON`
**To this:**
`Then visit localhost:8000 in a web browser to see Telescope running locally.`
=> Removed reference to localhost:3000/posts

package.json
Fixes #3671
This fixes the `pnpm dev` script in the root directory so you're not stuck in a loop
3. Checkout my branch: `git checkout issue-3671`
5. Run `pnpm dev` or `pnpm develop`. This should run `pnpm dev` in the src/web/app (Next.js frontend) directory so you can visit `localhost:8000` in your browser
=> Fixes #3671 updates `pnpm dev` script in root

src/web/docusaurus/docusaurus.config.js
Issue #3675
Link to Telescope documentation fix
Sorry for any inconvenience, this is my first experience contributing to big projects :)
=> Link to Telescope documentation bug fix

src/satellite/package.json
=> Satellite release 1.28.0

package.json
Fixes #3671 
A better fix to the #3672. Thank you @Kevan-Y in #3693
3. Checkout my branch: `git checkout issue-3671`
5. Run `pnpm dev` or `pnpm develop`. This should run `pnpm dev` in the src/web/app (Next.js frontend) directory so you can visit `localhost:8000` in your browser
=> #3671 update pnpm dev script in root with pnpm --filter

pnpm-lock.yaml
This PR fixes the `Vercel` errors that we were seeing in recent builds.
=> chore: fix dependencies

pnpm-lock.yaml, src/web/app/package.json
Fixes #3650
Vercel doesn't fail all the time, but when it does, it complains about `Cannot find module '@babel/runtime/helpers/interopRequireDefault'`. This PR should fix the problem
=> Fixes #3650 add @babel/runtime dep to next.js frontend

src/web/docusaurus/docusaurus.config.js, src/web/docusaurus/i18n/zh/docusaurus-plugin-content-docs/current/overview.md
Fixes #3686 
This adds a Mandarin(traditional Chinese) translation to About US page(`overview.md`), and it also lists this translation to `docusaurus.config.js`.
Please navigate to `src/web/docusaurus/docs/overview.md` to find the `overview.md` document.
=> Fixes #3686 Adding Mandarin(traditional Chinese) translation to About US page

pnpm-lock.yaml, src/api/status/package.json
=> Fixes #3717 update engine to node.js 16 and deps for status service

pnpm-lock.yaml, src/api/planet/package.json
=> Fixes #3713 update engine to node.js 16 and deps for planet service

pnpm-lock.yaml, src/satellite/package.json
=> Fixes #3727 update engine to node.js 16 and deps for satellite service

pnpm-lock.yaml, src/api/image/package.json
=> Fixes #3712 update engine to node.js 16 and deps for image service

src/satellite/package.json
We recently updated the engine and dependencies in our Satellite service in #3728 so we need to update its version
=> chore: upgrade satellite to v1.29.0

pnpm-lock.yaml, src/api/dependency-discovery/package.json, src/api/feed-discovery/package.json, src/api/image/package.json, src/api/parser/package.json, src/api/planet/package.json, src/api/posts/package.json, src/api/search/package.json, src/api/sso/package.json, src/api/status/package.json, tools/autodeployment/package.json, tools/migrate/package.json
=> chore: update satellite to v.1.29.0 in all telescope services

src/api/feed-discovery/package.json
Fixes #3711 
Upgraded node 12 to 16 in feed-discovery services
Using steps in [setup telescope](https://telescope.cdot.systems/docs/getting-started/environment-setup):
Run pnpm i
Run the services using pnpm services:start. Ensure all the containers are running
Ensure all posts are working correctly for the post service.
=> 3711: Upgraded node in feed discovery from v12 to 16

pnpm-lock.yaml, src/api/search/package.json
=> Fixes #3715 update engine to node.js 16 and deps for search service

pnpm-lock.yaml, src/api/sso/package.json
=> Fixes #3716 update engine to node.js 16 and deps for sso service

src/web/app/src/components/Posts/index.tsx, src/web/app/src/theme/index.ts
Fixes #3734
Improve accessibly score to 100% by making colour darker shade of grey to be visible for visually impaired people.
- Go to 'app' directory
- `pnpm install`
- In src/components/Posts/index.tsx change the colour of error and error icon
- Open url and go to 'http://localhost:8000/'
- Scroll down to 'Blog Timeline Failed to Load!'
=> Fixes #3734:  Improve google Lighthouse accessibly score #3734

src/web/app/src/components/SignUp/Forms/BlogFeeds.tsx, src/web/app/src/components/SignUp/Forms/ChannelFeeds.tsx, src/web/app/src/components/SignUp/Forms/RSSFeeds.tsx
Fixes #3759 
Fixes button label to correctly describe the action. As seen in the screenshot:
Go to signup, go to YouTube/Twitch form to see the fix.
=> Fixed button text on YouTube and Twitch form

src/web/app/src/components/SignUp/Forms/Review.tsx
Fixes #3612 
This PR addresses the issue of unconfirmed Twitch channel URLs being accepted, by filtering out those URLs after users "submit" the data in "YouTube and Twitch" page during sign-up.
This is done by matching confirmed twitch URL(s) under "Twitch/YouTube Channel RSS" in the review page against Twitch channel URLs listed under "Channel URLs" in the review page.
If users would like to backtrack to make changes, unconfirmed Twitch URLs that are not accepted will not be listed, for consistency.
Change:
- Add code to filter unconfirmed Twitch channel URLs in `src\web\app\src\components\SignUp\Forms\Review.tsx`
Future issues can be considered to handle unconfirmed URLs for YouTube and Blog URLs. 
Test this by going through the sign-up process to view the channel page.
During testing, …
=> Filter unconfirmed Twitch channel URLs during sign-up

pnpm-lock.yaml, src/api/sso/package.json, src/satellite/package.json
This PR addresses the security issue mentioned in #3783. For some reason, `renovate` failed to create a stable fix for the issue, so I'm addressing it here.
=> chore: update jsonwebtoken to v9

package.json, pnpm-lock.yaml, src/db/package.json
Closes #3778 
This PR updates `prisma` from v3.12.2 to v4.9.0.
- Run telescope
- Assert that migration and seeding work as expected with v4.
=> Closes #3778: Update prisma

.github/workflows/e2e-tests-ci.yml, .github/workflows/eslint-ci.yml, .github/workflows/pnpm-lock-check-ci.yml, .github/workflows/pnpm-publish.yml, .github/workflows/prettier-ci.yml, .github/workflows/unit-tests-ci.yml, package.json, src/api/dependency-discovery/Dockerfile, src/api/feed-discovery/Dockerfile, src/api/image/Dockerfile, src/api/parser/Dockerfile, src/api/posts/Dockerfile, src/api/search/Dockerfile, src/api/sso/Dockerfile, src/api/status/Dockerfile, src/db/Dockerfile, src/satellite/package.json, src/web/Dockerfile
=> chore: update nodejs version in our dockerfiles

package.json, pnpm-lock.yaml, src/github-url-parser/.parcelrc, src/github-url-parser/package.json, src/github-url-parser/tsconfig.json, src/web/docusaurus/package.json
Closes #3745 
This PR updates `docusaurus` to version v2.4.3.
N/A
=> chore: update docusaurus to v2.4.3
